### ISSUE TITLE
yaklang 怎么像golang一样导入别的包？

### ISSUE THREAD

**Issue by shadow1ng** [yaklang/yakit#1]
比如
import (
	"github.com/xxxx/xxxx"
)

**Comment by Vernon818** [comment]
@shadow1ng 为了感谢您对yak和yakit的支持，我们想邮寄一份小礼物给您，麻烦您微信添加一下：Juzi19880818，并备注好您的github账号。如已经添加账号，请微信联系我一下，谢谢
