### ISSUE TITLE
不走本地host文件

### ISSUE THREAD

**Issue by Bronya-Rayi** [yaklang/yakit#100]
本地搭建服务器调试web服务的时候，由于chromium系的无法对127.0.0.1地址进行代理，所以一般都改host文件
![image](https://user-images.githubusercontent.com/47048823/150893513-e4d468bb-f743-4244-bad7-008b84374158.png)
然而用yakit抓包后，再发送，会发现yakit不走host文件，显示域名不存在
![image](https://user-images.githubusercontent.com/47048823/150893600-767900c8-cf80-463d-adce-f834609bd904.png)

BurpSuite无此问题
![image](https://user-images.githubusercontent.com/47048823/150893678-76d46752-d8f7-464c-bdeb-7323dc527fa1.png)

**Comment by Bronya-Rayi** [comment]
直接放行是可以的，就是web fuzzer不行
![image](https://user-images.githubusercontent.com/47048823/150894205-d6eefe68-144f-4826-a107-6705b2e3487f.png)

**Comment by VillanCh** [comment]
Webfuzzer 的 dns 解析是直接发 dns 包进行的


感谢反馈，下一版本会增加对 hosts 的支持，如果着急使用，可以在高级配置中手动配置 host 和 port&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Bronya-Rayi ***@***.***&gt;
发送时间: 2022年1月25日 09:34
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 不走本地host文件 (Issue #100)





 
直接放行是可以的，就是web fuzzer不行
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Bronya-Rayi** [comment]
Webfuzzer好像发不了127.0.0.1的本地包
![3](https://user-images.githubusercontent.com/47048823/150896350-67f88ea7-0508-4ae1-b871-f53107fb4b34.gif)

**Comment by VillanCh** [comment]
稍等我到公司看一下，应该比较好定位



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Bronya-Rayi ***@***.***&gt;
发送时间: 2022年1月25日 09:56
收件人: yaklang/yakit ***@***.***&gt;
抄送: v1ll4n ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [yaklang/yakit] 不走本地host文件 (Issue #100)





 
Webfuzzer好像发不了127.0.0.1的本地包
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by VillanCh** [comment]
新版本修复了这个问题（hosts 不生效），大概今天中午或者晚些时候引擎会更新一个版本～

**Comment by Bronya-Rayi** [comment]
好的，师傅辛苦了

**Comment by Bronya-Rayi** [comment]
看到了更新后的版本，问题解决了
