### ISSUE TITLE
【bug]】MITM抓包过滤器设置无法保存，自动重置过滤器。

### ISSUE THREAD

**Issue by x155428** [yaklang/yakit#1002]
bug偶尔会出现：
启动拦截后，配置排除firefox包，无法保存，保存就恢复默认的。
![图片](https://github.com/yaklang/yakit/assets/83338415/ec59c363-c64e-48a7-884c-957e60d7df41)
确定之后再打开又恢复原来的：
![图片](https://github.com/yaklang/yakit/assets/83338415/f79755e6-317a-44f9-8d16-69f9d810acc1)
在启动拦截之前配置，点击确定，保存也没用：
![图片](https://github.com/yaklang/yakit/assets/83338415/44a4c8e9-0f9a-4420-8009-5d123fe848f9)
当前最新社区版，管理员启动。
建议：默认别排除那么多文件，很难配置，或者加一个一件清除功能。

**Comment by x155428** [comment]
经过测试，默认过滤全部删光后配置自己的规则会稳定触发这个bug:
![图片](https://github.com/yaklang/yakit/assets/83338415/3012ba07-cefa-4ed4-a4c7-1985e0cc9b61)
![图片](https://github.com/yaklang/yakit/assets/83338415/718f5087-1f77-4df4-9d3e-bdb1ad6679f2)
![图片](https://github.com/yaklang/yakit/assets/83338415/fbf77ad6-0e48-4569-bec8-19e096934487)

**Comment by Vernon818** [comment]
好的，感谢师傅反馈，确实是有点问题，我们修复一下。
师傅可联系工作人员：Juzi19880818，领取小礼物
