### ISSUE TITLE
【需求】history响应类型

### ISSUE THREAD

**Issue by YouChenJun** [yaklang/yakit#1007]
![image](https://github.com/yaklang/yakit/assets/53772533/31187fd0-87c4-4b4b-9184-dd4b4f04d677)
希望在history里面的响应类型里面可以做到排除xx，例如我不想看到JavaScript，想排除JavaScript的报文。而且这上面有的时候宽度就很抽象，希望可以改进一下
![image](https://github.com/yaklang/yakit/assets/53772533/18a86013-b6d6-4853-80fb-bff5135f955c)

**Comment by Vernon818** [comment]
这周上线就好了
