### ISSUE TITLE
【需求】请支持关闭或修改截屏快捷键功能

### ISSUE THREAD

**Issue by winezer0** [yaklang/yakit#1011]
## 需求描述

我在使用新版yakit时，总是被截图功能占用了Crtl Shift B 和 Crtl Shift X按钮，并且无法修改，导致我使用yakit时，无法使用其他工具

![image](https://github.com/yaklang/yakit/assets/46115146/30a5f338-bea1-4994-8abf-e6b1a8345e27)

## 解决方案

我希望产品能够实现：

1、自定义关闭截屏、录屏功能 或 支持修改截屏、录屏的快捷键

**Comment by Ruqian01** [comment]
应该弄一个按钮，可以选择是否使用快捷键

**Comment by Vernon818** [comment]
我们先把这个快捷键取消，等之后上了快捷键管理师傅们就可以自定义了~
（感谢师傅反馈，师傅可以联系wx：Juzi19880818，领取小礼物）

**Comment by winezer0** [comment]
好的，等待您的版本更新
