### ISSUE TITLE
【bug】漏洞和风险统计无法加载

### ISSUE THREAD

**Issue by YouChenJun** [yaklang/yakit#1012]
当漏洞和风险一多，就无法加载
![image](https://github.com/yaklang/yakit/assets/53772533/9494fae7-eb80-48c1-9d67-1d95fe192256)
![image](https://github.com/yaklang/yakit/assets/53772533/2cbc035f-95b3-4869-a8c4-384d0e1e8d53)
刷新也无法加载出来

**Comment by Vernon818** [comment]
昨天已经跟师傅解释了，是因为数据库被锁~

**Comment by Go0p** [comment]
https://github.com/yaklang/yakit/issues/1010 可能是一个问题
