### ISSUE TITLE
求助，更新后代理劫持报错

### ISSUE THREAD

**Issue by zhixuan-gif** [yaklang/yakit#1016]
![image](https://github.com/yaklang/yakit/assets/66342560/b53e9924-fb55-482c-abc0-68b9ee4d0943)

**Comment by zhixuan-gif** [comment]
![image](https://github.com/yaklang/yakit/assets/66342560/be4613e8-a72d-4557-b59c-86c7d5cc7d74)

**Comment by Vernon818** [comment]
师傅方便微信详聊看看吗，wx：Juzi19880818

**Comment by Vernon818** [comment]
应该是师傅有用杀软什么的，可以把杀软关掉，或者给我们加白
