### ISSUE TITLE
下载失败，代理关了也不行，有没有单独的引擎下载地址？想单独下载再放到安装目录下。

### ISSUE THREAD

**Issue by zhan741965531** [yaklang/yakit#102]
![图片](https://user-images.githubusercontent.com/18067503/150901660-e522a5de-b855-4572-bf28-f868eb450071.png)
![图片](https://user-images.githubusercontent.com/18067503/150901705-bacfb48c-2f04-4a6b-a972-68bf10a18376.png)
![图片](https://user-images.githubusercontent.com/18067503/150902116-2008beb6-8038-4935-a6d7-0fbe838b69e1.png)

**Comment by VillanCh** [comment]
https://yaklang.oss-cn-beijing.aliyuncs.com/yak/1.0.12-sp26/yak_windows_amd64.exe

Windows 下载这个应该就可以，下载后重命名到 %HOME%/yakit-projects/yak-engine/yak.exe 即可

**Comment by VillanCh** [comment]
是因为 IP 被阿里云 ban 了导致 OSS 无法访问吗？

**Comment by zhan741965531** [comment]
感谢，已经安装成功。ip没有被封，同事是正常一键安装成功，建议列出一页引擎下载页面作为备选引擎安装方案。
![图片](https://user-images.githubusercontent.com/18067503/150903277-fa514252-0bf9-4547-99e0-a2526b15e2aa.png)

**Comment by VillanCh** [comment]
可以本地删除之后重新下载

> 感谢，已经安装成功。ip没有被封，同事是正常一键安装成功，建议列出一页引擎下载页面作为备选引擎安装方案。 ![图片](https://user-images.githubusercontent.com/18067503/150903277-fa514252-0bf9-4547-99e0-a2526b15e2aa.png)

感谢提醒，确实安装文案需要调整，最近一直在忙项目功能忽略了相关文档
