### ISSUE TITLE
【需求】查看请求包需要主动关闭功能

### ISSUE THREAD

**Issue by Ruqian01** [yaklang/yakit#1028]
查看请求包这里无法主动关闭，非常占空间，特别是对于屏幕小的来说非常难受，还需要切换到另外页面在切换回来才会关闭
![image](https://github.com/yaklang/yakit/assets/138359666/0dd9c93e-6052-49c0-9f07-b43fb6143252)

**Comment by Go0p** [comment]
再次选中你图中的序号2 ，下面的就显示了呀
