### ISSUE TITLE
【需求】payload增加命中次数以提高扫描优先级

### ISSUE THREAD

**Issue by Liehu** [yaklang/yakit#1033]
建议payload增加命中次数以提高扫描优先级

有2个不错的项目，https://mp.weixin.qq.com/s/bf_6Ej07eungCHlVe9Wwcw，https://www.jianshu.com/p/2386e3727552。
这两个项目有个共同点，就是对命中的payload会增加命中次数以提高对应的优先级，这样的话可以在后续其他网站扫描或者爆破时，优先使用高优先级的payload，能有效提升检测效率。
目前想到的可能的实现方式：
1. 允许在payload表新增字段，如优先级。
2. 允许连接私有数据库，用户本地维护一个自有的库。

**Comment by Vernon818** [comment]
好的，感谢师傅反馈

**Comment by WAY29** [comment]
新版payload已支持优先级字段，且会在弱口令扫描命中时自动增加优先级
