### ISSUE TITLE
求助，编写插件如何实现像口令爆破插件那样选择自定义payload

### ISSUE THREAD

**Issue by Liehu** [yaklang/yakit#1034]
编写插件如何实现像口令爆破插件那样选择自定义payload。
最近在修改shiro的插件，发现原生的key较少，像通过维护payload去实现key的增减，但是问题是如何实现像口令爆破插件那样通过GUI选择自定义的payload呢

**Comment by VillanCh** [comment]
目前需要单独编写插件，插件内使用的参数字典目前没有UI可以添加，只能师傅单独写一个Yak原生插件来使用



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Lau Spence ***@***.***&gt;
发送时间: 2023年9月1日 16:33
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 求助，编写插件如何实现像口令爆破插件那样选择自定义payload (Issue #1034)





 
编写插件如何实现像口令爆破插件那样选择自定义payload。
 最近在修改shiro的插件，发现原生的key较少，像通过维护payload去实现key的增减，但是问题是如何实现像口令爆破插件那样通过GUI选择自定义的payload呢

**Comment by Lmg66** [comment]
同样遇到类似需求，翻阅api发现提供了SavePayload,但是没提供查询payload功能。翻阅了引擎代码发现是有通过group查询payload功能的函数，能把查询payload接口也开放吗？开放此查询接口插件可读payload，前端也能通过原有gui管理payload。
<img width="1280" alt="6073bd9a31e888813ad6e96bd693195" src="https://github.com/yaklang/yakit/assets/58671998/e97c1e17-08b4-4198-9d43-5cc6e6357772">
<img width="664" alt="0d09525e1e57480d38855b1cc331a85" src="https://github.com/yaklang/yakit/assets/58671998/654240d7-8876-46d3-8e6a-3ef3d4a8c660">
<img width="533" alt="ca70f3dbf398d9f4a2b49601274034f" src="https://github.com/yaklang/yakit/assets/58671998/c8d838ab-c97a-49d4-8b74-8aa350b5f4fd">
<img width="1280" alt="b6299dfdb104940c9050f5cadf233ae" src="https://github.com/yaklang/yakit/assets/58671998/d873e949-34cc-4e06-9a3f-18e4d0d99212">
<img width="1250" alt="912424f82d0b57743bafdabf6554da9" src="https://github.com/yaklang/yakit/assets/58671998/389818c5-4be9-482a-9601-de1c7ab134a8">

**Comment by VillanCh** [comment]
HERE: https://github.com/yaklang/yaklang/pull/1215/files#diff-f1cae3fd8f0fcf3e130645553eac4378eb779bc85896d13d915df0add7ca96fd

 今天（4.19）的版本应该会新增，可以参考用法 
![image](https://github.com/yaklang/yakit/assets/13946521/dca46f49-000f-41b6-afd6-bbc437b7f033)
