### ISSUE TITLE
对于在官网下载YAKIT的建议

### ISSUE THREAD

**Issue by QAZSEDFFD** [yaklang/yakit#1037]
![image](https://github.com/yaklang/yakit/assets/109219017/0e909316-8b62-4568-8193-b278ed9716ac)

![image](https://github.com/yaklang/yakit/assets/109219017/b409ac4c-a6cb-4002-a914-31d76804c881)

1、老手知道点哪下载，小白刚来这个页面，是真不知道在哪，谁能想到居然是点牛头下载
建议：加一个下载模块，或者牛头那加一个下载的提示

**Comment by QAZSEDFFD** [comment]
已经有好几个同事踩坑了，刚进去不知道在哪里下载

**Comment by Vernon818** [comment]
好的，感谢师傅反馈，我们把这个链接调整一下
