### ISSUE TITLE
对于在交互劫持模块右键发送到webfuzz的建议

### ISSUE THREAD

**Issue by QAZSEDFFD** [yaklang/yakit#1038]
![image](https://github.com/yaklang/yakit/assets/109219017/25bebda6-8726-464f-9882-355a6a1c0dc4)
![image](https://github.com/yaklang/yakit/assets/109219017/4d8b8be4-0824-4cf7-bbba-080a511276c0)

1、建议右键第二张图标注区域，出来的选项能有发送的webfuzz

**Comment by Vernon818** [comment]
师傅这个xin新建webfuzzer就是发送到webfuzzer名字不太一样，后面给他改成统一的
![image](https://github.com/yaklang/yakit/assets/94944398/90f3b215-8727-4e1f-ba5a-fd0fe6b8a35f)
