### ISSUE TITLE
有没有考虑将go-rod嵌入到yak当中？

### ISSUE THREAD

**Issue by jiaocoll** [yaklang/yakit#104]

**Comment by VillanCh** [comment]
![image](https://user-images.githubusercontent.com/13946521/151093225-f49877e5-ff0c-4636-9a43-c86805968022.png)

其实这个依赖一直有，只是没有封装合适的接口暴露给 yak 内置库，目前是以 go-sdk 的形式封装开放的

有一个浏览器爬虫正在研发中，配合 go-rod 的接口应该会一并开放出来

**Comment by jiaocoll** [comment]
不错，挺期待
