### ISSUE TITLE
【需求】websocket fuzzer 增加fuzzer tag 支持

### ISSUE THREAD

**Issue by burpheart** [yaklang/yakit#1040]
websocket fuzzer 增加fuzzer tag 支持
至少增加二进制(hex编码)发包的支持  发送二进制不可打印字符和字符串混合的数据包  在ws传输作为起始和结尾标记经常用到

**Comment by WAY29** [comment]
将会在这个[PR](https://github.com/yaklang/yaklang/pull/487)里添加支持
