### ISSUE TITLE
【需求】空间搜索引擎搜索的结果能够导入数据库进行下一步操作

### ISSUE THREAD

**Issue by allinu** [yaklang/yakit#1049]
## 需求描述

空间搜索引擎将搜索后的结果直接导入数据库进行下一步操作

## 解决方案

希望空间搜索引擎搜索的结果能够导入数据库进行下一步操作

## 可选方案

无

## 附加信息

<img width="1680" alt="image" src="https://github.com/yaklang/yakit/assets/32992109/62f85833-cdc3-47fb-919b-f795a5cfa22a">

**Comment by Vernon818** [comment]
yakit.SaveDomain(domain, ip)，师傅可以编辑插件加入这个函数，就会把域名、ip这些存在数据库—域名表里
