### ISSUE TITLE
【求助】暴力破解如何从响应包获取随机的token并加入到下一次请求中

### ISSUE THREAD

**Issue by K-7H7l** [yaklang/yakit#1050]
在测试中遇到校验token的情况，每次请求都需要从响应包中通过正则获取随机的token并加入到下一次发包中。望大佬指点。

**Comment by Go0p** [comment]
下面的两个可能可以解决你的需求

[序列场景案例：文件上传与校验](https://update-new-webfuzzer.yaklang-github-io.pages.dev/products/expert-mode/Web%20Fuzzer/fuzz-sequence-example2)

[热加载场景案例：csrf token保护下的爆破](https://update-new-webfuzzer.yaklang-github-io.pages.dev/products/expert-mode/Web%20Fuzzer/fuzz-hotpatch-example1)

**Comment by K-7H7l** [comment]
参考[序列场景案例：文件上传与校验](https://update-new-webfuzzer.yaklang-github-io.pages.dev/products/expert-mode/Web%20Fuzzer/fuzz-sequence-example2)无法实现“变量”获取“数据提取器”的值
<img width="1320" alt="image" src="https://github.com/yaklang/yakit/assets/38025386/75b82af1-aec7-4eb3-9c5d-edd1a43e7ecc">

**Comment by Go0p** [comment]
首先提取的结果，只能在下一个包中使用，所以你应该使用序列

第一个数据包设置如下

![image](https://github.com/yaklang/yakit/assets/38928800/95e718d8-ba03-4d85-9cc2-fd56fa4dca2a)

第二个包数据设置如下

![image](https://github.com/yaklang/yakit/assets/38928800/3d87a7a0-997a-4474-bf10-75e5691fb91b)

随后执行序列

![image](https://github.com/yaklang/yakit/assets/38928800/52d694fc-e11f-4f80-81af-cc711a63c035)
