### ISSUE TITLE
【BUG】劫持当前响应漏包

### ISSUE THREAD

**Issue by xbfding** [yaklang/yakit#1060]
## 问题描述
MITM 交互式劫持的劫持响应，若在发包前选择劫持“当前请求”，该数据包响应则截取不到。

## 复现步骤

1. 步骤 1

劫持请求前，在“手动劫持”中，选择劫持响应的“当前请求”。==注意：在劫持请求前，选择劫持响应的“当前请求”==
![image](https://github.com/yaklang/yakit/assets/62999907/9307bf0f-32a1-442c-ad5c-b96dcb9168b2)

2. 步骤 2
劫持请求，并提交请求，然后这个请求的响应包就会被漏包
![image](https://github.com/yaklang/yakit/assets/62999907/ba4c3d47-c211-4975-87b8-cb63f0fb6857)

## 环境信息

- 操作系统: win32
- 系统架构: x64
- Yakit 版本: 社区版 Yakit v1.2.5-sp1
- YakLang 版本: Yaklang v1.2.5-sp4

**Comment by Vernon818** [comment]
师傅这个应该是劫持到请求以后，选当前请求呢，去劫持这个请求的响应，你试试看这样操作呢

**Comment by xbfding** [comment]
那样是没问题的，我只是用的时候发现了一个这样的问题。

**Comment by Vernon818** [comment]
师傅目前的交互优化了一下，不会有这个问题啦
