### ISSUE TITLE
功能改进  显示软件版本和引擎版本

### ISSUE THREAD

**Issue by fantasy-2046** [yaklang/yakit#1069]
软件 左上方 ？那里是否添加 一个   关于 Yakit  显示  yakit版本和 yak引擎版本 以及是否需要更新yakit或yak引擎？

**Comment by ViCrack** [comment]
左上方已经有个更新通知，只管更新到最新就行了

**Comment by fantasy-2046** [comment]
一般?号那个位置不都是显示 软件版本之类的地方吗？

**Comment by Vernon818** [comment]
![image](https://github.com/yaklang/yakit/assets/94944398/833e93ef-5213-4092-8646-199ed1547d8e)
这里有显示软件版本噢~
