### ISSUE TITLE
【UI】dnslog 反连界面布局优化

### ISSUE THREAD

**Issue by allinu** [yaklang/yakit#1076]
当前版本为：`社区版 Yakit v1.2.5-sp2`

当存在的内容展开后将页面高度撑开之后，页面会有错位和重叠，如下,

<img width="1675" alt="image" src="https://github.com/yaklang/yakit/assets/32992109/6215cd01-2e82-4a58-8f15-50041a3fb7ea">

PS：还有就是现在光标滚动会有问题，就是不知道是滚布局内的滚动条还是最外面Yakit的滚动条，滚起来有时候狠抓狂，只能将光标放到空白区域或者不可滚动区域进行整体页面的滚动

**Comment by Vernon818** [comment]
好的，感谢师傅反馈，应该会在最近两个版本优化
