### ISSUE TITLE
DNSLog 自定义时间格式化

### ISSUE THREAD

**Issue by allinu** [yaklang/yakit#1082]
我自己写了一个插件进行获取dnslog，目前除了时间显示一切良好，我获取的返回时间格式为`"created_at": "2023-09-12 18:48:40"` 我这边吧这个时间直接赋值`"Timestamp": event["created_at"],`这样不行，也尝试了转换`ts = datetimeToTimestamp(event["created_at"])` 依旧没有正常显示为`2023-09-12 18:48:40` 都是显示为
<img width="1660" alt="image" src="https://github.com/yaklang/yakit/assets/32992109/dcdabd87-c207-46b8-ae88-32e20dcc2035">

请问我该怎么写这个变量呢？

**Comment by Go0p** [comment]
这个时间戳的后端处理逻辑有点问题，后续修改了应该就正常了
