### ISSUE TITLE
【需求】本地我的插件在编写调试完成后，私有插件转公开

### ISSUE THREAD

**Issue by allinu** [yaklang/yakit#1084]
我在本地编写了插件，同步云端的时候，我选择的为私有，编写完毕后我想分享岛商店，怎么分享呢？我没有找到相关入口，同时对于私有插件，我分享给别人，我希望别人不能对本插件进行公开，只有作者可以设置公开与否，而且要增加相关设置，让这种插件在提交公开的时候能够有一定措施进行阻止，同时，对于已经存在插件，有的插件还可以继续优化一下，或者进行更新，能否进行更新发布，毕竟我修改原来作者的代码，我发作者是我自己，多少有点道德问题，如果能在作者栏保留原作者，同时增加自己就更完美了。

**Comment by allinu** [comment]
私密转公开已找到 路径为 我的插件 -> 线上 -> 修改 -> 公开

**Comment by Vernon818** [comment]
1、分享可以在插件悬浮在作者名字上->复制id，发送给要分享的人即可（新版插件商店会把这个功能做明显一点）
![image](https://github.com/yaklang/yakit/assets/94944398/d31999bc-b48f-43c6-9b03-507639149149)
2、私密改公开确实只有作者本人可以，其他人是不可以的
3、编辑非本人的插件时，只能提交修改，等插件作者合并代码。合并后会提交人的名字会显示在协作者
![image](https://github.com/yaklang/yakit/assets/94944398/666b3bbc-246c-40b0-8a61-5948b153c172)
