### ISSUE TITLE
【需求】失去焦点时隐藏弹出的标签

### ISSUE THREAD

**Issue by ViCrack** [yaklang/yakit#1087]
![图片](https://github.com/yaklang/yakit/assets/18179821/56794650-ee52-434b-847c-420fe946faad)

有个比较尴尬的地方

每一次要截图fuzz窗口的时候，经常会被这个遮住。。。

能实现失去焦点或者超时几秒则自动隐藏或许更好

**Comment by VillanCh** [comment]
感谢师傅反馈，应该之后的版本中会优化这个行为

**Comment by Vernon818** [comment]
最新版本Yakit v1.2.7-sp2 已经加上了超过五秒会隐藏
