### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by lnsmile** [yaklang/yakit#109]
![image](https://user-images.githubusercontent.com/80399046/151480709-0f2c8d6e-5a64-4d34-bd4a-eb76eea50ccd.png)
在这里可以加一个一键关闭前面所有标签页的功能。由于从burp转型到yakit，可能很多功能不熟悉，有时候会打开很多标签页。一个一个关闭很麻烦

**Comment by VillanCh** [comment]
右键Tabs会有，”关闭全部” 之类的按钮呀～
