### ISSUE TITLE
Webfuzz 请求失败的数据包怎么从新发送请求?

### ISSUE THREAD

**Issue by gnusec** [yaklang/yakit#1091]
Webfuzz 请求失败的数据包怎么从新发送请求?

![image](https://github.com/yaklang/yakit/assets/11014864/c59e7842-174b-49a6-97fe-e3bf734e0940)
Bp是可以直接右键选中重发的

**Comment by VillanCh** [comment]
左边高级配置中设置重试条件即可，如果是已经失败的请求，可以点开详情重试？

**Comment by Vernon818** [comment]
后面我们会出一个一键重试来着，把失败的包都再发一次~

**Comment by Vernon818** [comment]
师傅最新版本Yakit v1.2.7-sp2，Yaklang v1.2.7-sp4  已经支持失败的包一键重试了
