### ISSUE TITLE
grpc安装报错

### ISSUE THREAD

**Issue by izj007** [yaklang/yakit#11]
Ubuntu按照文档一键安装成功，但是无法启动，启动报错

![](https://gitee.com/fuli009/images/raw/master/public/imgs/20211019103708.png)

**Comment by VillanCh** [comment]
这个是一个老问题了，尝试设置环境变量: GODEBUG=netdns=go 正在研发的新版本会自动设置这个点

**Comment by izj007** [comment]
谢谢，搞定了我指定一下--host 0.0.0.0就没报错了……
