### ISSUE TITLE
macOS 系统版本10.15.7用不了

### ISSUE THREAD

**Issue by o2e** [yaklang/yakit#110]
![image](https://user-images.githubusercontent.com/24642961/151546754-6b7248a9-a211-4ea4-9ddd-70142f41c318.png)

请问能不能兼容一下上一版的macOS系统

**Comment by VillanCh** [comment]
这个应该是最近升级了新版本的 Electron Chromium 内核导致的问题
实际并不需要11.0，保证 10.15.x 的最新版本应该也可以使用

（我的 mac mini x86 是 10.15.x 版本的

**Comment by o2e** [comment]
更新系统后可以了 谢谢~

**Comment by ekko-zhao** [comment]
> 

你好，你是直接更新大版本了吗？
