### ISSUE TITLE
【需求】在history当前数据包显示当前id

### ISSUE THREAD

**Issue by VVeakee** [yaklang/yakit#1111]
## 需求描述

突然蹦出来一堆数据包,把当前查看的数据包刷下去,要找到还要翻翻翻

## 解决方案
这样即使突然蹦出很多数据包也知道该翻到哪
![image](https://github.com/yaklang/yakit/assets/85714114/7d0699fd-0b98-4098-b5fe-e718875d6f04)

## 可选方案

请清晰明确地描述你考虑过的其他方案或功能。

## 附加信息

请提供任何与该功能请求相关的上下文信息、截图或其他材料等。

**Comment by Vernon818** [comment]
好的，感谢师傅建议

**Comment by Vernon818** [comment]
Yakit v1.2.7-sp4 已支持
