### ISSUE TITLE
【UI】记住最后一次展开或折叠

### ISSUE THREAD

**Issue by ViCrack** [yaklang/yakit#1124]
师傅好，这里有个小功能区，经常用不到想折叠了，节省空间，但是每次升级或者重启的时候还是会展开出来，能否能实现那种记住最后一次的展开或者折叠状态。

![图片](https://github.com/yaklang/yakit/assets/18179821/6698bc53-8113-4088-9105-ac6ed7974a15)

-------------------------------------------

主要是编码解码不是很常用，我自己用Cyber比较多，它的输入框的数据变化之后输出结果也会自动变化

**Comment by Vernon818** [comment]
最新版已经满足啦~

**Comment by ViCrack** [comment]
@Vernon818 最新版（v1.2.8-sp7）这个功能好像又没了，每次重启不会记忆

**Comment by Vernon818** [comment]
还真是，我们修一下

**Comment by ViCrack** [comment]
@Vernon818 师傅这功能有排期修复不，我发现最新版的1.2.9还是没有
