### ISSUE TITLE
【需求】过滤器在多种抓包环境下的快速切换

### ISSUE THREAD

**Issue by VVeakee** [yaklang/yakit#1127]
## 需求描述

在测试上传图片时需要调过滤器把一些图片后缀给去掉抓包
比如.png .jpg .jpeg 有些时候图片有没有后缀需要用Content-Type: image/jpeg Content-Type: image/jpg Content-Type: image/png  
在不测试的上传的时候又要把一些图片的后缀给加上,整个过程很繁琐

## 解决方案

方案1 加一个组合一键过滤图片
方案2 缓存一下修改记录,可以前后翻
方案3 保存当前的设置然后命名为1,修改过滤器的设置后,保存设置然后命名为2,达到多种抓包环境下过滤器的快速切换

**Comment by Vernon818** [comment]
好的，感谢建议，后面可能会考虑保存多个过滤器配置

**Comment by Vernon818** [comment]
Yakit v1.2.7-sp4  已支持
