### ISSUE TITLE
改进指纹扫描的扫描目标

### ISSUE THREAD

**Issue by ErLiang-Yuan** [yaklang/yakit#1130]
## 需求描述

扫描目标可以使用ip+端口，之前可以但是现在不行了，

## 解决方案

恢复一下

## 可选方案

请清晰明确地描述你考虑过的其他方案或功能。

## 附加信息

![image](https://github.com/yaklang/yakit/assets/74943385/69f255b1-1b35-4efc-9ee2-3953fd6353f8)

**Comment by VillanCh** [comment]
感谢师傅反馈，已经修复，在下一个引擎版本更新时将会更新～

**Comment by ErLiang-Yuan** [comment]
tks，cool!



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月13日(周五) 下午2:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yaklang/yakit] 改进指纹扫描的扫描目标 (Issue #1130)




 
感谢师傅反馈，已经修复，在下一个引擎版本更新时将会更新～
