### ISSUE TITLE
不安全的http代理不支持(已提交被驳回,提issue记录问题,供参考)

### ISSUE THREAD

**Issue by jhalx** [yaklang/yakit#1136]
通过proxypool抓取的大部分http代理不可使用,
经确认发现 问题出在代理本身,
proxy代理检测方式为 数据传输过去,有正确的数据传回即可,
但是 这个行为是不安全的. 部分http代理使用的并不是connect这一连接行为,这导致了可能会存在中间人监听,数据包被记录,
如果想使用这些不安全的代理,可以通过python等语言 开发一个 安全代理,将它代理到不安全的代理去.

**Comment by VillanCh** [comment]
REF: https://github.com/yaklang/yaklang/pull/526

**Comment by VillanCh** [comment]
目前已经实现，分支已合并，更新最新版本即可
