### ISSUE TITLE
【需求】能不能不安装在C盘啊？

### ISSUE THREAD

**Issue by Logider** [yaklang/yakit#1139]
## 需求描述

能不能不安装在C盘啊？

## 解决方案

我希望能够修改安装位置

## 可选方案

我希望能够修改安装位置

## 附加信息

我希望能够修改安装位置

**Comment by Vernon818** [comment]
其实安装包还好，主要是因为用户数据要迁移的话会有点问题，所以暂时还没处理

**Comment by ViCrack** [comment]
更新安装包下载之后会保留在C:\Users\xxxx\yakit-projects\yak-engine目录下面，随着版本的更新，文件会越来越多占用越来越大，这里可以考虑自动安装，安装完删除

我自己写了个用scoop也可以自动检测 绿色安装yakit
https://github.com/ViCrack/scoop-bucket/blob/master/bucket/yakit.json

**Comment by WAY29** [comment]
#508
