### ISSUE TITLE
优化空间引擎

### ISSUE THREAD

**Issue by ErLiang-Yuan** [yaklang/yakit#1153]
## 需求描述

一、空间引擎有时无法启动。                    建议：1.优化脚本。2.提供错误信息。
二、空间引擎额外信息（账号、API）无法保存
三、开放其他搜索引擎（除了fofa感觉都用不了）
四、考虑是否允许用户自主修改搜索引擎脚本

![image](https://github.com/yaklang/yakit/assets/74943385/27dc9b36-1d32-4e61-93c8-b573839640fb)

**Comment by Vernon818** [comment]
师傅引擎脚本是可以在本地插件那里找到插件改的

**Comment by WAY29** [comment]
师傅确定真的存在这些问题吗？经过测试保存key是可用的（只是不会展示在前端），但是直接执行是会读取到之前保存的key的，而且其他引擎也正常工作（测试了shodan）。
