### ISSUE TITLE
【需求】在webfuzzer中获取到上下文内置变量

### ISSUE THREAD

**Issue by ViCrack** [yaklang/yakit#1161]
我不确认是否已经有类似功能了，可能是我还不清楚如何使用。

就是内置一些常见的可获取的变量，类似于nuclei的{{Hostname}}，{{RootURL}}等等

![图片](https://github.com/yaklang/yakit/assets/18179821/f196d603-5f8f-415c-a961-b2a765c294e0)

举个例子，数据包填写
```
POST / HTTP/1.1
Content-Type: application/json
Host: www.example.com

{{Port}} {"key": "{{param(RootURL)}}/1111","key2": "{{param(RootURL)}}/2222","key3": "{{param(RootURL)}}/33333"}
```

发送请求时自动渲染成
```
POST / HTTP/1.1
Content-Type: application/json
Host: www.example.com

80 {"key": "htttp://www.example.com/1111","key2": "htttp://www.example.com/2222","key3": "htttp://www.example.com/33333"}
```

比如这种情况下，由于Host头是已知的，这样每次测试的时候只需要修改Host就不用到处更新其他地方的值了

**Comment by ViCrack** [comment]
对了，这种情况还可以在热加载代码中使用，因为我在文档中还没找到类似的写法。

假设有某种加密案例，加密条件需要跟当前url值（或者body、或者header、或者其他某部位的数据）来进行运算

![图片](https://github.com/yaklang/yakit/assets/18179821/f7f45fee-56ba-463d-a695-f8b8259bfa71)

这样就需要在热加载中获取到当前fuzz的一些web数据

比如
```go
handle = func(p) {
    return p + web_context.url + web_context.headers.token
}
```

**Comment by VillanCh** [comment]
感谢师傅反馈，不过热加载部分应该是可以 beforeRequest 中可以操作

但是日常确实应该可以保留这几个变量

**Comment by WAY29** [comment]
Ref: yaklang/yaklang#614
