### ISSUE TITLE
【求助】pikachu 靶场中的 token 放爆破如何使用序列？

### ISSUE THREAD

**Issue by mewhz** [yaklang/yakit#1167]
尝试了热加载方法后，在该项目的 issues 中发现有尝试使用序列去解决响应包返回的随机 token
于是也想尝试一下，但是不知道为何，每次我执行序列都会使用第一次获取的 token 值，请问有办法每次使用新获取的 token嘛？
以下是我 yakit 的序列和 fuzzer 的配置
![image](https://github.com/yaklang/yakit/assets/48837161/28516a36-a4b5-4a56-842d-dc5da396dd7a)
![image](https://github.com/yaklang/yakit/assets/48837161/b6c17048-488d-49fe-9664-76ce74a4d73c)
![image](https://github.com/yaklang/yakit/assets/48837161/ae77ef2a-c087-4106-bee7-49aab8f0c288)

**Comment by VillanCh** [comment]
在步骤二中直接使用 x(pass_top25) 对应的是第一个 key 的分身，师傅可以在第一个请求中就定义好 x(pass_top25)

具体做法是，在步骤一中设置变量，为变量添加。“fuzztag” 类型的变量，设置为 {{x(pass_top25)}} ，然后在后续的步骤中使用变量名

**Comment by mewhz** [comment]
感谢师傅的解答，我这边尝试修改步骤一和步骤二后，的确可以获取到不同的 token，但是每个响应依然提示 csrf token error，请问师傅这样该如何修改配置？
![image](https://github.com/yaklang/yakit/assets/48837161/0d125541-f14d-4bc7-965c-78241ee37a63)
![image](https://github.com/yaklang/yakit/assets/48837161/2db6b96c-31dc-4bdc-8f2f-1de5854dddb8)
![image](https://github.com/yaklang/yakit/assets/48837161/9304fdd4-68ab-4545-9e21-ae165a438caa)

**Comment by VillanCh** [comment]
一般来说，感觉是 Cookie 和 CSRF Token 绑定关系的问题，获取了 token 确实没错，但是需要获取相应中的 Cookie 以对应 CSRF Token

**Comment by Go0p** [comment]
没有复现出来你说的情况

Step 1：

![image](https://github.com/yaklang/yakit/assets/38928800/c621e8dd-57f7-4975-8cb2-81d56ddc6151)

Step 2:

![image](https://github.com/yaklang/yakit/assets/38928800/1ca89ba8-f5f8-41ea-90b8-47d22d618fd5)


爆破:

![image](https://github.com/yaklang/yakit/assets/38928800/f9e638be-b9f2-45f2-b282-46dccfe8a7e7)


响应结果验证

![image](https://github.com/yaklang/yakit/assets/38928800/b1bc7bde-6fa7-418e-b190-3649e7e95c2f)

**Comment by mewhz** [comment]
感谢师傅的耐心解答，我刚刚又一次尝试了一下，依然没有成功。并且尝试了重新安装 pikachu 靶场和 yakit 应用，又在虚拟机中重新尝试，均没有成功；不知道是不是我的整体流程有问题。
![image](https://github.com/yaklang/yakit/assets/48837161/43e870b7-cd20-45db-b659-5dbe1a047301)

![image](https://github.com/yaklang/yakit/assets/48837161/5b4e4293-9841-4462-920d-a23596348ec1)

![image](https://github.com/yaklang/yakit/assets/48837161/2a98fe4d-cf43-4aef-8e73-71c1c3a6171c)

![image](https://github.com/yaklang/yakit/assets/48837161/94ef8973-98bb-45cf-a309-336d501dab53)

![image](https://github.com/yaklang/yakit/assets/48837161/a36f08e2-74b8-4147-891c-1cbb63098e85)

![image](https://github.com/yaklang/yakit/assets/48837161/abc2489e-06ef-489e-838c-d5df25b54fd4)

![image](https://github.com/yaklang/yakit/assets/48837161/fe4dd04e-1cf4-4c6c-94c9-acbf83ceddd1)

![image](https://github.com/yaklang/yakit/assets/48837161/28cefd94-0cc4-46b4-a64e-dfcc98e9e3e2)


除此之外，其余设置均使用默认设置

**Comment by Go0p** [comment]
不然你试试在线的靶场 ？

http://1.116.45.67:82/

**Comment by WAY29** [comment]
师傅可以尝试把GET请求中的Cookie请求头删除，猜测原因可能是因为在服务器中，它的token是与PHPSESSID一一对应的，而在并发的情况下，你使用相同的Cookie请求头去获取token，这会导致后端存储的token被刷新，而此时你拿先前获取到的Token来进行爆破，就会导致csrf token error

**Comment by mewhz** [comment]
感谢各位师傅的帮助，经过调试确实是要删除请求头中的 Cookie 请求，已经测试成功，非常感谢🥳
