### ISSUE TITLE
导入 Yak 插件失败时日志不显示报错，右下角依然显示导入成功

### ISSUE THREAD

**Issue by YSwanmei** [yaklang/yakit#117]
如下图，从Git仓库在线导入插件时，由于网络原因导入失败，但是日志却不显示成功或者失败，右下角依然显示导入成功，建议把console的报错信息展示到前端并提示失败原因。
![image](https://user-images.githubusercontent.com/31237601/153405345-dd22a22a-c9ed-4000-bdf2-3517994063ff.png)
![image](https://user-images.githubusercontent.com/31237601/153405857-a969597b-633a-4021-b9ca-2fb49e76439e.png)

![image](https://user-images.githubusercontent.com/31237601/153405807-76bc114e-8d88-4fc4-b2c1-a9ddbbf83362.png)

**Comment by VillanCh** [comment]
收到，我记下了，下一个版本这边应该会及时修复，感谢提醒🙏



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: YSwanmei ***@***.***&gt;
发送时间: 2022年2月10日 20:09
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 导入 Yak 插件失败时日志不显示报错，右下角依然显示导入成功 (Issue #117)





 
如下图，从Git仓库在线导入插件时，由于网络原因导入失败，但是日志却不显示成功或者失败，右下角依然显示导入成功，建议把console的报错信息展示到前端并提示失败原因。
 
 
 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
