### ISSUE TITLE
【BUG】异常资源占用

### ISSUE THREAD

**Issue by chachajx** [yaklang/yakit#1175]
在渗透测试过程中，使用yakit进行抓包，然后在history功能模块中使用搜索关键字功能，apple m1pro芯片直接cpu拉满到100..
![image](https://github.com/yaklang/yakit/assets/65016180/b223bb7c-04ca-4c07-b54b-6f95e32ea13c)
![image](https://github.com/yaklang/yakit/assets/65016180/69279519-4809-4123-bb85-43019cf04579)
![image](https://github.com/yaklang/yakit/assets/65016180/b8652415-cbdc-4e42-a792-cfb802da4f33)

**Comment by VillanCh** [comment]
没有复现这个问题，师傅可以尝试新建一个 Project 或删除一些历史记录，或者 设置 -> 删除所有缓存

**Comment by chachajx** [comment]
> 如果没有复现这个问题，师傅可以尝试新建一个项目或者删除一些历史记录，或者设置->删除所有服务器

好嘞师傅，可能是我这边的偶发问题，我再使用看看
