### ISSUE TITLE
【需求】fuzztag生成字典太好用了,墙裂导出结果

### ISSUE THREAD

**Issue by VVeakee** [yaklang/yakit#1180]
## 需求描述
fuzztag生成字典太好用了,省去了py脚本的步骤
本来是要截取md5后的部分,但是目前还有substr的tag就先生成字典自己截取了
但是fuzztag的结果不能导出就很难受了
![image](https://github.com/yaklang/yakit/assets/85714114/3dd734b4-069b-4567-875c-7d85f043ef6c)

## 解决方案
增加导出结果的功能

**Comment by Vernon818** [comment]
好的，感谢师傅建议

**Comment by WAY29** [comment]
实际上想导出fuzz结果是一件很容易的事情，你可以使用类似`yak fuzz -t '{{int(1-10)}}'`的命令来生成fuzz结果，然后你只需要将输出重定向到文件中即可

**Comment by WAY29** [comment]
师傅可以试一下这个插件：fuzztag表格生成，ID是c4bbc966-9177-4742-bee2-c359c4069b0a
