### ISSUE TITLE
【需求】加入gzip标签

### ISSUE THREAD

**Issue by pykiller** [yaklang/yakit#1182]
很多情况下需要使用gzip压缩文件，建议加入。

**Comment by OrangeWatermelon** [comment]
可以加

**Comment by pykiller** [comment]
> 可以加

怎么搞老哥

**Comment by OrangeWatermelon** [comment]
> > 可以加
> 
> 怎么搞老哥

![image](https://github.com/yaklang/yakit/assets/47558664/6975fd8e-8ea7-4d77-bf37-3dc2db1be4b6)
![image](https://github.com/yaklang/yakit/assets/47558664/0867940d-6b45-4b53-8b34-974ee4db10f5)
可以先这么用，我后面把这个函数加到标签里

**Comment by pykiller** [comment]
> > > 可以加
> > 
> > 
> > 怎么搞老哥
> 
> ![image](https://user-images.githubusercontent.com/47558664/281642623-6975fd8e-8ea7-4d77-bf37-3dc2db1be4b6.png) ![image](https://user-images.githubusercontent.com/47558664/281642695-0867940d-6b45-4b53-8b34-974ee4db10f5.png) 可以先这么用，我后面把这个函数加到标签里

非常感谢🥳
