### ISSUE TITLE
【需求】风险与漏洞模块增加删除所有标签

### ISSUE THREAD

**Issue by wuxiaodai** [yaklang/yakit#1185]
## 需求描述

在实际测试过程中有个漏洞误报了几百条漏洞信息，需要删除这些错误信息，删除数据一次只能删除20条显示数据

## 解决方案

增加一键删除（清空）所有风险与漏洞，或者20/page 增加 50/page 100/page

## 可选方案

请清晰明确地描述你考虑过的其他方案或功能。

## 附加信息

请提供任何与该功能请求相关的上下文信息、截图或其他材料等。

**Comment by Vernon818** [comment]
好的，感谢师傅建议
