### ISSUE TITLE
【需求】大返回包显示不全

### ISSUE THREAD

**Issue by VVeakee** [yaklang/yakit#1189]
## 需求描述
![image](https://github.com/yaklang/yakit/assets/85714114/214ced26-1da1-45d6-9042-0a1c441f0cdf)

该包返回的是图片的base64编码,最下方有key看不到
burp中的显示
![image](https://github.com/yaklang/yakit/assets/85714114/86e85851-0a5c-4170-ab6d-04683808ffd5)

**Comment by VillanCh** [comment]
一般来说在右上角可以下载body内容或者打开本地文件





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: VVeaker ***@***.***&gt;
发送时间: 2023年11月13日 13:08
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 【需求】大返回包显示不全 (Issue #1189)





 
需求描述
 

 
该包返回的是图片的base64编码,最下方有key看不到
 burp中的显示

**Comment by Vernon818** [comment]
师傅可以更新一下新版yakit，超出限制的响应可以点击打开本地文件查看
![image](https://github.com/yaklang/yakit/assets/94944398/39944fce-dd91-4fb4-9d31-bf214de34fe1)
