### ISSUE TITLE
远程模式希望添加一个记住配置的选项

### ISSUE THREAD

**Issue by izj007** [yaklang/yakit#12]
远程模式希望添加一个记住配置的选项，貌似每一次退出之后重新连接都需要重新去填写ip和端口，有时候配置了证书就需要去复制，希望添加一个像cs一样的有记录配置的功能，这样切换服务端比较方便，谢谢大佬了

**Comment by Vernon818** [comment]
@izj007 @evi1hack 为了感谢您对yak和yakit的支持，我们想邮寄一份小礼物给您，麻烦您微信添加一下：Juzi19880818，并备注好您的github账号。如已经添加账号，请微信联系我一下，谢谢
