### ISSUE TITLE
您好请问域认证的应用如何代理？

### ISSUE THREAD

**Issue by chatwithyou** [yaklang/yakit#1204]
域认证的应用应该怎么代理抓包，类似burp 可以添加ntlm认证，请问yakit有类似的解决办法吗
![8b5aac5dd6c162d6e8f59414dba50ccd](https://github.com/yaklang/yakit/assets/130202397/070ce0f6-6e87-4e78-be44-b07b3cf89350)

**Comment by rookieBC** [comment]
目前只有Yak引擎支持，师傅现在可以使用Yak编程使用这部分的支持，我们后面也会为Yakit增加对应的GUI

**Comment by WAY29** [comment]
![image](https://github.com/yaklang/yakit/assets/41830147/27b5f861-ff4c-4f31-ac3e-6ee515e9c3ec)
师傅现在可以在Yakit的这个地方进行认证设置
