### ISSUE TITLE
【BUG】反连服务器的公网穿透报错

### ISSUE THREAD

**Issue by bupsdx** [yaklang/yakit#1216]
## 问题描述

反连服务器的公网穿透功能报错
1、按官方教程，上面填写IP，下面填写端口，链接后报错。同时公网服务器侧没有收到数据包
![image](https://github.com/yaklang/yakit/assets/72397929/a65f0eea-1a40-4341-995d-467181cadd16)
![image](https://github.com/yaklang/yakit/assets/72397929/ded5cc32-2b42-4a0d-a9f6-b50a95580407)

2、如果在IP后面补上端口，可以连接服务器，但是报错如下，同时服务器上可以收到数据包
![image](https://github.com/yaklang/yakit/assets/72397929/3b78ff7e-8a0f-423e-9e58-7b4acaa65043)
![image](https://github.com/yaklang/yakit/assets/72397929/6067c2c8-1b51-48af-b743-36e170fa9a84)

感觉像是忘了把端口拼接进去？
公网服务器linux，测试telnet端口通

## 环境信息

- 操作系统: win32
- 系统架构: x64
- Yakit 版本: 1.2.7-sp5
- YakLang 版本: v1.2.8-sp5

**Comment by VillanCh** [comment]
公网 Bridge 的端口需要和穿透端口不一样

**Comment by bupsdx** [comment]
了解~我看官网打码的图，以为就是IP地址
