### ISSUE TITLE
加一个扫描暂停，还能继续的功能就好了

### ISSUE THREAD

**Issue by XvChengNuo** [yaklang/yakit#1226]

**Comment by VillanCh** [comment]
这个功能核心引擎已经实现，现在在等待前端排期和实现，用不了几个版本应该就能和大家见面了

**Comment by XvChengNuo** [comment]
> 这个功能核心引擎已经实现，现在在等待前端排期和实现，用不了几个版本应该就能和大家见面了

牛的

**Comment by XvChengNuo** [comment]
> 这个功能核心引擎已经实现，现在在等待前端排期和实现，用不了几个版本应该就能和大家见面了

大佬，但是当我用批量插件扫描多个目标的话，总是会卡住然后就不动了

**Comment by VillanCh** [comment]
这个问题在新的版本中也会解决



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: XvChengNuo ***@***.***&gt;
发送时间: 2023年11月29日 23:04
收件人: yaklang/yakit ***@***.***&gt;
抄送: v1ll4n ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [yaklang/yakit] 加一个扫描暂停，还能继续的功能就好了 (Issue #1226)





  
这个功能核心引擎已经实现，现在在等待前端排期和实现，用不了几个版本应该就能和大家见面了
  
大佬，但是当我用批量插件扫描多个目标的话，总是会卡住然后就不动了
