### ISSUE TITLE
上传fuzz字典会导致CPU上升到100%

### ISSUE THREAD

**Issue by bigfishnew** [yaklang/yakit#1238]
上传文件特别慢 132kb要上传好久而且CPU会上升到 100%
连接方式：本地连接
yakit版本：社区版 Yakit v1.2.8
yaklang版本：Yaklang v1.2.9
![Snipaste_2023-12-02_16-55-29](https://github.com/yaklang/yakit/assets/103395709/e59f3558-19c5-4048-bfca-6eea127da47c)

**Comment by VillanCh** [comment]
在下周五的版本中，字典会重构，有新的UI和新的后端接口～



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: bigfishnew ***@***.***&gt;
发送时间: 2023年12月2日 16:58
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 上传fuzz字典会导致CPU上升到100% (Issue #1238)





 
上传文件特别慢 132kb要上传好久而且CPU会上升到 100%
 连接方式：本地连接
 yakit版本：社区版 Yakit v1.2.8
 yaklang版本：Yaklang v1.2.9
 Snipaste_2023-12-02_16-55-29.png (view on web)

**Comment by WAY29** [comment]
字典已经重构完成，师傅可以在尝试一下最新版的字典看看是否还有问题
