### ISSUE TITLE
Missing Language Change Option in Yakit Interface

### ISSUE THREAD

**Issue by VarmaKollu** [yaklang/yakit#1239]
Hey Team,

 I recently had the opportunity to explore Yakit. I like the application but encountered a challenge when running it. The interface is displayed exclusively in the Chinese language, posing difficulty for me to comprehend.

I would like to suggest the inclusion of a language change option within the application. This feature would greatly enhance user accessibility and make it more user-friendly, especially for individuals who are exploring and experimenting with the application for the first time.

**Comment by VillanCh** [comment]
Thank you for exploring Yakit. We are still in a period of rapid iteration of features and functionalities. Multilingual versions and internationalization are planned and will gradually commence in 2024. Moreover, we hope to bring international users a perfect set of functionalities and tool details. After all, tools based on a brand-new, advanced DSL (Domain-Specific Language), Yaklang, are not easily and quickly understood. The related ecosystem and knowledge base require multilingual support and internationalization.

**Comment by mastercho** [comment]
I will keep eye on this for English GUI, cant wait to test Yakit

**Comment by WAY29** [comment]
Ref: #1255

**Comment by VillanCh** [comment]
W.I.P in 2024 

XD

**Comment by NightlineStudios117** [comment]
i will keep an eye for german GUI.cant wait to explore and test yakit
