### ISSUE TITLE
MAC下每次使用Yakit MITM都需要重新导入证书才能正常访问https

### ISSUE THREAD

**Issue by PeNgPaiO** [yaklang/yakit#1243]
在mac上，每次打开Yakit使用MITM功能的时候，访问https协议都会报错

NET::ERR_CERT_AUTHORITY_INVALID
Subject: www.baidu.com
Issuer: Yakit MITM Root CA

重新导入证书后，就能够正常访问，但是只要重启yakit，之前导入的证书好像就不生效，又需要重新导入。

**Comment by PeNgPaiO** [comment]
把yakit-projects下的证书替换为bp的，问题消失。

**Comment by jielansudo** [comment]
你好，我也遇到你这样的问题，如何把yakit-projects目录下的证书替换为bp的，复制cacert.der 到yakit-projects目录即可吗，不需要其他目录修改吗，我试过这样，貌似不行。
