### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by burpheart** [yaklang/yakit#125]
使用file库中的ReadLines方法读取大体积文件时会占用大量内存 这限制了读取文件大小
建议增加逐行读取的操作
scan-service和synscan现有命令行一次只能扫描单一范围
建议增加从文件读取扫描列表的方法

**Comment by VillanCh** [comment]
感谢大哥的建议

相关接口在 yak 引擎内部有，但是 yak 语言的接口没有开放出来。大概在下一个版本预计 1.0.13-sp1+ 会添加流式文件处理的结果。

不过受限于目前 fuzz.Strings() 的处理模式，可能不是所有的文件大文件都可以很好的支持按行流式读取。

**Comment by WAY29** [comment]
文件读取已经有流式的按行回调函数：`file:ReadLinesWithCallback`
