### ISSUE TITLE
【bug】新版本参数着色后部分fuzztag没有颜色

### ISSUE THREAD

**Issue by VVeakee** [yaklang/yakit#1253]
![image](https://github.com/yaklang/yakit/assets/85714114/c86f8571-0688-42ce-98cb-b7049f202115)

![image](https://github.com/yaklang/yakit/assets/85714114/44cc34b5-8b1f-47bd-ad31-7bfe6ffbbdc0)

或许没考虑到body之外的fazztag?

**Comment by Vernon818** [comment]
好的，感谢师傅反馈

**Comment by WAY29** [comment]
Will fix by this pull request: #1273
