### ISSUE TITLE
【需求】Codec 中 Java  反序列化输出 Json 支持折叠

### ISSUE THREAD

**Issue by virusdefender** [yaklang/yakit#1261]
类似这种 Json 格式输出的需要支持折叠块，否则数据量比较大的时候看起来比较麻烦

![image](https://github.com/yaklang/yakit/assets/4939404/83dbd270-be43-4a32-b4ea-fd4beefc0908)

类似

![image](https://github.com/yaklang/yakit/assets/4939404/ec41ca63-308b-418c-93b9-c0916b4aff8f)

**Comment by WAY29** [comment]
codec将会在后续代码中进行重构，师傅可以先试用试验性功能-新版codec进行使用
