### ISSUE TITLE
【需求】建议发布时支持arm架构的Linux操作系统

### ISSUE THREAD

**Issue by Pyrrhax** [yaklang/yakit#1265]
在企业给安全人员配置了使用国产化操作系统的国产化笔记本电脑的情况下，有相当一部分笔记本为arm架构的Linux，建议在发布时增加对armLiunx既国产化设备的支持。

**Comment by cnrstar** [comment]
已经支持了，去官网下载哈~
https://yaklang.oss-cn-beijing.aliyuncs.com/yak/latest/Yakit-1.2.9-linux-arm64.AppImage
