### ISSUE TITLE
漏洞检测-批量执行 关键字匹配不准确

### ISSUE THREAD

**Issue by Superhero-zero** [yaklang/yakit#1269]
![image](https://github.com/yaklang/yakit/assets/66772820/7525b84c-3e9f-459a-9868-09ca491f0612)
匹配thinkphp关键字插件，但是还是筛选出了其他插件

**Comment by Vernon818** [comment]
这里搜索包含了插件名和代码这些，所以会搜索出来一些感觉像是不相关的插件
