### ISSUE TITLE
关于Web Fuzzer的建议

### ISSUE THREAD

**Issue by f1ashine** [yaklang/yakit#127]
POST请求在点击“改变HTTP方法成GET”后，POST请求的body、header中的“content-type”和“content-length”没有删掉

GET请求在点击“改变HTTP方法成POST”后，只在header加了“Content-Length”，“content-type”未添加

在修改为上传数据包之后，再点击修改get或者post，body内容未删除，希望可以优化下体验

**Comment by VillanCh** [comment]
感谢师傅提醒，马上就改好，大概在最快会在下一个引擎版本修复这个问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: f1ashine ***@***.***&gt;
发送时间: 2022年2月16日 12:40
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 关于Web Fuzzer的建议 (Issue #127)





 
POST请求在点击“改变HTTP方法成GET”后，POST请求的body、header中的“content-type”和“content-length”没有删掉
 
GET请求在点击“改变HTTP方法成POST”后，只在header加了“Content-Length”，“content-type”未添加
 
在修改为上传数据包之后，再点击修改get或者post，body内容未删除，希望可以优化下体验
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
