### ISSUE TITLE
【BUG】MITM手动劫持功能劫持不到数据

### ISSUE THREAD

**Issue by crazy-zxx** [yaklang/yakit#1271]
## 问题描述

MITM中在自动放行窗口显示心跳包，此时从默认的【自动放行】窗口切换到【被动日志】窗口，然后切换到【手动劫持】窗口，手动劫持就一直拦截不到请求了。但是历史记录里会显示请求数据包在一直正常更新。

## 复现步骤

1. 启动MITM后，默认进入自动放行窗口，出现心跳包。
![image](https://github.com/yaklang/yakit/assets/29439759/61e098d6-66cd-45f3-84df-b9c557356c2c)

2. 切换到被动日志。
![image](https://github.com/yaklang/yakit/assets/29439759/a0730b8d-0251-4e64-8258-7ba97f842574)

3. 切换到手动劫持，发现拦截不到请求。
![image](https://github.com/yaklang/yakit/assets/29439759/36c4bae2-fb98-499f-ac48-b4e7107639d1)

4. 查看history，发现在劫持状态依然在刷新数据包，数据包手动拦截失效了。
![image](https://github.com/yaklang/yakit/assets/29439759/6737f77d-0126-453b-89f8-9da5e4d1ee53)

**该bug可以稳定复现**

## 环境信息

- 操作系统: win32，Windows 11 23H2 22631.2792
- 系统架构: x64
- Yakit 版本: 1.2.8-sp1
- YakLang 版本: v1.2.9-sp2

**Comment by crazy-zxx** [comment]
难道说这个手动劫持，只有停留在这个手动劫持窗口的时候才起作用，即使没提交数据，但是切换到自动放行窗口后所有之前阻塞的都在一瞬间发出去了，所以才会看到很多心跳包被自动放行的现象吗？
不像bp那样，拦截到了数据包就一直阻塞？拦截期间还可以切换窗口查看历史请求数据包？
我觉得bp设计挺合理的，可以借鉴。
而不应该单纯的切换手动劫持和自动放行窗口就改变数据包的拦截和放行行为，使得用户无法在拦截请求的同时查看历史数据包了。

**Comment by VillanCh** [comment]
在Histroy可以同时查看实时流量，不一定必须要MITM列表查看，BP中也是分了两个Tab的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Xiangxin ***@***.***&gt;
发送时间: 2023年12月13日 13:36
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 【BUG】MITM手动劫持功能劫持不到数据 (Issue #1271)





 
难道说这个手动劫持，只有停留在这个手动劫持窗口的时候才起作用，即使没提交数据，但是切换到自动放行窗口后所有之前阻塞的都在一瞬间发出去了，所以才会看到很多心跳包被自动放行的现象吗？
 不像bp那样，拦截到了数据包就一直阻塞？拦截期间还可以切换窗口查看历史请求数据包？
 我觉得bp设计挺合理的，可以借鉴。
 而不应该单纯的切换手动劫持和自动放行窗口就改变数据包的拦截和放行行为，使得用户无法在拦截请求的同时查看历史数据包了。

**Comment by crazy-zxx** [comment]
> 在Histroy可以同时查看实时流量，不一定必须要MITM列表查看，BP中也是分了两个Tab的 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Xiangxin ***@***.***&gt; 发送时间: 2023年12月13日 13:36 收件人: yaklang/yakit ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [yaklang/yakit] 【BUG】MITM手动劫持功能劫持不到数据 (Issue #1271) 难道说这个手动劫持，只有停留在这个手动劫持窗口的时候才起作用，即使没提交数据，但是切换到自动放行窗口后所有之前阻塞的都在一瞬间发出去了，所以才会看到很多心跳包被自动放行的现象吗？ 不像bp那样，拦截到了数据包就一直阻塞？拦截期间还可以切换窗口查看历史请求数据包？ 我觉得bp设计挺合理的，可以借鉴。 而不应该单纯的切换手动劫持和自动放行窗口就改变数据包的拦截和放行行为，使得用户无法在拦截请求的同时查看历史数据包了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

感谢，确实如此。我大意了，没有闪。QAQ
我确认了一下，是我使用不当。拦截请求的功能是ok的，切换到自动放行窗口后所有之前阻塞的都在一瞬间发出去了，所以才会看到很多心跳包被自动放行的现象。

但是，这个拦截不到请求的bug，确实存在。
复现步骤：MITM劫持启动之后，从默认的【自动放行】窗口切换到【被动日志】窗口，然后切换到【手动劫持】窗口，就拦截不到请求了。但是历史记录里会显示请求数据包在一直更新。

**Comment by VillanCh** [comment]
> 
> 但是，这个拦截不到请求的bug，确实存在。 复现步骤：MITM劫持启动之后，从默认的【自动放行】窗口切换到【被动日志】窗口，然后切换到【手动劫持】窗口，就拦截不到请求了。但是历史记录里会显示请求数据包在一直更新。

感谢师傅反馈额，这个 BUG 在修了，不出意外的话，这周五的版本应该可以修好，确实是“被动日志”切换有问题
