### ISSUE TITLE
专项漏洞检测模块没有任何插件

### ISSUE THREAD

**Issue by yueqi77** [yaklang/yakit#1284]
## 问题描述

专项漏洞检测模块没有任何插件

## 预期行为

专项漏洞检测插件正常

## 实际行为
专项漏洞检测模块没有任何插件
![image](https://github.com/yaklang/yakit/assets/32604898/52854a37-f05d-47a0-b391-0d8279763db9)

## 复现步骤

1. https://github.com/yaklang/yakit/releases/tag/v1.2.8-sp1下载Yakit-1.2.8-sp1-windows-amd64.exe 
2. 安装，本地模式
3. 在线升级为1.2.9
4. 点开专项漏洞检测
5. 然后就发现里面的项目没有插件

## 环境信息

- 操作系统: Windows 11 家庭中文版
- 系统架构: x64
- Yakit 版本: 1.2.8-sp1
- YakLang 版本: v1.2.9-sp1

**Comment by tonyllsa** [comment]
插件需要自己去插件商店下载安装的，下好了就有了的

**Comment by yueqi77** [comment]
好的哦，已经解决，非常感谢！新手建议哈，我觉得这个插件使用顺序可以在手册提一提哎，比较不浪费你们的issues哈哈哈哈哈哈，我昨天提完后逛issues发现了之前有人提这个然后也去插件商店看了

**Comment by yueqi77** [comment]
> 插件需要自己去插件商店下载安装的，下好了就有了的

好的哦，已经解决，非常感谢！新手建议哈，我觉得这个插件使用顺序可以在手册提一提哎，比较不浪费你们的issues哈哈哈哈哈哈，我昨天提完后逛issues发现了之前有人提这个然后也去插件商店看了
