### ISSUE TITLE
无法抓取yakit自带的vulinbox靶场数据包

### ISSUE THREAD

**Issue by tonyllsa** [yaklang/yakit#1285]
## 问题描述

yakit搭建的vulinbox，在Google访问抓不到数据包，但是访问GitHub又可以抓到数据包。

## 预期行为

可以抓到靶场数据包

## 实际行为

不拦截数据包，靶场随意访问

## 复现步骤

1. 靶场正常启动
且可以访问

<img width="847" alt="3" src="https://github.com/yaklang/yakit/assets/127471434/ea900979-e69d-4339-8556-ec4cb083ac6f">

2.其他网站可以抓到数据包
<img width="986" alt="1" src="https://github.com/yaklang/yakit/assets/127471434/3d4238df-076b-4908-b155-6e01375cb2d1">

3.靶场不能抓数据包
<img width="943" alt="2" src="https://github.com/yaklang/yakit/assets/127471434/f49e6051-db6c-4105-9b9d-9daae23b2767">

## 环境信息

- 操作系统: win64
- 系统架构: x64
- Yakit 版本: 1.2.8-sp1
- YakLang 版本: v1.2.9-sp2

## 补充说明

如果您有任何其他有关该问题的信息或评论，请在此处添加。

**Comment by crazy-zxx** [comment]
这是本地回环地址127.0.0.1的问题，貌似bp也抓不了。

一般有俩解决方案：
1. 使用自己的内网IP替代127.0.0.1访问。前提是靶场监听的是0.0.0.0，不过一般靶场不会这样，so，推荐使用方案2。
2. 修改Windows系统的"C:\Windows\System32\drivers\etc\hosts"文件，加个自定义域名映射来解决。之后就可以通过这个自定义域名（www.vulinbox.local:8080）来替代 127.0.0.1:8080 来访问靶场实现抓包了。
    ```
    # vulinbox
    127.0.0.1 	www.vulinbox.local 
    ```

**Comment by tonyllsa** [comment]
感谢指导，用的是方法1，成功解决问题（因为方法2访问失败了）。
关于bp我的是可以抓127.0.0.1:8787的，就不是很懂了。 @crazy-zxx
