### ISSUE TITLE
【BUG】fuzz语法失效

### ISSUE THREAD

**Issue by crazy-zxx** [yaklang/yakit#1300]
## 问题描述

关于在fuzz的时候，有多个位置需要重复渲染与独立渲染的问题，参考你们给出的文档和代码( [https://www.yaklang.com/docs/buildinlibs/lib_fuzz#%E5%9F%BA%E7%A1%80%E6%A0%87%E7%AD%BEint-%E6%B8%B2%E6%9F%93%E6%95%B4%E6%95%B0%E7%AB%AF%E5%8F%A3](https://www.yaklang.com/docs/buildinlibs/lib_fuzz#%E5%9F%BA%E7%A1%80%E6%A0%87%E7%AD%BEint-%E6%B8%B2%E6%9F%93%E6%95%B4%E6%95%B0%E7%AB%AF%E5%8F%A3) )，我得出了与文档恰恰相反的结果，并且预期的正确fuzz语法无法渲染成功。

## 复现步骤

① 对于重复渲染，文档解释如下：

![image](https://github.com/yaklang/yakit/assets/29439759/232f2bae-bb00-4c2e-ad1e-170a4c102323)

而我执行代码得到的结果恰恰相反：

![image](https://github.com/yaklang/yakit/assets/29439759/02247a25-9a72-4512-8f23-075a937b4983)

② 对于独立渲染，文档解释如下：

![image](https://github.com/yaklang/yakit/assets/29439759/b61baa6d-50ac-4902-8c1c-b9a7b93adb8c)

而我执行代码得到的结果表明独立渲染直接失效了？

![image](https://github.com/yaklang/yakit/assets/29439759/7817f514-abae-4659-ade2-18e89f1e65f4)

## 环境信息

- 操作系统: win32，Windows 11 23H2 22631.2792
- 系统架构: x64
- Yakit 版本: 1.2.8-sp2
- YakLang 版本: v1.2.9-sp3

**Comment by OrangeWatermelon** [comment]
官网文档太久没更新了，明天更新下，师傅可以先看下最近公众号发的一篇文章
https://mp.weixin.qq.com/s/r6XN9HWJlKOSYSIqh0RZ2Q

可以测试下这两个案例
笛卡尔乘积：{{int(1-5)}}{{int(1-5)}}
同步渲染：{{int::1(1-5)}}{{int::1(1-5)}}
