### ISSUE TITLE
希望可以自定义安装位置

### ISSUE THREAD

**Issue by zsvpleased** [yaklang/yakit#1303]
## 需求描述

希望Yakit安装时能够自定义选择安装路径，并且项目文件可以自定义保存路径，插件也是相同。而不是默认就全在C盘。
C盘占用也很高，能自定义位置，或者免安装方式，我相信更多人更愿意集成到自己的武器库中。

## 附加信息

请提供任何与该功能请求相关的上下文信息、截图或其他材料等。
![图片](https://github.com/yaklang/yakit/assets/99797624/1c57b8bf-c3f4-467b-89fd-5c8ce3b16475)

**Comment by WAY29** [comment]
Repeat #508
