### ISSUE TITLE
一个小建议：正则修改返回包

### ISSUE THREAD

**Issue by sp4rkw** [yaklang/yakit#131]
认真的翻了相关功能和文档，好像没有burp中正则修改返回包的功能？强烈建议加上！
虽然手动劫持的时候可以修改返回包，但是一个个修改非常麻烦，而且有些功能对于数据包的相应时间非常苛刻，手动修改来不及

**Comment by VillanCh** [comment]
感谢大哥的建议，我尝试看一下有没有一些比较简单的处理办法。


如果师傅着急使用的话可以按照下面的操作先顶一下：
被动扫描中有一个 ”热加载“ 代码的功能，代码模版中最后一个 hook 可以劫持到之后对流量做任意处理并把处理后的流量返回。
这个功能可以实现用户对代码的任何处理，缺点是需要用户手动编写一些代码脚本来完成，或者使用 MITM 插件来实现这个目的。

**Comment by sp4rkw** [comment]
我去尝试编写一下，有问题再和您沟通，非常感谢
