### ISSUE TITLE
【需求】过滤器一键过滤所有ip类地址

### ISSUE THREAD

**Issue by VVeakee** [yaklang/yakit#1337]
## 需求描述

抓包的时候有时候会莫名其妙出现很多ip地址,用ip过滤,ip又乱又多,用路径过滤他们路径又不一样,反正都是干扰包,不如直接ip全部过滤掉,有需要测试ip网站的时候再开就行了

**Comment by WAY29** [comment]
现在过滤器中（除了后缀）支持编写正则表达式了，只需要在排除Hostname中写入一个ip的正则表达式即可
