### ISSUE TITLE
【需求】反连服务中添加反序列化功能

### ISSUE THREAD

**Issue by lcl-367** [yaklang/yakit#1352]
## 需求描述

在ldap注入中遇到存在反序列化漏洞的组件，希望可以通过LDAP的 javaSerializedData反序列化本地gadget来绕过高版本jdk的限制

## 解决方案

我希望产品能够实现以下功能：在开启反连时能够选择结合一些常见的反序列化gadget进行利用，而不只是恶意类

**Comment by OrangeWatermelon** [comment]
更新到最新版本，支持了
