### ISSUE TITLE
项目管理中的default项目怎么删除

### ISSUE THREAD

**Issue by jinjiao070** [yaklang/yakit#1354]
default项目该怎么删除，占用空间很大，没找到删除按钮也没有找到类似清空的功能

**Comment by VillanCh** [comment]
可以直接在项目文件目录把*.db文件删除～





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jinjiao070 ***@***.***&gt;
发送时间: 2024年1月11日 09:38
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 项目管理中的default项目怎么删除 (Issue #1354)





 
default项目该怎么删除，占用空间很大，没找到删除按钮也没有找到类似清空的功能
