### ISSUE TITLE
【需求】fuzz标签重命名焦点自动集中到输入框

### ISSUE THREAD

**Issue by VVeakee** [yaklang/yakit#1355]
## 需求描述

![image](https://github.com/yaklang/yakit/assets/85714114/1abaf72c-bed5-4265-a168-80d74168b6bc)
![image](https://github.com/yaklang/yakit/assets/85714114/f996ac6f-c0a5-403b-acee-578007c66e59)
需要点一下才能输入,有了焦点后还有先删除原来的WF-[13],
预期点击重命名后直接可以按键输入新的名字
类似全选的状态,点击重命名后自动全选
![image](https://github.com/yaklang/yakit/assets/85714114/ca5aa066-1602-48bf-8691-a179daa93569)
如果不需要改名字点击确定仍就是原来的名字
如果需要改新名字直接输入新名字即可

**Comment by Vernon818** [comment]
好的，感谢反馈，我们优化一下

**Comment by WAY29** [comment]
will support in this pr：#1418
