### ISSUE TITLE
【需求】漏洞模块能不能加上请求包和响应包

### ISSUE THREAD

**Issue by jinjiao070** [yaklang/yakit#1358]
漏洞模块能不能加上请求包和响应包，现在这个详情太丑陋了，第一次用根本看不懂啥意思。。。如果已经有这个功能了的话，在哪里看呢？

**Comment by Go0p** [comment]
不是有漏洞请求包和响应包吗

![image](https://github.com/yaklang/yakit/assets/38928800/a1176ebb-2447-49e8-b69a-9c4f3ac0b3de)

**Comment by jinjiao070** [comment]
> 不是有漏洞请求包和响应包吗
> 
> ![image](https://private-user-images.githubusercontent.com/38928800/296143968-a1176ebb-2447-49e8-b69a-9c4f3ac0b3de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDAwNzUsIm5iZiI6MTcwNTAzOTc3NSwicGF0aCI6Ii8zODkyODgwMC8yOTYxNDM5NjgtYTExNzZlYmItMjQ0Ny00OWU4LWI2OWEtOWM0ZjNhYzBiM2RlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA2MDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMTg3MjI0NmQxYjVlOThhOGQ5OTc3Y2ViMDYzN2FhN2JjODA3ZGJmOTkxMWY0MDlkMjY3M2I3NjM1M2Q5NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9YkC0zYkQqUYs2X5zPKQ-7_lG-SSkjKG-kvxrIEV83A)

。。。应该是我这环境有啥问题 我这里没看到图片里的请求和响应这两个栏目，我重新安装一下试试

**Comment by Go0p** [comment]
是有一些 插件里可能没有规范写，但是大部分的插件是请求和响应包的
