### ISSUE TITLE
链接失效

### ISSUE THREAD

**Issue by daikerSec** [yaklang/yakit#136]
Windows(x64) 下载：
https://yaklang.oss-cn-beijing.aliyuncs.com/yak//yak_windows_amd64.exe
MacOS(intel/m1) 下载：
https://yaklang.oss-cn-beijing.aliyuncs.com/yak//yak_darwin_amd64
Linux(x64) 下载：
https://yaklang.oss-cn-beijing.aliyuncs.com/yak//yak_linux_amd64

![image](https://user-images.githubusercontent.com/26897699/154655956-e7f0959b-4b7c-4e9b-bc58-2a7eed5e33cc.png)

**Comment by VillanCh** [comment]
\*yak/latest/yak_\* 即可下载

一般这种情况出现是访问阿里云遇到问题，过几分钟就好了。

**Comment by VillanCh** [comment]
> Windows(x64) 下载： https://yaklang.oss-cn-beijing.aliyuncs.com/yak//yak_windows_amd64.exe MacOS(intel/m1) 下载： https://yaklang.oss-cn-beijing.aliyuncs.com/yak//yak_darwin_amd64 Linux(x64) 下载： https://yaklang.oss-cn-beijing.aliyuncs.com/yak//yak_linux_amd64
> 
> ![image](https://user-images.githubusercontent.com/26897699/154655956-e7f0959b-4b7c-4e9b-bc58-2a7eed5e33cc.png)

可能是由于同 IP 下有人发起攻击或其他原因，导致 IP 被阿里云暂时封禁

也可以使用这里下载引擎二进制文件 [手动安装核心引擎下载地址](https://www.yaklang.io/docs/startup#%E6%89%8B%E5%8A%A8%E4%B8%8B%E8%BD%BD--%E5%AE%89%E8%A3%85)

**Comment by VillanCh** [comment]
最新的版本中如果获取不到版本，将会自动使用 “/latest/” 这个问题应该可以解决了

**Comment by VillanCh** [comment]
新的版本修复了版本获取不到导致下载链接失效的问题~ 

Happy Game! yakit-1.0.13-sp3
