### ISSUE TITLE
配置外部插件源菜单没了

### ISSUE THREAD

**Issue by Liehu** [yaklang/yakit#1364]
<img width="194" alt="PixPin_2024-01-15_01-51-39" src="https://github.com/yaklang/yakit/assets/4949212/010e1b9a-b00f-41b0-8acc-7d127e8a5397">

**Comment by Vernon818** [comment]
师傅，我们统一放在外面了
![image](https://github.com/yaklang/yakit/assets/94944398/dbaa5bf9-4d4b-4d76-babc-56430ea159eb)

**Comment by Vernon818** [comment]
师傅我们统一放在外面了
![image](https://github.com/yaklang/yakit/assets/94944398/2176c1e4-ba83-4abc-910a-91ffd8797abe)
