### ISSUE TITLE
劫持mmtls乱码咋么解决

### ISSUE THREAD

**Issue by mxh13920** [yaklang/yakit#1367]
POST /mmtls/0000592a HTTP/1.1
Accept: */*
Cache-Control: no-cache
Connection: close
Content-Length: 1287
Content-Type: application/octet-stream
Host: 101.227.131.222
Upgrade: mmtls
User-Agent: MicroMessenger Client
X-Online-Host: 101.227.131.222

�
![Uploading Snipaste_2024-01-15_16-14-48.png…]()

**Comment by Vernon818** [comment]
师傅，你这个图片没传上来，看不见，麻烦师傅再上传一下，或者加我微信发我（Juzi19880818）
