### ISSUE TITLE
引擎未完全启动，无法连接

### ISSUE THREAD

**Issue by dh-666** [yaklang/yakit#1369]
更新之后，本地模式一直连接超时
![微信图片_20240116153411](https://github.com/yaklang/yakit/assets/142130878/4d21bebd-bd91-48c2-afac-46bc755971ce)

**Comment by VillanCh** [comment]
师傅点一下小风车里面的重置引擎然后重启即可，这周也会修复一点这儿的小问题

**Comment by dh-666** [comment]
> 师傅点一下小风车里面的重置引擎然后重启就可以了，这周又修复了一点的小问题

好的感谢，已经可以了
