### ISSUE TITLE
求助：fuzz无法生成数字和字母混合字符串

### ISSUE THREAD

**Issue by lingwu111** [yaklang/yakit#1373]
比如，爆破时需要a-zA-Z0-9的字符串，e.g.  d8fdk90kdfn2、fdk9kn2kfdm ,这种的fuzz字段怎么写？我看文档随机字符串不包含数字，这种需求的时候没法写呀。

**Comment by VillanCh** [comment]
使用regen和regen::one标签
反向正则可以生成数据～



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 凌舞 ***@***.***&gt;
发送时间: 2024年1月17日 15:19
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 求助：fuzz无法生成数字和字母混合字符串 (Issue #1373)





 
比如，爆破时需要a-zA-Z0-9的字符串，e.g.  d8fdk90kdfn2、fdk9kn2kfdm ,这种的fuzz字段怎么写？我看文档随机字符串不包含数字，这种需求的时候没法写呀。
