### ISSUE TITLE
m1 最新版本yakit  证书问题

### ISSUE THREAD

**Issue by jielansudo** [yaklang/yakit#1377]
m1 已经把证书添加为始终信任了，但是还是无法正常抓包，一访问https 就会有如下报错，
<img width="1512" alt="Snipaste_2024-01-19_10-29-20" src="https://github.com/yaklang/yakit/assets/50390082/ecea4cd0-cec5-4d82-a3a9-b139c46685d9">

<img width="877" alt="Snipaste_2024-01-19_10-28-35" src="https://github.com/yaklang/yakit/assets/50390082/b9ad3030-a688-4daf-9e7c-f5d65d29564c">
已升级到最新版本了
<img width="369" alt="Snipaste_2024-01-19_10-28-22" src="https://github.com/yaklang/yakit/assets/50390082/fb1968df-dc24-4764-b942-ecc7f9869c47">

我导入burp的证书是正常，没有图一的报错

**Comment by OrangeWatermelon** [comment]
师傅执行命令ls -l ~/yakit-projects，看下目录下yak-mitm-ca的权限

**Comment by VillanCh** [comment]
免配置浏览器可用吗？如果可用的话，说明可能程序本身没有啥问题，证书权限有问题，可以手动删除 `~/yakit-projects/*.crt` 重启程序，会重新生成证书
