### ISSUE TITLE
【报毒】360报毒yakit-profile-plugin.db项目文件为PHP木马

### ISSUE THREAD

**Issue by VBPush** [yaklang/yakit#1379]
【报毒】360报毒yakit-profile-plugin.db项目文件为PHP木马
![image](https://github.com/yaklang/yakit/assets/140361823/1f1958a5-848b-4605-83fb-81adcdffecef)

另问个问题，为啥l漏洞这一块一直在刷接收到返连信息，我没开返连啊，啥都没开，地址是我公司的出口IP

![1705635290783](https://github.com/yaklang/yakit/assets/140361823/0aad088d-dc5a-4b9b-b9af-7bd1831429be)

**Comment by WAY29** [comment]
360杀毒应该是误报，因为我们的数据（包括插件内容）都是存储在sqlite数据库中的，而此数据库是没有加密的，360杀毒估计会扫描整个数据库，而你下载的某些插件中可能存在某些php代码的文本（例如代码执行），因此导致了误报
