### ISSUE TITLE
诊断 yak 核心引擎启动的错误：数据库权限错误 / localhost绑定的问题

### ISSUE THREAD

**Issue by ninefiger** [yaklang/yakit#138]
1. 本机环境macos12，装上yakit以后，启动grpc一直失败，手动启动了一下，发现~/yakit-projects/default-yakit.db 文件所属变成了root，该回来好了，（备注：log里的解决方案（1），应该是写错了，应该是chown命令）
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/20896099/155059300-2ba14737-549f-4979-9b1b-dc762bdff152.png">

2. 再次启动，有报错了，这有个有意思的地方，报错如图
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/20896099/155059400-5044cd1d-9776-4096-b9d3-f74507316fd4.png">
启动过程中，程序在lookup解析localhost，可能大部分兄弟的电脑环境可以解析出来这个localhost是127.0.0.1，但是我的网络环境，包括114.114.114.114的dns，解析不出来这个localhost，后来指向了一下好了，不过也建议师傅们考虑将localhost改成127.0.0.1

**Comment by VillanCh** [comment]
感谢师傅反馈，我下午来修复一下这个问题，额外应该再在Yakit再增加一些帮助排错的办法



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ninefiger ***@***.***&gt;
发送时间: 2022年2月22日 11:47
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 启动grpc遇到的两个小问题 (Issue #138)





  
本机环境macos12，装上yakit以后，启动grpc一直失败，手动启动了一下，发现~/yakit-projects/default-yakit.db 文件所属变成了root，该回来好了，（备注：log里的解决方案（1），应该是写错了，应该是chown命令） 
 

  
再次启动，有报错了，这有个有意思的地方，报错如图 
 

 启动过程中，程序在lookup解析localhost，可能大部分兄弟的电脑环境可以解析出来这个localhost是127.0.0.1，但是我的网络环境，包括114.114.114.114的dns，解析不出来这个localhost，后来指向了一下好了，不过也建议师傅们考虑将localhost改成127.0.0.1 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by VillanCh** [comment]
Yakit 新的版本中增加了错误排查和一件解决的方案

yakit-1.0.13-sp3
