### ISSUE TITLE
响应体中的中文unicode等编码能不能支持自动解码

### ISSUE THREAD

**Issue by smile-everyday** [yaklang/yakit#1382]
![image](https://github.com/yaklang/yakit/assets/33567645/42cefa55-0340-4ed6-b4db-d023ffaf12f7)
希望能够自动解码展示，不然每次都要右键选智能解码

**Comment by ViCrack** [comment]
我的话这块就不需要自动解码展示

**Comment by WAY29** [comment]
will add this feature in this [pr](https://github.com/yaklang/yakit/pull/1388)
