### ISSUE TITLE
【需求】请求包字段颜色搭配

### ISSUE THREAD

**Issue by mewhz** [yaklang/yakit#1387]
最近更新 yakit 发现，请求包字段颜色都变成了一种，请问能否内置几款可切换的字段颜色搭配，方便更好的查看每个字段
![image](https://github.com/yaklang/yakit/assets/48837161/4d4403c2-d439-427e-85ea-8188b9438abd)

**Comment by WAY29** [comment]
师傅你能分享一下数据包文本吗，这似乎是高亮有点问题

**Comment by mewhz** [comment]
```http
POST /ofcms-admin/admin/cms/template/save.json HTTP/1.1
Host: localhost:8080
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Content-Length: 5135
Origin: http://localhost:8080
DNT: 1
Sec-GPC: 1
Connection: keep-alive
Referer: http://localhost:8080/ofcms-admin/admin/cms/template/getTemplates.html
Cookie: JSESSIONID=5CE465604ECF469C30AF12E795D64F0B

file_path=D%3A%5CTomcat%5Cwebapps%5Cofcms-admin%5CWEB-INF%5Cpage%5Cdefault%5Cindex.html&dirs=%2F&res_path=&file_name=index.html&file_content=
```

**Comment by WAY29** [comment]
> ```httpspec
> POST /ofcms-admin/admin/cms/template/save.json HTTP/1.1
> Host: localhost:8080
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0
> Accept: application/json, text/javascript, */*; q=0.01
> Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
> Accept-Encoding: gzip, deflate
> Content-Type: application/x-www-form-urlencoded; charset=UTF-8
> X-Requested-With: XMLHttpRequest
> Content-Length: 5135
> Origin: http://localhost:8080
> DNT: 1
> Sec-GPC: 1
> Connection: keep-alive
> Referer: http://localhost:8080/ofcms-admin/admin/cms/template/getTemplates.html
> Cookie: JSESSIONID=5CE465604ECF469C30AF12E795D64F0B
> 
> file_path=D%3A%5CTomcat%5Cwebapps%5Cofcms-admin%5CWEB-INF%5Cpage%5Cdefault%5Cindex.html&dirs=%2F&res_path=&file_name=index.html&file_content=
> ```

已经找到问题了是Sec这个请求头的高亮匹配进入了状态之后没有退出，将在下一个版本修复，师傅临时想用的话可以先把这个请求头删除即可

**Comment by mewhz** [comment]
好的，感谢师傅
