### ISSUE TITLE
【bug】yakit靶场"CryptoJS.AES(CBC) 前端加密登陆表单"中概念错误！

### ISSUE THREAD

**Issue by wsYu9a** [yaklang/yakit#1390]
![image](https://github.com/yaklang/yakit/assets/99511228/10e26776-dde8-4cbd-87ec-3d1b0db68974)
AES默认使用的填充方式是 PKCS7Padding，但PKCS7Padding是在若明文块不足16个字节，在明文块末尾补足相应数量的字符，且每个字节的值等于缺少的字符数。而不是NULL
网上查到的，如果不对的话当我没说！
![image](https://github.com/yaklang/yakit/assets/99511228/d49949c8-75fa-4e18-afb9-1f652460da9b)
![image](https://github.com/yaklang/yakit/assets/99511228/8f8fb856-ba58-488c-a221-8b3ec3c0ea9d)

**Comment by VillanCh** [comment]
AES是AES，填充是填充，不同语言不通框架的填充行为是不同的，你甚至可以用ZeroPadding，并没有人规定AES必须用什么填充


这个一般属于约定，并不属于强制规定。
填充目的是为了让分块儿长度固定，任何填充方法都是可以的，只要最后还原了就好





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wsYu9a ***@***.***&gt;
发送时间: 2024年1月23日 23:38
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 【bug】yakit靶场"CryptoJS.AES(CBC) 前端加密登陆表单"中概念错误！ (Issue #1390)





 
image.png (view on web)
 AES默认使用的填充方式是 PKCS7Padding，但PKCS7Padding是在若明文块不足16个字节，在明文块末尾补足相应数量的字符，且每个字节的值等于缺少的字符数。而不是NULL
 网上查到的，如果不对的话当我没说！
 image.png (view on web)
 image.png (view on web)
