### ISSUE TITLE
标签拖动问题

### ISSUE THREAD

**Issue by xigagas** [yaklang/yakit#1391]
https://github.com/yaklang/yakit/assets/139865587/98233d04-614c-4049-8bf6-5ae55e8f1145

拖动后卡死

**Comment by Vernon818** [comment]
是不是拖动以后标签页拖动不了了

**Comment by Vernon818** [comment]
师傅可以关闭以后再打开看看，应该就好了，先将就用一下，这个比较难改，我让师傅们看看

**Comment by Vernon818** [comment]
我知道是什么问题了，师傅先用右键操作一下，这个比较难改，我让师傅们看看

**Comment by Vernon818** [comment]
师傅更新最新版即可，已经修复好了
