### ISSUE TITLE
导出端口扫描中得到的IP和端口信息

### ISSUE THREAD

**Issue by 951240434** [yaklang/yakit#140]
导出端口扫描中得到的IP和端口信息
在一次端口扫描任务发现存活端口后，请问能否开发一个导出功能，能够批量导出IP和对应的端口为EXCEL或者TXT格式。或者辛苦告知一下扫描到的IP保存在哪个路径呢，感谢

**Comment by VillanCh** [comment]
收到，数据库的导出功能将在后面加入，这个是完全可以实现的


如果着急使用的话，可以使用数据库客户端连接Yakit数据库即可



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: youknowwho ***@***.***&gt;
发送时间: 2022年2月23日 11:54
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 导出端口扫描中得到的IP和端口信息 (Issue #140)





 
导出端口扫描中得到的IP和端口信息
 在一次端口扫描任务发现存活端口后，请问能否开发一个导出功能，能够批量导出IP和对应的端口为EXCEL或者TXT格式。或者辛苦告知一下扫描到的IP保存在哪个路径呢，感谢
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
