### ISSUE TITLE
【需求】能不能像Burp一样将参数单独格式化展示

### ISSUE THREAD

**Issue by smile-everyday** [yaklang/yakit#1404]
![微信截图_20240127111659](https://github.com/yaklang/yakit/assets/33567645/ad6b1820-a4cd-43c9-835e-4880beae90e8)
如图，能不能像Burp一样把头信息和参数格式化展示在旁边，方便查看和修改

**Comment by smile-everyday** [comment]
还有正则匹配到的敏感信息能否直接展示出来，肉眼看太老火了

**Comment by OrangeWatermelon** [comment]
![image](https://github.com/yaklang/yakit/assets/47558664/ea2b7730-9f74-42d7-ba7f-389f8a52c0aa)
在History里是展示了的，MITM的实时流量暂时还没加，可以先看History

**Comment by Vernon818** [comment]
最新版Yakit v1.3.2-sp2在mitm里已经支持显示规则匹配到的内容了

**Comment by Vernon818** [comment]
但目前还不支持显示头信息和参数信息

**Comment by Go0p** [comment]
参数信息可以点击右上角的详情进行查看

![image](https://github.com/yaklang/yakit/assets/38928800/ad68ba29-b29e-4f25-8c2f-b72cd8d0cd35)
