### ISSUE TITLE
History显示跟实际不一致问题

### ISSUE THREAD

**Issue by Cl0udG0d** [yaklang/yakit#1405]
版本：yakit windows 最新版本
![image](https://github.com/yaklang/yakit/assets/45556496/14a4377f-af0c-457c-9d7b-248b0f97eae6)

蒽....其实是在测试yakit是否有安全问题的过程中发现的一个小BUG

扫描页面构造header
```php
<?php header('Content-type: php//<h1>aaa</h1>'); ?>
```
![image](https://github.com/yaklang/yakit/assets/45556496/7a65f083-ecdd-4e7c-bd12-5ca9336f7a1b)
详情页面是显示的正确内容
![image](https://github.com/yaklang/yakit/assets/45556496/bc777d8f-4caf-4164-aeb3-2fdaaad1302c)

but ....
![image](https://github.com/yaklang/yakit/assets/45556496/55b4adf6-4786-4e3e-9d89-33ae0f1b11b0)

history位置显示的响应类型是 最后一个反斜杠后面的内容 / 

我不知道这个是做了安全过滤所导致的还是其他的什么原因

**Comment by VillanCh** [comment]
会把这个字符串当成完整的 MIME 类型处理，一般来说的认为 MIME 类型长得酷似 major-type/sub-type，展示时候为了方便用户读，一般来说会处理后展示 sub-type

**Comment by Cl0udG0d** [comment]
好的~
