### ISSUE TITLE
升级后 原来的db导入错误

### ISSUE THREAD

**Issue by xigagas** [yaklang/yakit#1419]
![Snipaste_2024-02-03_10-11-02](https://github.com/yaklang/yakit/assets/139865587/be2dc44c-06af-4132-87c5-564197fe742f)

麻了  0.0

**Comment by VillanCh** [comment]
师傅暂时先新开数据库，或者直接替换数据库文件吧～😢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xigagas ***@***.***&gt;
发送时间: 2024年2月3日 10:12
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 升级后 原来的db导入错误 (Issue #1419)





 
Snipaste_2024-02-03_10-11-02.png (view on web)
 
麻了  0.0

**Comment by WAY29** [comment]
师傅更新Yakit新版本后再尝试以下，现在已经支持导入没有导出(压缩)过的项目了
