### ISSUE TITLE
【bug】按了快捷键CTRL+W没有二次确认会直接关掉所有的Fuzz窗口

### ISSUE THREAD

**Issue by ViCrack** [yaklang/yakit#1423]
windows，yakit最新版

鼠标先大概点到图标红框的位置，然后快捷键CTRL+W直接把所有的Fuzz窗口都关了。。。。本意应该是关掉当前的Fuzz子窗口

![image](https://github.com/yaklang/yakit/assets/18179821/e054ad87-6813-4caa-89bb-766bde599dc8)

**Comment by Vernon818** [comment]
这个应该是因为你的焦点已经在外面那一层的tab了，所以默认关的是webfuzzer的大tab页，但是没有二次弹框确实有问题

**Comment by ViCrack** [comment]
是这样的，主要是没有弹框确认用户是否真需要全部关闭
