### ISSUE TITLE
无法测试host头攻击漏洞

### ISSUE THREAD

**Issue by Feng4** [yaklang/yakit#1425]
yakit测试host头攻击漏洞时，会直接判断为跳转，和burp不一样。
![image](https://github.com/yaklang/yakit/assets/27730186/7b255c43-0fc7-422e-84a9-cf29ec72dcd7)

**Comment by VillanCh** [comment]
Host头后面的问号有解释，也可以在高级配置中修改实际的位置





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Feng4 ***@***.***&gt;
发送时间: 2024年2月5日 15:01
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 无法测试host头攻击漏洞 (Issue #1425)





 
yakit测试host头攻击漏洞时，会直接判断为跳转，和burp不一样。
 image.png (view on web)
