### ISSUE TITLE
webfuzzer变量预览，yak引擎崩溃

### ISSUE THREAD

**Issue by idealYan** [yaklang/yakit#1426]
1、在webfuzzer设置变量标签错误的时候，点击预览，yak引擎会崩溃

复现：
![image](https://github.com/yaklang/yakit/assets/87683003/a443947d-255b-4118-8d9f-f732b3270d59)
![image](https://github.com/yaklang/yakit/assets/87683003/59c9fe75-e80c-42ac-a9de-4a829d2aca13)

**Comment by Vernon818** [comment]
好的，谢谢师傅，我们修复一下

**Comment by OrangeWatermelon** [comment]
已经修了哈，师傅更新就好了
