### ISSUE TITLE
yak.exe 被 迈克菲(McAfee) 杀毒软件识别为可疑有害软件

### ISSUE THREAD

**Issue by mofee** [yaklang/yakit#1429]
启动 Yakit 初始化引擎时，迈克菲(McAfee) 认为 yak.exe 有可能有害程序，威胁为：  ti!14392C4E0B1E

操作系统：windows 10,  版本：Windows 10 专业版 22H2

迈克菲(McAfee)信息：
版本: 1.14.212
发行名称: 16.0 R114
Affld: 1357
语言: ZH-CN
上次更新时间: 2024/02/05
防病毒
内部版本号: 1.1.2569.0
内容创建日期: 2024/02/05
内容版本:1676.0
跟踪器删除程序
内部版本号:5版本: 1.14

**Comment by WAY29** [comment]
这是一件很正常的事情，因为yak引擎涉及到许多底层的操作（例如嗅探网卡流量，构造低级数据包等），这可能会导致杀毒软件误报，yak引擎是完全开源的（而非像很多项目一样只开源了一部分或者前端），每个人都可以翻阅其源代码，如果你认为这是一个有害程序，可以停止使用
