### ISSUE TITLE
Ubuntu 22.04 使用Yakit1.3.0无法连接引擎

### ISSUE THREAD

**Issue by pbuff07** [yaklang/yakit#1432]
Ubuntu 22.04 使用Yakit1.3.0无法连接引擎，但使用1.2.9可正常连接引擎
![image](https://github.com/yaklang/yakit/assets/118048548/63662077-0d4b-4571-ba31-f8f764ac007d)

**Comment by pbuff07** [comment]
![image](https://github.com/yaklang/yakit/assets/118048548/fe1b3aab-17e6-4048-9be7-27bb09e7e2d3)

**Comment by VillanCh** [comment]
感谢师傅反馈，本周五更新会修复这个问题～

**Comment by pbuff07** [comment]
thks



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月18日(周日) 晚上10:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yaklang/yakit] Ubuntu 22.04 使用Yakit1.3.0无法连接引擎 (Issue #1432)




 
感谢师傅反馈，本周五更新会修复这个问题～
