### ISSUE TITLE
【bug】debian 12下运行yak bridge报错

### ISSUE THREAD

**Issue by Maysec** [yaklang/yakit#1436]
yak:yak version v1.3.0-sp6
os:Linux debianbookworm 6.1.0-16-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.67-1 (2023-12-12) x86_64 GNU/Linux
<img width="1343" alt="image" src="https://github.com/yaklang/yakit/assets/53160265/09dc3f67-15a8-4569-9902-047c457e8b9d">
<img width="1548" alt="image" src="https://github.com/yaklang/yakit/assets/53160265/244dbbd8-c464-455f-a8ae-153b6ccd530a">

**Comment by WAY29** [comment]
这并不是bug，而是公网bridge地址需要输入端口，如127.0.0.1:64333
