### ISSUE TITLE
【需求】项目管理增加多级项目管理模式

### ISSUE THREAD

**Issue by Asura88** [yaklang/yakit#1441]
## 需求描述

项目管理增加多级项目管理模式

## 解决方案

项目管理增加多级项目管理模式

## 可选方案

项目管理增加多级项目管理模式

## 附加信息

项目管理增加多级项目管理模式

<img width="688" alt="cb7d428c2e3f18aaa8a3c96e40ff71f" src="https://github.com/yaklang/yakit/assets/25000885/08561bf5-6b1f-4eb0-b2f6-565a34ca5802">

**Comment by WAY29** [comment]
现在已经可以新建文件夹以管理多个项目了
