### ISSUE TITLE
【需求】将现在的历史回放功能改回原来的样子！！！！！

### ISSUE THREAD

**Issue by VBPush** [yaklang/yakit#1450]
## 需求描述

:(  最新版本的那个发包历史回放功能，能不能改回来，现在回放点击了就返回个列表，完全找不到这个回放数据包对应的相应数据(因为经过测试他会缓存大量的旧响应信息，关闭Webfuzzer标签也不会清空这些列表缓存数据)，找的时候完全是大海捞针，及其不好用！！！！！！！能不能改回原来的那个直接返回历史请求和对应响应信息的。

![ceshi_17089113378538](https://github.com/yaklang/yakit/assets/140361823/b9d2b029-f4a7-412d-ac6c-ca21f76e51c1)

## 解决方案

将请求包历史回放，改回原来的那个直接返回历史请求的对应响应信息,而不是返回一大堆没用的列表(数据一致缓存，关闭了都不自动清理......)。

## 附加信息
你们可能想问：

a:为何不重新发包？
q:因为我不想。

a:为何不用过滤器或搜索功能？
q:懒，用那个查记录就是为了便捷。

**Comment by gniuy** [comment]
我也遇到同样的问题，非常不方便，点一下历史记录，打开的却不是当前提交过的请求包，而是以前测其他网站的数据包有几千条。
![image](https://github.com/yaklang/yakit/assets/78132798/406aff11-81e5-4e02-a7c5-84a97c15cf5d)

**Comment by WAY29** [comment]
这是一个BUG，后续会修复

**Comment by WAY29** [comment]
Ref: #1448
