### ISSUE TITLE
pitchfork模式发包问题

### ISSUE THREAD

**Issue by TZ0385** [yaklang/yakit#1462]
pitchfork设置多组payload，如果数量不一致，最后会发多余的包，不是按照行最少的字典发包，这个怎么处理
![1](https://github.com/yaklang/yakit/assets/44598912/86b9db01-55d5-4f81-b558-6200d64cff64)

**Comment by OrangeWatermelon** [comment]
暂时不支持对齐最小字典长度的配置，可以介绍下什么场景下需要用到吗。因为一般用于pitchfork爆破的两个字典内容都是已知对应关系的，这个的前提就是长度相同（好像还没遇到过需要使用pitchfork爆破两个未知关系的字典的需求）
