### ISSUE TITLE
yakit在fuzz崩溃

### ISSUE THREAD

**Issue by sevck** [yaklang/yakit#1463]
问题：在fuzz {[a-z0-9]|5}的时候内存占用几个G，导致软件跑崩了
是否考虑内存转储，特别在较大的fuzz中，节省资源内存，提高fuzz可用性

**Comment by WAY29** [comment]
这是因为fuzz技术是先生成所有要发送的包再进行发送的，你可以暂时将其拆为多个regen来缓解这个问题，例如：
{[a-z0-9]|2}{[a-z0-9]|3}

**Comment by sevck** [comment]
thx
