### ISSUE TITLE
【BUG】mitm交互劫持使站点无法正常加载，从而无法正常进行捕获

### ISSUE THREAD

**Issue by VBPush** [yaklang/yakit#1480]
mitm交互劫持使站点无法正常加载，从而无法正常进行捕获

测试的系统是内网基于若依二次开发的系统。
捕获后会一直显示“页面正在加载中”

使用BRUP 可正常捕获并加载。

**Comment by yinsel** [comment]
> 请给出一个具体的样例或网站，否则无法进行复现

Windows 下，对一些网络流量较多的app抓包时，图片出现400，发送至fuzz重发正常。在多流量下，中间人劫持性能目前较差。
![image](https://github.com/yaklang/yakit/assets/91541985/688a500b-35b9-4203-ad32-2ecd276f596c)

![image](https://github.com/yaklang/yakit/assets/91541985/5622235c-bb77-4bf5-b75e-9825d1ea924b)

**Comment by yinsel** [comment]
> 请给出一个具体的样例或网站，否则无法进行复现

Windows 下，对一些网络流量较多的app抓包时，图片出现400，发送至fuzz重发正常。在多流量下，中间人劫持性能目前较差。
![image](https://github.com/yaklang/yakit/assets/91541985/688a500b-35b9-4203-ad32-2ecd276f596c)

![image](https://github.com/yaklang/yakit/assets/91541985/5622235c-bb77-4bf5-b75e-9825d1ea924b)

**Comment by VBPush** [comment]
> 请给出具体的样例或网站，否则无法进行复现

139.196.111.193:3000，原有系统无法提供，因为属于内网系统，我另找了一个系统，这个资源加载应该比较少，可以加载出来，但是仍会存在加载缓慢，5xx接口异常等问题

**Comment by gniuy** [comment]
![image](https://github.com/yaklang/yakit/assets/78132798/573cca0a-a8a7-471b-bea5-03316162de6a)
![image](https://github.com/yaklang/yakit/assets/78132798/d246d853-83f3-4a98-b0c3-b77c2ced44a9)
小程序劫持也抓不到包，bp是正常的，两者区别就是改了端口，其他配置一样

**Comment by Go0p** [comment]
> ![image](https://private-user-images.githubusercontent.com/78132798/311965512-573cca0a-a8a7-471b-bea5-03316162de6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzM5MTAsIm5iZiI6MTcxMDgzMzYxMCwicGF0aCI6Ii83ODEzMjc5OC8zMTE5NjU1MTItNTczY2NhMGEtYThhNy00NzFiLWJlYTUtMDMzMTYxNjJkZTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA3MzMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNzgyOTcxZGFkZjY5NjkyODBkNTFhZTVkYzliMTlmZjQ5M2I2OGU5NzI1NmUwZjhjZmIyMmRhODFmZGRhZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QHBzO7l3BRef8emZOQ0fDxz4WlYTCHFtv53DMNDuZMI) ![image](https://private-user-images.githubusercontent.com/78132798/311965877-d246d853-83f3-4a98-b0c3-b77c2ced44a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzM5MTAsIm5iZiI6MTcxMDgzMzY
xMCwicGF0aCI6Ii83ODEzMjc5OC8zMTE5NjU4NzctZDI0NmQ4NTMtODNmMy00YTk4LWIwYzMtYjc3YzJjZWQ0NGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA3MzMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5ODY4ZDNhNDM0MjQ1NmI1MTU1MGVhOTFlYzM0OGIwZTUwYmZiYjMwZDY3OTJiZWExYWQ5MDg1MWQ0OWI2ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gWq5T4XmSyVIDEfIqWiHs7BkveZcVumCRUviUA4FdTI) 小程序劫持也抓不到包，bp是正常的，两者区别就是改了端口，其他配置一样

Yakit 重新下载并且安装一次证书应该可以解决
