### ISSUE TITLE
yakit的抓包规则配置无法添加http头的问题

### ISSUE THREAD

**Issue by jingluodiguo** [yaklang/yakit#1489]

**Comment by jingluodiguo** [comment]
<img width="539" alt="image" src="https://github.com/yaklang/yakit/assets/149219253/26535fc2-ed10-405f-baeb-aa90c70db194">

**Comment by jingluodiguo** [comment]
<img width="471" alt="image" src="https://github.com/yaklang/yakit/assets/149219253/897bdd57-f47f-491d-8899-fc9c2b15e18b">

**Comment by jingluodiguo** [comment]
只能替换已有的accept，而不能增加额外的http头，我记得之前可以的，大概一个月前使用还是正常的，现在为什么不会自动添加新的http头部了呢

**Comment by jingluodiguo** [comment]
https://www.yaklang.com/products/manual/expert-mode/mitm/Mark-Replace-Traffic/
根据之前yakit的替换案例是可以增加header的，但是现在只能替换已有的，不能增加新的

**Comment by jingluodiguo** [comment]
有哥们回复一下嘛。。。
现在感觉有蚂蚁在身上爬

**Comment by VillanCh** [comment]
周末大家应该是都休息了，应该等晚上或者工作日大家手里有电脑会给师傅回复


师傅可以先用热加载代码的劫持函数一定可以生效的





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jingluodiguo ***@***.***&gt;
发送时间: 2024年3月10日 11:07
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] yakit的抓包规则配置无法添加http头的问题 (Issue #1489)





 
有哥们回复一下嘛。。。
 现在感觉有蚂蚁在身上爬

**Comment by jingluodiguo** [comment]
nice
