### ISSUE TITLE
【需求】数据包发送到fuzz模块可以给一个小提示的窗口,不要直接跳过去

### ISSUE THREAD

**Issue by VVeakee** [yaklang/yakit#1491]
## 需求描述

在history发送多个数据包到fuzz模块,每发送一个都会跳到fuzz模块,需要来回点

**Comment by Vernon818** [comment]
这个在改了哈~

**Comment by wlingze** [comment]
修复的版本已经发布，请师傅更新到Yakit:v1.3.1-sp3 & Yaklang:v1.3.1-sp3
