### ISSUE TITLE
yak控制台输出列表或者数组，整形和字符串没做区分，希望师傅们能优化一下

### ISSUE THREAD

**Issue by idealYan** [yaklang/yakit#1492]
和python对比
![image](https://github.com/yaklang/yakit/assets/87683003/516f7e12-7a88-4b35-ad5c-87318e09edd0)

**Comment by VillanCh** [comment]
师傅可以用 dump() 代替 println 

dump 会携带比较完整的调试类型信息

**Comment by idealYan** [comment]
好哒
