### ISSUE TITLE
最新版本生成的反连地址不带类名

### ISSUE THREAD

**Issue by fitzxxx** [yaklang/yakit#1493]
![image](https://github.com/yaklang/yakit/assets/162282048/e16d5976-f791-4e75-99be-eed44791df92)
而且我手动添加上还是请求不到，有佬遇到过吗

**Comment by Vernon818** [comment]
感谢师傅反馈，预计这周发版后会修复

**Comment by wlingze** [comment]
修复的版本已经发布，请师傅更新到Yakit:v1.3.1-sp3 & Yaklang:v1.3.1-sp3
