### ISSUE TITLE
前端样式代码格式

### ISSUE THREAD

**Issue by Michael18811380328** [yaklang/yakit#150]
我看到代码中，很多样式定义在 JS 中，以 style 属性定义，这样不利于样式和行为的分离，未来是否考虑使用 css 或者其他外部样式表处理呢？
<img width="474" alt="截屏2022-03-07 10 52 10" src="https://user-images.githubusercontent.com/37589122/156959818-251f5be7-f480-4e39-aeeb-ed466cbdb67c.png">

**Comment by Michael18811380328** [comment]
从前端的角度，如果使用公共类名，前端界面渲染样式的执行效率也更高，JS 代码可以只维护逻辑不需要处理样式

**Comment by VillanCh** [comment]
感谢师傅指出问题

一些简单的样式为了方便，在急行军过程中确实处理不当，不过现在已经有一些新的组件在编写过程中使用了类名来设置样式。

之前的这种不恰当的方式确实是有性能隐患的，当时这么做的原因是快速实现组件逻辑与样式的协调和统一变化，分离会造成对程序员来说理解成本增加。

如果在某些组件遇到性能问题，在拆分完大组件，解决完 memo* 类问题之后渲染进程仍然占比比较多，回去重点优化这一部分。

**Comment by Michael18811380328** [comment]
好的，希望未来产品迭代越来越好
