### ISSUE TITLE
【BUG】自带浏览器问题

### ISSUE THREAD

**Issue by 7yyk** [yaklang/yakit#1509]
## 问题描述

请在此处提供您遇到的问题的详细描述。请描述问题的表现、发生的频率、影响范围以及任何其他相关信息。如果可能，请提供具体的步骤来重现该问题。

![图片](https://github.com/yaklang/yakit/assets/74973138/5ccd7623-735f-4e06-a6dd-a17a9aaee01d)

自带浏览器一些功能用不了，比如oppo这里的登陆按钮点击不了，但是burp自带的可以

![图片](https://github.com/yaklang/yakit/assets/74973138/f1404e8e-f148-4585-b48c-8e34d7e32d5e)

理想这里的图片上传一直0%，burp自带的浏览器可以

## 预期行为

请在此处描述您预期的行为，也就是问题被解决后应该出现的结果。如果可能，请提供具体的结果示例。

## 实际行为

请在此处描述您实际看到的行为，也就是问题解决后出现的结果。如果可能，请提供具体的结果示例。

## 复现步骤

请在此处提供能够复现该问题的具体步骤。如果问题是随机发生的，或者需要特定的环境条件才能复现，请提供更详细的说明。

1. 步骤 1访问链接，如图片操作
2. 步骤 2每次都有这种问题
3. 步骤 3

## 环境信息

- 操作系统: win11
- 系统架构: x64
- Yakit 版本: 1.3.1-sp3
- YakLang 版本: v1.3.1-sp3
- 无代理，DNS8.8.8.8和114.114.114.114都不行

## 补充说明

如果您有任何其他有关该问题的信息或评论，请在此处添加。

**Comment by 7yyk** [comment]
https://www.lixiang.com/community/publish

https://id.oppo.com/index.html?callback=https%3A%2F%2Fe.oppomobile.com%2Fmarkets%2Fmanage%2FIndexManage

**Comment by VillanCh** [comment]
感谢师傅反馈，近期修复后会在这个 issue 下更新

**Comment by Mang0c** [comment]
> 感谢师傅反馈，近期修复后会在本期下更新

不好意思师傅，试了下win10的虚拟机，最后发现是mime的规则配置进行文本替换功能导致的异常。我以为不会对真实数据包进行修改的hhh

**Comment by VillanCh** [comment]
<img width="1018" alt="image" src="https://github.com/yaklang/yakit/assets/13946521/2b6d049c-ee49-46d2-a92e-179f08864318">

师傅这里有提示信息吗？不过应该再修改替换规则的时候，他会二次确认～

**Comment by Mang0c** [comment]
> <img alt="image" width="1018" src="https://private-user-images.githubusercontent.com/13946521/313480965-2b6d049c-ee49-46d2-a92e-179f08864318.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2ODczNTYsIm5iZiI6MTcxMDY4NzA1NiwicGF0aCI6Ii8xMzk0NjUyMS8zMTM0ODA5NjUtMmI2ZDA0OWMtZWU0OS00NmQyLWE5MmUtMTc5ZjA4ODY0MzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE0NTA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2OWI2Y2ZhMDVkODUzOTRlOTQzZjM4ZmFjOTc2OWNkM2M3Zjk1Y2RhODU0NmUyYTdkMWQyMmU0NDQ1NDZhZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ECBh-p2ZZaDnz4UMqT14bOLRcfr0qh7afZ4ftimipXI">
> 师傅这里有提示信息吗？不过应该再修改替换规则的时候，他会二次确认～

有的有的，我以为只是修改匹配到的关键字方便我ctrl f检索到，没想到真实响应包也被改了

**Comment by VillanCh** [comment]
了解😉～



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mang0c ***@***.***&gt;
发送时间: 2024年3月17日 22:54
收件人: yaklang/yakit ***@***.***&gt;
抄送: v1ll4n ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [yaklang/yakit] 【BUG】自带浏览器问题 (Issue #1509)





   师傅这里有提示信息吗？不过应该再修改替换规则的时候，他会二次确认～  
有的有的，我以为只是修改匹配到的关键字方便我ctrl f检索到，没想到真实响应包也被改了
