### ISSUE TITLE
sqlmap 本地代理到yakit ,自动放行模式不能抓到数据包

### ISSUE THREAD

**Issue by cnBLKSail** [yaklang/yakit#1515]
## 问题描述
yakit mitm 监听端口8080
sqlmap  --proxy http://127.0.0.1:8080  代理到yakit ,自动放行模式不能抓到数据包
手动劫持能抓到数据包
## 预期行为

监视sqlmap 发出的数据包

## 实际行为
使用sqlmap 1.7 版本  代理到8080 端口自动放行模式sqlmap 能获取到数据,yakit 没有数据包显示
使用sqlmap 1.8 版本  代理到8080 端口自动放行模式sqlmap 不能获取数据yakit  显示502 代码数据包

## 复现步骤

yakit mitm 监听端口8080
sqlmap  --proxy http://127.0.0.1:8080  代理到yakit 
python sqlmap.py -r  timesql.txt --dbms=mssql -p sKeyvalue -b --proxy http://127.0.0.1:8080

## 环境信息

- 操作系统: win32
- 系统架构: x64
- Yakit 版本: 1.3.1-sp3
- YakLang 版本: v1.3.1-sp3

**Comment by Q16G** [comment]
（1）`sqlmap1.8`版本即使不使用代理也无法正常发送数据包：原因是：`sqlmap -r 1.txt` 解析`host`有误，`sqlmap 1.7`没有这个问题。
（2）无法抓到数据包：是因为在`yakit`内部将`image/jpeg` 该类型进行过滤，不进行显示。
