### ISSUE TITLE
【BUG】Webfuzzer使用热加载以及fuzztag分组后爆破无法到达预期

### ISSUE THREAD

**Issue by sovegetable** [yaklang/yakit#1519]
## 问题描述

Webfuzzer使用热加载以及fuzztag分组后爆破无法到达预期

## 预期行为

爆破时有四个参数(用户名,密码,验证码id,验证码结果),前两个参数为字典,后两个为热加载从web api获取数据(由于验证码有效期60s无法使用字典)。我将用户名和密码的fuzztag index设置为::1,后两个设置为::2。预期是1,2两个分组同时向后移动（即用户名和密码笛卡尔积爆破，同时每次同步更换验证码id和验证码结果），但是实际只有分组1移动了，分组2在爆破中为固定值。 

热加载代码
![image](https://github.com/yaklang/yakit/assets/62092842/a7d91c9a-cc87-4847-9451-ffda27ef496d)

## 实际行为

做了如下尝试
1. 问题为验证码固定
 ![image](https://github.com/yaklang/yakit/assets/62092842/1c5cebc5-73df-4336-98ee-fdcaef9449d4)
    1号包body ：`{"account":"admin","password":"mynoob","codeValue":"178","code":"CaptchaCode1710920192808"}`
    2号包body ：`{"account":"root","password":"18atcskd2w","codeValue":"178","code":"CaptchaCode1710920192808"}`
    3号包body ：`{"account":"test","password":"3rjs1la7qe","codeValue":"178","code":"CaptchaCode1710920192808"}`
     
——————————————————————————————————————————————————————
2. 问题为验证码固定
![image](https://github.com/yaklang/yakit/assets/62092842/fff0c305-5877-437b-a84d-ca2e4669c86b)
    1号包body ：`{"account":"admin","password":"mynoob","codeValue":"276","code":"CaptchaCode1710920194459"}`
    2号包body ：`{"account":"root","password":"mynoob","codeValue":"276","code":"CaptchaCode1710920194459"}`
    3号包body ：`{"account":"test","password":"mynoob","codeValue":"276","code":"CaptchaCode1710920194459"}`

——————————————————————————————————————————————————————
3. 问题为出现空序列（第一个有值后续没有）
![image](https://github.com/yaklang/yakit/assets/62092842/2770087a-8784-422f-8b10-1ec1519b0e1d)
    1号包body ：`{"account":"admin","password":"mynoob","codeValue":"","code":""}`
    2号包body ：`{"account":"root","password":"mynoob","codeValue":"375","code":"CaptchaCode1710920194984"}`
    3号包body ：`{"account":"test","password":"mynoob","codeValue":"","code":""}`
    4号包body ：`{"account":"info","password":"mynoob","codeValue":"","code":""}`

——————————————————————————————————————————————————————

4. 
![image](https://github.com/yaklang/yakit/assets/62092842/83d95dea-20db-41d9-8965-4c5afbf3bb80)
（输出模式 同2）

## 环境信息

- 操作系统: win32
- 系统架构: x64
- Yakit 版本: 1.3.1-sp1
- YakLang 版本: v1.3.0-sp3

**Comment by WAY29** [comment]
对fuzztag概念请参考官网WebFuzzer的文章

fuzztag与发包的关系是**先渲染再发包**，这是一个最重要的概念，如果你能理解的话就应该明白问题1和2是预期行为。对于热加载标签来说，其只会在发包前先进行渲染一次，所以这个值永远是固定的，想要实现你希望的的行为应该使用的是[这篇文章](https://yaklang.com/products/Web%20Fuzzer/fuzz-hotpatch-example1)，即使用热加载中的beforeRequest。

[这篇文章](https://yaklang.com/products/Web%20Fuzzer/fuzz#:~:text=%E5%90%8C%E4%B8%80%E4%B8%AA%E5%88%86%E7%BB%84%E7%9A%84fuzztag%E4%BC%9A%E8%A2%AB%E6%9B%BF%E6%8D%A2%E4%B8%BA%E5%90%8C%E4%B8%80%E4%B8%AA%20Index%20%E7%9A%84%E5%80%BC)则对分组已经有了详细的解释：**同一个分组的fuzztag会被替换为同一个 Index 的值**。这也可以用于解释上述的问题3和4，对于普通的热加载来说，你只产生了一个值，所以只会在Index为0（即第一个时）会使用热加载产生的那个值，后续的Index时热加载已经没有值，则为空。

**Comment by sovegetable** [comment]
醍醐灌顶! 感谢解答

**Comment by sovegetable** [comment]
> 对fuzztag概念请参考官网WebFuzzer的文章
> 
> fuzztag与发包的关系是**先渲染再发包**，这是一个最重要的概念，如果你能理解的话就应该明白问题1和2是预期行为。对于热加载标签来说，其只会在发包前先进行渲染一次，所以这个值永远是固定的，想要实现你希望的的行为应该使用的是[这篇文章](https://yaklang.com/products/Web%20Fuzzer/fuzz-hotpatch-example1)，即使用热加载中的beforeRequest。
> 
> [这篇文章](https://yaklang.com/products/Web%20Fuzzer/fuzz#:~:text=%E5%90%8C%E4%B8%80%E4%B8%AA%E5%88%86%E7%BB%84%E7%9A%84fuzztag%E4%BC%9A%E8%A2%AB%E6%9B%BF%E6%8D%A2%E4%B8%BA%E5%90%8C%E4%B8%80%E4%B8%AA%20Index%20%E7%9A%84%E5%80%BC)则对分组已经有了详细的解释：**同一个分组的fuzztag会被替换为同一个 Index 的值**。这也可以用于解释上述的问题3和4，对于普通的热加载来说，你只产生了一个值，所以只会在Index为0（即第一个时）会使用热加载产生的那个值，后续的Index时热加载已经没有值，则为空。

醍醐灌顶! 感谢解答
