### ISSUE TITLE
【BUG】nuclei 插件调试模块不能使用

### ISSUE THREAD

**Issue by cnBLKSail** [yaklang/yakit#1521]
## 问题描述

nuclei 插件调试模块不能使用

## 预期行为

正常会有http数据包
## 实际行为

没有任何数据包返回
## 复现步骤

1. 步骤 1
2. 步骤 2
3. 步骤 3

## 环境信息

- 操作系统: win32
- 系统架构: x64
- Yakit 版本: 1.3.1-sp4
- YakLang 版本: v1.3.1-sp4

**Comment by VillanCh** [comment]
已知Bug，师傅可以先回退一个版本的引擎应该可以使用，最近更新引擎就会修复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Abby ***@***.***&gt;
发送时间: 2024年3月20日 22:29
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 【BUG】nuclei 插件调试模块不能使用 (Issue #1521)





 
问题描述
 
nuclei 插件调试模块不能使用
 
预期行为
 
正常会有http数据包
 
实际行为
 
没有任何数据包返回
 
复现步骤
  
步骤 1
 
步骤 2
 
步骤 3
  
环境信息
  
操作系统: win32
 
系统架构: x64
 
Yakit 版本: 1.3.1-sp4
 
YakLang 版本: v1.3.1-sp4

**Comment by WAY29** [comment]
已经在最新引擎版本修复
