### ISSUE TITLE
更新后无法编辑框中的紫色字体

### ISSUE THREAD

**Issue by xigagas** [yaklang/yakit#1550]
webfuzzer中  请求包体 紫色部分无法编辑
![image](https://github.com/yaklang/yakit/assets/139865587/057ee32c-e371-4a23-8254-59bb84f10956)

**Comment by VillanCh** [comment]
新版本更新出了问题，再重新发布版本，应该几分钟后新版更新即可





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xigagas ***@***.***&gt;
发送时间: 2024年3月29日 18:19
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 更新后无法编辑框中的紫色字体 (Issue #1550)





 
webfuzzer中  请求包体 紫色部分无法编辑
 image.png (view on web)

**Comment by VillanCh** [comment]
师傅更新刚刚发版的 Yakit 可修复~

**Comment by WAY29** [comment]
已在Yakit v1.3.1-sp6中修复
