### ISSUE TITLE
【需求】在子域名检查页面增加一个一键复制功能

### ISSUE THREAD

**Issue by Ruqian01** [yaklang/yakit#1558]
在子域名收集页面面对搜集的子域名时往往需要对搜索到的域名/IP进行复制，然后粘贴到别处进行扫描，但现页面如果子域名很多复制起来非常麻烦，希望可以加个一键复制功能

**Comment by WAY29** [comment]
在表中可以使用导出全部来将其导出到文件
![Uploading image.png…]()
