### ISSUE TITLE
M2 PRO MAC，使用file或者file:line对应的fuzztag，返回数据均为空，测试文件中存在数据。

### ISSUE THREAD

**Issue by vul1ha0** [yaklang/yakit#1559]
<img width="656" alt="image" src="https://github.com/yaklang/yakit/assets/123882048/9b63f447-ea52-460e-aefc-d493f32406e8">

**Comment by WAY29** [comment]
因为某些安全原因，所以默认无法在YakRunner的fuzztag中使用file标签，只能在WebFuzzer中使用
实际上有许多方式来读取文件，不需要使用fuzztag，例如：
```yaklang
lines = file.ReadLines("/tmp/test.txt")
```
