### ISSUE TITLE
【需求】yaml 插件

### ISSUE THREAD

**Issue by twsec-pro** [yaklang/yakit#1560]
## 需求描述

以前那些nuclei插件咋没了？

## 解决方案

建议恢复nuclei插件源更新

## 可选方案

请清晰明确地描述你考虑过的其他方案或功能。

## 附加信息

请提供任何与该功能请求相关的上下文信息、截图或其他材料等。

**Comment by VillanCh** [comment]
并没有移除，在导入外部资源的那边





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: twsec ***@***.***&gt;
发送时间: 2024年4月7日 01:10
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 【需求】yaml 插件 (Issue #1560)





 
需求描述
 
以前那些nuclei插件咋没了？
 
解决方案
 
建议恢复nuclei插件源更新
 
可选方案
 
请清晰明确地描述你考虑过的其他方案或功能。
 
附加信息
 
请提供任何与该功能请求相关的上下文信息、截图或其他材料等。
