### ISSUE TITLE
web_fuzzer

### ISSUE THREAD

**Issue by wodi98k** [yaklang/yakit#1561]
使用web_fuzzer无法进行打字但是中文输入法再按shift可以正常输出英文输入法不行

**Comment by VillanCh** [comment]
师傅方便说一下哪个版本 Windows 还是 Mac 出现的问题吗？最新的版本中应该是测试修复过类似的问题的

**Comment by wodi98k** [comment]
Windows的版本问题是偶发性的更新版本后插件没办法使用我降级就成这样子了

**Comment by wodi98k** [comment]
版本是Yakit-1.3.1-sp5-windows-amd64重新安装了也是不正常不知道是否是电脑问题

**Comment by wodi98k** [comment]
师傅，更新解决了谢谢回答
