### ISSUE TITLE
【需求】Yakit中是否存在Burp中类似Recursive Grep的操作，如果没有，是否可以考虑增加这样的功能。

### ISSUE THREAD

**Issue by vul1ha0** [yaklang/yakit#1566]
<img width="573" alt="image" src="https://github.com/yaklang/yakit/assets/123882048/7b471e7c-3d68-412b-8392-3c323f3ccf55">

**Comment by VillanCh** [comment]
高级配置中的数据提取匹配和Web Fuzzer序列基本可以满足这部分的功能需要，师傅可以尝试探索一下～



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: vul1ha0 ***@***.***&gt;
发送时间: 2024年4月8日 23:51
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 【需求】Yakit中是否存在Burp中类似Recursive Grep的操作，如果没有，是否可以考虑增加这样的功能。 (Issue #1566)





 image.png (view on web)

**Comment by vul1ha0** [comment]
OK，感谢师傅这么晚了还回复问题。
