### ISSUE TITLE
使用Yakit如何实现类似BurpSuite的Intruder中的Recursive Grep的操作，重点在于递归获取上个响应数据包中的数据作为下一个请求的输入

### ISSUE THREAD

**Issue by vul1ha0** [yaklang/yakit#1567]
### 【问题】
我尝试使用Fuzzer序列，但是Fuzzer序列不能循环，导致只能获取前一个数据包的数据包的提取数据一次，如果在后一个数据包进行Fuzzer爆破，则只能用到第一个数据，无法递归爆破。除了使用热加载的beforeRequest方法外，还有其他方法吗
### 【解决方案】

**Comment by VillanCh** [comment]
第一个数据包是可以分裂的，在第一个数据包中设置fuzztag作为字典就可以直接遍历所有需要爆破的数据了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Abby ***@***.***&gt;
发送时间: 2024年4月9日 09:49
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 使用Yakit如何实现类似BurpSuite的Intruder中的Recursive Grep的操作，重点在于递归获取上个响应数据包中的数据作为下一个请求的输入 (Issue #1567)





 
【问题】
 
我尝试使用Fuzzer序列，但是Fuzzer序列不能循环，导致只能获取前一个数据包的数据包的提取数据一次，如果在后一个数据包进行Fuzzer爆破，则只能用到第一个数据，无法递归爆破。除了使用热加载的beforeRequest方法外，还有其他方法吗
 
【解决方案】

**Comment by vul1ha0** [comment]
具体该如何操作呢，使用Pikachu靶场的token防爆破进行测试，目前我是在第一个响应数据包中提取了token，然后第二个数据包爆破。
<img width="1512" alt="image" src="https://github.com/yaklang/yakit/assets/123882048/d7149347-dc1b-4616-ab6a-942346f43def">
<img width="1512" alt="image" src="https://github.com/yaklang/yakit/assets/123882048/aefab7d9-9d05-431e-b535-b0f5da300e43">
<img width="1512" alt="image" src="https://github.com/yaklang/yakit/assets/123882048/101e927c-72dd-4b59-a309-013e65d957c8">

**Comment by Vernon818** [comment]
师傅可以看一下这个csrf的教程 https://mp.weixin.qq.com/s/i9ISVD2kLDqs5UhVpq4oFw

**Comment by WAY29** [comment]
https://yaklang.com/products/Web%20Fuzzer/fuzz-hotpatch-example1
