### ISSUE TITLE
【需求】数据包扫描以及专项漏洞检测可自主选择插件

### ISSUE THREAD

**Issue by twsec-pro** [yaklang/yakit#1581]
## 需求描述

在数据包扫描以及专项漏洞检测中可以自主选择插件，而不是只能选择分好的组，仅测试一个插件时无法实现

## 解决方案

在数据包扫描以及专项漏洞检测中可以自主选择插件

## 可选方案

请清晰明确地描述你考虑过的其他方案或功能。

## 附加信息
![image](https://github.com/yaklang/yakit/assets/58679784/9c69f4a5-aaf9-47d8-83e0-98cbd43aafaf)

**Comment by twsec-pro** [comment]
数据包扫描可以使用批量执行，专项漏洞检测好像只能按组选择插件

**Comment by rookieBC** [comment]
师傅，在本地插件里可以单独执行一个插件，需要执行多个插件可以使用批量执行
![image](https://github.com/yaklang/yakit/assets/129090558/67e86e6b-4ef0-441c-b65a-175eb7b763f8)
