### ISSUE TITLE
【需求】匹配高亮显示

### ISSUE THREAD

**Issue by VVeakee** [yaklang/yakit#1586]
## 需求描述

数据包匹配到了敏感信息和oss key却不知道在哪

## 解决方案
![image](https://github.com/yaklang/yakit/assets/85714114/79db2397-9d20-49ca-ad22-7be64495a4cc)

增加对应的标签按钮或选项,匹配到了敏感信息,那我可以选择匹配到敏感信息信息的部分高亮,类似于在返回包搜索的效果,快速查看匹配到的敏感信息,防止有数据被多个规则同时匹配到,建议还是单独选择匹配到的一个标签进行高亮,或者可以同时选择多个标签用不同颜色进行高亮,重合部分再处理

**Comment by Vernon818** [comment]
感谢师傅建议，有计划做高亮显示

**Comment by WAY29** [comment]
Reference: #1526
