### ISSUE TITLE
自行编译，运行无界面显示

### ISSUE THREAD

**Issue by TBOsec** [yaklang/yakit#159]
### **自行编译相应平台，在Mac和window中运行均无界面显示，请问什么原因呢？😅**
<img width="969" alt="image" src="https://user-images.githubusercontent.com/24735925/157823675-b29dfb5f-9168-4c74-a3e7-ab93d4a65a98.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/24735925/157823830-a77cba26-de3e-47fc-8784-0bca004d14d0.png">
-----------------------------------------------------------------------------------------------

**Comment by VillanCh** [comment]
参考 github actions 中的脚本，前端项目和 Electron 都需要编译

可以参考以下命令依次执行
 
1. yarn install-render
2. yarn build-render
3. yarn install
4. yarn build....

**Comment by TajangSec** [comment]
> 参考 github actions 中的脚本，前端项目和 Electron 都需要编译
> 
> 可以参考以下命令依次执行
> 
> 1. yarn install-render
> 2. yarn build-render
> 3. yarn install
> 4. yarn build....

请问现在如何编译？我在你这个步骤的第三步报错
