### ISSUE TITLE
远程模式MITM代理报错

### ISSUE THREAD

**Issue by jetming** [yaklang/yakit#1594]
[bug][mitmloop:191] check socks5 handle shake failed: peek failed: read tcp 10.0.20.9:8083->106.***.10.162:14725: read: connection reset by peer

看报错， 是远程引擎要回连我客户端的公网出口端口， 客户端公网出口肯定没有这个端口监听啊。

**Comment by Go0p** [comment]
给出 mitm 界面的启动的截图看看
