### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by ketchup1995** [yaklang/yakit#16]
yak_windows_amd64.exe install
panic: The system cannot find the path specified.

goroutine 1 [running]:
palm/common/spec.init.1()
        D:/a/yak/yak/common/spec/strings.go:17 +0xa5

**Comment by VillanCh** [comment]
yak v1.0.9-beta7  修复了这个问题，打开 yakit 重新安装一下最新版本即可

**Comment by VillanCh** [comment]
![image](https://user-images.githubusercontent.com/13946521/139781322-871f5edf-d062-4f74-ae6e-49f336c58e9d.png)

**Comment by ketchup1995** [comment]
更新后会提示无网络连接，重新安装升级出现如下
![图片](https://user-images.githubusercontent.com/87350553/139781398-9eeb5a8a-80ce-4c92-a7c3-dcbedd82d6ec.png)

**Comment by ketchup1995** [comment]
![图片](https://user-images.githubusercontent.com/87350553/139781622-f6944223-9d3b-4c3a-a6c5-d0fe8794ab02.png)

**Comment by VillanCh** [comment]
新版本已经修复这个问题，yakit 界面内更新即可～ 🎉

**Comment by Vernon818** [comment]
@ketchup1995 为了感谢您对yak和yakit的支持，我们想邮寄一份小礼物给您，麻烦您微信添加一下：Juzi19880818，并备注好您的github账号。如已经添加账号，请微信联系我一下，谢谢
