### ISSUE TITLE
【需求】抓的包怎么设置自动对某一字段加解密

### ISSUE THREAD

**Issue by ruiwen123** [yaklang/yakit#1612]
## 需求描述
抓的包怎么设置自动对某一字段加解密，能否自定义脚本写加解密？

平时用sql注入爆破插件，能不能对某个字段进行注入爆破，而不是一键遍历所有字段注入。

**Comment by WAY29** [comment]
1. 编写mitm插件实现hijackRequest接口即可
2. 现在只能通过修改sql注入插件实现
