### ISSUE TITLE
上传包webfuzz优化

### ISSUE THREAD

**Issue by n1ec** [yaklang/yakit#1613]
在进行fuzz上传功能的时候 ，比如上传头像、文件是否可以修改后缀名就会抓包进行wenfuzz测试，原包的是这样的，带有二进制等数据
![image](https://github.com/yaklang/yakit/assets/96775289/50517eac-ba13-4eb3-a0a8-ffce26a3b9fc)
发到webfuzz这里应该是直接置空二进制数据包部分，
![image](https://github.com/yaklang/yakit/assets/96775289/bcd31e64-355b-4296-af8b-8c455ccec56b)

**Comment by WAY29** [comment]
不应该置空，这是不对的，发送到webfuzzer的数据包应该保留完整的样子
