### ISSUE TITLE
【BUG fuzz param 对null的处理异常】

### ISSUE THREAD

**Issue by Sleepybear-lxx** [yaklang/yakit#1614]
当报文中含有json格式数据，且值为null时，无法通过fuzz param获取该参数值
![image](https://github.com/yaklang/yakit/assets/48982906/627892ec-3f50-403d-a838-1b6b4804d106)

**Comment by Go0p** [comment]
[#1097](https://github.com/yaklang/yaklang/pull/1097) 已修复此问题，等待更新后即可

![image](https://github.com/yaklang/yakit/assets/38928800/7d47f93c-db9d-4d58-b730-b7d73dbc4f0b)
