### ISSUE TITLE
页面UI问题

### ISSUE THREAD

**Issue by aHlo666** [yaklang/yakit#1618]
有一些模块打开后在最左侧有一些配置，可以加一个收起按钮吗？配置好之后就可以收起。就像最上面那些有一个收起按钮
![image](https://github.com/yaklang/yakit/assets/67671500/a300ad28-c405-4015-86d7-02b60b9cc726)

**Comment by WAY29** [comment]
再次点击左侧按钮即可收起，这是一个很常见的操作~
