### ISSUE TITLE
代理配置问题

### ISSUE THREAD

**Issue by aHlo666** [yaklang/yakit#1619]
有时候会使用burp+proxifier进行抓包，burp开启监听127.0.0.1:8080，在proxifier中配置代理127.0.0.1:8080之后，就可以抓一些本身不支持配置代理的应用，比如一些PC客户端，以及微信小程序PC端的。但是今天试了一下用yakit+proxifier好像不行，不知道是不是我配置不对。yakit开启监听127.0.0.1:8083，然后在proxifier中配置代理127.0.0.1:8083后，访问一个网址刷新不出来，yakit中查看history全是响应502：
![image](https://github.com/yaklang/yakit/assets/67671500/db62f598-722d-4f84-9a01-c2194a6886be)

**Comment by VillanCh** [comment]
502提示TLS错误一般是证书出现问题，需要本地看一下证书是否安装正确，或者跟着官方文档走





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: aHlo666 ***@***.***&gt;
发送时间: 2024年4月28日 17:30
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 代理配置问题 (Issue #1619)





 
有时候会使用burp+proxifier进行抓包，burp开启监听127.0.0.1:8080，在proxifier中配置代理127.0.0.1:8080之后，就可以抓一些本身不支持配置代理的应用，比如一些PC客户端，以及微信小程序PC端的。但是今天试了一下用yakit+proxifier好像不行，不知道是不是我配置不对。yakit开启监听127.0.0.1:8083，然后在proxifier中配置代理127.0.0.1:8083后，访问一个网址刷新不出来，yakit中查看history全是响应502：
 image.png (view on web)

**Comment by gringoddjw** [comment]
解决了么老哥

**Comment by aHlo666** [comment]
> 解决了么老哥
我这个是因为本地有clash开着系统代理导致的，关闭之后就好了
