### ISSUE TITLE
请求进化

### ISSUE THREAD

**Issue by fzrk9** [yaklang/yakit#1621]
咱可以把bp的拓展加进yakit里面嘛，类似与hae、onescan啥的，最近在做渗透，有些bp能抓出来的我用yakit抓不出来，用bp抓了一个框架然后找了个严重漏洞，但是用yakit就抓不出来，但是yakit又很好我舍不得抛弃yakit，咱能进化一下吗🤞
![微信图片_20240429165351](https://github.com/yaklang/yakit/assets/164461192/6a6cac8f-2c2d-4e3e-aaf4-a3179da25397)

**Comment by WAY29** [comment]
hae功能在yakit中有内置规则功能作为代替，至于漏洞扫描可以编写对应的yak插件来实现。
至于抓不到包请开新的issue并把详细情况（网站，操作等）列出
