### ISSUE TITLE
无法标注颜色

### ISSUE THREAD

**Issue by WenGuiO** [yaklang/yakit#1624]
添加标签颜色时报错：
Error: Error invoking remote method 'SetTagForHTTPFlow': Error: 13 INTERNAL: runtime error: invalid memory address or nil pointer dereference

导致无法标注颜色，某些项目可行，但是某些项目不可行

**Comment by WAY29** [comment]
师傅可以重新复现一下，在复现前打开控制台并截图看看是否有错误日志：
![image](https://github.com/yaklang/yakit/assets/41830147/7acd913f-e558-4280-81f5-bd311640ad4c)

**Comment by WAY29** [comment]
漏洞已经尝试修复了，师傅可以看看最新版本还有没有问题
