### ISSUE TITLE
【需求】history加载数据问题

### ISSUE THREAD

**Issue by VVeakee** [yaklang/yakit#1626]
## 需求描述

在history和fuzz之间切换的时候,每次切到history都会从最新的开始显示,点击下面数据包的id也跳不过去,因为history每次都加载一块区域,没加载到的不会跳

![image](https://github.com/yaklang/yakit/assets/85714114/daff4818-d1f4-41ab-a6ae-32f37dc43a79)

**Comment by Vernon818** [comment]
在history和fuzz之间切换的时候,每次切到history都会从最新的开始显示

这个我好像没复现到，我切换的时候他都定位在之前查看的位置

**Comment by WAY29** [comment]
已经在Yakit最新版本修复
