### ISSUE TITLE
无法拦截部分网站请求，一直弹窗显示query HTTP Flow failed

### ISSUE THREAD

**Issue by Bronya-Rayi** [yaklang/yakit#164]
query HTTP Flow failed: Error: Error invoking remote method 'QueryHTTPFlows': Error: 13 INTERNAL: grpc: error while marshaling: string field contains invalid UTF-8
一直弹窗，删掉yak引擎，再重装后才不再弹窗
![image](https://user-images.githubusercontent.com/47048823/158772109-4aece3a9-780b-40e1-a46f-a8cf1dbd51a7.png)
以下是触发的流程
![image](https://user-images.githubusercontent.com/47048823/158772170-f3fe559f-2d03-4d50-959c-6c4ca8fe3587.gif)
burpsuite拦截无异常
![image](https://user-images.githubusercontent.com/47048823/158772493-e5f036e5-7823-4d43-b70b-06819d87dfe9.png)

**Comment by Bronya-Rayi** [comment]
把所有HTTP history删掉后也不弹窗了

**Comment by VillanCh** [comment]
感谢师傅反馈，初步判断是 gRPC 传输的时候在 string 类型中传输入非 UTF-8 的 rune/block

大概引擎会在下一个版本修复这个问题～

**Comment by VillanCh** [comment]
![image](https://user-images.githubusercontent.com/13946521/158777433-48c957a0-ae5c-43b3-9b5a-35d1dc7ca582.png)

感谢师傅反馈，定位到问题了，因为这里定义了两种编码，导致识别的时候进行错误的 GBK 解码导致的
感谢反馈，引擎下一个版本将会修复这个问题

**Comment by VillanCh** [comment]
yak v1.0.13-sp26 版本中修复了该问题，大约几分钟后可以更新引擎

1. 是由于 UTF8 和 GB* 同时存在的时候，以 GB* 编码优先的错误处理导致的。
2. 因为错误解码导致 HtmlTitle 出现非 UTF8 编码，gRPC 不识别，导致接口调用失败。

感谢师傅反馈，🎉

**Comment by VillanCh** [comment]
这个问题在新版本中已经修复，我暂时先关掉了～师傅验证如果有问题 ReOpen 即可
