### ISSUE TITLE
启动更新错误

### ISSUE THREAD

**Issue by 1954688024** [yaklang/yakit#1641]
## 问题描述

当每次启动yak时，会每次弹出检测到引擎版本升级

## 预期行为

请在此处描述您预期的行为，也就是问题被解决后应该出现的结果。如果可能，请提供具体的结果示例。

## 实际行为

请在此处描述您实际看到的行为，也就是问题解决后出现的结果。如果可能，请提供具体的结果示例。

## 复现步骤

请在此处提供能够复现该问题的具体步骤。如果问题是随机发生的，或者需要特定的环境条件才能复现，请提供更详细的说明。

1. 步骤 1
2. 步骤 2
3. 步骤 3

## 环境信息

- 操作系统: Windows_NT
- 系统架构: x64
- Yakit 版本: 1.3.2-sp2
- YakLang 版本: 1.3.2-sp2

## 补充说明

如果您有任何其他有关该问题的信息或评论，请在此处添加。

**Comment by WAY29** [comment]
更新到最新的Yakit即可
