### ISSUE TITLE
【BUG】Yakit自带的DNSLog未获取到远端IP地址

### ISSUE THREAD

**Issue by xbfding** [yaklang/yakit#1643]
# 问题描述
![image](https://github.com/yaklang/yakit/assets/62999907/e55993f0-0c12-4746-9da2-1214a4cd8c4a)
在DNSLog记录中，远端IP一栏是空白的，没有获取到来源IP

# 环境信息
操作系统: Windows
系统架构: x64
Yakit 版本: Yakit v1.3.2-sp3
YakLang 版本: Yaklang 1.3.3-rc4

**Comment by Go0p** [comment]
z9z.top 的server 端的返回值就不带 ip

![image](https://github.com/yaklang/yakit/assets/38928800/1117be39-c27d-4132-b220-e615519cc39b)
