### ISSUE TITLE
【BUG】undefined 's isHttps called

### ISSUE THREAD

**Issue by xigagas** [yaklang/yakit#1644]
![image](https://github.com/yaklang/yakit/assets/139865587/582c7c8f-fce6-4843-b645-d8419c7bf6da)

**Comment by xigagas** [comment]
跑了上万个包，，

**Comment by VillanCh** [comment]
这不是因为数据大小的问题，是一个 BUG

**Comment by VillanCh** [comment]
师傅是 Yakit 哪个版本出现的这个问题呢？方便看一下嘛？

**Comment by Vernon818** [comment]
师傅方便的话可以加个wx：Juzi19880818，我们具体排查看看

**Comment by xigagas** [comment]
![image](https://github.com/yaklang/yakit/assets/139865587/771bd975-69bb-4eb7-b580-134931e32df1)
呜呜呜 ，所有的webfuzz都没了
![image](https://github.com/yaklang/yakit/assets/139865587/480a6ff6-3278-4425-ba94-73447af65fdb)

**Comment by Vernon818** [comment]
可以看看历史里面还有没有

**Comment by xigagas** [comment]
组可以恢复吗。。

**Comment by Vernon818** [comment]
组不太行……

**Comment by xigagas** [comment]
https://github.com/yaklang/yakit/assets/139865587/2e86e0dd-26ae-41b4-ba56-ea5e06c45658

这种是什么bug，输入卡然后输入的字符串直接到后面了

**Comment by Vernon818** [comment]
在Yakit v1.3.3-sp2 中已经修复
