### ISSUE TITLE
websocket fuzzer 发送数据不支持自定义字符

### ISSUE THREAD

**Issue by tarihub** [yaklang/yakit#1648]
环境信息
```
yakit 版本 1.3.2-sp2 (1.3.2-sp2)
操作系统 windows x86 版本
```

【遇到的问题】
建立 websocket 后，走 websocket 发送数据包，能发送数据，输入一个字符，服务端也能正常响应，但无法结束输入。然后用 burp 去抓包发现，正常业务通过 `\n` 作为结束和换行标志。yakit 默认用 `\r\n` ，然后 yakit websocket 不支持 fuzztag ，所以无法替换 \r\n 为 \n，web fuzzer 倒是没这种问题

**Comment by Go0p** [comment]
https://github.com/yaklang/yakit/issues/1648
