### ISSUE TITLE
FATAL:gpu_data_manager_impl_private.cc(448) GPU process isn't usable

### ISSUE THREAD

**Issue by k3rwin** [yaklang/yakit#1649]
win10安装最新版本无法打开版本 1.3.2-sp4,闪退，无进程，重启也无效

**Comment by Vernon818** [comment]
右键管理员或者兼容模式可以吗？

**Comment by Go0p** [comment]
找到 yakit.exe 所在目录，打开 cmd 执行 Yakit.exe ，贴出控制台输出的日志，如下

![image](https://github.com/yaklang/yakit/assets/38928800/f05c60d0-c947-405b-a0e9-309e8be7b393)

**Comment by k3rwin** [comment]
> yakit.exe

![image](https://github.com/yaklang/yakit/assets/59213152/eeb17882-15e1-4950-a9d1-ab1999610a15)

**Comment by WAY29** [comment]
尝试添加启动选项`--no-sandbox`或者将Yakit卸载重新安装到C盘

**Comment by k3rwin** [comment]
> 右键管理员或者兼容模式可以吗？



> 尝试添加启动选项`--no-sandbox`或者将Yakit卸载重新安装到C盘

安装C盘后可以了，谢谢师傅
