### ISSUE TITLE
关于新版本yakit插件商店问题

### ISSUE THREAD

**Issue by charis3306** [yaklang/yakit#1652]
新版本yakit插件商店问题，添加插件现在搞得真花里胡哨。真难用

**Comment by WAY29** [comment]
你应该提供具体可能有问题或者需要优化地方的截图以及可能的优化方案，而不是只是埋怨，这并不能解决问题

**Comment by Vernon818** [comment]
师傅觉得是哪里有问题，可以详细描述一下嘛，正好最近有打算优化一下
