### ISSUE TITLE
【需求】remote grpc下 mitmproxy 持久化

### ISSUE THREAD

**Issue by Airboi** [yaklang/yakit#1653]
## 需求描述

remote grpc下，不能保证grpc连接持续稳定， 需要持久化mitmproxy，避免客户端（异常网络）关闭后，mitmproxy自动关闭导致代理失效

## 解决方案

yak 服务端开放mitmproxy功能，持久化开放mitmproxy

## 可选方案

-

## 附加信息

-

**Comment by WAY29** [comment]
yak引擎里很早就支持了这个功能，使用`mitm.Start()`来启动mitm即可，不需要启动yakit
