### ISSUE TITLE
高分屏下字体显示太小，建议添加全局字体设置。

### ISSUE THREAD

**Issue by cgw-99** [yaklang/yakit#1664]
高分屏下字体显示太小，建议添加全局字体设置。

**Comment by WAY29** [comment]
Duplicated: #1573

**Comment by nikKrian** [comment]
字体确实很难受

**Comment by VillanCh** [comment]
可以使用Chrome缩放来直接实现，Mac下Command++



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: nikKrian ***@***.***&gt;
发送时间: 2024年8月13日 10:59
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 高分屏下字体显示太小，建议添加全局字体设置。 (Issue #1664)





 
字体确实很难受

**Comment by nikKrian** [comment]
这边windows环境下，使用 Chrome 的缩放快捷键来控制缩放并不管用

**Comment by VillanCh** [comment]
Windows应该是Control++吧？可以搜一下百度看看呢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: nikKrian ***@***.***&gt;
发送时间: 2024年8月13日 11:06
收件人: yaklang/yakit ***@***.***&gt;
抄送: v1ll4n ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [yaklang/yakit] 高分屏下字体显示太小，建议添加全局字体设置。 (Issue #1664)





 
这边windows环境下，使用 Chrome 的缩放快捷键来控制缩放并不管用

**Comment by nikKrian** [comment]
还是不行，看到不少issues提了这个全局字体的问题了，现在只有http报文编辑框可以调节字体，windows全局缩放好像对它都没有作用
