### ISSUE TITLE
被动指纹识别插件无法正常工作于MITM

### ISSUE THREAD

**Issue by guchangan1** [yaklang/yakit#1666]
## 问题描述

MITM功能勾选被动指纹识别插件后，并未获取指纹。

## 预期行为

应该在漏洞处看到指纹。

## 实际行为

![image](https://github.com/yaklang/yakit/assets/54949079/32c2717e-ce8d-4ce3-b533-9c296e18097f)

## 环境信息

- 操作系统: Darwin
- 系统架构: arm64
- Yakit 版本: 1.3.3-sp1
- YakLang 版本: 1.3.3-sp1

**Comment by WAY29** [comment]
该插件只会在MITM的被动日志处输出指纹，可以自行修改代码使其能够在漏洞处输出指纹

**Comment by guchangan1** [comment]
了解
