### ISSUE TITLE
插件商店的插件已安装和未安装不好区分，安装进度和成功或失败也看不到

### ISSUE THREAD

**Issue by eric-nie** [yaklang/yakit#1667]
## 需求描述

请清晰明确地描述你遇到的问题，例如：我在使用该产品时总是遇到以下问题...

## 解决方案

请清晰明确地描述你希望达成的目标和解决方案，例如：我希望产品能够实现以下功能...

## 可选方案

请清晰明确地描述你考虑过的其他方案或功能。

## 附加信息

请提供任何与该功能请求相关的上下文信息、截图或其他材料等。

**Comment by charis3306** [comment]
我也一样，这个新版本的插件仓库。没有之前的好用。我现在都不知道如何自定义组。还有默认定义的组可以删除吗？我真觉得没有。

**Comment by charis3306** [comment]
例如在组管理中，我无法理解怎么添加到组和删除组中单个插件。每次启动都要重新选择。
![image](https://github.com/yaklang/yakit/assets/84823804/9e4f1ee3-37b3-4d96-921a-98169adab68b)
![image](https://github.com/yaklang/yakit/assets/84823804/165e8346-bddc-4a4c-b91a-5e7b77a6453a)
没版本好用。

**Comment by Vernon818** [comment]
（之前改的时候是想着把组得操作放在一起去管理，方便一点，但是现在看来大家不是很习惯，这里后面会把交互重新改一下，师傅可以按照下面的说明先用着）
删除组，悬停上去就可以删除
![image](https://github.com/yaklang/yakit/assets/94944398/20017e7b-c0ea-4e52-aaaf-4b3ea2376c38)
![image](https://github.com/yaklang/yakit/assets/94944398/9607458e-9655-4c78-b468-fbb263ce2e83)
![image](https://github.com/yaklang/yakit/assets/94944398/6a15e5e3-0fa4-40eb-b6fb-baae632bd382)

**Comment by Vernon818** [comment]
例如在组管理中，我无法理解怎么添加到组和删除组中单个插件。每次启动都要重新选择。

**Comment by Vernon818** [comment]
例如在组管理中，我无法理解怎么添加到组和删除组中单个插件。每次启动都要重新选择。

师傅说得每次都要重新选择，是操作完以后，重启，组都没有了吗（方便的话师傅可以加一下我微信Juzi19880818）

**Comment by Vernon818** [comment]
（之前改的时候是想着把组得操作放在一起去管理，方便一点，但是现在看来大家不是很习惯，这里后面会把交互重新改一下，师傅可以按照下面的说明先用着）
删除组，悬停上去就可以删除
![1716518899626](https://github.com/yaklang/yakit/assets/94944398/b56b065d-76a1-45fb-9ac3-eb8dc3240bf5)
![1716518905365](https://github.com/yaklang/yakit/assets/94944398/030fe46a-01c1-4e79-8141-1436238b897f)
![1716518911667](https://github.com/yaklang/yakit/assets/94944398/53c266e7-83ce-40c0-ae3c-8a705fa43b22)

**Comment by charis3306** [comment]
好的，感谢！

**Comment by Vernon818** [comment]
关于师傅说得是否安装，我们在最近在进行交互优化这里有考虑到，等改版后就能知道是否有安装。进度或者成功失败之后也会做一些明显的提示或者进度条什么的

**Comment by eric-nie** [comment]
收到，辛苦了
