### ISSUE TITLE
浏览器导入了crt证书，有些https网站还是无法访问

### ISSUE THREAD

**Issue by w990222** [yaklang/yakit#167]
浏览器导入了crt证书，有些https网站还是无法访问，或是访问https网站有些内容无法加载出来

**Comment by VillanCh** [comment]
推荐使用 Chrome，Chrome 使用系统证书，并不是浏览器证书。

**Comment by w990222** [comment]
crt证书直接导入到系统？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月18日(星期五) 下午4:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yaklang/yakit] 浏览器导入了crt证书，有些https网站还是无法访问 (Issue #167)





 
推荐使用 Chrome，Chrome 使用系统证书，并不是浏览器证书。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by VillanCh** [comment]
> crt证书直接导入到系统？

和 BurpSuite 的劫持 HTTPS 导入证书的操作是完全一致的，导入到系统，然后 Chrome 就会识别系统的证书。
