### ISSUE TITLE
【BUG】payload迁移数据无进度

### ISSUE THREAD

**Issue by k1nm0** [yaklang/yakit#1673]
## 问题描述

新建临时项目后，点击payload功能提示迁移数据，但是等了很长时间无进度。取消迁移后无法删除和更改payload字典。

## 预期行为

可以正常的迁移数据

## 实际行为

一直提示迁移数据且无任何进度。
![QQ截图20240522150405](https://github.com/yaklang/yakit/assets/51749714/584406f7-e58f-443d-9933-cb85056ddc78)

## 复现步骤

1. 新建临时项目
2. 点击payload，提示需要迁移数据
3. 点击确定

## 环境信息

- 操作系统: Windows_NT
- 系统架构: x64
- Yakit 版本: 1.3.3-sp1
- YakLang 版本: 1.3.3-sp1

**Comment by AWDSCAN** [comment]
我也遇到了同样的问题
环境信息：
操作系统: Microsoft Windows 11
系统架构: x64
Yakit 版本:  Yakit v1.3.3-sp1
YakLang 版本: Yaklang 1.3.3-rc7

**Comment by VillanCh** [comment]
![image](https://github.com/yaklang/yakit/assets/13946521/41808fab-ba05-49c2-9c30-064dfa1e8e44)
师傅使用 “更多版本” 选择 1.3.3-beta10 的增补版可以试一下

**Comment by AWDSCAN** [comment]
1.3.3-beta10版本可行，使用1.3.3-beta10版本后就没有卡住的情况了

> ![图像](https://private-user-images.githubusercontent.com/13946521/332729243-41808fab-ba05-49c2-9c30-064dfa1e8e44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjk2ODQsIm5iZiI6MTcxNjM2OTM4NCwicGF0aCI6Ii8xMzk0NjUyMS8zMzI3MjkyNDMtNDE4MDhmYWItYmEwNS00OWMyLTljMzAtMDY0ZGZhMWU4ZTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA5MTYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmZTYyNDI3MTEzNjMwNDhiNjU2NTE4OGJiNDJjYzAyY2I0NzIxZGM3YWVjNzExZTAyYTZhYTFmOGY0YThkNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KHoFnk7adNoVnPXP9kA-YCE70yfS1JT7IGv-ThcG70o)师傅使用 “更多版本” 选择 1.3.3-beta10 的增补版可以试一下

**Comment by k1nm0** [comment]
> ![image](https://private-user-images.githubusercontent.com/13946521/332729243-41808fab-ba05-49c2-9c30-064dfa1e8e44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzk4MDAsIm5iZiI6MTcxNjM3OTUwMCwicGF0aCI6Ii8xMzk0NjUyMS8zMzI3MjkyNDMtNDE4MDhmYWItYmEwNS00OWMyLTljMzAtMDY0ZGZhMWU4ZTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDEyMDUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkZmFkMzBlMDg5NjczODdkMWM5NGVhOGZlODUxMWFiZGE3YTBlNzUyNGFhYjliNzA5ZDliNTkyZTM3NTIzOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uZ9YZa6fmSJ-Qifsa9SMrWH5NrQJKzSqVoymPQb2tyw) 师傅使用 “更多版本” 选择 1.3.3-beta10 的增补版可以试一下

方法可行，感谢师傅
