### ISSUE TITLE
Windows Server 2016上安装无反应

### ISSUE THREAD

**Issue by Trevor3000** [yaklang/yakit#1682]
Windows Server 2012R2上运行会报错
![error](https://github.com/yaklang/yakit/assets/7857883/b3e8d588-cd82-45c1-a7ac-e26c9bef8c9f)
好像是因为electron版本支持的问题，希望能更新一下基于electron低版本的打包
目前1.3.3整个版本都有这样的问题1.3.2-sp5也不行，更低的版本我就没有试了

**Comment by WAY29** [comment]
由于升级了electron版本，所以后续Yakit版本只支持新版本Windows。你可以使用最后一个支持的版本：1.2.8-sp5

**Comment by Trevor3000** [comment]
> 由于升级了electron版本，所以后续Yakit版本只支持新版本Windows。你可以使用最后一个支持的版本：1.2.8-sp5

好的感谢，另外新版在Windows Server 2016下安装没反应

**Comment by WAY29** [comment]
> > 由于升级了electron版本，所以后续Yakit版本只支持新版本Windows。你可以使用最后一个支持的版本：1.2.8-sp5
> 
> 好的感谢，另外新版在Windows Server 2016下安装没反应

我找了一台Windows Server 2016 测试没有问题，你安装包是否是在远程直接运行的？如果是的话可能是因为网络问题，安装包并没有下载到本地，你先将安装包下载到本地再试试呢

**Comment by WAY29** [comment]
stale
