### ISSUE TITLE
Yak Runner模块方面的需求

### ISSUE THREAD

**Issue by aNewMind** [yaklang/yakit#1688]
## 需求描述

我在使用Yak Runner编码时，我想在终端里面输入一些参数，通过终端来运行脚本，很遗憾这里面没有。

## 解决方案

我希望可以在Yak Runner里面引入终端模块。

## 可选方案

请清晰明确地描述你考虑过的其他方案或功能。

## 附加信息
![Snipaste_2024-05-28_06-57-42](https://github.com/yaklang/yakit/assets/118876271/f4192920-2a73-491d-9349-acfbfbb8f13b)

**Comment by WAY29** [comment]
yak runner 正在完全重构中，现在想添加参数可以在yak runner右上角：
![image](https://github.com/yaklang/yakit/assets/41830147/2b0ba40b-cce6-4347-9db6-ec41049c51fb)
