### ISSUE TITLE
【BUG】文件上传09字节丢失问题

### ISSUE THREAD

**Issue by Xpr0adic** [yaklang/yakit#1697]
## 问题描述

文件上传的时候，数据流中出现09字节丢失

## 预期行为

正常上传图片时，图片或者数据流不应该有字节丢失

## 实际行为

通过yakit代理进行上传，图片出现损坏；
![image](https://github.com/yaklang/yakit/assets/45072269/2f18ec5c-dc43-4198-bbd3-af00a0aac775)
![image](https://github.com/yaklang/yakit/assets/45072269/67e3883f-e365-4caf-866f-8ca17f0fc452)

## 复现步骤

1、通过yakit代理进行上传，图片出现损坏；
![image](https://github.com/yaklang/yakit/assets/45072269/2f18ec5c-dc43-4198-bbd3-af00a0aac775)
![image](https://github.com/yaklang/yakit/assets/45072269/67e3883f-e365-4caf-866f-8ca17f0fc452)

2、正常访问网站进行上传，图片未出现损坏，排除网站问题
![image](https://github.com/yaklang/yakit/assets/45072269/08c82d9d-4d5b-4b8a-9e94-fbe7e91a96d0)
![image](https://github.com/yaklang/yakit/assets/45072269/2dca4ccc-c329-4b4b-8d2d-5cf2daccc4f6)

3、我把两张图片对比了一下，似乎是因为在4940行少了一个09，不知道是啥原因，而且之后的49B0行没有少
![image](https://github.com/yaklang/yakit/assets/45072269/3f6254a4-fd76-4494-b073-7c1a931ac26a)
然后在yakit数据包的二进制流中查找可以发现确实少了09
![image](https://github.com/yaklang/yakit/assets/45072269/d04e01d9-9410-4127-b6d1-0fb781991443)

## 环境信息

- 操作系统: Windows_NT
- 系统架构: x64
- Yakit 版本: 1.3.3-sp2
- YakLang 版本: 1.3.3-sp2

## 补充说明

不知道是哪次更新出现的问题，至少上个月还没发现这个问题

**Comment by Xpr0adic** [comment]
对了，再排除一下浏览器问题，用yakit代理chrome传了一次
![image](https://github.com/yaklang/yakit/assets/45072269/782eb645-c6da-4cca-b082-55ade9d076b6)

**Comment by VillanCh** [comment]
稍等排查一下，最近一个版本引擎有对 escape 有一点调整

**Comment by rookieBC** [comment]
已修复，师傅更新最新的1.3.3版本的引擎即可

**Comment by Xpr0adic** [comment]
好的，辛苦
