### ISSUE TITLE
【需求】一键复制一个 Web Fuzzer 所有配置到新的标签

### ISSUE THREAD

**Issue by ErickWei** [yaklang/yakit#1704]
## 需求描述
有时候使用 Web Fuzzer 进行调试时，参数和各种配置设置比较多，有时需要部分修改或者删除部分参数进行调试，但是又可能涉及到恢复原配置的情况，所以希望能有一个功能，能直接将一个 web fuzzer 的 tab 复制到一个新的 tab，包含所有的配置，尤其是那些参数设置，每次都要重新手动输入，太难了

**Comment by WAY29** [comment]
师傅更新最新的Yakit版本，现在应该已经实现了这个功能
