### ISSUE TITLE
【需求】增加支持输入多个匹配器

### ISSUE THREAD

**Issue by ErickWei** [yaklang/yakit#1706]
## 需求描述
目前只能输入一个匹配器，不能满足需求，希望能增加输入多个。比如说，需要显示错误信息为红色或者直接过滤掉，还需要将所特需的数据显示成绿色等等

## 解决方案

请清晰明确地描述你希望达成的目标和解决方案，例如：我希望产品能够实现以下功能...

## 可选方案

请清晰明确地描述你考虑过的其他方案或功能。

## 附加信息

请提供任何与该功能请求相关的上下文信息、截图或其他材料等。

**Comment by Vernon818** [comment]
好的，感谢师傅反馈，我们后期优化一下
