### ISSUE TITLE
【需求】Web Fuzzer中的标签是否自己可以设置多排显示，或者是单排显示

### ISSUE THREAD

**Issue by OnlycAreYou666** [yaklang/yakit#1707]
## 需求描述

Web Fuzzer中的标签是否自己可以设置多排显示，当标签开的很多的时候，那这个标签横排现在显示的话，很不容易找到标签，或者切换到其他标签，也很容易直接关闭掉。

## 解决方案

建议能修改成如编辑器那样当标签达到一个临界线后，可以自己设置成进行多排显示，或者是一排显示。

**Comment by Vernon818** [comment]
感谢师傅反馈，有计划优化为多排展示

**Comment by Vernon818** [comment]
最新版Yakit v1.3.4-sp3 已经支持
