### ISSUE TITLE
增加插件配置持久化等功能

### ISSUE THREAD

**Issue by Alex-null** [yaklang/yakit#172]
目前的插件配置无法持久化，使用api key的插件易用性较低，建议类似一个注册中心的kv数据库形式

**Comment by VillanCh** [comment]
Great! 感谢师傅建议

刚好社区的同学最近也提到了这个问题，近期的版本应该会找一个比较好的方式解决这个问题～

**Comment by Alex-null** [comment]
https://github.com/yaklang/yaklang.github.io/blob/master/docs/api/db.md
