### ISSUE TITLE
在交互式劫持页面没有显示延迟（ms）

### ISSUE THREAD

**Issue by db131** [yaklang/yakit#1722]
## 需求描述

在交互式劫持页面没有显示延迟（ms）

## 解决方案

在交互式劫持页面添加显示延迟（ms），

## 可选方案

或选择延迟（ms）开启或关闭

## 附加信息

在交互式劫持页面没有显示延迟（ms），但是在web fuzzer页面是有的

**Comment by Vernon818** [comment]
师傅是想手动劫持的时候显示延时哇

**Comment by db131** [comment]
> 师傅是想手动劫持的时候显示延时哇

yesyes，或者加个开关也可以哇
