### ISSUE TITLE
像burp一样内置浏览器

### ISSUE THREAD

**Issue by 75ACOL** [yaklang/yakit#1724]
因为一个环境等原因，我想在kali 使用 yakit，但是没有浏览器，需要我自己下载一个，这个就很麻烦了，可以内置一个浏览器么

**Comment by db131** [comment]
> 因为一个环境等原因，我想在kali 使用 yakit，但是没有浏览器，需要我自己下载一个，这个就很麻烦了，可以内置一个浏览器么

有内置浏览器，你点那个免配置启动qaq

**Comment by 75ACOL** [comment]
> > 因为一个环境等原因，我想在kali 使用 yakit，但是没有浏览器，需要我自己下载一个，这个就很麻烦了，可以内置一个浏览器么
> 
> 有内置浏览器，你点那个免配置启动qaq

免配置是指已经安装了chrome浏览器，不需要配置，打开环境路径中chrome浏览器，希望yakit自带浏览器
