### ISSUE TITLE
下游代理无法转发流量给xray

### ISSUE THREAD

**Issue by FP1uto** [yaklang/yakit#1729]
设置yakit的下游代理为xray被动扫描地址后，xray不仅无法接收流量，web站点也无法打开。这个是yakit无法和xray被动扫描联动吗

**Comment by VillanCh** [comment]
一般来说是不会有影响的，可能是系统的证书问题或者啥其他原因，可以打开日志看一下错误提示或者响应码下面的错误原因，截图脱密后发一下明天工作时间同事会看到～



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: FP1uto ***@***.***&gt;
发送时间: 2024年6月11日 23:28
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 下游代理无法转发流量给xray (Issue #1729)





 
设置yakit的下游代理为xray被动扫描地址后，xray不仅无法接收流量，web站点也无法打开。这个是yakit无法和xray被动扫描联动吗

**Comment by FP1uto** [comment]
试了试。还是会存在同样的问题。
单独使用yakit或者单独使用xray都没问题。
![屏幕截图 2024-06-12 095555](https://github.com/yaklang/yakit/assets/63441938/7ebd5394-36be-4583-b88a-accb33c3bd67)
但是将下游代理设置成xray后，极少数web流量能转发给xray，绝大部分web都无响应。
![屏幕截图 2024-06-12 095741](https://github.com/yaklang/yakit/assets/63441938/9e6aedcc-754b-4e77-806f-4f311436e58f)
比如访问user.skyeye.qianxin.com流量可以转发给xray，但是其他的web（比如edge，zhihu，还有其他的站点）一直无响应

**Comment by VillanCh** [comment]
可以看一下是不是Yakit开启了HTTP2选项



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: FP1uto ***@***.***&gt;
发送时间: 2024年6月12日 10:06
收件人: yaklang/yakit ***@***.***&gt;
抄送: v1ll4n ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [yaklang/yakit] 下游代理无法转发流量给xray (Issue #1729)





 
试了试。还是会存在同样的问题。
 单独使用yakit或者单独使用xray都没问题。
 2024-06-12.095555.png (view on web)
 但是将下游代理设置成xray后，极少数web流量能转发给xray，绝大部分web都无响应。
 2024-06-12.095741.png (view on web)
 比如访问user.skyeye.qianxin.com流量可以转发给xray，但是其他的web（比如edge，zhihu，还有其他的站点）一直无响应

**Comment by FP1uto** [comment]
感谢指导，的确是开了http2导致流量转发失败。关掉选项后流量能转发成功
