### ISSUE TITLE
【BUG】数据库中的域名资产全选后选择发送到漏洞检测毫无作用，并未发送过去

### ISSUE THREAD

**Issue by money0day** [yaklang/yakit#1730]
【BUG】数据库中的域名资产全选后选择发送到漏洞检测毫无作用，并未发送过去
如图点按钮跳过去，但是域名并没有发送过去
![image](https://github.com/yaklang/yakit/assets/172468189/56ae35e8-b877-4f16-bae1-b0ca9b2f8285)

![image](https://github.com/yaklang/yakit/assets/172468189/20ff65dc-b04e-4234-9299-830872d6ec81)

**Comment by Vernon818** [comment]
好的，估计是改版遗漏了，我们改一下哈

**Comment by Vernon818** [comment]
最新版已经修复
