### ISSUE TITLE
【需求】希望增强信息收集功能

### ISSUE THREAD

**Issue by lucky-ecat** [yaklang/yakit#1731]
## 需求描述

希望可以实现自动化信息收集, 目前的资产收集主要来自两个插件
1. 子域名收集, 存在不完全的问题
2. 空间搜索引擎, 一次只能调用一个引擎, 而且需要自己写语法, 且批量不友好

## 解决方案

希望可以合并两个插件并作出优化, 用户提供一个或者多个域名
在除了使用字典等方法收集资产的同时也可以根据用户填写的配置文件来调用多个引擎进行收集, 然后合并去重

## 参考方案

oneforall
fofa_view (狼组)
enscan

## 附加信息

请提供任何与该功能请求相关的上下文信息、截图或其他材料等。

**Comment by WAY29** [comment]
师傅可以自行编写插件来解决这种需求~
