### ISSUE TITLE
启动时提示超时

### ISSUE THREAD

**Issue by eric-nie** [yaklang/yakit#1741]
## 问题描述

点了一下面配置启动，第一次启动成功，关闭浏览器后再启动就提示错误

## 预期行为

请在此处描述您预期的行为，也就是问题被解决后应该出现的结果。如果可能，请提供具体的结果示例。

## 实际行为

请在此处描述您实际看到的行为，也就是问题解决后出现的结果。如果可能，请提供具体的结果示例。

## 复现步骤

请在此处提供能够复现该问题的具体步骤。如果问题是随机发生的，或者需要特定的环境条件才能复现，请提供更详细的说明。

1. 步骤 1关闭yakit程序再打开无效
2. 步骤 2电脑重启无效
3. 步骤 3重新安装sp5也无效

## 环境信息

- 操作系统: Windows_NT
- 系统架构: x64
- Yakit 版本: 1.3.3-sp5
- YakLang 版本: 1.3.4-beta2

## 补充说明
防火墙，杀毒软件都没有拦截
如果您有任何其他有关该问题的信息或评论，请在此处添加。
启动就提示如图，没有点面配置启动时一直都正常
![image](https://github.com/yaklang/yakit/assets/39858837/480b5733-d01d-46ea-ae17-c3fcccab8871)
![image](https://github.com/yaklang/yakit/assets/39858837/08e6b734-4636-476c-baac-52da9e8877b4)

**Comment by Vernon818** [comment]
因为没有找到本地的谷歌浏览器，师傅可以在这里配置浏览器位置
![483228cd3ad60b04f62fb33ffef7f47](https://github.com/user-attachments/assets/02ebd547-601b-4986-b5b2-516cac7af48b)
