### ISSUE TITLE
【需求】专项漏洞检测  或者 批量检测等，上传的资产没法超过 1024KB

### ISSUE THREAD

**Issue by money0day** [yaklang/yakit#1753]
【需求】专项漏洞检测  或者 批量检测等，上传的资产没法超过 1024KB
这个是根据性能决定跑的时候，这个可以改成自定义么

![image](https://github.com/yaklang/yakit/assets/172468189/c25bdd09-9f99-4d0d-8c8c-db4cec5c978d)

**Comment by Vernon818** [comment]
不是性能问题，是因为考虑远程使用，这里选择路径是需要前端把内容读出来填到框里的，太大的话，读取有问题，所以这里限制了大小

**Comment by money0day** [comment]
> 不是性能问题，是因为考虑远程使用，这里选择路径是需要前端把内容读出来填到框里的，太大的话，读取有问题，所以这里限制了大小

如果资产数目过大，有什么解决方案吗，可以添加一个本地使用的上传无大小限制

**Comment by Vernon818** [comment]
有的，我们到时候把这个限制放开，弄成自定义吧

**Comment by Vernon818** [comment]
最新版yakit v1.3.4-sp4已支持

**Comment by 0day4day** [comment]
1
