### ISSUE TITLE
【BUG】yakit file标签文件上传问题

### ISSUE THREAD

**Issue by Niiiiko** [yaklang/yakit#1754]
无后缀情况下，无法正常上传
![image](https://github.com/yaklang/yakit/assets/88720946/64d41021-0347-4429-854e-8a771e6a4469)
更改为jpg后可正常添加标签
![image](https://github.com/yaklang/yakit/assets/88720946/1a5e0b36-c3ed-46bf-a6d4-3a82bf0966ff)
![image](https://github.com/yaklang/yakit/assets/88720946/ff7ef106-d06a-43b4-8b18-d4f5a0d2fcad)

**Comment by VillanCh** [comment]
看起来是前端组件限制了，师傅可以直接在数据包中写 {{file(...)}} 这个标签即可，在之后的部分应该会修复这个前端问题

**Comment by WAY29** [comment]
已经在新版本中修复
