### ISSUE TITLE
【BUG】yakit 1.3.3 版本文件上传存在问题

### ISSUE THREAD

**Issue by Niiiiko** [yaklang/yakit#1755]
MITM时，抓取的文件上传数据包能正常上传并访问
![image](https://github.com/yaklang/yakit/assets/88720946/3dad65d1-820d-4476-b286-0ba2a5e3cbfb)
![image](https://github.com/yaklang/yakit/assets/88720946/8849681c-0aa9-43e0-bb53-31594f36fb5c)
重放后，无法正常访问
![image](https://github.com/yaklang/yakit/assets/88720946/678fc47b-d91d-477b-8d92-8ada251bc3da)
![image](https://github.com/yaklang/yakit/assets/88720946/d033b7d5-25c2-4b29-89df-16f762e7250f)

**Comment by WAY29** [comment]
只更新前端是没有用的，请更新至最新的yaklang版本

**Comment by Niiiiko** [comment]
> 只更新前端是没有用的，请更新至最新的yaklang版本

好的好的

**Comment by WAY29** [comment]
问题是否已经解决？如果解决的话可以关闭issue

> > 只更新前端是没有用的，请更新至最新的yaklang版本
> 
> 好的好的
