### ISSUE TITLE
【优化】关于fofa查询获取子域名的问题

### ISSUE THREAD

**Issue by Sea8ye** [yaklang/yakit#176]
关于spacengine.FofaQuery方法，实际场景是我想获取到fofa查询返回的域名，但是只能获取到顶级域名，然后发现函数返回的domains应该是取的fields中的domain，实际获取子域名需要取的字段是fields中的host：
![图片](https://user-images.githubusercontent.com/52484629/159283753-e974d889-8a2f-4ab2-a58c-9fd8752ff49d.png)

ps：Yak Runner输出面板可否支持复制的功能，不然每次都要打开cmd调用才能复制，不是很友好。

**Comment by Vernon818** [comment]
你好，可以升级一下最新版，Yak Runner已经支持复制了

**Comment by Sea8ye** [comment]
![image](https://user-images.githubusercontent.com/52484629/159421707-e39a138c-90e5-4485-98d3-8f7bd128eee2.png)
![image](https://user-images.githubusercontent.com/52484629/159422028-98c01c8e-ad44-452e-8433-2856639fbb1d.png)

已经升级最新版本了，但还是复制不了，右键或者ctrl+c都没有效果，是我哪里没弄对吗

**Comment by Vernon818** [comment]
修了但没完全修好，我们再看看
