### ISSUE TITLE
Mac arm版本新建文件夹失败

### ISSUE THREAD

**Issue by killdayu** [yaklang/yakit#1763]
<img width="1440" alt="iShot_2024-06-21_19 19 58" src="https://github.com/yaklang/yakit/assets/62084769/19c5835e-a51c-4dba-9362-af189b43993a">

**Comment by killdayu** [comment]
<img width="1440" alt="iShot_2024-06-21_19 20 41" src="https://github.com/yaklang/yakit/assets/62084769/9dbf9930-af95-4b3b-b333-531d39e7f0af">

**Comment by WAY29** [comment]
已经在yaklang最新版本(v1.3.4-beta4)修复
