### ISSUE TITLE
【BUG】history无法正常加载

### ISSUE THREAD

**Issue by VVeakee** [yaklang/yakit#1765]
序号10775-10251再往前拉就报错了
![image](https://github.com/yaklang/yakit/assets/85714114/41d192e1-afe3-43d0-8a67-60b00066e32f)

![image](https://github.com/yaklang/yakit/assets/85714114/694d684c-8b3c-4083-9025-89e447cdd475)

**Comment by WAY29** [comment]
应该会在下个版本修复
