### ISSUE TITLE
【BUG】好友无法下载分享插件

### ISSUE THREAD

**Issue by tadahana** [yaklang/yakit#1766]
插件设置为私密，将插件ID复制给好友，好友下载报错。
![1719113206337](https://github.com/yaklang/yakit/assets/168087709/9e77c4b9-0207-4b58-9204-2c8f41d4683b)

**Comment by VillanCh** [comment]
感谢师傅反馈，可以暂时先使用导出成zip文件



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: tadahana ***@***.***&gt;
发送时间: 2024年6月23日 11:27
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 【BUG】好友无法下载分享插件 (Issue #1766)





 
插件设置为私密，将插件ID复制给好友，好友下载报错。
 1719113206337.jpg (view on web)

**Comment by Vernon818** [comment]
师傅这个报错是引擎版本不对，之前这里有优化过，把引擎升级就好了
