### ISSUE TITLE
【需求】在规则匹配中匹配到的颜色和选中的颜色不一致

### ISSUE THREAD

**Issue by VVeakee** [yaklang/yakit#1768]
## 需求描述
在该区域内选中部分进行编码或解码或粘贴行为时并不能明确看到自己选中了哪些
![image](https://github.com/yaklang/yakit/assets/85714114/ba3420ec-9d91-4c94-be99-9ab0e8ac8667)

**Comment by Vernon818** [comment]
好的，我们下周会安排把这个颜色调整一下

**Comment by Vernon818** [comment]
最新版yakit v1.3.4-sp3已经支持
