### ISSUE TITLE
在哪可以执行ssa啊，这饼都画了半天了，终端也不能用

### ISSUE THREAD

**Issue by LztCode** [yaklang/yakit#1769]
<img width="944" alt="image" src="https://github.com/yaklang/yakit/assets/73683679/0cab0ebe-c175-4ec0-852d-046af06ff3bf">

**Comment by VillanCh** [comment]
Try this. https://github.com/yaklang/syntaxflow-zero-to-hero

每周会更新新的案例和教程，如果想了解发布前的最新动态，可以在
![image](https://github.com/yaklang/yakit/assets/13946521/31cc63ae-09eb-4a17-ab4f-bc53cd4ce143)
代码仓库找到
