### ISSUE TITLE
SQL注入扫描：UNION注入 插件代码问题

### ISSUE THREAD

**Issue by y9y2x8sz** [yaklang/yakit#1775]
d7015281-f355-4f23-9d36-3c4a5ec68458

你好，这个插件63行好像有点问题，pureInt = str.MatchAllOfRegexp(paramValue, `\d+`)
如果在request请求中参数的值是sms-123456  这类字母+数字的混合，正则也能匹配到，之后放到generateIntCastCheckingExpr函数的paramInt = atoi(i)~时就会报错。
看起来应该用`^\d+$`来匹配纯数字；但跟写的代码进行数字型注入的检测逻辑有点不一样，还是需要匹配出(字符串+数字)，只对数字部分进行"+2"请求后的相识度比对来判断是否是数字型注入。
![image](https://github.com/yaklang/yakit/assets/41031373/933cfe55-a1db-4c53-978b-c91a2a35c5ce)

**Comment by Vernon818** [comment]
好的，感谢师傅反馈~
