### ISSUE TITLE
Web Fuzzer模块下header头Content-Length问题

### ISSUE THREAD

**Issue by urdr-gungnir** [yaklang/yakit#178]
你好，我不知道是我的问题，还是没有这个设置。

在发送数据包的时候Content-Length并不会随着post数据改变而改变，

我希望能有个配置，可以配置自动改变content-length的值。

改变post参数，但Content-Length不改变，有时候是件麻烦事

![image](https://user-images.githubusercontent.com/73213935/159398341-fe8772a5-d400-4c15-9b56-ca816b582fbd.png)

**Comment by VillanCh** [comment]
实际上如果不在高级配置中配置的话，他是自动修复的


只是自动修复的时候并没有把修复后的数据包返回回来，导致好像没有修复数据包这个错觉，具体可以点开详情看请求，是修复后的数据


之后会增加一个把修复后的返回的按钮或者新特性



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: urdr-gungnir ***@***.***&gt;
发送时间: 2022年3月22日 10:58
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] Web Fuzzer模块下header头Content-Length问题 (Issue #178)





 
你好，我不知道是我的问题，还是没有这个设置。
 
在发送数据包的时候Content-Length并不会随着post数据改变而改变，
 
我希望能有个配置，可以配置自动改变content-length的值。
 
改变post参数，但Content-Length不改变，有时候是件麻烦事

**Comment by urdr-gungnir** [comment]
好的，了解了，谢谢
