### ISSUE TITLE
【BUG】启用DoH抗污染未生效

### ISSUE THREAD

**Issue by emhha** [yaklang/yakit#1781]
# 问题描述

浏览器中已经设置了只会使用安全DNS。

1. 在全局配置中设置了启用DoH抗污染选项，相关配置如图
![image](https://github.com/yaklang/yakit/assets/48557732/363410cf-5308-4e86-a6ab-4f72702e40b8)
使用Wireshark抓包抓到了明文DNS请求
![image](https://github.com/yaklang/yakit/assets/48557732/f67190f4-887a-4a0d-9571-4c137a50028d)

2. 关闭yakit代理后，刷新DNS缓存，重新使用浏览器访问，无法抓取到访问地址的DNS请求

# 环境信息

操作系统: Windows_NT
系统架构: x64
Yakit 版本: v1.3.4-sp2
YakLang 版本: v1.3.4-beta5

# 补充说明

如果您有任何其他有关该问题的信息或评论，请在此处添加。

**Comment by VillanCh** [comment]
感谢师傅反馈，一般在这个配置中需要额外禁用系统 DNS

如果未禁用系统 DNS 还是会有 UDP 发出

**Comment by VillanCh** [comment]
![image](https://github.com/yaklang/yakit/assets/13946521/fd6473f0-1f87-47b9-ab34-11651e292db7)
关闭系统 DNS 之后，就会在 Wireshark 中看到类似的 DoH TLS 请求

**Comment by VillanCh** [comment]
如果仅开启 DoH 不禁用系统设置，那么 DoH 一般会作为 “补充策略”，意思是当你的系统 DNS 不生效的时候可能才会启用 TCP 或者 DoH 作为补充

**Comment by emhha** [comment]
> 如果仅开启 DoH 不禁用系统设置，那么 DoH 一般会作为 “补充策略”，意思是当你的系统 DNS 不生效的时候可能才会启用 TCP 或者 DoH 作为补充

明白了，谢谢师傅
