### ISSUE TITLE
【BUG】WebFuzzer跟随重定向问题

### ISSUE THREAD

**Issue by lazy-forever** [yaklang/yakit#1782]
貌似遇到了一个WebFuzzer的BUG

访问 A.com/a ->302(Location: /e) 跟随重定向到A.com/e
此时的A.com/e返回值->302(Location: https://b.com/bbb) 继续跟随重定向到b.com/bbb
此时的b.com/bbb返回值->302(Location: /login) 

此时正常应该跟随重定向到**b.com/login** 查看详情却发现跟随到了**A.com/login**

**Comment by Vernon818** [comment]
感谢师傅反馈，修复后会在这里告知~

**Comment by WAY29** [comment]
已经在最新版本中修复
