### ISSUE TITLE
序列数据提取器

### ISSUE THREAD

**Issue by TZ0385** [yaklang/yakit#1792]
我想提取如图中的数字，但是前后有换行和空格，xpath提取出来的数据用在第二个数据包中存在空格换行，正则自动生成是五个整数，请问这种情况下怎么搞，或者怎样在第二个数据包中处理第一步的变量数据
![image](https://github.com/yaklang/yakit/assets/44598912/88316da6-63c2-4f6b-ac79-67cbeff3a65f)

**Comment by VillanCh** [comment]
{{trim({{param(name)}})}} 外层套一个 trim 可以移除前后空白



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: TZ0385 ***@***.***&gt;
发送时间: 2024年7月8日 19:50
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 序列数据提取器 (Issue #1792)





 
我想提取如图中的数字，但是前后有换行和空格，xpath提取出来的数据用在第二个数据包中存在空格换行，正则自动生成是五个整数，请问这种情况下怎么搞，或者怎样在第二个数据包中处理第一步的变量数据
 image.png (view on web)

**Comment by TZ0385** [comment]
谢谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月08日 19:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [yaklang/yakit] 序列数据提取器 (Issue #1792) |

{{trim({{param(name)}})}} 外层套一个 trim 可以移除前后空白



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: TZ0385 ***@***.***&gt;
发送时间: 2024年7月8日 19:50
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 序列数据提取器 (Issue #1792)






我想提取如图中的数字，但是前后有换行和空格，xpath提取出来的数据用在第二个数据包中存在空格换行，正则自动生成是五个整数，请问这种情况下怎么搞，或者怎样在第二个数据包中处理第一步的变量数据
image.png (view on web)
