### ISSUE TITLE
【需求】Codec功能配置复用WebFuzz

### ISSUE THREAD

**Issue by woshilao123** [yaklang/yakit#1796]
很多时候对于一些网站的fuzz 包括登录爆破，会有加密，当逆向出来加密方式 在Codec功能上做编排验证，希望可以直接在Codec编排后直接生成一个函数，或者有图形化操作可以直接复用到WebFuzz进行加密遍历。可以节省很多时间

**Comment by WAY29** [comment]
现在已经有这个功能了,只需要将codec流程保存成后在可以使用Fuzztag的地方使用对应`{{codecflow(流程名字)}}`即可

**Comment by x-f1v3** [comment]
> 现在已经有这个功能了,只需要将codec流程保存成后在可以使用Fuzztag的地方使用对应`{{codecflow(流程名字)}}`即可

mitm热加载时，怎么复用这个codec流程啊，比如在 hijackHTTPResponse 方法里写
