### ISSUE TITLE
【BUG】mitm交互劫持使站点无法正常加载完整js，如下

### ISSUE THREAD

**Issue by Ashupup** [yaklang/yakit#1797]
yakit的免配置加载的
![image](https://github.com/yaklang/yakit/assets/78542852/d2035697-254e-42f3-b30a-9162440fb690)

burp的免配置加载的
![image](https://github.com/yaklang/yakit/assets/78542852/7042ed6f-38ea-47c0-a992-f2a038026a0c)

好多情况下，yakit的劫持无法完整加载js，举例其中一个站点

**Comment by VillanCh** [comment]
最近修复了这个问题，师傅可以等今天更新引擎可以看到

**Comment by VillanCh** [comment]
师傅可以手动选择 - 更多版本 - 更新 1.3.4-beta8 版本，或者等待推送
