### ISSUE TITLE
nuclei 当前版本 2.3.8 太低了，导致很多yaml漏洞检测插件无法正常使用。

### ISSUE THREAD

**Issue by coffeehb** [yaklang/yakit#18]
![image](https://user-images.githubusercontent.com/5829776/140475718-ca45ae1d-f70a-46d0-9b76-3f6f5b7ef29f.png)

插件使用了类似dnslog的Out of band based detection.
验证，当前版本的nuclei不支持这个功能。

**Comment by VillanCh** [comment]
👌，周末我来安排一下，因为这个 nuclei 版本是特制的，更新的时候需要改一些东西

**Comment by Vernon818** [comment]
@coffeehb 为了感谢您对yak和yakit的支持，我们想邮寄一份小礼物给您，麻烦您微信添加一下：Juzi19880818，并备注好您的github账号。如已经添加账号，请微信联系我一下，谢谢
