### ISSUE TITLE
yakit不能启动引擎问题

### ISSUE THREAD

**Issue by jjjxusbx** [yaklang/yakit#1807]
![屏幕截图 2024-07-11 164549](https://github.com/yaklang/yakit/assets/146902099/2443fcf7-bd5f-4123-acd8-ff58465a9092)

下面是 start-engine-grpc.bat的运行日志，能看看问题出在哪了嘛。谢谢！！
[ERRO] 2024-07-11 18:36:40 [database:114] chmod +rw failed: chmod D:\Program Files\Yakit\yakit-projects\yakit-profile-plugin.db: Access is denied.
[ERRO] 2024-07-11 18:36:40 [database:114] chmod +rw failed: chmod D:\Program Files\Yakit\yakit-projects\default-yakit.db: Access is denied.

┓ ┳┳━┓┳┏ ┳  ┳━┓┏┓┓┏━┓
┗┏┛┃━┫┣┻┓┃  ┃━┫┃┃┃┃ ┳
 ┇ ┛ ┇┇ ┛┇━┛┛ ┇┇┗┛┇━┛
    1.3.4-beta7 yaklang.io

[INFO] 2024-07-11 18:36:40 [yak:410] start to initialize database
[ERRO] 2024-07-11 18:36:40 [database:114] chmod +rw failed: chmod D:\Program Files\Yakit\yakit-projects\default-cve.db: Access is denied.

(attempt to write a readonly database)
[2024-07-11 18:36:40]

(attempt to write a readonly database)
[2024-07-11 18:36:40]
[ERRO] 2024-07-11 18:36:40 [yak:413] init database failed: CallPostInitDatabase failed: attempt to write a readonly database
[FTAL] 2024-07-11 18:36:40 [yak:894] CallPostInitDatabase failed: attempt to write a readonly database

D:\Program Files\Yakit\yakit-projects\yak-engine>

**Comment by jjjxusbx** [comment]
本人的本机系统信息 
处理器信息：
CPU 供应商：GenuineIntel
CPU 品牌：13th Gen Intel(R) Core(TM) i5-13500H
![Uploading 屏幕截图 2024-07-11 184321.png…]()

**Comment by VillanCh** [comment]
看起来是数据库读写的时候发生了权限问题，可以考虑把数据库位置的整个文件夹删除重建，或者用管理员打开



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: bigbigworld ***@***.***&gt;
发送时间: 2024年7月11日 18:46
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] yakit不能启动引擎问题 (Issue #1807)





 
本人的本机系统信息
 处理器信息：
 CPU 供应商：GenuineIntel
 CPU 品牌：13th Gen Intel(R) Core(TM) i5-13500H

**Comment by jjjxusbx** [comment]
好的，问题解决了。感谢！
