### ISSUE TITLE
【需求】MITM交互式劫持规则匹配增加筛选或定位

### ISSUE THREAD

**Issue by HongLuDianXue** [yaklang/yakit#1820]
劫持的时候，经常遇到能根据规则匹配到一些需要关注的信息，但是返回数据包太大，又找不到匹配到的内容是什么。
比如下面这个场景，提示有“email泄漏，RSA私钥”，但找半天也找不到泄漏的内容具体在包的哪个位置，因为返回包太长了。
![WX20240714-091446@2x](https://github.com/user-attachments/assets/409b1196-7949-444d-8057-41a07b6e42e6)

如果能够添加一个按钮，一键把规则匹配到的内容给筛选出来显示就好了，或者定位到匹配内容的位置那里，这样都不需要每次翻找半天。
真的非常需要这个功能！拜托啦555

**Comment by WAY29** [comment]
点开右侧的按钮，会将匹配到的内容高亮
![image](https://github.com/user-attachments/assets/8076fd0d-4de8-4995-8067-11c92083fd86)

**Comment by Vernon818** [comment]
更新到最新版，就算不展开也会自动把匹配内容高亮哈~
