### ISSUE TITLE
[bug] release版本的问题

### ISSUE THREAD

**Issue by AhrendsSchmidt** [yaklang/yakit#1821]
从release里面下载适配arm架构的安装包，打开后显示安装包已经损坏无法使用，打开x64架构的安装包，可以正常使用，是否是上传包的时候出问题了，当前机器，m1 pro

**Comment by VillanCh** [comment]
官网安装文档有相关说明

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Michelski ***@***.***&gt;
发送时间: 2024年7月14日 10:04
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] [bug] release版本的问题 (Issue #1821)





 
从release里面下载适配arm架构的安装包，打开后显示安装包已经损坏无法使用，打开x64架构的安装包，可以正常使用，是否是上传包的时候出问题了，当前机器，m1 pro
