### ISSUE TITLE
【BUG】cli.StringSlice未按正常逻辑展示

### ISSUE THREAD

**Issue by Cha111Ng1** [yaklang/yakit#1822]
## cli.StringSlice未按正常逻辑展示

当我使用cli.StringSlice进行编程时，为在UI界面显示官网介绍的情况展示
当我使用cli.StringSlice("targets", cli.setSelectOption("下拉框选项", "下拉框值"))
在UI界面应当展示为了“下拉框值”。
## 预期行为

当我使用cli.StringSlice("targets", cli.setSelectOption("下拉框选项", "下拉框值"))
在UI界面应当展示为“下拉框选项”，而非“下拉框值”

## 实际行为

略

## 复现步骤

<img width="1181" alt="image" src="https://github.com/user-attachments/assets/411d6fe2-fd10-47d0-8e46-48a4763f2b33">

## 环境信息

- 操作系统: Darwin
- 系统架构: arm64
- Yakit 版本: 1.3.4-sp3
- YakLang 版本: 1.3.4-rc1

**Comment by rookieBC** [comment]
已修复
