### ISSUE TITLE
[bug] Accept-Encoding : zstd 未解压缩导致乱码

### ISSUE THREAD

**Issue by ccdyc** [yaklang/yakit#1824]
url：https://www.facebook.com/chinabusinesses/onboarding
预期：正常加载js并返回登录页面
目前状况：返回乱码的js
![20240715101922](https://github.com/user-attachments/assets/1fcedef7-0511-4340-9651-89e64af88db2)
![20240715101946](https://github.com/user-attachments/assets/759bb9ac-a3ca-4c45-94b4-b8cb72a073d4)

**Comment by WAY29** [comment]
将会在下个版本修复，增加zstd的支持

**Comment by WAY29** [comment]
Support By yaklang/yaklang#1552
