### ISSUE TITLE
不支持hosts解析覆盖？

### ISSUE THREAD

**Issue by defidead** [yaklang/yakit#1825]
我看bp有这个功能，yakit上没找到，能否增加此功能？
![image](https://github.com/user-attachments/assets/17696825-ef8c-4ea7-8833-87739b4889ee)

**Comment by OrangeWatermelon** [comment]
webfuzzer左侧高级配置，支持配置host映射

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月15日 12:36 |
| 收件人 | yaklang/yakit ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [yaklang/yakit] 不支持hosts解析覆盖？ (Issue #1825) |

我看bp有这个功能，yakit上没找到，能否增加此功能？
image.png (view on web)

**Comment by defidead** [comment]
感谢回复，我原本意思是mitm中不支持此项操作，现在已经找到，但是有个新的问题，高级配置不能够动态修改吗？现在修改hosts映射需要每次停止劫持然后重新启动劫持

**Comment by OrangeWatermelon** [comment]
暂时不支持动态修改，暂时还没遇到需要在劫持时频繁修改映射的需求，能提供下场景吗

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月15日 12:45 |
| 收件人 | yaklang/yakit ***@***.***> |
| 抄送人 | z3 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [yaklang/yakit] 不支持hosts解析覆盖？ (Issue #1825) |

感谢回复，我原本意思是mitm中不支持此项操作，现在已经找到，但是有个新的问题，高级配置不能够动态修改吗？现在修改hosts映射需要每次停止劫持然后重新启动劫持
