### ISSUE TITLE
[BUG]Host解析问题

### ISSUE THREAD

**Issue by Ms-yin** [yaklang/yakit#1826]
当我在虚拟机中使用phpEnv 创建网站后 
我在物理机中修改host文件绑定对应的iP地址
但是当我在yakit中抓包的时候 会发现 并没有解析我本地的hosts文件 而是直接去因特网中找寻 upload.local 
![image](https://github.com/user-attachments/assets/2b42a879-ed0e-4be8-abd5-b92f502edd89)

**Comment by VillanCh** [comment]
![image](https://github.com/user-attachments/assets/c0a089f7-efbd-4b05-ab43-b075dbb19af5)
师傅可以在这里设置

**Comment by VillanCh** [comment]
从数据包看起来，好像 host 写了个 typo， `upload.loaca`

**Comment by Ms-yin** [comment]
好的师傅 就是这个意思 方法可以用谢谢
