### ISSUE TITLE
请求过多导致的失败

### ISSUE THREAD

**Issue by Ms-yin** [yaklang/yakit#1829]
当我联系 upload靶场的时候 使用条件竞争来做测试 
正常上传文件的时候 访问过多会显示"dial tcp 192.168.67.134:80: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted." 这是什么原因 我并没有开其他的服务 只有yakit

**Comment by WAY29** [comment]
大量的发包可能耗尽了你的端口，尝试修改以下配置：
https://learn.microsoft.com/en-us/biztalk/technical-guides/settings-that-can-be-modified-to-improve-network-performance

**Comment by Ms-yin** [comment]
是的 已解决
