### ISSUE TITLE
【BUG】弱口令爆破的次数异常

### ISSUE THREAD

**Issue by wvykey** [yaklang/yakit#1830]
## 问题描述

弱口令检测模块，爆破的次数异常

爆破次数比字典数量不匹配（爆破lian两次就停止了）
![yakit_bug](https://github.com/user-attachments/assets/170d92c9-3d9b-49ee-ba2e-5ca85baa0db3)
![image](https://github.com/user-attachments/assets/ce874b96-79f9-43a0-b651-1a4db8f9d31b)

## 预期行为

爆破次数应该与字典数目匹配

## 实际行为

只爆破两次弱口令就停止了

## 环境信息

- 操作系统: Windows_NT
- 系统架构: x64
- Yakit 版本: 1.3.3-sp2
- YakLang 版本: 1.3.3-sp2

## 补充说明

无

**Comment by WAY29** [comment]
实际上当连接目标失败时会自动停止
