### ISSUE TITLE
【BUG】Web fuzzer 修改数据包后，「复制curl命令」的结果为修改数据包前的curl包

### ISSUE THREAD

**Issue by rcsupermanjob** [yaklang/yakit#1837]
## 问题描述

Web fuzzer 修改数据包后，「复制curl命令」的结果为修改数据包前的curl包

## 预期行为

「复制curl命令」的结果为修改数据包前的curl包

## 实际行为

「复制curl命令」的结果为修改数据包后的curl包

## 复现步骤

1. MITM 抓取任意包，并发送到 Web fuzzer  
<img width="612" alt="image" src="https://github.com/user-attachments/assets/9761bddb-86e9-4fe8-8f97-5490cebee6c0">
<img width="602" alt="image" src="https://github.com/user-attachments/assets/34d7e42a-f37c-4f7b-8b52-a56030522978"> 
  
2. 这里修改UA为yakit  
<img width="629" alt="image" src="https://github.com/user-attachments/assets/0493f749-3e40-4db0-9612-a4c4d37590e8">
  
3. 此时的curl包：curl -H 'Connection: keep-alive' -H 'sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'sec-ch-ua-mobile: ?0' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36' -H 'sec-ch-ua-platform: "macOS"' -H 'Origin: https://www.json.cn' -H 'Sec-Fetch-Site: same-site' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Dest: empty' -H 'Referer: https://www.json.cn/' -H 'Accept-Encoding: gzip, deflate, br, zstd' -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8' -H 'If-None-Match: W/"661a6b87-1d92f"' -H 'If-Modified-Since: Sat, 13 Apr 2024 11:24:55 GMT' 'https://static.json.cn/r/json/search_list.json'    
4. 此时需要把当前数据包再次发送到Web fuzzer才能拿到正确的curl包：curl -H 'Connection: keep-alive' -H 'sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'sec-ch-ua-mobile: ?0' -H 'User-Agent: yakit' -H 'sec-ch-ua-platform: "macOS"' -H 'Origin: https://www.json.cn' -H 'Sec-Fetch-Site: same-site' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Dest: empty' -H 'Referer: https://www.json.cn/' -H 'Accept-Encoding: gzip, deflate, br, zstd' -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8' -H 'If-None-Match: W/"661a6b87-1d92f"' -H 'If-Modified-Since: Sat, 13 Apr 2024 11:24:55 GMT' 'https://static.json.cn/r/json/search_list.json'
<img width="798" alt="image" src="https://github.com/user-attachments/assets/12210346-a482-4bad-8ec0-35d81e249271">

## 环境信息

- 操作系统: Darwin
- 系统架构: arm64
- Yakit 版本: 1.3.4-sp3
- YakLang 版本: 1.3.4-rc1

**Comment by Vernon818** [comment]
好的，感谢师傅反馈

**Comment by Vernon818** [comment]
最新版yakit v1.3.4-sp4已经修复
