### ISSUE TITLE
【BUG】漏洞风险详情弹窗报错

### ISSUE THREAD

**Issue by cheng-GT** [yaklang/yakit#1848]
## 问题描述

查看风险详情时弹窗报错

## 预期行为

显示风险详情

## 实际行为
![1](https://github.com/user-attachments/assets/7e3871f7-cfd7-4486-9bc8-bb840e989270)

## 复现步骤

请在此处提供能够复现该问题的具体步骤。如果问题是随机发生的，或者需要特定的环境条件才能复现，请提供更详细的说明。

1. 步骤 1
2. 步骤 2
3. 步骤 3

## 环境信息

- 操作系统: Windows_NT
- 系统架构: x64
- Yakit 版本: 1.3.4-sp3
- YakLang 版本: 1.3.4-rc1

## 补充说明

如果您有任何其他有关该问题的信息或评论，请在此处添加。

**Comment by Vernon818** [comment]
感谢师傅反馈，我们看一下

**Comment by Vernon818** [comment]
师傅是用哪个插件扫出来的，这是因为你等级那里是空，没有数据，所以前端加载出问题了

**Comment by Vernon818** [comment]
最新版Yakit v1.3.4-sp4已修复
