### ISSUE TITLE
m1 os11 更新后用不了是系统版本低了吗

### ISSUE THREAD

**Issue by BxYQ** [yaklang/yakit#1849]
获取引擎版本号...
错误: Error: Error invoking remote method 'get-current-yak': Error: 引擎由于信号而终止: SIGABRT Stderr: dyld: Symbol not found: _kIOMainPortDefault Referenced from: /Users/lalala/yakit-projects/yak-engine/yak (which was built for Mac OS X 14.0) Expected in: /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit

**Comment by VillanCh** [comment]
师傅可以重置一下引擎看看，或者手动安装一下 yak 引擎，放在 yakit-projects/yak-engine 目录下

**Comment by XC9409** [comment]
同寻求解决方式

**Comment by iSee857** [comment]
执行/yakit-projects/yak-engine/yak后
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
依旧是

**Comment by VillanCh** [comment]
CI 发布的编译版本确实是使用的 macOS 14 编译的，MacOS 比较新的版本修改了 IOKit 的一些接口，师傅可以先升级一下系统版本。但是一般不需要升级到最新的 macOS 14 版本也可以使用，可能只需要升级一到二个版本就行了

**Comment by VillanCh** [comment]
我们稍后调查一下 macOS11 到底修改了哪些 IOKit 的接口，看有没有办法规避这些风险

**Comment by iSee857** [comment]
> CI 发布的编译版本确实是使用的 macOS 14 编译的，MacOS 比较新的版本修改了 IOKit 的一些接口，师傅可以先升级一下系统版本。但是一般不需要升级到最新的 macOS 14 版本也可以使用，可能只需要升级一到二个版本就行了

在升级到14.x版本后问题得到解决了，感谢大佬支持
