### ISSUE TITLE
M3 ARM芯片安装问题

### ISSUE THREAD

**Issue by cmacckk** [yaklang/yakit#1850]
sudo xattr -r -d com.apple.quarantine /Applications/Yakit.app
会报错 option -r not recognized
暂时没有找到激活方法

**Comment by VillanCh** [comment]
师傅的 MacOS 版本是什么呢？which 一下 xattr 看看

```
❯ which xattr
/usr/bin/xattr
```

**Comment by VillanCh** [comment]
`find /Applications/Yakit.app -exec xattr -d com.apple.quarantine {} \;`

**Comment by VillanCh** [comment]
https://sysin.org/blog/macos-if-crashes-when-opening/

师傅也可以参考这个操作

**Comment by cmacckk** [comment]
感谢感谢 已解决
