### ISSUE TITLE
【需求】希望支持chromium免配置启动代理

### ISSUE THREAD

**Issue by asvidfhxadvdsfabskhh** [yaklang/yakit#1852]
## 需求描述

目前免配置启动代理只支持chrome，希望后面能支持chromium免配置启动代理

**Comment by WAY29** [comment]
![image](https://github.com/user-attachments/assets/ff5df667-ce2d-47dc-b260-2ba2756aba30)
尝试修改这个路径，启动免配置浏览器是通过此启动路径配合一些特殊的chrome启动参数实现的，按理来说chromium也支持

**Comment by asvidfhxadvdsfabskhh** [comment]
你好：


&nbsp; &nbsp; 修改路径之后可以使用chromium，感谢！




zhangyb.rookie
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yaklang/yakit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月26日(星期五) 上午10:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yaklang/yakit] 【需求】希望支持chromium面配置启动代理 (Issue #1852)





 
image.png (view on web)
 尝试修改这个路径，启动免配置浏览器是通过此启动路径配合一些特殊的chrome启动参数实现的，按理来说chromium也支持
