### ISSUE TITLE
webfuzzer 的Responses的渲染返回结果不全

### ISSUE THREAD

**Issue by recyvan** [yaklang/yakit#1853]
当前版本：Yakit v1.3.4-sp3，Yaklang 1.3.4-rc1
webfuzzer 的Responses的渲染返回结果不全,浏览器显示正常，但渲染界面数据部分丢失
如下：
![image](https://github.com/user-attachments/assets/3ab69b8f-fd31-4712-b93e-3dadb2c568b1)

**Comment by rookieBC** [comment]
师傅可以仔细看看，此页面的数据是通过JS动态填入dom树的，而在webfuzzer的渲染去解析运行js是不合理且不安全的。
