### ISSUE TITLE
【问题】空间引擎相关

### ISSUE THREAD

**Issue by ACEKILLER-YOU** [yaklang/yakit#1858]
![image](https://github.com/user-attachments/assets/6e23edcc-9458-4999-97fe-e85ff2c60857)
![image](https://github.com/user-attachments/assets/aa149d44-aa21-41b1-83d9-5506e9ba57fb)

配置了API-KEY，但是使用空间引擎功能提示令牌缺失。

**Comment by WAY29** [comment]
师傅你使用的是最新版的Yaklang和Yakit吗？这边复现不出来
