### ISSUE TITLE
【bug】特殊的payload名在模糊插入时会丢一部分字符串

### ISSUE THREAD

**Issue by SexyBeast233** [yaklang/yakit#1861]
![image](https://github.com/user-attachments/assets/cd8aaf9c-038f-4eb7-9fdd-72906cf3d17d)
这种带`-`的payload名称，在右键-模糊插入时，会丢失后半段字符串

![image](https://github.com/user-attachments/assets/eff2176f-e87a-48e9-b0bd-bf97a7fe990a)

![image](https://github.com/user-attachments/assets/cff56576-f323-4753-b186-6c60c4ced904)

**Comment by Vernon818** [comment]
Yakit v1.3.4-sp6 已修复
