### ISSUE TITLE
M2 系列 Macos 14.5 网卡权限失效

### ISSUE THREAD

**Issue by icefins** [yaklang/yakit#1883]
刚开始下载是好的，用过两次 然后重启一次电脑以后，网卡权限就失效了，自动修复也解决不了。
试过 重制引擎，更新最新引擎，卸载后重新安装，都无法解决。
<img width="1469" alt="image" src="https://github.com/user-attachments/assets/a698a5ac-87df-48e1-9589-65d5e5a2feac">
<img width="1029" alt="image" src="https://github.com/user-attachments/assets/e743131f-a639-4f79-ba4f-5af1d8ed5e17">

**Comment by VillanCh** [comment]
网卡权限指的是直接从网卡设备抓包的权限，一般SYN扫描和流量分析才会用，不影响其他功能


师傅可以尝试直接执行 sudo chmod +x /dev/bpf* 来直接给网卡权限，也可以通过 wireshark 设置 access_bpf 来间接修复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: icefins ***@***.***&gt;
发送时间: 2024年8月3日 20:54
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] M2 系列 Macos 14.5 网卡权限失效 (Issue #1883)





 
刚开始下载是好的，用过两次 然后重启一次电脑以后，网卡权限就失效了，自动修复也解决不了。
 试过 重制引擎，更新最新引擎，卸载后重新安装，都无法解决。
 image.png (view on web)
 image.png (view on web)

**Comment by icefins** [comment]
你好  我按照你提供的方法设置了sudo chmod +x /dev/bpf* 没有效果，能说一下 wireshark的设置方法吗？

**Comment by Vernon818** [comment]
师傅方便加我vx吗，Juzi19880818

**Comment by icefins** [comment]
感谢

**Comment by clhtylz** [comment]
> 感谢

你好 请问解决了吗？我也有相同的问题
