### ISSUE TITLE
Mac m1 安装后启动

### ISSUE THREAD

**Issue by Treasurez** [yaklang/yakit#1894]
提示 Yakit.app 已损坏，无法打开

**Comment by VillanCh** [comment]
直接百度搜索 m1 安装 dmg 提示已损坏的解决办法，或者跟随官网 yaklang.com 的安装引导



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Treasurez ***@***.***&gt;
发送时间: 2024年8月8日 17:36
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] Mac m1 安装后启动 (Issue #1894)





 
提示 Yakit.app 已损坏，无法打开

**Comment by Zeng-aN** [comment]
yaklang.com官网有解决方案
