### ISSUE TITLE
yakit远程连接使用域名连接卡死

### ISSUE THREAD

**Issue by chennimei** [yaklang/yakit#1895]
![image](https://github.com/user-attachments/assets/d630dfff-03a2-4257-917b-9613117e15ce)
使用域名连接就直接卡死掉
![image](https://github.com/user-attachments/assets/906f0aa2-1883-4f5b-bb55-a6f9d6652593)

用ip直接连就没事

**Comment by WAY29** [comment]
师傅我没复现出来呢，你这个123123.com是通过修改hosts添加的吗？

**Comment by chennimei** [comment]
> 师傅我没复现出来呢，你这个123123.com是通过修改hosts添加的吗？

这个只是演示，并不是我的domain

**Comment by chennimei** [comment]
> 师傅我没复现出来呢，你这个123123.com是通过修改hosts添加的吗？

师傅可以，你的域名绑定一下ip，然后使用域名连接试试？

**Comment by WAY29** [comment]
> > 师傅我没复现出来呢，你这个123123.com是通过修改hosts添加的吗？
> 
> 师傅可以，你的域名绑定一下ip，然后使用域名连接试试？

我这边测试过了，没有问题，正常链接
