### ISSUE TITLE
页面UI

### ISSUE THREAD

**Issue by ZXGbilibili** [yaklang/yakit#1899]
页面UI功能区不能自定义大小吗。？还有只有白的模式吗，真刺眼，整个暗夜模式啥的

**Comment by ZXGbilibili** [comment]
抓包，数据大的，只能看一部份，可以把顶部一些布局不用的时候关掉....或者可自定义调节（仅代表个人意见，谢谢）

**Comment by VillanCh** [comment]
顶部的菜单的右上角有个收起按钮，是可以按需点击收起



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 摘星怪 ***@***.***&gt;
发送时间: 2024年8月10日 17:29
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 页面UI (Issue #1899)





 
抓包，数据大的，只能看一部份，可以把顶部一些布局不用的时候关掉....或者可自定义调节（仅代表个人意见，谢谢）

**Comment by ZXGbilibili** [comment]
> 顶部的菜单的右上角有一个收起按钮，是可以点击收起自行发iPhone的
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 摘星怪 ***@* **.***> 发送时间：2024年8月10日 17:29 食谱：yaklang/yakit ***@***.***> 抄送：已订阅***@***.***> 主题: Re: [yaklang/yakit] PageUI (Issue #1899 ) 抓包，数据大的，只能看一个个体，可以把顶部一些布局不用的时候关掉....或者可自定义调节（仅代表个人意见，谢谢） — 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您订阅了该主题。消息 ID：***@***.***>

哈哈，看到了，谢谢
