### ISSUE TITLE
【需求】hijackSaveHTTPFlow 只能对MITM中的响应包进行染色，怎么对History中插件的响应包进行染色呢？

### ISSUE THREAD

**Issue by AA8j** [yaklang/yakit#1904]
hijackSaveHTTPFlow = func(flow /* *yakit.HTTPFlow */, modify /* func(modified *yakit.HTTPFlow) */, drop/* func() */) {
    flow.Red();
    modify(flow);
}

**Comment by WAY29** [comment]
将会在后续代码中新增保存flow结构体的接口，如:
```go
for flow in db.QueryHTTPFlowsByKeyword("keyword") {
    flow.Green()
    db.SaveHTTPFlowInstance(flow)
}
```
