### ISSUE TITLE
增加流量转发插件，用于转发单个数据包

### ISSUE THREAD

**Issue by taileilei** [yaklang/yakit#1905]
## 需求描述

在使用xray等被动代理工具时，通过下游代理总是将所有流量转发到xray等工具中，一个是流量过大很多数据包没有转发必要，二是容易忘记导致测试添加、删除功能时影响系统数据。

## 解决方案

我希望添加一个插件，可以在web fuzzer中，通过右键可选择“流量转发”，将单个数据包发送到指定的下游代理端口中，下游代理配置与mitm劫持中配置的不同，进行单独配置。可防止冲突。
如在插件中配置端口127.0.0.1:7777，在web fuzzer指定的数据包中右键，选择“流量转发”，即可将该数据包发送到配置的代理端口中。
或者在web fuzzer中的数据包扫描模块中活旁边新增一个模块，用于单独流量转发。如附加信息图片
## 可选方案

请清晰明确地描述你考虑过的其他方案或功能。

## 附加信息

![image](https://github.com/user-attachments/assets/8c9fc7c3-fab1-4ece-920d-5bccdced3759)

**Comment by WAY29** [comment]
这个功能只需要简单的添加一个可以用于webfuzzer的codec插件即可,唯一需要考虑的是如何配置转发的地址,这可能暂时没法实现,暂时只能写死

**Comment by WAY29** [comment]
可以使用MITM插件(被动扫描助手),然后在webfuzzer时挂上mitm代理即可
