### ISSUE TITLE
【建议】优化编辑插件时“获取参数”功能触发的逻辑

### ISSUE THREAD

**Issue by Sleepybear-lxx** [yaklang/yakit#1922]
在编辑插件时，只要对源码改动，就会触发右侧获取参数逻辑，且cpu占用飙升，当代码量大时会出现消耗大量时间且未准确分析出cli参数的情况，
![image](https://github.com/user-attachments/assets/1638444a-8766-4e77-9ce1-2d86c5fc1dc8)
建议触发获取参数的逻辑改为以下场景：
1.手动点击获取参数后触发
2.执行保存插件相关的操作后触发

**Comment by WAY29** [comment]
代码量一共有多少？

**Comment by Sleepybear-lxx** [comment]
700行左右

**Comment by Sleepybear-lxx** [comment]
还有个问题就是，调试时候设置请求类型为原始请求， 每次获取参数功能被自动触发后，原始请求都会被置空

**Comment by Vernon818** [comment]
> 还有个问题就是，调试时候设置请求类型为原始请求， 每次获取参数功能被自动触发后，原始请求都会被置空

好的，我们修一下
