### ISSUE TITLE
国密功能bug

### ISSUE THREAD

**Issue by smile127** [yaklang/yakit#1923]
MITM的国密访问国密浏览器的国密站点，访问之前的连接为国密，然而通过yakit的国密配置访问，连接变成了TLSv1.2
![屏幕截图 2024-08-19 142005](https://github.com/user-attachments/assets/d42587ed-8932-4303-8b73-6a8333be4ce9)
![屏幕截图 2024-08-19 142141](https://github.com/user-attachments/assets/f29b22a1-e9cd-48a1-bc65-c3cd5cbf617a)

**Comment by VillanCh** [comment]
在 “高级” 中有 “国密优先”

默认开始 国密 支持指的是 “兼容模式”

在 MITM 的 “高级” 配置中，可以配置 “只接受国密” “国密优先” 等选项

**Comment by VillanCh** [comment]
另，加上代理之后，你看到的证书是你和 MITM 之间的，这个被劫持掉的 HTTPS 其实无所谓是什么了，MITM 服务器发起的和服务器的链接是 GM

**Comment by smile127** [comment]
是的，勾选了只接受国密，那wireshark抓包得到的也是TLS

**Comment by smile127** [comment]
那怎么样才能抓到MITM服务发起的包啊

**Comment by VillanCh** [comment]
用 Wireshark 筛选目标服务器 IP 看下 TLS 层的选项

**Comment by smile127** [comment]
![屏幕截图 2024-08-19 160641](https://github.com/user-attachments/assets/5799b9be-fe80-42b4-864a-5ec64243cc07)
