### ISSUE TITLE
报告一个可能存在的逻辑缺陷

### ISSUE THREAD

**Issue by iSee857** [yaklang/yakit#1927]
提交插件时候 将待提交插件先改为私密状态，再改成公开状态。即时插件处于待审核状态也可以上线
![image](https://github.com/user-attachments/assets/5bb378c9-e6e4-4ddb-a6c4-c80a2394b2bc)
![image](https://github.com/user-attachments/assets/99e46db7-7957-4f7b-b09b-8ba3a4a048de)
![image](https://github.com/user-attachments/assets/a7205cab-7fc3-4fbb-8606-632cfd7822cb)

**Comment by Vernon818** [comment]
师傅可以讲一下操作流吗？我没复现出来……

**Comment by iSee857** [comment]
> 师傅可以讲一下操作流吗？我没复现出来……
使用版本：
社区版 Yakit v1.3.4-sp7
复现步骤：
1、编写插件脚本保存退出
2、选择上传，进行自动检测
3、提交后在我的-插件右下角改为私密状态。然后再重新改为公开状态

**Comment by Vernon818** [comment]
好的，谢谢师傅，我们复现出来了，马上修复一下发版~
