### ISSUE TITLE
[BUG] Yak Runner 修改文件名出现无限闪烁bug

### ISSUE THREAD

**Issue by navigt** [yaklang/yakit#1928]
## 问题描述

yak runner打开文件夹，修改任意文件名之后，文件名出现无限闪烁bug，应用直接卡死，重启打开有概率无法再打开文件夹内yak文件，有概率再次无限闪烁应用再次卡死无法使用。

## 复现步骤

请在此处提供能够复现该问题的具体步骤。如果问题是随机发生的，或者需要特定的环境条件才能复现，请提供更详细的说明。

1. yak runner打开文件夹
2 .修改当前文件夹内任意文件名之后
3. 个人环境稳定触发此BUG，已录屏

https://github.com/user-attachments/assets/ad217a90-eccb-428b-8eca-44a86a29885f

## 环境信息

- 操作系统: Darwin
- 系统架构: arm64
- Yakit 版本: 1.3.4-sp7
- YakLang 版本: 1.3.5-beta7

## 补充说明

重启引用有时候会再此卡住。

**Comment by Vernon818** [comment]
好的，感谢师傅反馈

**Comment by WAY29** [comment]
师傅可以试试最新版本Yakit v1.3.4-0827-sp1，是否还存在这个问题？

**Comment by navigt** [comment]
> 师傅可以试试最新版本Yakit v1.3.4-0827-sp1，是否还存在这个问题？

正常了 师傅。
