### ISSUE TITLE
【bug】内置插件"ssrf http public"判断逻辑有误

### ISSUE THREAD

**Issue by shlye1** [yaklang/yakit#1937]
![image](https://github.com/user-attachments/assets/19f934f7-c403-4d1e-b151-04caf67e18d4)
原来的 if risk.CheckDNSLogByToken(token)[1] == nil 在 未触发dnslog时也会报洞，
应该将判断改为if risk.CheckDNSLogByToken(token)[0] != nil

**Comment by WAY29** [comment]
感谢反馈，会在后续修复
