### ISSUE TITLE
【Help~】Yakit 如何有效测试越权、未授权，就类似Bp里的插件，填写低权限的Cookie、未授权要删除的头部认证标识，管理员只需要点点点就可以最后看结果了。

### ISSUE THREAD

**Issue by ss3931** [yaklang/yakit#1940]
几位解惑的师傅，你们好
    我在Bilibili上把课程都看过了，但仍存在一个疑惑：
    Yakit 如何有效测试越权、未授权，就类似Bp里的插件，填写低权限的Cookie、未授权要删除的头部认证标识，管理员只需要点点点就可以最后看结果了，那些URI存在越权，哪些URI存在未授权。
     Yakit里我看到有类似介绍的插件，但都不尽人意，自己添加了替换规则，比如捕获Cookie替换为低权限用户的Cookie值，但是没成功（我开启了替换功能）。
     麻烦解惑，或者 能提供一点小小的帮助，即解决方法，谢谢。

**Comment by WAY29** [comment]
可以尝试使用MITM中的交互插件：多认证综合越权测试

**Comment by VillanCh** [comment]
![image](https://github.com/user-attachments/assets/2d6a7556-e437-430e-b1f6-43937b90b0af)
下载最新版本之后，可以按需配置，然后过流量后查看结果即可

**Comment by InventorMAO** [comment]
Header如果有多个认证参数怎么，不能配置多个header进行替换。可以参考以下burpsuite xia_yue这个插件

**Comment by VillanCh** [comment]
认证模式选择 Header 填了就好了

> Header如果有多个认证参数怎么，不能配置多个header进行替换。可以参考以下burpsuite xia_yue这个插件

**Comment by InventorMAO** [comment]
怎么填多个Key呢，比如系统的header有A、B、C三个参数一起进行校验，Value可以按行分割，Key好像不行
![image](https://github.com/user-attachments/assets/bbf00136-d448-4f4a-8619-d4f8ef195b05)
