### ISSUE TITLE
无法联网的情况下，如何更新软件和插件。

### ISSUE THREAD

**Issue by MasterBaron** [yaklang/yakit#1950]
因软件部署的环境无法联网，请问在保留原来数据的情况下，如何更新软件及插件？

**Comment by WAY29** [comment]
1.更新软件可以通过直接将安装包复制到离线机器安装即可
2.更新插件可以通过在联网的机器中下载好插件之后，将`安装目录/yakit-projects`文件夹下的yakit-profile-plugin.db复制到离线机器对应位置

**Comment by MasterBaron** [comment]
yakit-profile-plugin.db复制到对应位置了，但是打开软件还是没有看到本地插件更新。

**Comment by Vernon818** [comment]
建议可以下载以后导出插件，再换到另一台机器导入即可
![image](https://github.com/user-attachments/assets/74c85c11-dd29-4dfc-852c-6077b1e2ec4c)
![image](https://github.com/user-attachments/assets/1553ec01-b972-42ef-8e49-5098e6e13c95)
