### ISSUE TITLE
录屏功能-录制的视频不可播放

### ISSUE THREAD

**Issue by wy876** [yaklang/yakit#1960]
![image](https://github.com/user-attachments/assets/b8199767-741d-4724-9322-1c9921afc5ad)

![image](https://github.com/user-attachments/assets/e21f449b-4196-4ae6-b9f8-ef00fe4b034e)

**Comment by Vernon818** [comment]
视频的时间和首页图都读不到了，估计是视频信息丢失了，师傅可以从路径点过去看看文件还在不

**Comment by wy876** [comment]
> 视频的时间和首页图都读不到了，估计是视频信息丢失了，师傅可以从路径点过去看看文件还在不

文件是存在，但是文件大小0kb，我录制好几分钟的，都是只有0kb  
![image](https://github.com/user-attachments/assets/966d0334-8406-4c83-bceb-d2f2971e8c8f)

**Comment by wy876** [comment]
最新测试，yakit在物理机上录屏是正常的，虚拟机yakit录屏不正常
