### ISSUE TITLE
在yakit的web Fuzzer模块，重放请求包会出现详细原因：dial tcp ip:443: connect: bad file descriptor

### ISSUE THREAD

**Issue by y9y2x8sz** [yaklang/yakit#1962]
![image](https://github.com/user-attachments/assets/1d18e43c-8caa-48cd-bb93-097fc9c4b37d)

电脑是OSX端的，是哪里没有进行授权吗？或者是dns配置错误吗？
在google上搜索是linux文件操作符的问题。
![image](https://github.com/user-attachments/assets/9df39d46-eba2-4c35-b64e-7e6d3a0858a2)

属于偶发性的，过几分钟就可以继续发包。

**Comment by WAY29** [comment]
重放请求包指的是直接在Webfuzzer中发送请求吗

**Comment by WAY29** [comment]
系统可能达到了文件描述符的限制。可以通过运行 ulimit -n 命令来查看当前用户的文件描述符限制。如果限制过低，可以通过 ulimit -n [number] 命令来增加这个值。

**Comment by y9y2x8sz** [comment]
感谢，我试试看ulimit -n [number] 命令，当前又不会报错
