### ISSUE TITLE
shiro-gcm漏洞靶场有bug

### ISSUE THREAD

**Issue by pwnhxl** [yaklang/yakit#1978]
http://192.168.0.102:8787/shiro/gcm

DQCDO7mdQ3IWD0VxXYBc9Lf45NQSZqYpvsyW1eErrcixmIL9lQauwpzXBy3cGnPsDvtovnH+SJlg0hOqPhnDuN75AWloU+Hm8MTWteu/fKCq4wxxQCBrlrRQRyph+/ajQlqb5TS8zlzQzXcFEixU6EcN6qHaaVzR6T9IXdC7qlEgXYflIavircb64HMK5L0pJswJG1Z92/++Kqb7

Key: 2itfW92XazYRi5ltW0M2yA==

如图 gcm加密模式的靶场只有这个被动插件能检出  其他任何shiro检测工具都检测不出来  并且你们扫描出来的payload 用这个蓝队分析工具也解密不出来了   几个月前我测试的时候不这样的    最新版才有这个bug

<img width="855" alt="shiro-1" src="https://github.com/user-attachments/assets/8bd37421-0796-4f12-9dc3-79cac8c50b8e">
<img width="659" alt="shiro-2" src="https://github.com/user-attachments/assets/c5f097d5-7679-4796-a1b3-6e30abd30002">

**Comment by Go0p** [comment]
感谢反馈，确实有点问题，后续完成修复

**Comment by ruisika** [comment]
![image](https://github.com/user-attachments/assets/5e07c31a-5040-4c9c-8ae4-93b689efe5c3)

![image](https://github.com/user-attachments/assets/915aad1b-68d8-45b1-9e7d-1557bf606e42)

lT2UvDUmQwewm6mMoiw4Ig==


0mUI014sbXraqplgKlfuYn0+WxKVdn2hrppT4olXXcVSY6eP5ZuMI70Dj6cCq6Wb7yx850d//KLrcaDgr0GBjie6Ns6Xqk8f7UIJoLV1ilrA+5W/a197ytZrZZ4QBqRzOBwsiogyEHOeMHSnxEA3ATs+MEAQQMukJCpWFi4P6GYekGhH64W/L5e3kXinyiCxqPgHxUlhHrGeXjM7

![image](https://github.com/user-attachments/assets/bd708509-06c4-4c96-99da-afc84195ce74)

是不是还有问题
