### ISSUE TITLE
橙黄是yakit的保护色😊

### ISSUE THREAD

**Issue by ZXGbilibili** [yaklang/yakit#1986]
每日一提：
对于经常用yakit的使用者，白色的鼠标指针加上白色的背景版...............橙黄色倒是成了yakit独有的代表色了，每次发包测试，都是对眼睛的挑战，更何况是熬夜加班的牛马人🤐或者哪位大神能开发个UI插件也行啊

**Comment by VillanCh** [comment]
黑夜模式有望今年上线，师傅临时可以该系统鼠标样式缓解



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 摘星怪 ***@***.***&gt;
发送时间: 2024年9月14日 00:04
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 【需求】需求标题 (Issue #1986)





 
每日一提：
 对于经常用yakit的使用者，白色的鼠标指针加上白色的背景版...............橙黄色倒是成了yakit独有的代表色了，每次发包测试，都是对眼睛的挑战，更何况是熬夜加班的牛马人🤐或者哪位大神能开发个UI插件也行啊

**Comment by WAY29** [comment]
#1987

**Comment by ZXGbilibili** [comment]
是的，感谢yakit让我知道了，原来鼠标可以换颜色，已经用一个多月了，不过还是期待，新模式的上线🎉🎉🎉🎉
