### ISSUE TITLE
【BUG】问题标题

### ISSUE THREAD

**Issue by Alfalfaaaa** [yaklang/yakit#1998]
## 问题描述
某些相应包乱码
用burpsuit查看 乱码内容应为空

- 操作系统: Windows_NT
- 系统架构: x64
- Yakit 版本: 1.3.6-0906
- YakLang 版本: 1.3.6-beta1

**Comment by Alfalfaaaa** [comment]
![Uploading 微信截图_20240919122204.png…]()

**Comment by WAY29** [comment]
给出具体的例子和复现步骤

**Comment by Alfalfaaaa** [comment]
★Alfalfa★???
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yaklang/yakit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月20日(星期五) 上午10:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yaklang/yakit] 【BUG】问题标题 (Issue #1998)





 
给出具体的例子和复现步骤
