### ISSUE TITLE
【小需求】fuzzer模块批量执行时无法对响应延迟进行检索

### ISSUE THREAD

**Issue by iSee857** [yaklang/yakit#2000]
![image](https://github.com/user-attachments/assets/495c215e-596f-4b11-af84-e722bdc2d3f7)
场景：
在对ip或者域名进行批量sql时间盲注时候 无法根据响应体延迟时间进行筛选
需求：
在fuzzer响应体的延迟中增加一个搜索框便于sql时间盲注时筛选出存在问题的ip或域名
类型响应大小的检索框
![image](https://github.com/user-attachments/assets/9cadc51f-6aa6-4069-8d94-afac49434aa1)

如果可以实现的话 那真是太感谢了！！！

**Comment by Vernon818** [comment]
可以，我记一下~安排~

**Comment by WAY29** [comment]
#2008
