### ISSUE TITLE
Mac 10.15.7无法使用

### ISSUE THREAD

**Issue by ekko-zhao** [yaklang/yakit#201]
![image](https://user-images.githubusercontent.com/26781518/161212620-0390d338-c024-4ea9-a186-8b7d9e139923.png)
查询发现已经是10.15.x最新版本了。能否提供支持呢？

**Comment by VillanCh** [comment]
师傅需要升级新的 macOS 版本，这个是因为苹果系统机制的问题，某些新的安全特性启用了会导致旧的版本出现问题
