### ISSUE TITLE
【需求】关闭Yak Runner标签时添加提示用户保存临时代码再关闭

### ISSUE THREAD

**Issue by Zeng-aN** [yaklang/yakit#2015]
## 需求描述

我在使用该产品时总是遇到以下问题，关闭YakRunner标签时，没有提示用户去保存临时文件，此时未保存的临时文件直接就没了，误点关闭YakRunner时，代码直接无了

## 解决方案

我希望产品能够实现以下功能，在关闭YakRunner标签时，提示用户保存临时文件，而不是直接关闭整个标签

## 可选方案

暂无

## 附加信息

![2081727350536_ pic](https://github.com/user-attachments/assets/0684d7b7-1ad1-40d2-a48f-282cc678c8b3)

**Comment by WAY29** [comment]
已经在最新版本中支持
