### ISSUE TITLE
端口指纹扫描批量扫描错误

### ISSUE THREAD

**Issue by KrystianLi** [yaklang/yakit#2018]
yakit版本如下
![image](https://github.com/user-attachments/assets/f29b5790-a568-4610-a20d-50df98142db2)
Pcap 权限权限正确，使用管理员启动的yakit.exe
![image](https://github.com/user-attachments/assets/eefe3093-d3cc-4147-8d58-2b9a175755f1)

额外参数没有变动，在进行200多个域名端口扫描的时候出现错误，会自动退出yakit并处于一种不断连接本地引擎的状态
![image](https://github.com/user-attachments/assets/d15b41d4-c328-4c84-9bd0-b9e3ffdde900)

查询失败: Error: Error invoking remote method 'QueryRisks': Error: 14 UNAVAILABLE: No connection established

![image](https://github.com/user-attachments/assets/b5486e4b-4c76-4a3c-8def-a437a77ba219)

![image](https://github.com/user-attachments/assets/15704df1-2c4e-400f-bdfe-bd63037f606b)

**Comment by Vernon818** [comment]
师傅，方便加个微信吗？Juzi19880818，麻烦师傅给私发一下引擎日志

**Comment by Vernon818** [comment]
该问题最新版引擎已经修复
![image](https://github.com/user-attachments/assets/25f538c3-ba04-4feb-8270-5a433b663dfe)
