### ISSUE TITLE
【求助】如何使得请求的Host继承到下一个序列中

### ISSUE THREAD

**Issue by LtmThink** [yaklang/yakit#2021]
假设请求包host位置插入有一个临时字典，那么第一个序列将会发送多次请求到不同的host
![image](https://github.com/user-attachments/assets/f7c0f940-c240-438a-821a-521235b90df5)

那么我该如何配置序列2，使得每发送一次序列1，就会发送对应序列1的host一次。
现在的情况是每发送一次序列1，序列2就会发送临时字典里的所有host
![image](https://github.com/user-attachments/assets/c5db4a44-dbec-4e09-af54-ec545f622e07)

**Comment by LtmThink** [comment]
你好，需要实现的是从**请求头**中获取键值对匹配，现在好像只支持从响应包中获取数据?

**Comment by WAY29** [comment]
> 你好，需要实现的是从**请求头**中获取键值对匹配，现在好像只支持从响应包中获取数据?

不需要提取，直接添加变量即可
![image](https://github.com/user-attachments/assets/4814790a-0a64-4423-b6fb-5a7b28569dda)

**Comment by LtmThink** [comment]
原来如此，被这个问题困扰很久，感谢!!
