### ISSUE TITLE
yakit安装后打不开

### ISSUE THREAD

**Issue by mathematival** [yaklang/yakit#2022]
**问题描述**：
我在 Windows 11 系统上安装了 Yakit-1.3.6-0927-windows-amd64 版本，但是在尝试启动应用程序时，程序窗口出现了几秒钟便消失，并没有任何错误提示。

**系统信息**：
- 操作系统：Windows 11 专业版, 版本号 23H2，操作系统版本 22631.4249
- Yakit 版本：Yakit-1.3.6-0927-windows-amd64
- 硬件配置：处理器AMD Ryzen 7 6800H with Radeon Graphics, 机带RAM16.0 GB, 系统类型为64 位操作系统, 基于 x64 的处理器

**复现步骤**：
1. 下载并安装 Yakit-1.3.6-0927-windows-amd64，目标文件夹为E:\Yakit。
2. 双击桌面上的 Yakit 快捷方式。
3. 等待几秒钟，程序窗口出现了几秒钟便消失，并没有任何错误提示。

**期望结果**：
双击快捷方式后，Yakit 应用程序能够正常启动并显示主界面。

![屏幕截图 2024-10-05 125127](https://github.com/user-attachments/assets/83ca20b7-2c5a-4676-b2a7-626fc309306e)
如图所示，我按照上图安装好，并运行，只是出现了一个白屏窗口、几秒后便消失
![image](https://github.com/user-attachments/assets/9aea1da7-802f-4919-b611-d25159d4c2ef)

**已尝试的方法**：
1.以管理员运行
2.安装旧版本yakit，最早是Yakit-1.3.0-windows-amd64.exe
3.安装兼容版本，支持win7系统的版本
4.安装界面不运行yakit、不卸载旧引擎等
5.官网说可能pcap/libpcap 依赖出现问题，但电脑上已经安装npcap-1.79.exe
**均无效**

**Comment by VillanCh** [comment]
尝试在C盘安装启动，某些情况会有非C盘启动失败这个问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mathematival ***@***.***&gt;
发送时间: 2024年10月5日 13:08
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] yakit安装后打不开 (Issue #2022)





 
问题描述：
 我在 Windows 11 系统上安装了 Yakit-1.3.6-0927-windows-amd64 版本，但是在尝试启动应用程序时，程序窗口出现了几秒钟便消失，并没有任何错误提示。
 
系统信息：
  
操作系统：Windows 11 专业版, 版本号 23H2，操作系统版本 22631.4249
 
Yakit 版本：Yakit-1.3.6-0927-windows-amd64
 
硬件配置：处理器AMD Ryzen 7 6800H with Radeon Graphics, 机带RAM16.0 GB, 系统类型为64 位操作系统, 基于 x64 的处理器
  
复现步骤：
  
下载并安装 Yakit-1.3.6-0927-windows-amd64，目标文件夹为E:\Yakit。
 
双击桌面上的 Yakit 快捷方式。
 
等待几秒钟，程序窗口出现了几秒钟便消失，并没有任何错误提示。
  
期望结果：
 双击快捷方式后，Yakit 应用程序能够正常启动并显示主界面。
 
2024-10-05.125127.png (view on web)
 如图所示，我按照上图安装好，并运行，只是出现了一个白屏窗口、几秒后便消失
 image.png (view on web)
 
已尝试的方法：
 1.以管理员运行
 2.安装旧版本yakit，最早是Yakit-1.3.0-windows-amd64.exe
 3.安装兼容版本，支持win7系统的版本
 4.安装界面不运行yakit、不卸载旧引擎等
 均无效

**Comment by VillanCh** [comment]
也可以在命令行中运行Yakit.exe看错误提示



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mathematival ***@***.***&gt;
发送时间: 2024年10月5日 13:08
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] yakit安装后打不开 (Issue #2022)





 
问题描述：
 我在 Windows 11 系统上安装了 Yakit-1.3.6-0927-windows-amd64 版本，但是在尝试启动应用程序时，程序窗口出现了几秒钟便消失，并没有任何错误提示。
 
系统信息：
  
操作系统：Windows 11 专业版, 版本号 23H2，操作系统版本 22631.4249
 
Yakit 版本：Yakit-1.3.6-0927-windows-amd64
 
硬件配置：处理器AMD Ryzen 7 6800H with Radeon Graphics, 机带RAM16.0 GB, 系统类型为64 位操作系统, 基于 x64 的处理器
  
复现步骤：
  
下载并安装 Yakit-1.3.6-0927-windows-amd64，目标文件夹为E:\Yakit。
 
双击桌面上的 Yakit 快捷方式。
 
等待几秒钟，程序窗口出现了几秒钟便消失，并没有任何错误提示。
  
期望结果：
 双击快捷方式后，Yakit 应用程序能够正常启动并显示主界面。
 
2024-10-05.125127.png (view on web)
 如图所示，我按照上图安装好，并运行，只是出现了一个白屏窗口、几秒后便消失
 image.png (view on web)
 
已尝试的方法：
 1.以管理员运行
 2.安装旧版本yakit，最早是Yakit-1.3.0-windows-amd64.exe
 3.安装兼容版本，支持win7系统的版本
 4.安装界面不运行yakit、不卸载旧引擎等
 均无效

**Comment by mathematival** [comment]
<img width="780" alt="image" src="https://github.com/user-attachments/assets/8d18c15a-b2a4-4d7d-92cb-a80733d019f6">
命令行中运行Yakit.exe，错误提示如上

**Comment by mathematival** [comment]
尝试禁用硬件加速：
右键点击 Yakit 的快捷方式。
选择“属性”。
在“目标”字段中，在程序的路径后添加 --disable-gpu（确保有一个空格分隔）。
点击“应用”并“确定”。
尝试重新启动 Yakit。

还是无效：
<img width="779" alt="image" src="https://github.com/user-attachments/assets/4413ca51-0bb3-4e8c-a7ef-5bf9d9ba8e81">

**Comment by mathematival** [comment]
尝试在C盘安装启动，成功！

但不想在C盘安装🤣😭

**Comment by WAY29** [comment]
> 尝试禁用硬件加速： 右键点击 Yakit 的快捷方式。 选择“属性”。 在“目标”字段中，在程序的路径后添加 --disable-gpu（确保有一个空格分隔）。 点击“应用”并“确定”。 尝试重新启动 Yakit。
> 
> 还是无效： <img alt="image" width="779" src="https://private-user-images.githubusercontent.com/131344375/373847519-4413ca51-0bb3-4e8c-a7ef-5bf9d9ba8e81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNTgxNjYsIm5iZiI6MTcyODM1Nzg2NiwicGF0aCI6Ii8xMzEzNDQzNzUvMzczODQ3NTE5LTQ0MTNjYTUxLTBiYjMtNGU4Yy1hN2VmLTViZjlkOWJhOGU4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwMzI0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTJkYjBmYWUxYWU5YjJjYmQxY2VmMjgwM2RiMGY4ZDY3MmNiODAzMGYwMWI4YTI2OGNkNGQ3NmVkYzA2YjE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VNo06n8BXgInHWWAkg2j9UGz_mKIkrRTfIoz48QSgHE">

截图看看快捷方式是怎么写的？应该加上`--disable-gpu`就可以了的？
