### ISSUE TITLE
老版本正常运行，更新到最新版报错打不开，无法找到入口【无法定位程序输入点DiscardVirtualMemory于动态链接库D:/Yakit.exe上】

### ISSUE THREAD

**Issue by 0day4day** [yaklang/yakit#2024]
卸载重新安装也是这个报错

![image](https://github.com/user-attachments/assets/43085d95-f2cd-41bd-a5fa-524dc5865911)

**Comment by WAY29** [comment]
请在[官网](https://yaklang.com/)中下载兼容版本：
![image](https://github.com/user-attachments/assets/46c5451b-3b35-4b72-8d01-9927c0e92992)
