### ISSUE TITLE
【问题/bug】意外的部分不能拦截，出现大量8083端口的数据包

### ISSUE THREAD

**Issue by linxiao-wangchuan** [yaklang/yakit#2027]
浏览器访问8083后出现大量的爆红503，已经安装上yakit的证书到浏览器，但是未知原因无法拦截数据包，访问127.0.0.1:8083后出现了大量如下数据包，有直接崩溃的风险（早上崩了一次）
请问大佬知道这是啥原因吗？
![爆红截图](https://github.com/user-attachments/assets/4ee0df90-af78-49e0-94e4-811a5830b158)
系统信息：win11-23H2-22631.4169
yak信息：目前是更新到最新的版本
目前的临时解决办法是：屏蔽掉这个URL，但是有时候其他的网址访问也会出现类似的502问题，去掉yak代理后就没有问题了。使用BP的时候也没有这个问题。

**Comment by rookieBC** [comment]
这种情况出现的原因是，师傅你访问了mitm监听的地址 127.0.0.1:8083，多次经过mitm服务段导致了循环劫持
