### ISSUE TITLE
【问题/求助】桌面快捷方式启动闪退

### ISSUE THREAD

**Issue by DmTomHL** [yaklang/yakit#2037]
问题描述：使用不同权限启动时引擎闪退，使用桌面快捷方式以管理员启动GUI界面闪退，使用管理员命令提示符启动正常。

**Comment by DmTomHL** [comment]
排查了一下，发现从桌面启动会存在gpu问题，但是我从桌面启动的快捷方式即使已经添加了 --disable-gpu参数，仍然会闪退。

**Comment by Vernon818** [comment]
师傅是win吗？gpu问题建议参考这里https://github.com/yaklang/yakit/issues/2022

**Comment by DmTomHL** [comment]
> 师傅是win吗？gpu问题建议参考这里#2022

收到，感谢跟进。
