### ISSUE TITLE
redis爆破结果错误

### ISSUE THREAD

**Issue by qingchenhh** [yaklang/yakit#204]
![微信截图_20220402125327](https://user-images.githubusercontent.com/37011241/161367111-4b4a0bea-3a2f-448b-b2ab-ee356c90c0c7.png)
![微信截图_20220402125338](https://user-images.githubusercontent.com/37011241/161367116-b5037e4e-2765-4781-a02b-0afa12217afe.png)
![微信截图_20220402125521](https://user-images.githubusercontent.com/37011241/161367118-dbf3f2c2-d3a1-42a9-a76c-bf5cd793888a.png)
![微信截图_20220402125531](https://user-images.githubusercontent.com/37011241/161367123-b1c11732-6a58-4529-89ca-1d5734edf624.png)

**Comment by Vernon818** [comment]
谢谢师傅反馈，我们稍后排查看看
