### ISSUE TITLE
20241012更新后无法连接引擎

### ISSUE THREAD

**Issue by hg0434hongzh0** [yaklang/yakit#2041]
![image](https://github.com/user-attachments/assets/3dd43c58-d3fd-4584-8eb8-9d1e1b87c9c3)

**Comment by Vernon818** [comment]
![image](https://github.com/user-attachments/assets/29673725-87d7-4c54-877b-fee58aed581b)
因为端口被占用，师傅点击切换端口
![image](https://github.com/user-attachments/assets/9ad3b827-5b02-4796-86fb-4fe4377f4bcc)
