### ISSUE TITLE
劫持监听好像有问题

### ISSUE THREAD

**Issue by pinklinux** [yaklang/yakit#2043]
HTTP/1.1 502 Bad Gateway
Content-Type: text/html;charset=utf-8
Warning: 199 "martian" "dial tcp 192.168.3.21:9999: connect: can't assign requested address" "Tue, 15 Oct 2024 14:42:23 GMT"

**Comment by rookieBC** [comment]
是由于系统分配的客户端连接端口用尽，无法建立socket连接所致，是一个常见的错误
