### ISSUE TITLE
【需求】响应延迟的显示逻辑复杂

### ISSUE THREAD

**Issue by sunflowerkk** [yaklang/yakit#2044]
师傅你好。我这边发现进行延时注入时，发包的顺序并没有按照fuzztag给定的范围依次发包，是随机发包，希望后续可以改为按照顺序发包，或者提供可修改的选项。同时也发现回包显示的延迟时间是累加的（请求1命中了延时7秒，其余未命中），使用比较麻烦，希望可以改为每个请求单独计算延时时间。
![image](https://github.com/user-attachments/assets/609ea9ee-32d1-4866-810c-9de7e198ec11)
版本信息
![image](https://github.com/user-attachments/assets/80e81e63-ca4c-4317-9499-8efe2cd80fba)

**Comment by Vernon818** [comment]
![image](https://github.com/user-attachments/assets/79fb00fd-a22b-4452-8c91-78b099d6b298)
