### ISSUE TITLE
【BUG！！】yakit和bp访问同一网站，js响应不同

### ISSUE THREAD

**Issue by AhrendsSchmidt** [yaklang/yakit#2045]
yakit和bp访问同一网站，js响应不同。yakit的js响应包长度为0，状态码为304
<img width="1159" alt="image" src="https://github.com/user-attachments/assets/67381a99-eab7-4294-a920-d3419eec540e">

<img width="1338" alt="image" src="https://github.com/user-attachments/assets/591a1295-2c22-4b7c-b88a-64cb93838814">

bp的js响应包大小正常，状态码为200。
<img width="707" alt="image" src="https://github.com/user-attachments/assets/8fbb854d-dd06-463d-a07a-ff9fdb4c55b0">

<img width="1222" alt="image" src="https://github.com/user-attachments/assets/f4968dd7-f469-4058-af42-83069c440e5e">

**Comment by MisakaMikato** [comment]
师傅, 304状态码应该是浏览器缓存了js文件, 尝试清除浏览器缓存后, 再使用Yakit后, 看看是否会有此问题。
