### ISSUE TITLE
【BUG】all tls strategy failed: [EOF]

### ISSUE THREAD

**Issue by VBPush** [yaklang/yakit#2048]
## 问题描述
复现host头未校验漏洞时，遇到如下图所示错误（系统为https），浏览器直接访问可以成功访问到系统站点

![image](https://github.com/user-attachments/assets/4e5e32d4-d262-4e55-a4a5-ab19666a9be2)

这铁定是**BUG**，我通过yakit代理服务捕获浏览器访问的请求包，可以成功获取到资源，但是发送给Web fuzz执行却仍然报错all tls strategy failed: [EOF]

![image](https://github.com/user-attachments/assets/18d7cbd4-31d2-4e38-96db-ba7611cb1722)

其中HTTP的也报错：EOF，浏览器测试可访问，前几个版本我记得是可以正常测试的，不知道什么时候再测就一直报错EOF了
![image](https://github.com/user-attachments/assets/2db05b99-185e-455a-9469-3c07e44e9454)

## 预期行为
可成功访问到站点

## 实际行为
报错all tls strategy failed: [EOF]

## 复现步骤
1.获取系统IP并修改hosts文件，使其与随机字符串绑定；
2.通过yakit访问该字符串:端口进行验证，报错all tls strategy failed: [EOF]

不用管红圈，我写报告用的，然后就是这个是系统支持的tls协议及版本

## 环境信息

- 操作系统: Windows 11
- 系统架构: x64
- Yakit 版本: 1.3.6-1012
- YakLang 版本: 1.3.7-beta1

**Comment by VBPush** [comment]
请官方确认问题后（可自行保存后），删除执行步骤中的tsl版本信息截图

**Comment by rookieBC** [comment]
师傅是否未关闭左侧的系统代理配置，windows系统代理可能出现这样问题，因为代理并没有得到对应的hosts，所以会在握手的时候直接切断TCP链接导致这样的错误，之前的windows代理处理有问题会获取不到，近期版本更新修复了，所以造成了这样的问题。
之后会优化一下前端的展示提示使用了系统代理

**Comment by VBPush** [comment]
> 师傅是否未关闭左侧的系统代理配置，windows系统代理可能出现这样问题，因为代理并没有得到对应的hosts，所以会在握手的时候直接切断TCP链接导致这样的错误，之前的windows代理处理有问题会获取不到，近期版本更新修复了，所以造成了这样的问题。 之后会优化一下前端的展示提示使用了系统代理

我目前是最新版本Yakit v1.3.6-1012 + Yaklang 1.3.7-beta2  经测试，关闭全局代理后确实可以进行访问。前往你们什么时候会修复不支持全局代理的问题啊，我记得之前几个版本（大概是7-8月）是支持的，我当时同样进行同类型测试，就没这个问题。

**Comment by rookieBC** [comment]
是这样的，现在的全局代理是修好了的，之前是有问题的。

师傅你这个的问题是 全局代理正确的获取到了，主流的代理处理都是将大部分的工作交给代理，包括说域名解析。

而代理主机上没有师傅修改的hosts文件，代理主机找不到正确的目标，这样就导致了握手/连接失败，一般的代理就会直接关闭连接，外在表现就是EOF

**Comment by VBPush** [comment]
原来如此，我理解岔了
