### ISSUE TITLE
macos14.4，m3芯片无法安装yakit

### ISSUE THREAD

**Issue by bronnywang** [yaklang/yakit#2049]
<img width="536" alt="2" src="https://github.com/user-attachments/assets/243c52fb-2ae7-4f89-ad1b-66f7e9b76836">
<img width="244" alt="2024-10-18 15 04 24" src="https://github.com/user-attachments/assets/05e2fb33-7aa7-4adc-9908-51d138d3aafb">
<img width="559" alt="1" src="https://github.com/user-attachments/assets/645221f4-ffd9-4b4b-b0f3-3930d8bc0bb2">

**Comment by OrangeWatermelon** [comment]
看起来是直接在dmg镜像里直接双击打开的，
应该先把Yakit拖进Application文件夹再执行sudo xattr -r -d com.apple.quarantine /Applications/Yakit.app，再在mac启动器里打开

**Comment by bronnywang** [comment]
> 看起来是直接在dmg镜像里直接双击打开的， 应该先把Yakit拖进Application文件夹再执行sudo xattr -r -d com.apple.quarantine /Applications/Yakit.app，再在mac启动器里打开
谢谢师傅，问题已解决，最近刚换到macos，还在摸索使用中。
