### ISSUE TITLE
扫描无存活目标时，无法退出扫描

### ISSUE THREAD

**Issue by Anwen954** [yaklang/yakit#2052]
连接VPN之后，端口/指纹扫描模块进行主机存活检测会进入死循环，不进行主机存活检测仅进行SYN端口扫描可以正常进行，没有返回结果，详情请看VCR。

不进行主机存活检测：
![recording](https://github.com/user-attachments/assets/14200f16-1f08-4eb5-8b88-a86003adb279)

进行主机存活检测：
![recording](https://github.com/user-attachments/assets/8055f2aa-3bae-470d-950f-1ce707e6cd49)

相同环境使用jak脚本写一段代码进行测试报FTAL异常：
[FTAL] 2024-10-21 19:03:50 [yak:909] Panic Stack:
File "C:\Users\Anwen\AppData\Local\Temp\yakit-code-2542094046.yak", in __yak_main__
1 | # input your yak code
   2 | println(`Hello Yak World!`)
   3 > for result in synscan.Scan("awd19-b22.aqlab.cn", "80,443")~ {
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
   4 |     println(result.String())
   5 | }
   6 | println(`Hello Yak World!`)

YakVM Panic: native func `synscan.Scan` call error: get iface failed: handle route failed: %!s(<nil>)
![recording](https://github.com/user-attachments/assets/11d24cf4-ab51-47d3-b9ab-b9ed926a0aaf)

软件为最新版
![image](https://github.com/user-attachments/assets/44a02487-1ed9-42f7-85fd-bd50731799b1)
管理员启动
![image](https://github.com/user-attachments/assets/27d8b532-011a-4c19-8c49-b0d4ac3a82da)
代理正常
![image](https://github.com/user-attachments/assets/b1a153c5-c25e-4174-814e-45cdde4ce86f)
一般配置
![image](https://github.com/user-attachments/assets/734bffaf-5962-48ef-b181-3ebe6e20a7a9)

额外配置
![image](https://github.com/user-attachments/assets/28a38d84-06a2-46f1-9f01-8a5539d09d4e)

**Comment by Go0p** [comment]
用的是什么 VPN 软件呢？

**Comment by Anwen954** [comment]
和VPN关系应该不大，我在不连接VPN的时候进行测试也出现了这个问题。

**Comment by Anwen954** [comment]
![image](https://github.com/user-attachments/assets/b701ce12-3c16-4721-a2f2-08be91a8f5f4)
应该是捕获到了异常，但是没有终止事件循环

**Comment by Anwen954** [comment]
![image](https://github.com/user-attachments/assets/a7cc0ee9-0641-40a4-a939-24035281a990)
手动停止之后，扫描器状态未更新

**Comment by Vernon818** [comment]
师傅可以加我一下吗，我们想具体排查看看，vx：Juzi19880818
