### ISSUE TITLE
【BUG】规则匹配参数右下角查看有时会失效

### ISSUE THREAD

**Issue by RoyTse** [yaklang/yakit#2054]
如图所示，规则匹配提取的参数有时候会无法查看。

![image](https://github.com/user-attachments/assets/a1397ad2-94b9-467a-a8c9-0bc8202f3f93)

![image](https://github.com/user-attachments/assets/fd0bb75c-ca65-45b1-a88c-658b8e82be54)

**Comment by Vernon818** [comment]
好的，感谢师傅反馈，我试试看能否复现

**Comment by Vernon818** [comment]
师傅更新最新版引擎和yakit，已经修复了，但是需要重新抓包才可以
![image](https://github.com/user-attachments/assets/ca701ef3-4065-42a7-8556-d810bcf2e36f)
