### ISSUE TITLE
【需求】Codec增加将编解码顺序转为yaklang代码的功能。

### ISSUE THREAD

**Issue by Liehu** [yaklang/yakit#2055]
在使用codec工具时，往往需要把已经调试的工具转为热加载代码，因此，建议新增将编解码顺序直接转换为yak代码的功能，能有效提高热加载代码的编写效率，因为部分codec的接口并没有完全引出

**Comment by rookieBC** [comment]
![image](https://github.com/user-attachments/assets/3ff3d543-b284-4de0-8987-8ce68221d2fe)
可以将codec工具的工作流保存，即可在项目里使用fuzztag调用
