### ISSUE TITLE
新版本yakit出现闪屏情况

### ISSUE THREAD

**Issue by Starryvon** [yaklang/yakit#2060]
会一直闪屏

**Comment by VillanCh** [comment]
感谢师傅反馈，可以说一下大概是哪个页面或者怎么触发的吗？可以本地先暂时回退一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Feng Xinyu ***@***.***&gt;
发送时间: 2024年10月26日 13:22
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 新版本yakit出现闪屏情况 (Issue #2060)





 
会一直闪屏

**Comment by Starryvon** [comment]
我重装了兼容版本解决了，如果要那段闪屏的录屏可以私发给师傅

**Comment by VillanCh** [comment]
师傅是win7或者win8的一些系统吗？还是？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Feng Xinyu ***@***.***&gt;
发送时间: 2024年10月26日 13:39
收件人: yaklang/yakit ***@***.***&gt;
抄送: v1ll4n ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [yaklang/yakit] 新版本yakit出现闪屏情况 (Issue #2060)





 
我重装了兼容版本解决了，如果要那段闪屏的录屏可以私发给师傅

**Comment by Starryvon** [comment]
OS Name:                   Microsoft Windows 11 家庭中文版
OS Version:                10.0.22631 N/A Build 22631

**Comment by Starryvon** [comment]
Uploading 屏幕录制 2024-10-26 131932.mp4…

**Comment by Starryvon** [comment]
https://github.com/user-attachments/assets/34fc1a6a-c4bb-4c50-b8f9-9d076f67eb6b

**Comment by Starryvon** [comment]
每个界面都有类似的情况

**Comment by VillanCh** [comment]
感谢师傅反馈，我们研究一下看咋回事儿，可能是某些组件版本升级导致的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Feng Xinyu ***@***.***&gt;
发送时间: 2024年10月26日 13:45
收件人: yaklang/yakit ***@***.***&gt;
抄送: v1ll4n ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [yaklang/yakit] 新版本yakit出现闪屏情况 (Issue #2060)





 
https://github.com/user-attachments/assets/34fc1a6a-c4bb-4c50-b8f9-9d076f67eb6b

**Comment by Starryvon** [comment]
麻烦了

**Comment by Starryvon** [comment]
我感觉是windows11的问题，有其他的软件出现了类似的闪屏问题，都需要回退版本才可以
