### ISSUE TITLE
payload中无法导入字典

### ISSUE THREAD

**Issue by bamuwe** [yaklang/yakit#2061]
我尝试在payload页面导入字典，但是 导入文件 的选项似乎无法使用，导入到数据库又奇慢无比。与此同时，在发生这个错误后，yakit无法正常退出，我已经更新至最新版本，并且在mac和win机器上都做了测试，都存在这样的问题。我想知道这是页面显示的错误还是一个bug。通过console我发现偶然会有translate相关的错误，但是我并没有截到相应的图片。
![image](https://github.com/user-attachments/assets/bca5d28a-cf31-4217-814f-f5eab46453b1)

**Comment by WAY29** [comment]
你是否隔着一层wsl进行操作？文件看起来是存放在wsl中的，而客户端是在windows上，在wsl2中的跨windows与wsl访问文件io都会变得很慢，建议直接在windows中使用Yakit，引擎起本地模式

**Comment by WAY29** [comment]
这个文件存储的进度条是有一点问题，没有显示进度，后续会修复

**Comment by bamuwe** [comment]
好的，感谢感谢。昨天导入rockyou到数据库用了将近两个小时，磁盘读写超过800g，期待后续的更新

**Comment by WAY29** [comment]
> 好的，感谢感谢。昨天导入rockyou到数据库用了将近两个小时，磁盘读写超过800g，期待后续的更新

后续会新增大文件导入接口，rockyou大概1分钟内就能导入完

**Comment by bamuwe** [comment]
好的，期待越来越好，感谢您的耐心回复。
