### ISSUE TITLE
WebFuzzer栏出现匹配失败

### ISSUE THREAD

**Issue by ViCrack** [yaklang/yakit#2066]
Yakit v1.3.7-1025
Yaklang 1.3.7-beta3

发送数据包之后会出现一个 【匹配失败】，但是不知道匹配的什么东西，配置栏也没有开启匹配的才对

另外提下，师傅，这里Host碰撞的提示能加个开关隐藏掉吗

![图片](https://github.com/user-attachments/assets/cddc7cde-b327-4174-9b70-76addf209588)

![图片](https://github.com/user-attachments/assets/0cd3c47b-73f8-4ea7-8098-6e16cc42782c)

**Comment by Vernon818** [comment]
社区版 Yakit v1.3.7-1101 已修复
