### ISSUE TITLE
交互劫持的数据列先后顺序可以自定义吗？

### ISSUE THREAD

**Issue by ca1je** [yaklang/yakit#2071]
大佬们，交互劫持的数据列先后顺序可以自定义吗？好像没看到可以自定义的地方，每次有想看的数据列都不能直接看到，还得拖下面的条才能看，能不能搞个自定义数据列顺序的功能？
![image](https://github.com/user-attachments/assets/d80fadfb-ed04-41bf-a2af-b4c0ad545a19)

**Comment by WAY29** [comment]
duplicate with #2108
