### ISSUE TITLE
【需求】自定义全局配置

### ISSUE THREAD

**Issue by Cha111Ng1** [yaklang/yakit#2074]
## 需求描述

需要自定义全局配置内容，如我有一个全局变量，好几个插件我可能都会用到，如项目根路径，某个网站的key等，目前个人根据现有条件实现该功能的方案是，设置一个字典，然后用fuzz去读取这个值
例：
<img width="480" alt="image" src="https://github.com/user-attachments/assets/68511f1a-ee42-4d63-955d-daa93d8ff822">

## 解决方案

我希望产品能够实现在全局配置界面设置该值，即可使用该全局变量。
<img width="629" alt="image" src="https://github.com/user-attachments/assets/f1f4aea3-6186-49d6-9ba6-24473af680ba">

## 可选方案

略

## 附加信息

略

**Comment by Vernon818** [comment]
好的，感谢师傅反馈

**Comment by WAY29** [comment]
现在已经支持
![image](https://github.com/user-attachments/assets/65e3f0ec-2e4f-4b14-832e-e3419c465788)
![image](https://github.com/user-attachments/assets/a1ec7286-8f17-4ea6-9597-e1071e9f917b)
