### ISSUE TITLE
【BUG】被动插件选中后重新打开不记录上次选中的插件

### ISSUE THREAD

**Issue by lsclsclsc** [yaklang/yakit#2080]
1.选中插件并开启监听
![image](https://github.com/user-attachments/assets/7761551e-3786-4aa8-8564-0fd35e232fe5)

2.关闭yakit重新打开
![image](https://github.com/user-attachments/assets/27c347f9-d5b0-4aba-8d2d-6662eb7816a6)

**Comment by rookieBC** [comment]
![image](https://github.com/user-attachments/assets/4955ce4d-e1ad-4b1b-86bf-6414bf9781a0)
师傅是否操作过这个选项，开关此选项会清空插件启用记录

**Comment by lsclsclsc** [comment]
这个我用的时候一直是开启状态，当关闭重新打开开启劫持显示没有启用
