### ISSUE TITLE
【需求】代码审计中Syntax Flow 审计过程支持鼠标缩放

### ISSUE THREAD

**Issue by Liehu** [yaklang/yakit#2083]
如题，Syntax Flow 审计过程当前只支持点击缩放，影响操作体验，建议支持鼠标滚轮缩放，同时支持另存为png图，这样可以使用其他图片工具进行查看
![PixPin_2024-11-05_16-36-04](https://github.com/user-attachments/assets/d18e3eb7-cc8a-4084-835e-892be51928ce)

**Comment by rookieBC** [comment]
计划中的任务，我们在后面的版本会尝试支持

**Comment by wlingze** [comment]
在最新版本 Yakit v1.3.7-1206 中代码审计支持鼠标滚轮缩放以及简单的鼠标拖拽功能。并且建议配合
Yaklang 1.3.7-beta9一起使用完整功能。
