### ISSUE TITLE
变量传递

### ISSUE THREAD

**Issue by DamnVanish** [yaklang/yakit#2087]
请问现在版本的在使用序列的功能的时候，第一个数据包提取的到的一个量不能作为第二个数据包的变量的值的参数吗，就是我从第一个数据包中提取出path1，但是需要用nuclei的函数对path做处理然后变为变量path2，但是在使用设置变量的时候一直无法处理成功第一个变量，我确定没有用错nuclei的函数，比如{{remove_bad_chars(path1, "formmode")}}这样，或者其他的函数我都有尝试都无法成功的得到需要的结果，是没有这种传递的功能了吗

**Comment by VillanCh** [comment]
在fuzztag使用参数的时候，需要用fuzztag的语法，可以使用热加载标签直接加载一段yak代码实现功能，一般情况下不推荐在web fuzzer进行nuclei的表达式语法混用



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: DamnVanish ***@***.***&gt;
发送时间: 2024年11月7日 00:03
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 变量传递 (Issue #2087)

**Comment by WAY29** [comment]
看起来是一个BUG，会在下个版本修复
