### ISSUE TITLE
[插件显示问题]HTTP请求头伪造IP插件返回包显示异常

### ISSUE THREAD

**Issue by Crany-web** [yaklang/yakit#2091]
由下图可知启用```HTTP请求头伪造IP```插件后response包为空，导致红框区显示的```状态码```、```响应长度```为0，```IP```、```Title```、```响应类型```显示为-，但在浏览器中仍然显示403
<img width="1153" alt="image" src="https://github.com/user-attachments/assets/5bb90d9c-5983-4cc7-a851-901a5220ed4c">

> 上图中涉及的URL仅是我用于测试插件反馈项目问题，并无其他用途或目的，请勿用于非法用途

```shell
系统：Arch Linux
浏览器：Google Chrome 130.0.6723.116
浏览器代理插件：SwitchyOmega 2.5.21
yakit版本：Yakit v1.3.7-1101
yakit引擎版本：1.3.7-beta4
```

**Comment by WAY29** [comment]
这个流量是插件手动插入进去的，确实没有响应。这个插入的流量没有必要，后续可以由插件作者删除。
