### ISSUE TITLE
nuclei的函数使用异常

### ISSUE THREAD

**Issue by DamnVanish** [yaklang/yakit#2097]
在设置变量使用的nuclei的函数处理字符串的时候遇到返回结果错误的问题，自动变为一个数组的结果了，实际应该就返回处理好的字符串，这是bug吗
![1](https://github.com/user-attachments/assets/9b4213fd-9909-44c0-982b-8252d0217200)
![2](https://github.com/user-attachments/assets/54ee450d-75ba-4918-b412-008a51997b21)
![3](https://github.com/user-attachments/assets/a9f72a1b-7ec9-422f-829f-f0480892cd9a)
另外对于字符串处理的fuzztag在官方的fuzztag文档中没有找到可以用来处理字符串的函数，（https://www.yaklang.com/docs/yakexamples/fuzztag/#tagtable）是没写出来吗😢

**Comment by WAY29** [comment]
nuclei的函数并没有问题,而是太过兼容了,实际上path2的结果是数组的原因是因为path1的结果就是一个数组,这是因为数据提取器不管最终结果提取到多少个,都以数组的形式返回,所以简单的做法是将path2中的path1改为path1[0]

![image](https://github.com/user-attachments/assets/e4b7f2e0-fd4e-4d1a-89c3-96d6a8d00eab)

**Comment by WAY29** [comment]
yak引擎版本是？

**Comment by DamnVanish** [comment]
Yaklang 1.3.7-beta5

**Comment by WAY29** [comment]
> yak引擎版本是？

我刚在这个版本引擎中测试，没有遇到问题，nuclei中的内容正常渲染

**Comment by WAY29** [comment]
师傅是否还遇到问题？如果没问题的话就可以关闭该issue了。

**Comment by DamnVanish** [comment]
可以关了，转战yak了，yaml局限太多了😂😂😂
