### ISSUE TITLE
一直向存储桶

### ISSUE THREAD

**Issue by jibochang8** [yaklang/yakit#2103]
## 问题描述
会一直通过8080端口往yakit服务器发起请求
![qingqiu](https://github.com/user-attachments/assets/47afca67-4d9f-4965-bab7-6e51fc852b1f)

## 复现步骤

1.劫持8080端口

## 环境信息

- 操作系统: Windows_NT
- 系统架构: x64
- Yakit 版本: 1.3.7-1108
- YakLang 版本: 1.3.7-beta5

**Comment by Vernon818** [comment]
这个是查询最新版本的接口，是会轮训查询的
![image](https://github.com/user-attachments/assets/fa864d97-744f-4848-8d3e-53b40bd32839)

**Comment by WAY29** [comment]
应该是系统代理设置了mitm的原因，导致yakit去查询存储桶时会被mitm记录
