### ISSUE TITLE
「需求」Codec加入换行符替换？

### ISSUE THREAD

**Issue by fishBone000** [yaklang/yakit#2117]
今天搞Weblogic的SSRF的时候遇到需要URL编码CRLF的问题，但是可能是我复制的恶意代码不带CR，所以编码也没有CR。利用要求是要用CRLF的。  
可否在Codec加入换行符替换？界面顶上的小Codec加入使用CRLF/LF的选项，或者Codec主界面里加入换行符替换的功能。

感谢！

**Comment by WAY29** [comment]
![image](https://github.com/user-attachments/assets/3cbfea73-ce97-437f-862a-f857f8f9073f)
