### ISSUE TITLE
建议增加MITM劫持中手动劫持板块web fuzz板块请求/响应体的字体大小调节功能

### ISSUE THREAD

**Issue by nhqqxs** [yaklang/yakit#2125]
在MITM的自动放行板块中，数据包的请求/响应体字体大小是可以调节的
![图片](https://github.com/user-attachments/assets/7f3763f0-0f20-422f-ae5d-034f0f3167e9)
然而到了MITM的手动劫持板块和web fuzz板块中，数据包的请求/响应体字体大小却没法调节
![图片](https://github.com/user-attachments/assets/28720ebd-7af8-4384-ab47-732ab19076a7)

**Comment by Vernon818** [comment]
![image](https://github.com/user-attachments/assets/19f274c7-1078-4b15-88a1-06c12de620da)
可以右键调节
