### ISSUE TITLE
alert提示功能

### ISSUE THREAD

**Issue by n1ec** [yaklang/yakit#2127]
yakit.StatusCard是卡片
那么能不能开放这个api呢
场景：
插件开启后 ，可能某个配置未修改，需要弹框提示
![image](https://github.com/user-attachments/assets/226db1e9-3d0c-4e2e-b8b2-310a94dc2188)

比如 yakit.alert(”粘贴过快吧啦吧啦“) 之类的
![image](https://github.com/user-attachments/assets/d588fa72-e817-452c-b6c4-15e9ed49efe5)

**Comment by WAY29** [comment]
不考虑开放，因为这可能会被滥用
