### ISSUE TITLE
【BUG】{{file:dir}}标签不生效

### ISSUE THREAD

**Issue by winezer0** [yaklang/yakit#2141]
## 问题描述

{{file:dir}}标签不生效

## 预期行为

flie:dir应该实现文件的fuzz

## 实际行为

flie:dir()传上去的结果是空的，file()是OK的

## 复现步骤

上传包调用file:dir函数

## 环境信息

- 操作系统: Windows_NT
- 系统架构: x64
- Yakit 版本: 1.3.7-1122
- YakLang 版本: 1.3.7-beta6
![image](https://github.com/user-attachments/assets/0635c6c2-ec10-46bb-8cce-ab3d8d60719d)

## 补充说明

如果您有任何其他有关该问题的信息或评论，请在此处添加。

**Comment by Vernon818** [comment]
感谢师傅反馈，我们看看

**Comment by OrangeWatermelon** [comment]
已修复，下版本更新
