### ISSUE TITLE
【BUG】代码扫描功能 一直卡在项目编译中 进度99

### ISSUE THREAD

**Issue by Ca1mly** [yaklang/yakit#2146]
## 问题描述

java springboot项目

## 环境信息

- 操作系统: Windows_NT
- 系统架构: x64
- Yakit 版本: 1.3.7-1122
- YakLang 版本: 1.3.7-beta7

## 补充说明

如果您有任何其他有关该问题的信息或评论，请在此处添加。

**Comment by Vernon818** [comment]
感谢师傅反馈，我们复现看看

**Comment by Ca1mly** [comment]
不是每个项目都是这样，我个人测试三个，卡在99的两个

**Comment by wlingze** [comment]
> 不是每个项目都是这样，我个人测试三个，卡在99的两个

复现确实存在这个情况。这个是进度还没有结束，需要继续等待。
指令会在编译过程中保存到数据库，而编译最后一部分是将剩余的指令保存到数据库。进度条计算了所有文件的进度没有计算剩余指令保存的进度，只标记了99%等待结束。然后如果剩余指令过多的话可能这里会耗时比较久，看起来像是卡住了。
接下来将会调整下指令储存的机制和进度计算的逻辑。

**Comment by wlingze** [comment]
在yaklang 1.3.7-beta8版本该问题已经修复。
编译速度可能会感觉慢，但是其实是正常的，在1.3.7-bate7版本处理编译进度是错误的，编译的前半部分过快而后部分卡住，该问题只影响1.3.7-bate7这一个版本。
