### ISSUE TITLE
yakit插件点击编辑保存并退出会导致插件无法正常使用，除非二次下载，用户误触会导致体验不佳

### ISSUE THREAD

**Issue by Xianyu0day** [yaklang/yakit#2161]
![正常显示](https://github.com/user-attachments/assets/b25a362d-e18e-4539-937d-c61725ec0b97)
[](url)
正常界面
点击插件编辑：
![错误1](https://github.com/user-attachments/assets/a651fbb3-3d4a-4783-a7cb-f0cb6ae75be3)
![错误2](https://github.com/user-attachments/assets/c087b473-06c6-465b-a604-90f5cb31d72e)

**Comment by WAY29** [comment]
这是旧插件没有更新导致的，之前插件参数进行了改版，需要修改才可以正常使用。
