### ISSUE TITLE
【BUG】MacOS ARM M4 Vulinbox 靶场打不开

### ISSUE THREAD

**Issue by NEX-S** [yaklang/yakit#2163]
## 问题描述

MacOS ARM M4 靶场打不开

## 实际行为

[StartVulinbox] error:  fork/exec /Users/nex/yakit-projects/projects/libs/vulinbox: bad CPU type in executable

## 环境信息

- 操作系统: Darwin
- 系统架构: arm64

**Comment by VillanCh** [comment]
师傅可以安装 macOS rosette 转译工具，vulinbox 的跨平台编译没有像 yaklang 引擎这样晚上，使用 rosette 使用 amd64 兼容版本
