### ISSUE TITLE
【需求】数据列需要做筛选和自定义排序

### ISSUE THREAD

**Issue by Alfalfaaaa** [yaklang/yakit#2178]
## 需求描述

当我查看 历史请求 和 MITM 里的请求时，展示的**数据列**过多，我需要 筛选我想看的列 ，比如说我只想看 URL IP 时间 这三列 ，就没办法实现，我遇到的最大问题也就是 我想看的URL IP 和时间 无法在屏幕中同时显示。

## 解决方案

解决方案也是简单，设置一个 复选页面，勾选需要看的列  然后再设置一个 可以调整列的顺序的设置，比如我想再第一列 看时间，第二列URL，第三列IP 。

**Comment by WAY29** [comment]
duplicate with #2108

**Comment by VillanCh** [comment]
W.I.P
