### ISSUE TITLE
 fuzz tag 优化

### ISSUE THREAD

**Issue by virusdefender** [yaklang/yakit#2181]
## 界面和交互

- 输入 `{{xxx}}` 然后又删除了一些字符成为 `{{` 之后，再输入任意字符都不会弹出提示了，或者弹出的提示不对
- 按住 ctrl / command 然后鼠标点击 tag 的时候，可以显示提示或者跳转文档，就像写代码 ide 跳转那样

## 增加更多的 tag 和参数

- `file::dir` 增加 glob 筛选，然后能自动展开生成一堆请求作为 body 等数据。我的场景是有些写好的 http header + body 保存在文件夹中，想批量发出去看下 status code.
- 增加一些 json 处理的逻辑，比如 json 读取文件然后获取其中的 key value 放在这个位置；缺少 hex 编码等常见的函数。
- tag 可以嵌套，类似 `hex("some string")` 或者 `hex(file("some path"))` 这样的，再比如配合上述的 json 功能，可以提供 `json(data: string)` 和 `json_file(path: string)` 两种形式，同时也可以使用 `json(file(path: string))` 这样的。

## 支持使用代码增加自定义的 tag 

能写代码本来也是 yakit 的一些特色

## 联动

比如支持将 yso-java-hack 生成的 payload 保存为一个名字，然后使用 fuzz tag 引用，现在虽然有一个类似的 payload 引用的功能，但是看上去更像是爆破字典的场景。

**Comment by WAY29** [comment]
1. tag是可以嵌套的,例如:`{{base64({{url(123)}})}}`
2. hex编码是有fuzztag的,例如:`{{hex(123)}}`
3. 增加自定义tag是一个存在安全风险的行为,需要后续谨慎评估这个功能是否需要添加

**Comment by WAY29** [comment]
后续会加入jsonpath标签

**Comment by WAY29** [comment]
支持使用代码增加自定义的 tag will not support，在webfuzzer使用热加载代替

**Comment by WAY29** [comment]
现在fuzztag已经支持补全与悬浮提示
