### ISSUE TITLE
关于自带浏览器的一个建议。

### ISSUE THREAD

**Issue by bamuwe** [yaklang/yakit#2183]
<img width="129" alt="image" src="https://github.com/user-attachments/assets/1952f92b-e325-49a0-a82c-155b2c156d7b">
hello，后续能否考虑修改一下自带免配置浏览器的图标，使其更有辨识度？brup的chrome图标是蓝色的版本，而我们的图标和chrome一致，我在使用的过程中经常混淆自己查资料的chrome和yakit提供的免配置浏览器，或者有其他什么办法能够帮助我更好的切换到我想要的浏览器？

**Comment by WAY29** [comment]
yakit中使用的是自己安装的浏览器,而burp中使用的是Chromium(就是你说的蓝色的版本),这在技术上是没法实现改图标的

**Comment by VillanCh** [comment]
![image](https://github.com/user-attachments/assets/245d0980-abbd-44b8-8550-1a91d3874f0c)
可以考虑配置这个
