### ISSUE TITLE
【需求】关于webfuzz中热加载的需求建议

### ISSUE THREAD

**Issue by idealYan** [yaklang/yakit#2185]
当前的热加载模板仅有一个，多个webfuzz共用一个模板。如果测试a系统配置的热加载代码忘记重置，在测试b系统的时会返回错误的结果。当测试多个系统时，每次都要重新配置热加载代码。希望可以出一个热加载保存的功能，能配置自定义的热加载代码模板。
![image](https://github.com/user-attachments/assets/d6d4a754-f8f2-49de-98fc-8e5c7e894e60)

**Comment by WAY29** [comment]
测试新系统时应该直接开一个新的项目,这样流量什么的也能分离开

**Comment by WAY29** [comment]
另外一个建议是在逻辑中添加判断域名或者URL的情况,这样可以避免你其他无关的请求被修改
