### ISSUE TITLE
webfuzz标签描述有误，webfuzz标签解析时候无法停止

### ISSUE THREAD

**Issue by idealYan** [yaklang/yakit#2186]
1、webfuzz标签描述信息有误
![image](https://github.com/user-attachments/assets/b4045499-36fc-43cd-aba2-9c67548fe36e)
![image](https://github.com/user-attachments/assets/9182af0a-b97f-4b0d-af06-39b6cac89de3)
![image](https://github.com/user-attachments/assets/c71059c1-f2db-4bce-b7fb-ea28294c7cf5)
按照示例使用，无法进行fuzz解析
2、如果错误的使用标签，如：{{int(1-999999999)}}，会让cpu快速吃满，并且无法暂停
![image](https://github.com/user-attachments/assets/4efb495a-a2bf-4c9d-9739-c5568da20903)
![image](https://github.com/user-attachments/assets/e350dd53-8981-41d6-9847-ad20094eed5f)
![image](https://github.com/user-attachments/assets/12a48f72-0bcb-479c-b0f8-09f2ab609be8)

**Comment by WAY29** [comment]
已经在最新版本修复
