### ISSUE TITLE
需求 - history搜索

### ISSUE THREAD

**Issue by n1ec** [yaklang/yakit#2189]
history加个搜索请求或者响应功能，避免回显太多不应要的请求包，这应该能适当的优化些搜索速度和资源占用吧
![3dd6f57b66461a60022a4f2282f4c15](https://github.com/user-attachments/assets/3db9d438-5fd9-4008-a05f-2554cb1119c1)

**Comment by WAY29** [comment]
后续会加入此功能

**Comment by WAY29** [comment]
已经在最新版本中支持
![image](https://github.com/user-attachments/assets/e8887d9a-e0bf-43c0-93fd-54c23571eea6)
