### ISSUE TITLE
【BUG】Yak Runner语法检查错误

### ISSUE THREAD

**Issue by kang0x0** [yaklang/yakit#2192]
## 问题描述

编辑器的语法检查会提示字符串没有函数Rzfill()、Rfind()，但实际上可执行。
![image](https://github.com/user-attachments/assets/3eeb9b8a-3f97-43fc-b4a1-d12023af2f23)

assert "abc".Rzfill(5) == "abc00"
println("abc".Rzfill(5))
assert "abc".Rzfill(2) == "abc"

assert "abcabc".Rfind("abc") == 3
println("abcabc".Rfind("abc"))
assert "abcabc".Rfind("qwe") == -1

## 环境信息

- 操作系统: Windows11
- 系统架构: x64
- Yakit 版本: 1.3.7-1206
- YakLang 版本: 1.3.7-beta9

**Comment by WAY29** [comment]
这个我认为是不需要修改的,在执行时对于函数/方法是忽略大小写的,这是为了兼容性的考虑,但实际上仍然推荐写对函数名,所以这个报错是合理的

**Comment by wlingze** [comment]
关于`RFind`的报错是因为大小写，这是因为执行时忽略了大小写，而静态分析的报错应该检查这一点，这事没问题的，同时也建议你修改为正确的大小写 `RFind` 而非 `Rfind`。 
关于`Rzfill`的报错则是因为静态分析时的解析错误，缺少了这一内置函数导致的。目前已经确认并修复，将会在下次版本更新时修复。
> 一般版本更新时间为每周五

ref: https://github.com/yaklang/yaklang/pull/2268

**Comment by wlingze** [comment]
在最新版本Yaklang 1.3.8-beta1中已经修复。
