### ISSUE TITLE
标签关闭

### ISSUE THREAD

**Issue by getcode2git** [yaklang/yakit#22]
标签关闭是否可以批量，或者除此标签外关闭的其他的

**Comment by VillanCh** [comment]
指的是页面上方的 tab 框吗？可以实现的，我记下了

https://github.com/yaklang/yakit/projects/1#card-72802849

**Comment by VillanCh** [comment]
![image](https://user-images.githubusercontent.com/13946521/141639682-8219112d-3515-4fe3-b2b8-c09a34ffe514.png)

开发版已经加上了 @@getcode2git 

大约在下次更新将会使用到，右键即可触发 😄

**Comment by Vernon818** [comment]
@getcode2git 为了感谢您对yak和yakit的支持，我们想邮寄一份小礼物给您，麻烦您微信添加一下：Juzi19880818，并备注好您的github账号。如已经添加账号，请微信联系我一下，谢谢
