### ISSUE TITLE
规则匹配显示窗口过小/增加导出功能

### ISSUE THREAD

**Issue by mhtsec** [yaklang/yakit#2200]
1、在设置规则配置后，右下角显示输出的区块过小，容易显示不完全，很不方便，尝试往左边拉大它失败，好像是左边的请求包和发送包区域大小定死的，没法影响，建议搞个按钮，像发送到webfuzz那样发送到新窗口去查看，或者支持拉大它
<img width="481" alt="image" src="https://github.com/user-attachments/assets/867a7fb0-48c7-4f5e-921b-b75f6589a46b" />

2、建议增加一个功能，支持按匹配的分类选择，导出这些数据为表格，比如在邮箱数据非常多的的时候，需要批量使用到这些邮箱去爆破，按匹配规则分类选择，是为了可能同时存在sql注入点，文件读取点，邮箱数据等匹配到的数据时，可以单独选择sql注入点或邮箱数据导出，方便后续利用，而不用用户再去做一次分类

**Comment by rookieBC** [comment]
support: https://github.com/yaklang/yaklang/pull/2255
