### ISSUE TITLE
http劫持无法显示部分图片，包括验证码图片也无法劫持，且响应包渲染也没有加载图片

### ISSUE THREAD

**Issue by syslog-123** [yaklang/yakit#2204]
pikachu靶场，劫持流量，没有验证码图片，响应包也无法显示，BurpSuite可正常显示，免配置启动也一样。其他网页劫持流量，部分图片也无法显示。

https://github.com/user-attachments/assets/bf3b97eb-2704-40c7-b2ea-1e504c14d651

**Comment by rookieBC** [comment]
此处渲染处于安全考虑，使用的是沙箱模式，css，js等资源的外部加载与渲染。若需要查看渲染后的网页，可以使用浏览器
