### ISSUE TITLE
客户端认证证书无法导入

### ISSUE THREAD

**Issue by defidead** [yaklang/yakit#2230]
客户端证书使用密码进行导入 无法导入 在bp中可以正常导入 
<img width="985" alt="image" src="https://github.com/user-attachments/assets/ea6aeede-048c-4a46-8022-06d48d9de8d9" />
yakit中导入输入正确密码提示密码错误
<img width="1727" alt="image" src="https://github.com/user-attachments/assets/f119912e-eff7-4cb8-9452-869782828803" />

**Comment by defidead** [comment]
证书是从浏览器中已经导入的证书再次导出的，输入的密码是浏览器导出时提示设置的密码

**Comment by Vernon818** [comment]
同样的证书师傅再bp中正常导入，但是在yakit就一直提示密码失败是吧

**Comment by defidead** [comment]
是的

**Comment by rookieBC** [comment]
师傅如果方便的话可以提供一个样本嘛，我本地openssl生成了一个证书导入没有问题

**Comment by defidead** [comment]
给我个微信或者邮箱，我私发你证书

**Comment by defidead** [comment]
问题解决了，我将证书导入到系统重新再导出一个新的证书就能正常导入了，好像是windows和mac的系统问题？

**Comment by Vernon818** [comment]
好的，解决了我们就先关掉了哈~
