### ISSUE TITLE
【需求】爆破模块中重试添加关键字重试

### ISSUE THREAD

**Issue by Adm1nx1** [yaklang/yakit#2235]
yakit爆破模块这个重试条件能不能加个关键字重试
比如说我用验证码识别爆破，然后验证码没识别成功，但是是正常有返回的验证码错误
![3e926d8bc85ec0b0c126c1f54419009](https://github.com/user-attachments/assets/6cf23750-c474-4634-9721-f475a778042d)

**Comment by WAY29** [comment]
不是很希望再加入新的重试机制了，这种功能推荐师傅还是直接写yak脚本比较来的快

另外爆破验证码这种场景其实写个匹配器或者爆破完之后再筛选是不是就可以了，不需要重复发包，因为重复发包payload也是一样的
