### ISSUE TITLE
关于http history 的一些建议

### ISSUE THREAD

**Issue by Vulner-6** [yaklang/yakit#226]
![image](https://user-images.githubusercontent.com/56946543/164911612-812e9c38-cae3-47dd-bf2c-0d6f72efaa4e.png)
1.能否像burpsuite一样，对于感兴趣的请求包，自己可以定义高亮颜色。
2.我发现请求包的顺序和burpsuite里面的history请求包顺序完全不一样。burp是根据服务器的响应顺序，依次往下排列，且每一个请求包的序号都是唯一。而yakit则是每一页都是从1排列到20，每一个请求包的先后顺序与真实顺序不一致，这个很影响大部分安全从业者查看数据包的习惯。
![image](https://user-images.githubusercontent.com/56946543/164911914-e0437048-17fb-4a97-8c31-02146b093917.png)

最后，yakit的想法非常好，希望能成为改变整个行业的工具！

**Comment by VillanCh** [comment]
请求包的序号目前主要作用是为了助记，正序倒序其实都是可以改的～ 

感谢师傅的建议，在后续的版本中将会优化这几个点

**Comment by Vulner-6** [comment]
对了，我还希望 http history 的展示方式，像 burpsuite 一样，直接是滚动条下拉。假设对某个服务器的请求数据包数量刚好一页不够展示（比如一个点击功能，背后却包含着几十次数据交互，又或者有的网站每隔0.5秒就自动交互一次），那么分页展示就会十分影响使用者对数据包的筛选与理解。
这方面burpsuite的高亮与滚动条下拉的方式，再配合筛选数据包的功能，就可以避免这样的问题。（我认为目前数据包筛选功能远没有burpsuite强大易用）
另外，如果yakit的操作习惯十分接近burpsuite，那也能很好的进行用户“引流”，毕竟减少了新工具的学习成本，而且还拥有burpsuite没有的“特色”。
总结：
高亮+滚动展示+数据包筛选

**Comment by VillanCh** [comment]
自定义高亮在下一个版本就会有了


目前数据包的筛选和内容是兼容 VScode 的编辑器搜索这种操作的，如果师傅熟悉 Vscode 会更熟悉一点，这块儿我们在研究一下看怎么再做好一点


无限滚动的方案确实更好一点，先记下，感觉这块儿可能会在接下来的一些版本慢慢做调整


其实有一部分原因是不够紧凑，这块儿也会慢慢调整


感谢师傅的建议



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Vulner-6 ***@***.***&gt;
发送时间: 2022年4月24日 22:33
收件人: yaklang/yakit ***@***.***&gt;
抄送: v1ll4n ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [yaklang/yakit] 关于http history 的一些建议 (Issue #226)





 
对了，我还希望 http history 的展示方式，像 burpsuite 一样，直接是滚动条下拉。假设对某个服务器的请求数据包数量刚好一页不够展示（比如一个点击功能，背后却包含着几十次数据交互，又或者有的网站每隔0.5秒就自动交互一次），那么分页展示就会十分影响使用者对数据包的筛选与理解。
 这方面burpsuite的高亮与滚动条下拉的方式，再配合筛选数据包的功能，就可以避免这样的问题。（我认为目前数据包筛选功能远没有burpsuite强大易用）
 另外，如果yakit的操作习惯十分接近burpsuite，那也能很好的进行用户“引流”，毕竟减少了新工具的学习成本，而且还拥有burpsuite没有的“特色”。
 总结：
 高亮+滚动展示+数据包筛选
