### ISSUE TITLE
[BUG]上传大文本字典,yakit白屏

### ISSUE THREAD

**Issue by XiaoSong2017** [yaklang/yakit#229]
很感谢这款工具!!!然而目前在使用最新版的工具时,遇到如下问题:
![image](https://user-images.githubusercontent.com/35443773/165200988-657ade62-df14-4932-ae03-21e24033e7b3.png)
在该界面拖拽上传字典后,工具一直白屏,无法使用:
![image](https://user-images.githubusercontent.com/35443773/165201190-4e3270cb-529e-4871-abcb-7465283ca6fc.png)
期待能在未来修复这个问题

**Comment by XiaoSong2017** [comment]
使用文件路径也会长时间卡在这个界面:
![image](https://user-images.githubusercontent.com/35443773/165243886-23ad6c44-3d43-4e16-99af-c09075b14d0b.png)

**Comment by VillanCh** [comment]
这个确实是因为写入数据库建索引需要一点时间，在大字典的情况下确实会有一点点小问题

**Comment by VillanCh** [comment]
瓶颈并不在读文件的速度，而在于字典的存储需要构建索引，并往数据库写入，这个过程并不是多线程的，数据库自带锁会让过程没那么快

**Comment by XiaoSong2017** [comment]
这样啊....那可不可以使前台的预览和写入数据库采用异步的方式呢?

**Comment by WAY29** [comment]
已完全重构字典实现，可以再进行测试，大字典写入速度快很多
