### ISSUE TITLE
【优化】导航栏配置、nuclei漏报、history加快捷键、MITM劫持、标签调整

### ISSUE THREAD

**Issue by Vernon818** [yaklang/yakit#233]
![image](https://user-images.githubusercontent.com/94944398/165470994-10bd8852-a92e-4c39-ba5e-0849b0d9cf05.png)
![image](https://user-images.githubusercontent.com/94944398/165471099-b95e1d73-2e77-492f-b2cf-f2e513b76166.png)
![image](https://user-images.githubusercontent.com/94944398/165471585-21061949-e0cc-4f7f-8b5c-fc759b6379f5.png)
![image](https://user-images.githubusercontent.com/94944398/165471636-40a5ff26-5f2e-429b-bdc7-88052ed60bf6.png)
![image](https://user-images.githubusercontent.com/94944398/165471674-c8508198-c5f3-4fc2-98a0-005e5096debb.png)

**Comment by linksucre** [comment]
nuclei是一个折中的方案  nuclei检测不准确的脚本 会用yak脚本进行替换。 yakit是支持快捷键的 不过目前在其他平台上不是很理想
