### ISSUE TITLE
【需求】收集js中敏感信息

### ISSUE THREAD

**Issue by Vernon818** [yaklang/yakit#235]
2. 收集 js 中的敏感信息啥的。类似之前 米斯特 key 做的那个。

**Comment by linksucre** [comment]
方便提供一下正则吗

**Comment by linksucre** [comment]
参考 正则 https://github.com/ScriptKid-Beta/Unexpected_information/blob/master/src/main/java/burp/Re.java

**Comment by VillanCh** [comment]
#241 重复问题
