### ISSUE TITLE
【需求】spacengine fofa增加host字段

### ISSUE THREAD

**Issue by apsry** [yaklang/yakit#239]
只返回了ip和端口，不太方便用于批量，可能需要判断http和https

**Comment by Alex-null** [comment]
缺少host字段同样造成无法通过fofa查询子域名

**Comment by VillanCh** [comment]
v1.0.14-sp23 中增加了相关字段
扩充了其他指纹和组件信息，hunter 的 API 被 yaklang.io 支持

师傅可以更新看一下～

**Comment by apsry** [comment]
> v1.0.14-sp23 中增加了相关字段 扩充了其他指纹和组件信息，hunter 的 API 被 yaklang.io 支持
> 
> 师傅可以更新看一下～

大师傅，我试了下增加的字段，可能我开始没有说明白，就是其实fofa的api是可以返回这样的host，如果是带https的话会带https
![image](https://user-images.githubusercontent.com/55017061/166110640-b278a3d7-ef80-44c6-95a3-8202f5667be3.png)

这样我做批量的时候就可以直接判断https再去分别发起请求，因为那个Addr字段其实是没有https的
但是您这边更新后的host就是一个单独的host，不带端口和协议
![image](https://user-images.githubusercontent.com/55017061/166110726-c811dca2-a525-48f8-9e98-4846d2da415f.png)
请问有没有其它的字段能实现我所说的这个功能呢，毕竟如果每个都去用str.IsTLSServer判断太浪费时间了，或者说有没有其它的方法我不了解的能实现我的需求呢？

**Comment by Alex-null** [comment]
> > v1.0.14-sp23 中增加了相关字段 扩充了其他指纹和组件信息，hunter 的 API 被 yaklang.io 支持
> > 师傅可以更新看一下～
> 
> 大师傅，我试了下增加的字段，可能我开始没有说明白，就是其实fofa的api是可以返回这样的host，如果是带https的话会带https ![image](https://user-images.githubusercontent.com/55017061/166110640-b278a3d7-ef80-44c6-95a3-8202f5667be3.png)
> 
> 这样我做批量的时候就可以直接判断https再去分别发起请求，因为那个Addr字段其实是没有https的 但是您这边更新后的host就是一个单独的host，不带端口和协议 ![image](https://user-images.githubusercontent.com/55017061/166110726-c811dca2-a525-48f8-9e98-4846d2da415f.png) 请问有没有其它的字段能实现我所说的这个功能呢，毕竟如果每个都去用str.IsTLSServer判断太浪费时间了，或者说有没有其它的方法我不了解的能实现我的需求呢？

师傅试下Url字段是否能满足需求

**Comment by apsry** [comment]
> > > v1.0.14-sp23 中增加了相关字段 扩充了其他指纹和组件信息，hunter 的 API 被 yaklang.io 支持
> > > 师傅可以更新看一下～
> > 
> > 
> > 大师傅，我试了下增加的字段，可能我开始没有说明白，就是其实fofa的api是可以返回这样的host，如果是带https的话会带https ![image](https://user-images.githubusercontent.com/55017061/166110640-b278a3d7-ef80-44c6-95a3-8202f5667be3.png)
> > 这样我做批量的时候就可以直接判断https再去分别发起请求，因为那个Addr字段其实是没有https的 但是您这边更新后的host就是一个单独的host，不带端口和协议 ![image](https://user-images.githubusercontent.com/55017061/166110726-c811dca2-a525-48f8-9e98-4846d2da415f.png) 请问有没有其它的字段能实现我所说的这个功能呢，毕竟如果每个都去用str.IsTLSServer判断太浪费时间了，或者说有没有其它的方法我不了解的能实现我的需求呢？
> 
> 师傅试下Url字段是否能满足需求

不太能满足，他只会给出https，不会给出http协议，http协议的返回结果会为空
![image](https://user-images.githubusercontent.com/55017061/166111662-eef8bf18-c7b2-4330-a43d-6fdc2eae09a8.png)

**Comment by VillanCh** [comment]
1. 新增的字段有 Url，用来兼容 fofa host 为 url 的情况
2. ConfirmHttps: 从结果来看确定他是一个 Https 端口（TLS 端口）

这两个字段应该可以帮助师傅完成这个工作

**Comment by VillanCh** [comment]
由一些额外的内容需要说明一下哈：
1. fofa 的 “Host” 并不符合我们对 host 的常见定义，在实际处理中，我们会把 fofa 的数据尽可能的标准化成我们制定好的数据内容
2. 不能直接用 fofa 数据的一大原因是需要和其他平台保持兼容，一个平台的不当定义不应该影响通用数据结构哈
3. 在兼容之后，Addr 包含端口和主机信息，ConfirmHttps 能标注 Https 协议，同时 Url 也能保持兼容一些 “畸形” 数据，这是合理的。如果 Host 既包含 Url 又包含 Addr 又包含 IP 或者域名，这是非常非常不正确的操作
