### ISSUE TITLE
【需求】yakit.EnableTable表格交互优化

### ISSUE THREAD

**Issue by Alex-null** [yaklang/yakit#240]
## 需求背景
在表格使用过程中常常涉及数据的复制，但是目前只能对表格全选复制，不利于数据导出、处理

## 需求描述
1. 希望yakit.EnableTable表格支持按行或者按列复制
![image](https://user-images.githubusercontent.com/41976416/166132575-af721efa-a275-4d37-b55a-b0dc7531a2bc.png)
2. 希望yakit.EnableTable表格支持前端筛选，可以考虑在表头添加，比如筛选出状态码为200的
3. 希望yakit.EnableTable表格支持排序，比如按照ContentLength长度进行排序
4. 希望yakit.EnableTable表格支持导出csv数据

**Comment by Vernon818** [comment]
目前已经支持导出和排序
