### ISSUE TITLE
数据库前两项无内容

### ISSUE THREAD

**Issue by ccongc** [yaklang/yakit#244]
Parse Report[0]'s items failed
插件执行结果无数据

**Comment by VillanCh** [comment]
插件执行结果依赖 yakit_save() 输出

"报告" 依赖于 >= yak-v1.0.14-sp26 端口扫描会输出专属报告，目前 “报告处于测试中/研发中” 的功能，具体扫描数据可以在其他 Tab 中的资产库之类的地方找到～
