### ISSUE TITLE
功能建议：专项漏洞检测流量优化

### ISSUE THREAD

**Issue by cnrstar** [yaklang/yakit#25]
可以对专项漏洞检测的插件，不管是nuclei还是yak原生插件，都可以对其收发包给一个类似MITM中history的流量展示方式。
如此以来，用户可直观看到每一个脚本的收发包，通过观察是否超时、是否reset，以及收发包关键内容，来判断该脚本是否是误报。
同样，用户可通过将这个数据包发送到repeater的方式，低成本改变发包的内容，构造自己想要的exp。

**Comment by VillanCh** [comment]
WIP
