### ISSUE TITLE
爆破模块bug?

### ISSUE THREAD

**Issue by lsadaharu** [yaklang/yakit#251]
使用爆破模块爆破tomcat时，设置更多参数中，无论是设置字典payload还是手动添加字典，爆破只有默认的两次，使用的是最新版
![image](https://user-images.githubusercontent.com/50976099/167354154-5fa8b806-3ce0-49b8-823e-0ade4cc2b001.png)
![image](https://user-images.githubusercontent.com/50976099/167354220-602bcac9-18ed-4f7c-8b82-a26a3a8ab11a.png)
![image](https://user-images.githubusercontent.com/50976099/167354371-b38455c9-56c1-49cb-9cd7-7eea04988018.png)
![image](https://user-images.githubusercontent.com/50976099/167354337-237d66e0-8fdc-4081-9100-41508cb1deaf.png)

**Comment by VillanCh** [comment]
爆破提前停止一半原因是

“这不是一个可以爆破的对象，或者指纹检查说明不是 tomcat”

稍等我看下啥原因，师傅如果着急的话，更新最新的插件在 端口扫描中 也有一个简单的 “tomcat” 爆破插件

**Comment by VillanCh** [comment]
![image](https://user-images.githubusercontent.com/13946521/167356696-8e082ca8-42d1-4fbd-813b-191412523238.png)

刚测试了一下，功能没啥问题。
tomcat8 

师傅可以看一下是否是
1. 目标 URL 不正确
2. 并发设置
3. 是否更新最新的插件库或者引擎

**Comment by lsadaharu** [comment]
![image](https://user-images.githubusercontent.com/50976099/167410120-7487d4e7-b21a-4033-9116-874962a21736.png)
![image](https://user-images.githubusercontent.com/50976099/167410184-08feb1c5-d4d7-4c53-8cec-85c7420124a5.png)
我也是tomcat8，插件库和引擎也是最新了，苦恼，而且抓包后，HTTP History一直刷新，已全部重装过还是存在同样的问题
![image](https://user-images.githubusercontent.com/50976099/167411051-6a2aa6f6-530b-433a-b1a3-efd9c6d08617.png)

**Comment by VillanCh** [comment]
不慌，稍后我们会发一个新的小版本来修复这个问题

**Comment by lsadaharu** [comment]
刷新问题更新版本已解决，但是爆破问题还是感觉有问题，我设置的目标内爆破并发:5，设置的payload为user_top10,pass_top25,爆破数量上应该是250个才对，但是只有7个，爆破并发：1时，爆破数量为2
![image](https://user-images.githubusercontent.com/50976099/167528546-a0297070-25f6-48a3-a163-d72fdf8f2457.png)
![image](https://user-images.githubusercontent.com/50976099/167528554-6fa18f74-72dc-40e3-97b0-1616267599b9.png)
![image](https://user-images.githubusercontent.com/50976099/167528593-817aa4e5-02f7-419a-8e56-5725ab9e5085.png)
![image](https://user-images.githubusercontent.com/50976099/167528625-00bd3abc-98b5-4691-91b4-ba78381e7921.png)
师傅测试下你的是否有这个问题，还是说我这个设置有问题
