### ISSUE TITLE
【需求】扫描端口增加自定义任务名称

### ISSUE THREAD

**Issue by givemefivw** [yaklang/yakit#258]
师傅好，在尝试将Yakit作为渗透测试主要工具过程中，发现有两个使用中的小问题：
1.针对【IP端口指纹扫描】，希望在更多参数中增加自定义此次扫描任务的名称，再将自动入库的扫描结果根据任务名称进行标签分类管理，因为在使用过程中发现，一旦扫描的结果越来越多，仅凭现有的搜索很难有效的进行管理，而如果根据扫描任务的不同来进行管理可能效果效率会提高一些；
2.【目录扫描】功能，希望在结果的StatusCode字段增加自定义筛选，或可提高扫描的效率

**Comment by VillanCh** [comment]
感谢师傅的反馈

目前在端口和指纹扫描中，会自动把结果输出到 “报告（Beta*）” 中，“报告” 功能会保存每一次端口扫描的进度信息，师傅可以尝试看一下。关于扫描报告，之后会增加相应参数或者增加对报告的“修改”功能

目录扫描目前的版本中，在 “高级配置” 中增加了 “排除 StatusCode” 之类的细节选项，师傅可以点选设置一下～

**Comment by VillanCh** [comment]
![image](https://user-images.githubusercontent.com/13946521/168507714-adaa7305-5f25-46e2-a1fa-c46f118ed619.png)

**Comment by givemefivw** [comment]
Get  √
