### ISSUE TITLE
【优化】MITM History 渲染卡顿 / hijackHTTPResponse 

### ISSUE THREAD

**Issue by VillanCh** [yaklang/yakit#263]
![image](https://user-images.githubusercontent.com/13946521/168958002-0354a0f1-5d40-42ce-a879-acef3ac2c4a7.png)

**Comment by VillanCh** [comment]
![image](https://user-images.githubusercontent.com/13946521/168961225-be11140a-736a-456d-873c-e017b682703e.png)

**Comment by VillanCh** [comment]
![image](https://user-images.githubusercontent.com/13946521/168961306-cd01d4de-09bc-447f-8117-1c5b4665660e.png)

**Comment by rizaust** [comment]
+1
