### ISSUE TITLE
ui设计的建议

### ISSUE THREAD

**Issue by k4n5ha0** [yaklang/yakit#27]
![image](https://user-images.githubusercontent.com/22064977/142971032-3dfbc482-6ee9-443b-8303-9ea4bdb0b7a6.png)
1）填写 MITM 代理端口127.0.0.1:8080 这句话显得有点空，一行页面就这么一个提示，浪费了不少空间，并且和下面的可复制的提示逻辑重复
![image](https://user-images.githubusercontent.com/22064977/142971334-d945b185-e776-41f6-9f05-74e5bc5fd9ed.png)

2）以下两个按钮逻辑其实是累赘了，一般来说大家用bp习惯了，都直接在包上面改动后直接发送，所以可以直接把提交劫持后的逻辑覆盖到直接转发上
![image](https://user-images.githubusercontent.com/22064977/142971122-c04237cb-4968-41d1-81cb-2dbf801d8aea.png)
![image](https://user-images.githubusercontent.com/22064977/142971192-5ac65ae9-b2f9-4842-838e-6f1b28395d95.png)

3）可以把下图中的按钮的逻辑修改为：按下后发送当前请求，并且该请求可以看到响应包。减少用户鼠标点击的次数，既满足减少响应包噪音的问题，又能满足在关键请求时可以看到响应包。
![image](https://user-images.githubusercontent.com/22064977/142971510-3c13ae5c-491d-48f4-92ca-258d20e4c5c7.png)
建议这个按钮的位置挪到提交劫持后数据包这个按钮，以免用户在直接发送、直接丢弃、查看响应发送三个按钮上点错了。
![image](https://user-images.githubusercontent.com/22064977/142971810-e46eac74-8e6e-45f0-afc2-14411ca562d8.png)

4)下图中的两处逻辑重复，其实可以保留左上角，直接写8080劫持中，简单明了一点，这样“请设置代理http..”也可以不要了
![image](https://user-images.githubusercontent.com/22064977/142975467-b934864b-20a6-43e6-91cd-c0501467a4e6.png)

5）去掉sudo，在win上没有sudo的概念
![image](https://user-images.githubusercontent.com/22064977/142975816-697eccd4-f41f-4a56-b363-fdb29b9cfe81.png)

6)去掉文本框的加载图像，保持与抓包时一致，增加体验的一致性
![image](https://user-images.githubusercontent.com/22064977/142976326-a50d7f18-27cc-433c-a83d-756e43310671.png)
![image](https://user-images.githubusercontent.com/22064977/142976335-12f3ba3f-ace8-4ab8-83be-e26bf1b4dfe6.png)

7）关闭yakkit时，可以提示一下是否关闭后台的yak进程，单兵模式建议直接关闭。

**Comment by VillanCh** [comment]
roger that，劫持界面近期将会被重新设计 🎉

现有的很多交互逻辑其实并不是特别科学，需要慢慢打磨，感谢大佬建议

**Comment by cnrstar** [comment]
大佬建议提的好~

**Comment by Vernon818** [comment]
@k4n5ha0 为了感谢您对yak和yakit的支持，我们想邮寄一份小礼物给您，麻烦您微信添加一下：Juzi19880818，并备注好您的github账号。如已经添加账号，请微信联系我一下，谢谢
