### ISSUE TITLE
可以把引擎部署在Linux上吗

### ISSUE THREAD

**Issue by wcxxxxx** [yaklang/yakit#28]
没找到Linux的引擎

**Comment by VillanCh** [comment]
https://www.yaklang.io/docs/startup

如果引擎没有自动安装 linux 版本的话，可以参考这里手动安装一下～

**Comment by Vernon818** [comment]
@wcxxxxx 为了感谢您对yak和yakit的支持，我们想邮寄一份小礼物给您，麻烦您微信添加一下：Juzi19880818，并备注好您的github账号。如已经添加账号，请微信联系我一下，谢谢
