### ISSUE TITLE
【功能】代理问题

### ISSUE THREAD

**Issue by Mumuuu** [yaklang/yakit#281]
请问本系统是否支持全局代理？只看到部分功能（如Web FUZZ高级配置中的代理）有代理功能

**Comment by VillanCh** [comment]
如果需要非常纯净的代理系统，师傅可以采用远程模式。

全局代理并不能保证所有请求都过代理，这个问题挺大的。比如说 dns(udp)，或者一些第三方依赖不好设置代理

**Comment by VillanCh** [comment]
会尽力给每一个功能都增加代理的配置入口，统一在 Yakit 配置尽量使用这个代理～
