### ISSUE TITLE
【优化】优化match & replace 适应更多场景

### ISSUE THREAD

**Issue by Vernon818** [yaklang/yakit#287]
![image](https://user-images.githubusercontent.com/94944398/171316954-c3e9aad6-b2a0-4ee3-8a78-b3db254d6552.png)

**Comment by linksucre** [comment]
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/22881777/173402395-44895bfd-b7f8-4a9c-9074-276a313ba8e8.png">
类似这种吗
