### ISSUE TITLE
[需求建议] 支持插件化被动扫描

### ISSUE THREAD

**Issue by XTeam-Wing** [yaklang/yakit#30]
支持设置上一级代理，对流量进行被动扫描，重点是可视化展示扫描的漏洞结果。

**Comment by RedTeamWing** [comment]
FUZZ的话正常情况还是习惯了Burp

**Comment by VillanCh** [comment]
感谢建议

> 支持设置上一级代理，对流量进行被动扫描，重点是可视化展示扫描的漏洞结果。

在启动 MITM 的时候一直可以设置下游代理，只是没有明显的说可以接其他被动扫描工具用于扫描，后续与其他工具的联动将会用各种文章来补充说明。

很多时候希望把更多的 自动化 / 半自动 的功能，放在 MITM 的插件系统

插件系统的接口目前还不够好用，应该再有几个版本，会有更好用的插件接口/输出，和自带的一些比较好用的插件来辅助工作。

关于插件的数据和漏洞入库展示，其实也算是插件系统的一部分。

**Comment by Vernon818** [comment]
@XTeam-Wing 为了感谢您对yak和yakit的支持，我们想邮寄一份小礼物给您，麻烦您微信添加一下：Juzi19880818，并备注好您的github账号。如已经添加账号，请微信联系我一下，谢谢
