### ISSUE TITLE
【需求】Fuzzer 增加数据包导出

### ISSUE THREAD

**Issue by Vernon818** [yaklang/yakit#300]
<img width="192" alt="1655286598691" src="https://user-images.githubusercontent.com/94944398/173798761-11b68d78-34a3-4226-9a2d-0051a98c9b73.png">
![af6d67a50fc59c2c5fcd0d8d1f421f6](https://user-images.githubusercontent.com/94944398/173798772-4bbed2a0-6365-4447-b470-54d0222388e5.png)

**Comment by VillanCh** [comment]
Web Fuzzer 在多数据包的时候，新增的导出功能可以支持多个字段以及整个数据包导出
