### ISSUE TITLE
热加载标签里的参数里有右括号则无法正常进行加载

### ISSUE THREAD

**Issue by zlowly** [yaklang/yakit#307]
例如希望把“select database()”作为param参数，{{yak(handle|select database(),1)}}的写法只会原样输出整个标签，似乎不能得到想要的结果。猜测是有右括号在参数里影响了解析yak的缘故。那有没什么例如转义之类或者其它解决方法？

**Comment by VillanCh** [comment]
感谢师傅反馈

转义目前是会有点小问题，可以暂时可以先直接写死数据在热加载函数中临时用一下

这边的小问题最近会尽力修好～ 解决后会在这个 issue 中反馈～
