### ISSUE TITLE
【优化】环境变量需要补一下文档

### ISSUE THREAD

**Issue by Vernon818** [yaklang/yakit#308]
![81fee917e6d1e502fde1dd40c9314e93_](https://user-images.githubusercontent.com/94944398/174515862-8bdc6770-3c56-4f27-9c12-e71e43fe3b3f.jpg)
![image](https://user-images.githubusercontent.com/94944398/174515888-d73e442a-b87e-4b34-ac65-1550a8788777.png)

**Comment by VillanCh** [comment]
![image](https://user-images.githubusercontent.com/13946521/174740818-8c4861a3-4cc6-4ca0-b48d-965de77519c1.png)
