### ISSUE TITLE
MAC安装后 普通权限和管理员权限运行均报错

### ISSUE THREAD

**Issue by wangyanhui406874** [yaklang/yakit#314]
WeChat042ca72e16abc9313bb15bf0002f518d.png
WechatIMG16.png

**Comment by wangyanhui406874** [comment]
普通权限。 Error invoking remote method 'start-local-yak-grpc-server': Error: spawn /Users/yanhuiwang/yakit-projects/yak-engine/yak EACCES

**Comment by wangyanhui406874** [comment]
管理员 Error invoking remote method 'start-local-yak-grpc-server': Error: Command failed: /Users/yanhuiwang/yakit-projects/yak-engine/yak grpc --port 44905 sudo-prompt-command: line 2: /Users/yanhuiwang/yakit-projects/yak-engine/yak: is a directory

**Comment by VillanCh** [comment]
![image](https://user-images.githubusercontent.com/13946521/175196528-c9ff30e5-9015-447e-bb23-082ea87af7d5.png)

**Comment by VillanCh** [comment]
师傅在核心引擎安装与升级界面操作一下，如果遇到问题，点击 “网络问题无法下载？手动下载” 中会有具体如何手动排查问题和安装的办法
