### ISSUE TITLE
【优化】抓包自动解码

### ISSUE THREAD

**Issue by guozhi1** [yaklang/yakit#348]
![image](https://user-images.githubusercontent.com/84212009/179002165-2d5ece5c-1088-42f6-8f1f-f227f6ec1323.png)
在抓到包的时候可以自动进行解码 增加数据包的可读性

**Comment by VillanCh** [comment]
![image](https://user-images.githubusercontent.com/13946521/179133905-b36d8a53-34c9-4384-bdfc-d7af27348f1e.png)

师傅选中全部数据包右键自动解码可以尝试解码一下内容，师傅可以先凑合用一下，看能不能在原数据包基础上增加一个更方便的 inspector
