### ISSUE TITLE
Feature Request: 增加快捷键

### ISSUE THREAD

**Issue by fade03** [yaklang/yakit#349]
希望可以增加一些类似于 ctrl + R 发送到 WebFuzzer 的快捷键

**Comment by VillanCh** [comment]
感谢师傅反馈

MacOS 测试下目前在 History 下 选中一个 History 记录，上下箭头选择， Ctrl + R 可以自动发送到 Web Fuzzer

应该在 MITM 劫持中也可以做到；

在 Windows 平台上的表现按理说应该是一致的，稍等周一瞅一下看各平台的支持情况

**Comment by WAY29** [comment]
该快捷键已在yakit 1.1.2-sp2添加
