### ISSUE TITLE
web-Fuzz优化建议

### ISSUE THREAD

**Issue by guozhi1** [yaklang/yakit#350]
在手工测试xss的时候需要找到自己定义的字符，来判断是否插入成功 再找特征的时候ctrl+F可以找到但是每次重新发包还需要从新输入特征，能否把查找功能分离出来这可以一直查找这个关键字
![image](https://user-images.githubusercontent.com/84212009/179244803-b257350e-659b-4a68-98b1-adb3c5c91a1d.png)

**Comment by VillanCh** [comment]
感谢师傅反馈，应该是可以

在前端缓存后，编辑器默认高亮一部分关键字应该不是特别复杂的事儿
