### ISSUE TITLE
图形化界面BUG

### ISSUE THREAD

**Issue by guozhi1** [yaklang/yakit#351]
图形化界面BUG

![2bkzb-bjwdi](https://user-images.githubusercontent.com/84212009/179400481-e201aa5a-4da8-4a04-b6ad-9513d8419015.gif)

**Comment by VillanCh** [comment]
明天马上修！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: guozhi1 ***@***.***&gt;
发送时间: 2022年7月17日 21:24
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 图形化界面BUG (Issue #351)

**Comment by VillanCh** [comment]
这个问题已经修复了，师傅更新新版本即可
