### ISSUE TITLE
中间人插件BUG

### ISSUE THREAD

**Issue by guozhi1** [yaklang/yakit#356]
版本：社区专业版：1.0.16-sp1 
位置： MITM插件
版本特性,还是BUG??
![lsanv-oew84](https://user-images.githubusercontent.com/84212009/179744270-a33ff88f-63a4-47ca-be8e-4439b9b69823.gif)

**Comment by VillanCh** [comment]
感谢师傅反馈，看起来应该是一个 BUG，组件数据同步出现了问题

**Comment by Vernon818** [comment]
![image](https://user-images.githubusercontent.com/94944398/180681823-56dd7982-c1ba-4031-a2d5-7e4116bc0b80.png)
