### ISSUE TITLE
【需求】yakit全局代理

### ISSUE THREAD

**Issue by Alex-null** [yaklang/yakit#362]
## 需求场景
场景1：yak的teamserver端需要yakit挂代理才能访问
场景2：yakit的插件等功能对代理有一定依赖，每个功能都设置一遍有些冗余，建议集中一个位置做全局的yak代理和yakit代理
## 需求描述
1. yakit支持全局代理，方便访问境外的teamserver端
2. yakit内的代理统一入口，分为yakit代理和yak代理

**Comment by Asura88** [comment]
已阅
