### ISSUE TITLE
[优化]POST数据包内容匹配

### ISSUE THREAD

**Issue by guozhi1** [yaklang/yakit#367]
版本：
Yak-v1.0.16-sp12
Yakit-v1.0.16-sp1
位置：Http history
我想在大量数据包POST 里找黄标的内容我该怎么做
![image](https://user-images.githubusercontent.com/84212009/179987331-70e03772-b3ad-426a-ad42-00f2466cadb3.png)
![image](https://user-images.githubusercontent.com/84212009/179987506-6a934444-0529-4c53-bcb6-5fbd28ee3383.png)

**Comment by Asura88** [comment]
流量替换匹配规则处设置

<img width="1516" alt="image" src="https://user-images.githubusercontent.com/25000885/180138293-24d371fa-dfcc-482f-92e8-f20ddebd8846.png">

**Comment by Vernon818** [comment]
全局搜索已在以下版本支持，更新即可使用
![image](https://user-images.githubusercontent.com/94944398/180681093-8153822b-39ed-42c6-8bd3-c2ef3ecfaabb.png)
