### ISSUE TITLE
[需求] web-fuzz优化显示回显大小

### ISSUE THREAD

**Issue by guozhi1** [yaklang/yakit#370]
在使用web-fuzz的时候 多次发包确定返回数据包是否产生变化 ，这单纯的靠肉眼无法分辨数据包大小，如果想看大小需要点击数据包的详细麻烦不快捷。
我建议把回显大小  单独列出来放到延时时间旁边
![image](https://user-images.githubusercontent.com/84212009/180735395-d8bf1bf3-01ed-47b1-ac40-09a6176621be.png)

**Comment by Vernon818** [comment]
好的，谢谢师傅的建议，我们后续优化一下

**Comment by WAY29** [comment]
已添加显示字节:
![image](https://user-images.githubusercontent.com/41830147/185874563-a7c4c3d6-f71b-436d-b9da-dc328089c3cd.png)
