### ISSUE TITLE
【BUG】中间人插件显示仍然存在问题

### ISSUE THREAD

**Issue by guozhi1** [yaklang/yakit#375]
版本：
Yakit-v1.0.16-sp3
yak-1.0.16-sp14  
位置: 中间人插件
![ed9yt-20srt](https://user-images.githubusercontent.com/84212009/181148026-c18ff357-f1a1-4d76-9cbd-ce68cb352dab.gif)

**Comment by VillanCh** [comment]
在修了在修了～ 😄

**Comment by Vernon818** [comment]
已修复~
