### ISSUE TITLE
无法配置系统代理

### ISSUE THREAD

**Issue by N0o01** [yaklang/yakit#387]
<img width="847" alt="image" src="https://user-images.githubusercontent.com/56007495/182055965-8e12e405-b9c2-439f-9b0e-5c4a1e0a97e0.png">
点击配置：
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/56007495/182056012-b0d29407-c194-49e0-8de7-720637f5e714.png">

然后重新查看
<img width="839" alt="image" src="https://user-images.githubusercontent.com/56007495/182056039-730b5645-eccd-4384-b15e-5dfb9798fe9d.png">
就显示断开....

**Comment by VillanCh** [comment]
师傅可以查看一下本机的机场的系统代理设置，可能冲突了，Yakit 设置系统代理优先级不高



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: uaqHahqa ***@***.***&gt;
发送时间: 2022年8月1日 09:36
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 无法配置系统代理 (Issue #387)





 

 点击配置： 

 
然后重新查看
 
 就显示断开....

**Comment by N0o01** [comment]
> 师傅可以查看一下本机的机场的系统代理设置，可能突破了，Yakit 系统设置代理优先级不高发自备的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人：uaqHahqa ***@*** .***> 发送时间：2022 年 8 月 1 日 09:36 监护日：yaklang/yakit ***@***.***> 抄送：已订阅***@***.***> 主题： Re: [yaklang/yakit] 配置系统代理 (Issue87 ) 点击配置：然后重新查看就显示破坏[#](https://github.com/yaklang/yakit/issues/387) 3.... — 直接回复此邮件，查看 GitHub，或取消订阅。您收到此消息是因为您订阅了此线程。消息 ID：***@***.***>

Yakit的也尝试过了也是会自动掉，机场关掉我也尝试过了也是点击代理成功后面再点进去还是自动关掉了
