### ISSUE TITLE
win安装后 普通权限和管理员权限运行均无反应

### ISSUE THREAD

**Issue by zglaozhu** [yaklang/yakit#388]
![image](https://user-images.githubusercontent.com/31888299/182072803-1e7930ef-6f53-4c26-94dd-420f7d117d60.png)
![image](https://user-images.githubusercontent.com/31888299/182072877-45c8ef69-95d8-4ddf-92bb-d4067b8c0146.png)
![image](https://user-images.githubusercontent.com/31888299/182072899-4b5ebccd-b9c7-4106-83ee-5275d2d39132.png)
提示进程已经启动 但是没有后续了

**Comment by WAY29** [comment]
师傅可以试一下在cmd或者powershell中手动执行netstat截图下命令执行结果呢？

**Comment by zglaozhu** [comment]
> 师傅可以试一下在cmd或者powershell中手动执行netstat截图下命令执行结果呢？

win 哪里有netstat

**Comment by WAY29** [comment]
> > 师傅可以试一下在cmd或者powershell中手动执行netstat截图下命令执行结果呢？
> 
> win 哪里有netstat

师傅用的是什么版本windows？据我了解win7开始就有netstat了

**Comment by zglaozhu** [comment]
> > > 师傅可以试一下在cmd或者powershell中手动执行netstat截图下命令执行结果呢？
> > 
> > 
> > win 哪里有netstat
> 
> 师傅用的是什么版本windows？据我了解win7开始就有netstat了

win10  你的意思是端口占用吗？8083端口？

**Comment by WAY29** [comment]
> > > > 师傅可以试一下在cmd或者powershell中手动执行netstat截图下命令执行结果呢？
> > > 
> > > 
> > > win 哪里有netstat
> > 
> > 
> > 师傅用的是什么版本windows？据我了解win7开始就有netstat了
> 
> win10 你的意思是端口占用吗？8083端口？

我的意思是 你看看你的windows里能否正常运行netstat命令

**Comment by zglaozhu** [comment]
> > > > > 师傅可以试一下在cmd或者powershell中手动执行netstat截图下命令执行结果呢？
> > > > 
> > > > 
> > > > win 哪里有netstat
> > > 
> > > 
> > > 师傅用的是什么版本windows？据我了解win7开始就有netstat了
> > 
> > 
> > win10 你的意思是端口占用吗？8083端口？
> 
> 我的意思是 你看看你的windows里能否正常运行netstat命令

'netstat' 不是内部或外部命令，也不是可运行的程序
或批处理文件

**Comment by WAY29** [comment]
> > > > > > 师傅可以试一下在cmd或者powershell中手动执行netstat截图下命令执行结果呢？
> > > > > 
> > > > > 
> > > > > win 哪里有netstat
> > > > 
> > > > 
> > > > 师傅用的是什么版本windows？据我了解win7开始就有netstat了
> > > 
> > > 
> > > win10 你的意思是端口占用吗？8083端口？
> > 
> > 
> > 我的意思是 你看看你的windows里能否正常运行netstat命令
> 
> 'netstat' 不是内部或外部命令，也不是可运行的程序 或批处理文件

这个应该就是yakit无法启动的原因，在yakit里会使用到netstat命令查看yak命令对应的端口，由于你的windows上无法执行netstat命令所以yakit启动不了

**Comment by zglaozhu** [comment]
> > > > > > > 师傅可以试一下在cmd或者powershell中手动执行netstat截图下命令执行结果呢？
> > > > > > 
> > > > > > 
> > > > > > win 哪里有netstat
> > > > > 
> > > > > 
> > > > > 师傅用的是什么版本windows？据我了解win7开始就有netstat了
> > > > 
> > > > 
> > > > win10 你的意思是端口占用吗？8083端口？
> > > 
> > > 
> > > 我的意思是 你看看你的windows里能否正常运行netstat命令
> > 
> > 
> > 'netstat' 不是内部或外部命令，也不是可运行的程序 或批处理文件
> 
> 这个应该就是yakit无法启动的原因，在yakit里会使用到netstat命令查看yak命令对应的端口，由于你的windows上无法执行netstat命令所以yakit启动不了

请问有好的解决办法吗?

**Comment by WAY29** [comment]
> 

你可以试试全局搜索一下netstat.exe看看能否找到，如果找到了证明这个文件所在的文件夹不在环境变量PATH中，那就将其所在文件夹假如PATH中。如果找不到则证明没这个命令，可以考虑找方法安装，后续yak版本会解决这个问题，不再使用netstat命令。

**Comment by zglaozhu** [comment]
> > 
> 
> 你可以试试全局搜索一下netstat.exe看看能否找到，如果找到了证明这个文件所在的文件夹不在环境变量PATH中，那就将其所在文件夹假如PATH中。如果找不到则证明没这个命令，可以考虑找方法安装，后续yak版本会解决这个问题，不再使用netstat命令。

好的 谢谢 我试试

**Comment by zglaozhu** [comment]
> > > 
> > 
> > 
> > 你可以试试全局搜索一下netstat.exe看看能否找到，如果找到了证明这个文件所在的文件夹不在环境变量PATH中，那就将其所在文件夹假如PATH中。如果找不到则证明没这个命令，可以考虑找方法安装，后续yak版本会解决这个问题，不再使用netstat命令。
> 
> 好的 谢谢 我试试

启动成功
