### ISSUE TITLE
【需求】添加 render 功能 添加改变请求方式选项

### ISSUE THREAD

**Issue by PoriaMs** [yaklang/yakit#389]
希望
1.  添加一个类似 burpsuits 的 render 功能
2.  在劫持页面添加改变请求方式的选项

**Comment by VillanCh** [comment]
感谢师傅反馈和建议

大概之后会在某个版本出现在 Yakit 中，这两个功能有在计划做了～ 

Render 因为一些安全问题在评估，想要找到一个比较好的方式去做这个事情～
