### ISSUE TITLE
[BUG] 选择插件变为灰色无法选择 

### ISSUE THREAD

**Issue by guozhi1** [yaklang/yakit#390]
![image](https://user-images.githubusercontent.com/84212009/182286771-2b7494ea-3b9a-4fc7-9e65-8322e2a5099b.png)

**Comment by VillanCh** [comment]
![Uploading image.png…]()

师傅勾选这个按钮即可打开开关

**Comment by VillanCh** [comment]
![image](https://user-images.githubusercontent.com/13946521/182330700-bb931c4c-bc89-47f1-b713-2c26266f2580.png)
