### ISSUE TITLE
 [需求]断点抓包

### ISSUE THREAD

**Issue by guozhi1** [yaklang/yakit#393]
在测试的过程中会生成大量数据包  ，如和单项抓住一个数据包。
一个一个放行效率低 这中间网站会有多次通信。 

我的需求：我要测试传输的姓名是否有xss

![image](https://user-images.githubusercontent.com/84212009/182619772-7665b0f7-62ad-4bb5-a16c-6c77672355df.png)

我的数据包样子
![image](https://user-images.githubusercontent.com/84212009/182619945-4f410122-f444-4fa5-b6d6-0535fc7f2722.png)
这是我传输的数据包，回显没有我的姓名
现在我考虑这个包的姓名 是否会 影响 第一个截图的 姓名

环境: 姓名网站 ---> 三方登录 ---> 返回我的姓名 -->  姓名网站
                               
三方登录 ---> 这些包都是我不需要的
返回我的姓名 ---> 这个数据包是我需要的

我是是否可以给我想要 测试的数据包 设置断点  完成xss测试

疑问 webfuzz  可以完成这种测试吗？ ，我在webfuzz 修改数据包 通过 一些方法影响浏览器 显示？

**Comment by VillanCh** [comment]
Web Fuzzer 一般是纯手动测试，如果要和浏览器交互的话，可能并不适合这种场景

师傅在 MITM 代理开启之后，可以通过设置过滤器以及 “染色” 标记的方法来寻找想要测试的点。

如果需要更进阶一些的操作：

需要编写更复杂的 MITM 一边过流量，一边在 MITM 插件中寻找自己感兴趣的信息
