### ISSUE TITLE
【优化】格式化数据包，劫持代理监听主机增加可选的常用值

### ISSUE THREAD

**Issue by Doatcr** [yaklang/yakit#403]
1、格式化数据包
yakit抓到的包：
![image](https://user-images.githubusercontent.com/38397410/183842309-43b114b6-7a07-4e12-8972-2afa9d558b9b.png)
Burp抓到的包：
![image](https://user-images.githubusercontent.com/38397410/183843002-beb58be6-dc6d-4688-b742-7f34412702f6.png)
建议新增格式化数据包（类似于Burp的Pretty）
![image](https://user-images.githubusercontent.com/38397410/183842725-f46353fd-81aa-4a66-80d2-e736c1c3d6c3.png)
2、劫持代理监听主机增加可选的常用值
![image](https://user-images.githubusercontent.com/38397410/183843107-fbacdb1b-6b03-46a5-b01e-79225b41c7d2.png)
建议增加可选项，保存历史输入的地址和常用地址显示在里面，另外远程模式建议此处默认地址为远程服务器网卡地址。
3、建议内置浏览器或增加多种常用浏览器的免配置启动。

**Comment by Vernon818** [comment]
谢谢师傅的建议，我们会在之后的版本慢慢迭代。（第二个可以理解为增加监听主机的历史吗？使用过的可以在这里选择）

**Comment by Doatcr** [comment]
> 谢谢师傅的建议，我们会在之后的版本慢慢迭代。（第二个可以理解为增加监听主机的历史吗？使用过的可以在这里选择）

是的

**Comment by Vernon818** [comment]
师傅目前版本已经支持劫持代理监听主机增加可选的常用值

**Comment by Go0p** [comment]
右键有一个美化数据包，目前只有 json

![image](https://github.com/yaklang/yakit/assets/38928800/caa22a63-a2ae-49ea-96fc-8eb27742c0c1)
