### ISSUE TITLE
【需求】建议增加一个RequestRaw字段

### ISSUE THREAD

**Issue by Kong-li** [yaklang/yakit#408]

**Comment by Vernon818** [comment]
师傅现在详情有的，如果有的漏洞没有的话，估计是插件里面没有写返回数据包
![image](https://user-images.githubusercontent.com/94944398/184325741-1bd38513-9f0f-4d2d-94cb-9713ce8ad237.png)

**Comment by Kong-li** [comment]
懂了，只需要在risk.NewRisk()中传入risk.response risk.request即可，API文档中写的不是很详细，例子中没有使用这两个参数，我以为没有。使用下来。发现只支持传入类型ResponseRaw: []uint8类型的值，传入指针类型不能正常显示。在使用fuzz功能批量测试的结果中没有RequestRaw字段，保存时需要转换一下，有点麻烦。建议下面的结构体中增加一个RequestRaw字段。
![Pasted image 20220813013712](https://user-images.githubusercontent.com/71125134/184423444-588c1dea-9205-41b3-aa71-afaf8bfba5c8.png)

**Comment by Vernon818** [comment]
好的，谢谢师傅建议

**Comment by WAY29** [comment]
您好师傅，RequestRaw这个字段实际上在这个结构体已经有了，由于文档老旧未更新所以未写上去。您可以尝试访问`*_httpResult.RequestRaw`这个字段。
