### ISSUE TITLE
mitm数据格式化

### ISSUE THREAD

**Issue by Vernon818** [yaklang/yakit#41]
![fe93b20ab2d5b60fe2fc2be563e27f4](https://user-images.githubusercontent.com/94944398/144167749-fb9693f4-4f8b-44b4-870a-e90412d6f9d3.png)

**Comment by cnrstar** [comment]
嘿，这个我也是刚需，请求包和返回包给自动化格式化展示，可增加个pretty和raw的小tab，默认pretty格式化后数据，raw是原始包
