### ISSUE TITLE
【需求?BUG?】MITM拦截发向本地的web请求

### ISSUE THREAD

**Issue by l3v3lFORall** [yaklang/yakit#413]
配置代理为http://127.0.0.1:8883时，不能拦截访问http://127.0.0.1:3000的请求
![image](https://user-images.githubusercontent.com/27011243/184520076-69d50c04-1390-4118-9977-bb0faf68ec2a.png)

配置代理为http://0.0.0.0:8883时，免配置浏览器无法拦截所有请求，并且不能正常联网
![屏幕截图 2022-08-14 104036](https://user-images.githubusercontent.com/28909778/184520201-4ca68890-79cf-4568-8079-8ba08b1d1401.png)

**Comment by VillanCh** [comment]
师傅可以临时通过设置 hosts 给 127.0.0.1 设置本地解析可以解析到
