### ISSUE TITLE
jwt.JWTGenerate的params的使用方法？

### ISSUE THREAD

**Issue by l3v3lFORall** [yaklang/yakit#414]
> func jwt.JWTGenerate(alg: string, params: any, secretKey: bytes) return (token: string, err: error)  
```
println(jwt.AllAlgs())
param = {"iss":"admin","sub":"admin","jti":"e6eaf81fa8d3dde7ed987169680e932a"}
key = []byte("aaab")
println(jwt.JWTGenerate("HS256", param, key)) 
```
上面代码的结果是payload部分只有``{}``没有数据
没写过go，有点不太理解param的类型？希望官网手册上增加函数使用的例子就更好了

**Comment by WAY29** [comment]
你好师傅，这个是yak的一个bug，params的作用即是传递payload，是map类型，您的使用方法没有问题。这个bug将会在下个版本修复。

**Comment by WAY29** [comment]
已经在Yaklang 1.0.17-sp4修复
