### ISSUE TITLE
【需求】插件商店优化需求

### ISSUE THREAD

**Issue by Fiary-Tale** [yaklang/yakit#417]
![image](https://user-images.githubusercontent.com/87681228/184663909-9819396b-f194-4462-b8a2-b27d4fa99197.png)
登录上传插件至插件商店，建议用户自定义ID，不使用github的ID，因github的ID可能存在占用随意起的ID。
上传插件后，会在本地出现相同的两个插件，一个为原版本地插件，一个为上传后下载的插件。
建议上传私密插件，后期可改为公开并进行审核插件。
建议增加一个插件批量上传功能。及本地批量导入，而非需官方仓库

**Comment by Vernon818** [comment]
好嘞，慢慢优化了

**Comment by Vernon818** [comment]
除了改ID的内容其他都优化啦，不支持改ID是因为我们自己没有用户体系，为了安全，都是全部用三方返回的数据
