### ISSUE TITLE
【bug】web fuzzer中不能对超时时间应用过滤器模式

### ISSUE THREAD

**Issue by StinkAndShityAura** [yaklang/yakit#422]
web fuzzer中不能对超时时间应用过滤器模式，似乎也不能支持直接获取导致超时的参数，只能导出成功的payload。

**Comment by VillanCh** [comment]
感谢师傅反馈，之后 Web Fuzzer 的过滤会增加新的功能，除了超时之外，还会增加按长度等过滤这类
