### ISSUE TITLE
【Bug】MAC 插上拓展坞后无法启用系统代理

### ISSUE THREAD

**Issue by DMW11525708** [yaklang/yakit#430]
在mac 上插了拓展坞设备后无法启用系统代理，拔了就能用。。。

**Comment by DMW11525708** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/59634772/187872508-6732707f-3dfb-4acf-9f57-a183bc35a158.png">

**Comment by cnrstar** [comment]
这个bug有点神奇

**Comment by DMW11525708** [comment]
在mac 上插了拓展坞设备然后开启vpn代理，再开yakit ，yakit默认挂的系统代理是vpn的代理，修改不了。

**Comment by VillanCh** [comment]
可以在全局网络配置中修改引擎的代理



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: DMW11525708 ***@***.***&gt;
发送时间: 2024年1月25日 09:12
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 【Bug】MAC 插上拓展坞后无法启用系统代理 (Issue #430)





 
在mac 上插了拓展坞设备然后开启vpn代理，再开yakit ，yakit默认挂的系统代理是vpn的代理，修改不了。
