### ISSUE TITLE
【需求】可以设置都进行重定向，方便爆破时使用

### ISSUE THREAD

**Issue by Vernon818** [yaklang/yakit#434]
<img width="437" alt="1662434718063" src="https://user-images.githubusercontent.com/94944398/188540635-d30a1f17-5d30-4d92-8eed-22bba393a210.png">
<img width="552" alt="6512ff3d56161a9259a658411e46b731_" src="https://user-images.githubusercontent.com/94944398/188540653-b13e7caa-99d8-4053-a163-166ff94a9ac4.png">

**Comment by xyk7755** [comment]
这么久了还没解决，这是最基础的功能吧。。。burp重定向就正常

**Comment by VillanCh** [comment]
Web Fuzzer高级配置是有重定向配置的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xyk7755 ***@***.***&gt;
发送时间: 2023年7月12日 05:54
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 【需求】可以设置都进行重定向，方便爆破时使用 (Issue #434)





 
这么久了还没解决，这是最基础的功能吧。。。burp重定向就正常

**Comment by Vernon818** [comment]
![image](https://github.com/yaklang/yakit/assets/94944398/8ff079a3-0b9f-4149-94e1-431a5f4e8576)
webfuzzer里进行配置就行了，只是以前的issue忘记关了
