### ISSUE TITLE
【Bug】启动 yak grpc 进程 ,闪一下就没了

### ISSUE THREAD

**Issue by ydecl** [yaklang/yakit#442]
启动 yak grpc 进程 ,闪一下就没了
![image](https://user-images.githubusercontent.com/53930390/189782396-e946204e-adac-4ddc-be8e-7673966032f3.png)
![image](https://user-images.githubusercontent.com/53930390/189782410-72ad38ab-e84e-4750-8665-cb3a65ea1539.png)

普通和管理员都试过

**Comment by weiofcn** [comment]
`+1`

**Comment by xiaoming-sir** [comment]
同样问题,刚才修复了,可以更新一下引擎看看

**Comment by VillanCh** [comment]
![image](https://user-images.githubusercontent.com/13946521/189801374-43ff5262-5d0d-4836-b341-aaf65ceea779.png)

已经修复，师傅只更新引擎到 v1.1.2-sp4 即可解决
