### ISSUE TITLE
【需求】增强对HTTP History的可操作性

### ISSUE THREAD

**Issue by Luoooio** [yaklang/yakit#448]
1.希望对HTTP History增加去重功能，很多网站实际上在重复很多的请求包，在翻的时候很影响观感。
2.希望增强HTTP History的自定义操作（增加操作它的接口），毕竟很多时候想对一个站点所有的数据包进行分析，比如我想从数据包中筛选出POST请求，并且存在参数的请求，更快速方便分析，或者提取所有的api端点等等许多操作，如果每种思路都去实现一个mitm插件就很麻烦了。

**Comment by Vernon818** [comment]
好的，我们后面优化一下，感谢师傅反馈
