### ISSUE TITLE
【需求】增加FuzzPathRaw

### ISSUE THREAD

**Issue by Luoooio** [yaklang/yakit#452]
1.建议增加FuzzPathRaw，在mitm插件中还得自己提取path再拼接到payload不是很方便。

**Comment by WAY29** [comment]
师傅有使用过FuzzPath方法吗？这个方法不能够满足你的需求吗？可以提一个FuzzPathRaw的具体使用场景吗？

**Comment by Luoooio** [comment]
> 师傅有使用过FuzzPath方法吗？这个方法不能够满足你的需求吗？可以提一个FuzzPathRaw的具体使用场景吗？

比如mitm插件，使用mirrorNewWebsitePath，从req建立fuzz，path 是/ABC 。
我实际想fuzz的是/ABC/{{int(1-10)}}, 但如果直接FuzzPath("{{int(1-10)}}")，那么实际上是/{{int(1-10)}}，我的解决方法是先从URL中提取/ABC, 再拼接成/ABC/{{int(1-10)}}，多了两三步。后来很奇怪为什么没有FuzzPathRaw，我想要的是拼接而不是替换。

在实战中遇到的这类不同的路由是不同系统的情况还是很多的，所以拼接path感觉还是有必要的。

**Comment by WAY29** [comment]
确实是缺少了一个这样的接口: FuzzPathAppend，后续会增加这个接口，师傅关注这个issue即可。

**Comment by WAY29** [comment]
FuzzPathAppend方法已经在yak v1.1.3-sp1增加，师傅可以尝试该方法是否满足要求

**Comment by Luoooio** [comment]
> FuzzPathAppend方法已经在yak v1.1.3-sp1增加，师傅可以尝试该方法是否满足要求

很棒！

**Comment by WAY29** [comment]
> > FuzzPathAppend方法已经在yak v1.1.3-sp1增加，师傅可以尝试该方法是否满足要求
> 
> 很棒！

师傅如果觉得解决了问题的话,可以close issue
