### ISSUE TITLE
【bug】基础安全工具菜单疑似乱序

### ISSUE THREAD

**Issue by eleveni386** [yaklang/yakit#458]
<img width="499" alt="image" src="https://user-images.githubusercontent.com/4001669/191654787-c72d953e-90b0-4f6d-83e8-b3443d4281cf.png">
第一个菜单，菜单名称空白， 点击右侧显示内容“子域名收集”
<img width="981" alt="image" src="https://user-images.githubusercontent.com/4001669/191654864-abf913b6-458f-4cec-bb2b-46d0cb5b5352.png">
倒数第三个菜单，菜单名显示BatchHack， 点击右侧显示内容“ Hunter空间引擎”
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/4001669/191654977-7d8193fd-5b80-450a-9f2b-49b2856252de.png">
最后两个菜单，为灰色， 不可点击状态， 缺显示菜单名，空间引擎和子域名发现。 不知是否是存在问题。

**Comment by Vernon818** [comment]
师傅可以更新一下yakit的版本了，这个是因为yakit的版本太旧了，有点不适配了
