### ISSUE TITLE
【问题】webfuzzer 怎么查看请求记录

### ISSUE THREAD

**Issue by cahris** [yaklang/yakit#471]
新版的yakit windows版本怎么查看webfuzz请求记录

【这是新版本的】
![image](https://user-images.githubusercontent.com/84823804/193069211-23796da9-0de3-483e-93e8-f09a147d6162.png)

【这是旧的官网演示的】
![image](https://user-images.githubusercontent.com/84823804/193069247-50d52b4e-f593-4b98-9008-80d4b0524ed1.png)

**Comment by WAY29** [comment]
师傅说的是webfuzzer历史吗?在发送数据包那行就有

**Comment by cahris** [comment]
抱歉，由于我刚开始不太会用，给大家造成误解了。问题已解决，这里感谢各位师傅能在百忙之中为我解答，共同努力希望yakit越来越好。
![image](https://user-images.githubusercontent.com/84823804/197192017-0f367cf7-3fd1-4e88-875b-a2166d5052fc.png)
