### ISSUE TITLE
【优化】webfuzzer发包数量多导致前端页面卡死

### ISSUE THREAD

**Issue by Vernon818** [yaklang/yakit#479]
目前数据存在前端，导致数据过多的时候会卡
<img width="1176" alt="19dfe33147b9dde2364418c38fd9987" src="https://user-images.githubusercontent.com/94944398/194816653-ab70a916-715d-4f23-95b4-ef6393924c45.png">

**Comment by WAY29** [comment]
yakit最新版尝试解决了这个问题，请升级到最新版yakit进行测试，如有问题再反馈
