### ISSUE TITLE
【需求】append 函数开销太大了，可以优化一下吗

### ISSUE THREAD

**Issue by Luoooio** [yaklang/yakit#480]
写的东西发现运行很慢，看了一下发现是append耗费时间太长的，和 go 的append比起来差距太大了，5000次居然要3s左右
![image](https://user-images.githubusercontent.com/26653157/195112710-9f972bae-314d-44c9-87ca-c1bd8e9f9065.png)
或者说对于需要循环元素添加到切片，有什么更好的解决方法吗？

**Comment by WAY29** [comment]
师傅可以考虑slice = make([]type, num)然后直接slice[x] = y的形式优化一下，append现在确实存在花销大的问题。

**Comment by Luoooio** [comment]
> 

嗯，这样确实快很多。暂时可以这样解决。
