### ISSUE TITLE
【BUG】FUZZ 包的小BUG

### ISSUE THREAD

**Issue by Luoooio** [yaklang/yakit#481]
![image](https://user-images.githubusercontent.com/26653157/195628090-feb9b561-9c93-41e0-abf0-e1a2b8dd12d0.png)

![image](https://user-images.githubusercontent.com/26653157/195628519-11dec550-10e8-45be-b713-8ccc0d6ef108.png)

如图，如果从同一个freq建立fuzz的话，会有污染，需要重新构建新的freq对象。

**Comment by VillanCh** [comment]
感谢师傅反馈！马上修！

**Comment by WAY29** [comment]
新版本已经修复
