### ISSUE TITLE
【BUG】发送请求从https重定向到http时无法自动切换协议

### ISSUE THREAD

**Issue by Luoooio** [yaklang/yakit#482]
在httpool.Pool或者Execfirst等函数中指定httpool.https(isHttps)，但当从https重定向目标为http时会发生错误

`[ERRO] 2022-10-14 17:44:29 +0800 [exec.go:275] met error in redirect...: tls: first record does not look like a TLS handshake`
也就是说它仍然使用的是https协议，这点在需要批量解析重定向页面的时候会出现部分遗漏。

在webfuzz中使用强制https也会出现相同问题，不能自动换成http（这个还好可以手动调）
![image](https://user-images.githubusercontent.com/26653157/195817369-5902c44a-28ac-4b98-b819-f76897408a61.png)

**Comment by WAY29** [comment]
此bug应该已经在最新版yak和yakiit中修复，师傅再可以测试一下。
