### ISSUE TITLE
官网文档链接挂了

### ISSUE THREAD

**Issue by sanqiushu-ns** [yaklang/yakit#483]
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/37255994/195821950-96857a56-7799-4834-8c37-cab226be824e.png">

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/37255994/195821896-a44b9d0a-9982-46d2-92a9-db129cde1d21.png">

有没有大神先教教😭

**Comment by linksucre** [comment]
.... 貌似链接整错了 可以执行  yak doc -l codec 看看

**Comment by Vernon818** [comment]
我这边打开链接是：https://www.yaklang.io/docs/buildinlibs/lib_codec

**Comment by linksucre** [comment]
我这边看的链接 是正常的啊

**Comment by linksucre** [comment]
你访问 https://www.yaklang.com/docs/newforyak/fuzztag
