### ISSUE TITLE
【BUG】dns.dnsServers 配置不起作用

### ISSUE THREAD

**Issue by Luoooio** [yaklang/yakit#484]
`dnservers = ["8.8.4.4",
               "8.8.8.8",
               "114.114.114.114",
               "1.1.1.1",
               "119.29.29.29",
               "223.5.5.5",
               "180.76.76.76",
               "117.50.10.10",
               "208.67.222.222",
               "223.6.6.6",
               "4.2.2.1",
               "168.95.1.1",
               "202.14.67.4",
               "202.14.67.14",
               "168.95.192.1",
               "168.95.1.1",
               "202.86.191.50",
               "202.175.45.2",
               "202.248.20.133",
               "211.129.155.175",
               "101.110.50.105",
               "212.66.129.108",
               "104.152.211.99",
               "9.9.9.9",
               "82.127.173.122",
               "61.19.42.5",
               "210.23.129.34",
               "210.80.58.3",
               "62.122.101.59",
               "80.66.158.118",
               "101.226.4.6",
               "218.30.118.6",
               "123.125.81.6",
               "140.207.198.6",
               "80.80.80.80",
               "61.132.163.68",
               "202.102.213.68",
               "202.98.192.67",
               "202.98.198.167",
               "210.22.70.3",
               "123.123.123.123",
               "210.22.84.3",
               "221.7.1.20",
               "221.7.1.21",
               "202.116.128.1",
               "202.192.18.1", 
               "211.136.112.50", 
               "211.138.30.66"]

    allIP = dns.QueryIPAll("www.baidu.com",dns.dnsServers(dnservers...),dns.timeout(5))`
使用的大量的dnsServers，但结果没有变化。而使用python的结果明显是多出很多的。

**Comment by Vernon818** [comment]
好的，感觉师傅反馈，我们看看

**Comment by Rookie-is** [comment]
已经在1.1.3 sp8中修复
