### ISSUE TITLE
【Bug】提交模糊测试请求失败

### ISSUE THREAD

**Issue by Sgwb01** [yaklang/yakit#485]
在web Fuzz选项卡点击发送数据包，提示提交模糊测试请求失败 empty request is not allowed ，系统是mac m1 

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/93859858/196659451-4600d374-f52e-4661-9df2-512104e35c5c.png">

**Comment by Vernon818** [comment]
好的， 我们看一下
