### ISSUE TITLE
端口监听器双写

### ISSUE THREAD

**Issue by WAY29** [yaklang/yakit#49]
如题如图所示，已经关闭了输入法但是依然如此
![image](https://user-images.githubusercontent.com/41830147/144816054-c6e941bf-6764-45a7-8393-eaf0794bf5ba.png)

**Comment by Vernon818** [comment]
@WAY29 为了感谢您对yak的支持，我们想邮寄一份小礼物给您，麻烦您微信添加一下：Juzi19880818，并备注好您的github账号。如已经添加账号，请微信联系我一下，谢谢

**Comment by VillanCh** [comment]
新的版本中，增加了 “回显开关” 可以控制，这个问题应该可以通过这个操作解决掉～ 

我 Closed 这个 issue 了～

**Comment by HongLuDianXue** [comment]
Reopen备注：在多次环境中试过新增的 “回显开关” 控制，发现并不奏效，关了“回显”会导致无法输入新的命令。
