### ISSUE TITLE
GetCommonParams函数不能递归获取json参数，比如{”a“:{"b":"c"}}获取不到b参数

### ISSUE THREAD

**Issue by idealYan** [yaklang/yakit#500]
GetCommonParams函数不能递归获取json参数，比如{”a“:{"b":"c"}}获取不到b参数，yak语言，懒人必备，希望能优化。yak yyds嘻嘻

**Comment by Luoooio** [comment]
> 好的，感谢反馈，我们看一下

GetPostJsonParams存在相同问题

**Comment by WAY29** [comment]
已经在新版本新增了这个功能
