### ISSUE TITLE
[需求]增加basic 认证 爆破

### ISSUE THREAD

**Issue by VitoYane** [yaklang/yakit#512]
增加basic认证爆破功能, 很常见的

**Comment by WAY29** [comment]
现在的web fuzzer就已经支持了basic认证爆破功能,例如:
```
{{base64({{x(user_top10)}}:{{x(pass_top25)}})}}
```
这样就会使用payload字典中的user_top10和payload字典中的pass_top25一一生成对应的user:pass的base64字符串,即是http basic认证爆破的内容

**Comment by VitoYane** [comment]
> 现在的web fuzzer的fuzz tag就已经支持了basic认证爆破功能,例如:
> 
> ```
> {{base64({{x(user_top10)}}:{{x(pass_top25)}})}}
> ```
> 
> 这样就会使用payload字典中的user_top10和payload字典中的pass_top25一一生成对应的user:pass的base64字符串,即是http basic认证爆破的内容

嗯, 我发现了, 但是好像请求多了之后, UI就卡死了, 大概8k多个请求

**Comment by WAY29** [comment]
> > 现在的web fuzzer的fuzz tag就已经支持了basic认证爆破功能,例如:
> > ```
> > {{base64({{x(user_top10)}}:{{x(pass_top25)}})}}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样就会使用payload字典中的user_top10和payload字典中的pass_top25一一生成对应的user:pass的base64字符串,即是http basic认证爆破的内容
> 
> 嗯, 我发现了, 但是好像请求多了之后, UI就卡死了, 大概8k多个请求

repeat #479
