### ISSUE TITLE
MITM的URL路径匹配无法保存

### ISSUE THREAD

**Issue by one-pyy** [yaklang/yakit#532]
![image](https://user-images.githubusercontent.com/72590023/202891384-d69f3100-2e63-472d-959f-854eab9c2a1b.png)

输入完保存再点开又没了

**Comment by Vernon818** [comment]
点击确认修改以后没有保存上？

**Comment by one-pyy** [comment]
> 点击确认修改以后没有保存上？

确认, 是就我这不行嘛?

**Comment by Vernon818** [comment]
我看了一下是有点问题，让他们修一下哈

**Comment by WAY29** [comment]
已在新版本修复
