### ISSUE TITLE
history爆仓优化

### ISSUE THREAD

**Issue by faitHme000123** [yaklang/yakit#563]
我测试的时候的时候晚上忘记关了，目标站点会定时发出某些请求到服务端。

yakit在拦截的记录超过一定量之后，劫持功能阻塞，代理的网站一直超时打不开，重启无用。
需要清理记录（是否需要再次重启不清楚，我又重启了）劫持功能才能恢复。

**Comment by VillanCh** [comment]
感谢师傅反馈，类似的问题在最近的引擎中修复过一次，师傅可以尝试更新引擎观察一下是否会出现类似问题。

我在尝试复现一下看会不会出现类似的问题
