### ISSUE TITLE
WebSocket 实时预览无法看到明文或16进制数据不能完整恢复问题

### ISSUE THREAD

**Issue by TARI0510** [yaklang/yakit#568]
如下图为发送一个WebSocket数据包
```
["CONNECT\naccept-version:1.1,1.0\nheart-beat:10000,10000\n\n\u0000"]
```

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/39155974/209588968-eb1de0dd-9860-44f4-82cc-f277c0058110.png">

但返回包无法辨别任何东西，通过WireShark抓包对比，发现 \x8c \xf6 等部分数据是对的上的，但有的无法对上。数据帧详情界面更是全是乱码
<img width="796" alt="image" src="https://user-images.githubusercontent.com/39155974/209589012-59a0b53f-0e3f-4725-b529-3f830273df5e.png">

**Comment by TARI0510** [comment]
服务端代码：https://github.com/spring-guides/gs-messaging-stomp-websocket/tree/main/complete

**Comment by WAY29** [comment]
![image](https://user-images.githubusercontent.com/41830147/209624815-f2c2250a-830f-4c0a-995f-9e57a909d707.png)
测试了一下burp的websocket靶场，似乎没有问题

**Comment by WAY29** [comment]
看起来似乎是yakit中暂时为实现 permessage-deflate这个websocket扩展导致的乱码，后续会修复这个问题

**Comment by TARI0510** [comment]
> ![image](https://user-images.githubusercontent.com/41830147/209624815-f2c2250a-830f-4c0a-995f-9e57a909d707.png)
> 
> 测试了一下burp的websocket靶场，似乎没有问题

那奇怪了 不知是不是macos的问题，晚点我试试我win上是不是正常的

**Comment by WAY29** [comment]
已经在最新版yak引擎修复

**Comment by TARI0510** [comment]
<img width="490" alt="image" src="https://user-images.githubusercontent.com/39155974/210037263-dd777b05-8fc5-48e5-a376-6cb8ff2319e4.png">

服务端低版本的可尝试
