### ISSUE TITLE
【细节需求与改进】提供诸如对浏览器打开等操作的更细节描述

### ISSUE THREAD

**Issue by invoke888** [yaklang/yakit#598]
1.web fuzz 输入{{ 唤出自动提示 无论选择哪项 都是补全 {{array(abc|def|123)}}
2.fuzz字典数过大 页面卡顿
3.数据包扫描无法使用log4j2 插件

**Comment by WAY29** [comment]
1. 没有复现出来这个问题，测试正常
2. 新ui已经在路上了
3. 已经在叫相关师傅更新插件了
4. 能否提供相应的复现步骤和截图？

**Comment by WAY29** [comment]
第四个问题,请求肯定没办法在浏览器里打开,只有响应才能在浏览器里打开,所以在web fuzzer的Request使用右键浏览器打开是无效的
