### ISSUE TITLE
*http.Response  Body乱码

### ISSUE THREAD

**Issue by ruanzy506** [yaklang/yakit#6]
*http.Response  Body乱码  怎么解决啊

**Comment by imp0wd3r** [comment]
yak 1.0.10 仍出现上述问题

```shell
$ yak version
Yak Language Build Info:
    Version: v1.0.10-beta6-ef11e135322d916c95fe5827285e0e4538721d93
    GoVersion: go version go1.16.10 linux/amd64
    GitHash: ef11e135322d916c95fe5827285e0e4538721d93
    BuildTime: Mon Nov 22 17:33:11 2021 +0800
```

```go
err = mitm.Start(8082, mitm.callback(func(isHttps, url, req, rsp) {
    if req.Method == "CONNECT" {
        return
    }


    printf("[%5s] url: %v \n", req.Method, url)
    println()

    http.show(rsp)

}), mitm.useDefaultCA(true))
die(err)
```

```shell
http --verify=no --follow --proxy https:http://127.0.0.1:8082 https://www.yaklang.io/
```

![image](https://user-images.githubusercontent.com/17606044/147542845-72599eef-81af-4713-bdf0-14169c58ed6c.png)

**Comment by VillanCh** [comment]
> yak 1.0.10 仍出现上述问题
> 
> ```shell
> $ yak version
> Yak Language Build Info:
>     Version: v1.0.10-beta6-ef11e135322d916c95fe5827285e0e4538721d93
>     GoVersion: go version go1.16.10 linux/amd64
>     GitHash: ef11e135322d916c95fe5827285e0e4538721d93
>     BuildTime: Mon Nov 22 17:33:11 2021 +0800
> ```
> 
> ```go
> err = mitm.Start(8082, mitm.callback(func(isHttps, url, req, rsp) {
>     if req.Method == "CONNECT" {
>         return
>     }
> 
> 
>     printf("[%5s] url: %v \n", req.Method, url)
>     println()
> 
>     http.show(rsp)
> 
> }), mitm.useDefaultCA(true))
> die(err)
> ```
> 
> ```shell
> http --verify=no --follow --proxy https:http://127.0.0.1:8082 https://www.yaklang.io/
> ```
> 
> ![image](https://user-images.githubusercontent.com/17606044/147542845-72599eef-81af-4713-bdf0-14169c58ed6c.png)

这是因为 yakit 的 MITM 做了很多特殊处理，原声的 yak mitm 保留了最原始数据，并没有自动去处理编码问题，如果有自定义脚本需求的话，最合适的是使用 yakit 的 mitm 插件完成

**Comment by Vernon818** [comment]
@imp0wd3r @ruanzy506 为了感谢您对yak和yakit的支持，我们想邮寄一份小礼物给您，麻烦您微信添加一下：Juzi19880818，并备注好您的github账号。如已经添加账号，请微信联系我一下，谢谢
