### ISSUE TITLE
WEB FUZZ的TEXT和HEX不同步

### ISSUE THREAD

**Issue by xizyy** [yaklang/yakit#60]
WEB fuzz在TEXT中添加数据后想在HEX添加不可见字节。发现TEXT添加的数据并不会同步到HEX。

**Comment by VillanCh** [comment]
感谢提醒！


稍等我看一下，下午弄好后我来发个小版本修复一下这个问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xizy ***@***.***&gt;
发送时间: 2021年12月19日 13:17
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] WEB FUZZ的TEXT和HEX不同步 (Issue #60)





 
WEB fuzz在TEXT中添加数据后想在HEX添加不可见字节。发现TEXT添加的数据并不会同步到HEX。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by VillanCh** [comment]
@xizyy 已定位到该问题，在下一个版本中会修复！感谢反馈

**Comment by VillanCh** [comment]
最近的版本中已修复! 🙏

>= v1.0.11-sp4
