### ISSUE TITLE
【需求】“端口/指纹扫描”模块新增“项目名”来分类“端口资产”

### ISSUE THREAD

**Issue by HongLuDianXue** [yaklang/yakit#603]
项目组成员您好：
在我的实际使用场景中，经常会用到“端口/指纹扫描”模块。
Yakit中每次扫描的端口资产结果都会统一汇总到“端口资产管理”模块中，而做多个项目时，这些资产就会变得很混乱，分不清哪些资产是哪个项目的。对此我总是删除全部资产，再重新扫描，以此来排除其他资产的“干扰”。

我建议在扫描端口开始的时候，新增一个编辑框，让用户来输入“项目名”，后续产出的资产都与“项目名”进行关联，这样会更容易检索和管理端口资产。

**Comment by VillanCh** [comment]
感谢师傅的反馈

事实上师傅说的这个问题我们已经有明确的计划和排期，这大概会是一个明确的项目管理，在启动 Yakit 的时候，我们可以选择项目；
在这个项目中的流量，以及扫描的结果，端口指纹等信息都会记录。以方便用户导出或者打包作为工作成果
