### ISSUE TITLE
远程模式,密码问题

### ISSUE THREAD

**Issue by DistantWolf** [yaklang/yakit#606]
您好,新版本中远程模式连接在哪里输入设置的密码. 
![image](https://user-images.githubusercontent.com/122848952/212857809-c0e6c5b0-22b3-4987-b47a-2839892f61e1.png)

**Comment by Vernon818** [comment]
这个之前修复了，最新发版应该就好了

**Comment by Vernon818** [comment]
yakit 1.1.7-sp2已经支持
