### ISSUE TITLE
【需求】webfuzzer页面request子页面查看历史数据包

### ISSUE THREAD

**Issue by lsadaharu** [yaklang/yakit#611]
在webfuzzer页面request子页面查看历史数据包按钮与主页面的历史查看按钮内容重复，希望能改成与burp类似的前一个数据包与后一个数据包的查看方向类按钮
![image](https://user-images.githubusercontent.com/50976099/215313060-f17a9cef-60e3-4e23-949e-7f020045b35e.png)

**Comment by VillanCh** [comment]
感谢师傅反馈，可以加，感觉前后箭头确实要更方便一下，我先记录一下

**Comment by Vernon818** [comment]
yakit 1.1.7-sp2已经支持
