### ISSUE TITLE
【求助】 win11打开yakit后，audiodg.exe会占用大量CPU

### ISSUE THREAD

**Issue by twsec-pro** [yaklang/yakit#613]
win11打开yakit后，Windows 音频设备图形隔离（audiodg.exe）会占用大量CPU，也没声音播放，为啥audiodg.exe会占用大量CPU，用到了声卡？？？？
开启yakit后：
![image](https://user-images.githubusercontent.com/58679784/215318393-6fe2f6cb-0775-47b4-bac5-260122118ebf.png)
关闭yakit后：
![image](https://user-images.githubusercontent.com/58679784/215318484-1e1d8881-d772-4405-bc3e-4c5293b601fb.png)

**Comment by twsec-pro** [comment]
这个工具需要使用声卡？

**Comment by VillanCh** [comment]
不知道啊，这个不是 Yakit 启动的，是独立的进程，Yakit 也不会使用声卡；

目前没有收到有类似的反馈，这个确实不太清楚
