### ISSUE TITLE
【bug】yak.exe进程持续执行arp

### ISSUE THREAD

**Issue by Creatoria** [yaklang/yakit#617]
后端1.1.8 yak-engine，前端1.1.7 yakit

启动yak后端后持续执行arp，导致在运行中不断闪现cmd窗口。
且关闭前端后，后端仍在执行arp。

1.1.6 yakit无此问题出现
![image](https://user-images.githubusercontent.com/31544796/216493093-021a36a4-292f-488a-8cd5-e810b2cfb02d.png)
![image](https://user-images.githubusercontent.com/31544796/216494578-db037a3b-4368-4793-93ab-97ccd559b7f5.png)

**Comment by Go0p** [comment]
感谢您的反馈，目前已复现，排查中

**Comment by Go0p** [comment]
https://github.com/yaklang/yakit/pull/619

**Comment by HoTaru-Yuki** [comment]
Me too Me too，我也是这样的问题

**Comment by Go0p** [comment]
更新 Yakit 到 v1.1.7-sp1 应该可以解决问题，后续有问题可以重新打开此 issue
