### ISSUE TITLE
运行奔溃

### ISSUE THREAD

**Issue by biggermonester** [yaklang/yakit#623]
在windows 2016上面运行，打开就崩溃
![image](https://user-images.githubusercontent.com/52701155/216999001-5f795f90-ff2f-4298-bf89-326200969444.png)

**Comment by VillanCh** [comment]
师傅可以暂时先使用 1.1.7 之前的版本，

1.1.7 新增了桌面 UAC 权限提升的提示，可能会有系统不兼容的问题
