### ISSUE TITLE
[bug反馈+需求]kali无法导入字典+对于密码爆破时编码加密的需求

### ISSUE THREAD

**Issue by HongZhong001** [yaklang/yakit#625]
在payload中导入字典返回
**字典上传失败：group is empty
上传字典组成功**
实际并未导入

另外在进行爆破过程中，希望能添加对于字典编码的处理

**Comment by VillanCh** [comment]
在 Web Fuzzer 中可以使用右键导入文件或者字典进行使用，编码之类的需求通过使用 Fuzztag 来实现

**Comment by HongZhong001** [comment]
使用的是最新版本
![图片](https://user-images.githubusercontent.com/123642565/217183964-a60ecbc7-29e4-4d5d-8938-bd2fa4638e1c.png)

**Comment by HongZhong001** [comment]
> 在 Web Fuzzer 中可以使用右键导入文件或者字典进行使用，编码之类的需求通过使用 Fuzztag 来实现

![图片](https://user-images.githubusercontent.com/123642565/217184519-dddb2e2b-4a23-4576-9e58-075853ca14f3.png)
无法导入，如图所示

**Comment by VillanCh** [comment]
收到，感谢师傅反馈，我们找 kali 系统复现一下
