### ISSUE TITLE
【BUG】网站树视角，异常数据无法清空

### ISSUE THREAD

**Issue by 2bacc** [yaklang/yakit#633]
如题，在 网站树视角 不知道哪里来的 `://`，正常流程操作无法清空，版本 `Yakit v1.1.7-sp1`，虽然不影响使用，但是...

![Yakit](https://user-images.githubusercontent.com/113162527/217983820-20e6f6c5-abaf-418d-9357-33ea527e7450.gif)

**Comment by Vernon818** [comment]
好的，我们看看
