### ISSUE TITLE
「求助」MacOS下 反复提示弹窗“修复Yakit项目数据库权限”

### ISSUE THREAD

**Issue by byesec** [yaklang/yakit#646]
<img width="252" alt="image" src="https://user-images.githubusercontent.com/69515281/219305300-ea34345b-3880-4225-8132-ca6585cbf1f3.png">

**Comment by Go0p** [comment]
师傅数据库有重要数据吗，感觉是迁库有问题，没有的话，建议把库删掉看看，

<img width="1094" alt="998a98c37ca58ba497e4599f2cae23d" src="https://user-images.githubusercontent.com/38928800/219312590-7dd01a70-90ff-4463-9a46-2c02a20f197c.png">

你打开位置，然后删掉

**Comment by byesec** [comment]
> 师傅数据库有重要数据吗，感觉是迁库有问题，没有的话，建议把库删掉看看，
> 
> <img alt="998a98c37ca58ba497e4599f2cae23d" width="1094" src="https://user-images.githubusercontent.com/38928800/219312590-7dd01a70-90ff-4463-9a46-2c02a20f197c.png">
> 
> 你打开位置，然后删掉

删除掉后解决啦 谢谢
