### ISSUE TITLE
「求助」Web Fuzz模块 发送数据包后报错“提交模糊测试请求失败 panic from httpfuzzer: runtime error: invalid memory address or nil pointer dereference”

### ISSUE THREAD

**Issue by byesec** [yaklang/yakit#647]
<img width="1600" alt="image" src="https://user-images.githubusercontent.com/69515281/219316285-e559b8da-8fbf-4b0d-b7f5-47d11df0f835.png">

**Comment by VillanCh** [comment]
师傅麻烦贴一下Console中的内容，引擎和客户端版本呢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ma4 ***@***.***&gt;
发送时间: 2023年7月22日 13:34
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 「求助」Web Fuzz模块 发送数据包后报错“提交模糊测试请求失败 panic from httpfuzzer: runtime error: invalid memory address or nil pointer dereference” (Issue #647)





 
我也是这样，设置 -&gt; 其他操作 -&gt; 管理员模式解决了
