### ISSUE TITLE
无法抓包

### ISSUE THREAD

**Issue by linuxdy** [yaklang/yakit#689]
1、系统信息
mac m1
1、使用版本情况
![image](https://user-images.githubusercontent.com/50064309/226187547-670b2b3b-e907-421f-b5b8-ab8e66e323cf.png)
2、代理配置
![image](https://user-images.githubusercontent.com/50064309/226187594-c4cf3b7c-5a65-4130-88a2-ad77bfa428f9.png)
3、无法抓到数据包
![image](https://user-images.githubusercontent.com/50064309/226187667-97cc80f6-c984-4eda-a0f3-2fdd24cff365.png)

**Comment by WAY29** [comment]
师傅确认一下最新版本是否还存在这个问题？
