### ISSUE TITLE
使用插件被动扫描会受到手动劫持模式开关影响

### ISSUE THREAD

**Issue by SexyBeast233** [yaklang/yakit#69]
开启被动模式加载插件 挂中间人拦截监听 此时插件发包会受到手动劫持模式中自动放行和手动放行功能开关的影响。
每次手动劫持时忘及打开自动放行，再去插件中检测发包会受到拦截

**Comment by Vernon818** [comment]
好的，感谢反馈，我们定位一下问题

**Comment by VillanCh** [comment]
@SexyBeast233 感谢！这个问题已经修复合并到主线，在下一个版本时直接修复

**Comment by SexyBeast233** [comment]
![image](https://user-images.githubusercontent.com/34060869/147182334-be78245a-633a-4b5a-9dfb-551771383816.png)
此版本尝试 ：先选择手动劫持模式，关闭自动放行，开启手动拦截开关，再退出手动拦截模式 。打开被动扫描模式，以log4j2插件扫描为例 所有插件发送的请求包仍会被拦截 ，导致插件卡住退出自动扫描模式再进入手动拦截模式，打开自动放行开关，再进入被动扫描模式，加载插件，插件发包功能恢复正常

**Comment by VillanCh** [comment]
yak-v1.0.11-sp4 无法对前端功能进行更新，你反馈的这个是前端的功能的问题

大约在几分钟以前 Yakit-v1.0.11-sp1 中解决了这个小问题，整体更新 Yakit-v1.0.11-sp1 重新安装引擎即可～

**Comment by Vernon818** [comment]
@SexyBeast233 为了感谢您对yak和yakit的支持，我们想邮寄一份小礼物给您，麻烦您微信添加一下：Juzi19880818，并备注好您的github账号。如已经添加账号，请微信联系我一下，谢谢
