### ISSUE TITLE
risk.HaveReverseRisk函数bug

### ISSUE THREAD

**Issue by mrliminghao** [yaklang/yakit#690]
```
x = risk.NewPublicReverseHTTPUrl()
println(x)
http.Get(x)
token = risk.ExtractTokenFromUrl(x)
println(token)
if risk.HaveReverseRisk(x){
    println("666")
}
if risk.HaveReverseRisk(token){
    println("666")
}
```
<img width="1485" alt="图片" src="https://user-images.githubusercontent.com/18475437/226230641-919394fe-f495-4296-a562-bccdc5608229.png">
实际收到了请求 而且yakit提示了

**Comment by mrliminghao** [comment]
群内已反馈

**Comment by VillanCh** [comment]
v1.1.9-sp4中已修复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: tzrj ***@***.***&gt;
发送时间: 2023年3月20日 11:08
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] risk.HaveReverseRisk函数bug (Issue #690)





 
群内已反馈
