### ISSUE TITLE
【bug】最新版项目管理菜单丢失

### ISSUE THREAD

**Issue by twsec-pro** [yaklang/yakit#691]
最新版项目管理菜单丢失
![image](https://user-images.githubusercontent.com/58679784/226243522-9d233fba-38d3-4a9a-8b6f-538cf304b28d.png)

**Comment by Go0p** [comment]
现在项目管理的位置移到了设置中

![image](https://user-images.githubusercontent.com/38928800/226269214-222cb1c7-f4e3-45d0-8c5a-69d0d6079eb4.png)

如果数据库中没有什么重要的数据，在清除缓存后，图标就会显示正常了

![image](https://user-images.githubusercontent.com/38928800/226269544-1912eee8-2eaf-49fd-8838-5cfa5d3e26be.png)

**Comment by Vernon818** [comment]
师傅在自定义菜单里面删除掉一下就可以了

**Comment by Vernon818** [comment]
![image](https://user-images.githubusercontent.com/94944398/226276262-a69e9e4d-c155-44cd-887b-7c011d182c71.png)
