### ISSUE TITLE
更新后的端口扫描问题

### ISSUE THREAD

**Issue by The3ight** [yaklang/yakit#692]
导入的txt文本 刚开扫就提示结束了，换了两台服务器都是这样，更新之前是正常的，是需要改哪的设置吗
context deadline exceeded

![image](https://user-images.githubusercontent.com/51350609/226261598-b061a6c8-a0e2-4861-bf31-cba69a042a22.png)

**Comment by Go0p** [comment]
感谢师傅反馈，目前正在加紧修复中

**Comment by The3ight** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
