### ISSUE TITLE
m1 mac 安装最新版yakit出错

### ISSUE THREAD

**Issue by hn1e-sec** [yaklang/yakit#693]
开发者你们好，我在官网和github都尝试下载了最新的release版yakit，安装好打开后报错：“Yakit”已损坏，无法打开。 你应该将它移到废纸篓。

**Comment by cnrstar** [comment]
sudo xattr -r -d com.apple.quarantine /Applications/Yakit.app

你还可以多百度百度

**Comment by VillanCh** [comment]
师傅查看官方网站的安装指引即可，这个错误是因为没有订阅注册苹果开发者计划没有出钱签名导致的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hn13 ***@***.***&gt;
发送时间: 2023年3月21日 10:07
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] m1 mac 安装最新版yakit出错 (Issue #693)





 
开发者你们好，我在官网和github都尝试下载了最新的release版yakit，安装好打开后报错：“Yakit”已损坏，无法打开。 你应该将它移到废纸篓。
