### ISSUE TITLE
【bug】最新版无法抓取IP的数据包

### ISSUE THREAD

**Issue by twsec-pro** [yaklang/yakit#695]
过滤选择IP，无法抓包
![image](https://user-images.githubusercontent.com/58679784/226777810-40756613-812d-4929-8751-b1cbc05a02db.png)
![image](https://user-images.githubusercontent.com/58679784/226777872-a75e9696-e57a-4be1-984d-2bbe5b7751bc.png)

**Comment by VillanCh** [comment]
这个包含是白名单，需要包含完整的Host，师傅可以考虑IP后加星号设置通配



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: twsec ***@***.***&gt;
发送时间: 2023年3月22日 09:24
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 【bug】最新版无法抓取IP的数据包 (Issue #695)





 
过滤选择IP，无法抓包

**Comment by twsec-pro** [comment]
IP还是抓不到包
![image](https://user-images.githubusercontent.com/58679784/227127518-6e1848bf-59c7-46f3-9c79-d114d20a9b95.png)

**Comment by twsec-pro** [comment]
可以了
