### ISSUE TITLE
【bug】window11 web-fuzzer显示提交模糊测试请求失败

### ISSUE THREAD

**Issue by 5xxxxx-Y** [yaklang/yakit#700]
![image](https://user-images.githubusercontent.com/88443692/227135413-fc34c9fa-4f56-48c4-b3c9-8dc744d24891.png)

**Comment by TianwenOVO** [comment]
我在win10上也有此错误，求解决方案

**Comment by Vernon818** [comment]
师傅们更新一下最新版引擎看还会不会有问题
