### ISSUE TITLE
【BUG】抓包过滤器失效

### ISSUE THREAD

**Issue by twsec-pro** [yaklang/yakit#702]
设置过滤器
![image](https://user-images.githubusercontent.com/58679784/227151180-37d69b9a-91f1-467b-aff8-cf266019701a.png)
实际抓包
![image](https://user-images.githubusercontent.com/58679784/227151303-97934a39-4258-4650-9d73-bef19d2a6465.png)
还有在清空历史数据包，mitm 不能实时刷新
![image](https://user-images.githubusercontent.com/58679784/227151724-54655202-0a2e-4233-a417-e17b55b96f87.png)
![image](https://user-images.githubusercontent.com/58679784/227151780-8577ff53-7fbb-4270-ac8c-e7f59d5cbd3a.png)

**Comment by Vernon818** [comment]
我们看一下哈

**Comment by Vernon818** [comment]
我刚刚尝试了一下没有复现到呢，请问师傅是哪个版本的

**Comment by WAY29** [comment]
最新版师傅在测试一下呢？我测试过包含Hostname是没问题的

**Comment by HLPHLG** [comment]
我最新测试了一下最新版本，反复测试，只要打开过滤器，配置了包含字段，比如*.baidu.com ，然后我再手动劫持，结果已经看不到包了，而且浏览器直接访问，没有任何劫持的现象。这是环境配置问题吗？
