### ISSUE TITLE
[优化]建议web fuzzer能直接选择本地字典

### ISSUE THREAD

**Issue by Crany-web** [yaklang/yakit#708]
在这方面就不如burp方便了，yakit刚开始使用得上传本地字典再使用而不能直接使用本地的字典这很大程度上造成了很多不方便

**Comment by VillanCh** [comment]
师傅在想要插入标签的地方右键可以直接插入本地文件～



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Crany ***@***.***&gt;
发送时间: 2023年3月26日 01:37
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] [优化]建议web fuzzer能直接选择本地字典 (Issue #708)





 
在这方面就不如burp方便了，yakit刚开始使用得上传本地字典再使用而不能直接使用本地的字典这很大程度上造成了很多不方便

**Comment by Crany-web** [comment]
> 师傅在想插入标签的地方右键可以直接插入本地文件～ 发自己的iPhone
> [……](#)
> ------------------ 原始邮件 ------------------ 发布人: Crany ***@*** .***> 发送时间: 2023年3月26日 01:37 收件人: yaklang/yakit ***@***.***> 抄送: 已订阅 ***@***.***> 主题：re：[yaklang/yakit] [优化]建议web fuzzer能（问题[＃708](https://github.com/yaklang/yakit/issues/708)）在在在不如不如不如字体这么大的程序生成了很多不方便 — 直接回复这封电子邮件，在 GitHub 上查看它，或者取消订阅。您收到此消息是因为您订阅了此线程。消息 ID：***@***.***>
![芦笋-rywi_芦笋视频-20230326.gif](http://img.crany.fun/i/2023/03/26/641f9ad82ccf2.gif)
我的想法是在Payload/字典管理那里能直接调用本地的payload/字典，如果要把字典上传到yakit就会比较麻烦而且上传所用的时间环境不一样时间就不一样

**Comment by Vernon818** [comment]
![image](https://user-images.githubusercontent.com/94944398/230290667-1292800f-d450-4c61-8564-58f422eaa671.png)
这里可以直接右键上传本地文件
