### ISSUE TITLE
【BUG】CVE数据库初始化失败

### ISSUE THREAD

**Issue by 2bacc** [yaklang/yakit#725]
数据库加载失败（Reason）: [add index failed: no such table: main.cves]

数据库加载失败! Failed to load database

开始验证数据库加载：Start to verify database

![image](https://user-images.githubusercontent.com/113162527/229135891-8eae4ec4-2ce1-4239-a149-6e6dcaae6a6a.png)

**Comment by VillanCh** [comment]
加载失败主要在于解压过程可能需要一两分钟，这个时间差目前没有做进度条，如果方便的话师傅可以根据数据库的地址手动下载一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Kee ***@***.***&gt;
发送时间: 2023年3月31日 21:42
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 【BUG】CVE数据库初始化失败 (Issue #725)





 
数据库加载失败（Reason）: [add index failed: no such table: main.cves]
 
数据库加载失败! Failed to load database
 
开始验证数据库加载：Start to verify database
