### ISSUE TITLE
Yso-Javahack JavaPayload CC2链Tcp ReverseShell不能生成payload源码

### ISSUE THREAD

**Issue by yuyongxr** [yaklang/yakit#730]
Yso-Javahack JavaPayload CC2链Tcp ReverseShell生成payload时，不能生成base64和hex的代码，请问一下，这个问题应该如何排查。

**Comment by yuyongxr** [comment]
使用yak格式的代码，在runner中执行提示如下：
[ERRO] 2023-04-03 14:02:40 [GenClass:272] not found flag: HostVal
[ERRO] 2023-04-03 14:02:40 [yaki-code-1229387082] not found flag: HostVal

**Comment by Vernon818** [comment]
师傅说已经修了，本周发版会修复

**Comment by yuyongxr** [comment]
本周没修复呀
