### ISSUE TITLE
MITM启动免配chrome失败

### ISSUE THREAD

**Issue by skyblueflag** [yaklang/yakit#739]
MITM启动免配chrome失败，提示“Chrome 启动失败：Error: Error invoking remote method 'LaunchChromeWithParams': Error: No Chrome installations found.”

**Comment by Go0p** [comment]
尝试启动 Chrome 时遇到了问题。这个错误表明系统未找到任何已安装的 Chrome 实例。请尝试以下方法来解决这个问题：

1. 确保已安装 Google Chrome：
首先，请确认您的计算机上已安装了 Google Chrome 浏览器。如果您还未安装，请访问 https://www.google.com/chrome/ 下载并安装最新版本的 Chrome 浏览器。

2. 检查 Chrome 安装路径：
确保 Chrome 安装在了正确的文件路径下。通常情况下，Windows 操作系统下的默认安装路径是：
C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
对于 macOS，路径是：
/Applications/Google Chrome.app/Contents/MacOS/Google Chrome

3. 重新安装 Chrome：
如果已经安装了 Chrome 但仍然出现此问题，可能是安装出现了错误。建议卸载 Chrome，然后重新从官方网站下载并安装。
