### ISSUE TITLE
[BUG]内容过滤不生效

### ISSUE THREAD

**Issue by Liehu** [yaklang/yakit#743]
![image](https://user-images.githubusercontent.com/4949212/231346765-51f0d383-f14a-4fce-95a9-7362dc3eb292.png)
使用官方默认规则-密码泄漏点测试，无论如何配置规则作用范围，均无法匹配password。如图.yakit版本为最新版

**Comment by Vernon818** [comment]
稍等，让师傅看看

**Comment by Vernon818** [comment]
师傅方便加一下微信，你把这个包发我我让师傅复现一下吗？

**Comment by Liehu** [comment]
> 师傅方便加一下微信，你把这个地址发我我让师傅复现一下吗？ 微信号：Juzi19880818

已加并反馈

**Comment by Vernon818** [comment]
师傅可以更新最新版引擎，昨天已经修复并发版了

**Comment by Liehu** [comment]
> 师傅可以更新最新版引擎，昨天已经修复并发版了

感谢，辛苦了
