### ISSUE TITLE
【优化】劫持响应包发送到Fuzzer自动转化（类似Burp）

### ISSUE THREAD

**Issue by Doatcr** [yaklang/yakit#746]
![图片](https://user-images.githubusercontent.com/38397410/231987551-c3a595a9-1aeb-44cc-bd82-0593c7f911da.png)
劫持到的响应包右键发送到Web Fuzzer时自动转化为对应的请求包。

**Comment by Vernon818** [comment]
好的，我们后面安排优化一下

**Comment by WAY29** [comment]
已经在最新版yakit实现
