### ISSUE TITLE
[BUG] cve数据库无法加载

### ISSUE THREAD

**Issue by zaneSSS** [yaklang/yakit#753]
[UpdateCVEDatabase] error: 数据库加载失败（Reason）: cve database[/Users/yakit-projects/default-cve.db] failed: database disk image is malformed

**Comment by Go0p** [comment]
这个错误通常是由于 SQLite 数据库文件损坏或格式不正确导致的，

可以试试删掉对应路径下 default-cve.db，重新在 yakit 客户端下载试试，再不行的话，可以手动访问链接 https://cve-db.oss-cn-beijing.aliyuncs.com/default-cve.db.gzip下载后，移动到 yakit-projects 目录下

**Comment by Zijian-f** [comment]
yakit-projects这个文件夹在哪里，安装目录里面没有找到

**Comment by Go0p** [comment]
点击小房子，可以看到 yakit-projects 的绝对路径

![image](https://github.com/yaklang/yakit/assets/38928800/a82e2309-3a0a-40b2-abc2-e141a233cd85)

![image](https://github.com/yaklang/yakit/assets/38928800/b36f50fe-07d3-48e2-b2ae-372b9d2c7b94)

**Comment by Zijian-f** [comment]
您好，您的邮件我已经收到，会尽快查看！

**Comment by Zijian-f** [comment]
搞定了，用everything搜了一下
