### ISSUE TITLE
【BUG】使用MITM访问网站会502

### ISSUE THREAD

**Issue by F4nZzz** [yaklang/yakit#788]
## 问题描述

使用MITM访问网站会502
![image](https://github.com/yaklang/yakit/assets/52073911/c8ed88ed-257c-4692-8acd-ffe66f7b59cb)

## 环境信息

- 操作系统: win32
- 系统架构: x64
- Yakit 版本: 1.2.1
- YakLang 版本: v1.2.1-sp1

**Comment by F4nZzz** [comment]
而且这玩意失效，每次勾选了，下次还会出来
![image](https://github.com/yaklang/yakit/assets/52073911/0dc429aa-9d0e-4858-a7df-66909181b0d1)

**Comment by Go0p** [comment]
微信群内貌似已经回复解决了

**Comment by luoxiruoxi** [comment]
> 微信群内貌似已经回复解决了

请问一下您是怎么解决的呢
