### ISSUE TITLE
【需求】右键修改请求body编码

### ISSUE THREAD

**Issue by VVeakee** [yaklang/yakit#799]
## 需求描述

有些参数是a=1&b=2,需要修改为json格式或者xml格式

## 解决方案

参考burp插件Content Type Converter可右键修改请求参数的格式
![image](https://github.com/yaklang/yakit/assets/85714114/1d568e84-b5a9-416a-971f-f122cd2d50fd)

**Comment by Vernon818** [comment]
好的，谢谢师傅反馈

**Comment by WAY29** [comment]
已经在最新版实现了，师傅直接更新yakit和yak的最新版，然后在插件商店下载即可
![image](https://github.com/yaklang/yakit/assets/41830147/706e9699-48f0-4d6e-99c8-3af9dc503fbf)
![image](https://github.com/yaklang/yakit/assets/41830147/2c957932-7945-4cf9-b511-aa2d06047e60)
