### ISSUE TITLE
功能建议：扫描插件(mitm 插件) / 爆破

### ISSUE THREAD

**Issue by lapalipi** [yaklang/yakit#8]
1、扫描模块，其实我自己用burpsuite，除了一些插件以外还很喜欢burpsuite的scanner模块，扫描效果确实还可以，如果大佬们有兴趣可以加一个这方面的模块。
2、爆破模块，主要是MAC上好像没啥好的爆破工具，虽然有很多，但其实觉得那些爆破工具真的都不能解决问题。比不上超级弱口令爆破工具，超级弱口令爆破工具有一个很好的优点就是能够根据协议选择匹配的字典，那很多支持这个就不太友好，yakit如果能有这个功能也会很帮，可以加一个综合性的资产探测啥的模块。做一个真正强大的渗透测试辅助工具。

**Comment by Vernon818** [comment]
@lapalipi 为了感谢您对yak和yakit的支持，我们想邮寄一份小礼物给您，麻烦您微信添加一下：Juzi19880818，并备注好您的github账号。如已经添加账号，请微信联系我一下，谢谢
