### ISSUE TITLE
【BUG】Yakit-1.2.1-sp2-windows-amd64  端口/指纹扫描-插件日志-未见滚动条

### ISSUE THREAD

**Issue by miki-java** [yaklang/yakit#803]
## 问题描述

插件日志框区域太小，没有滚动条，无法查看基础插件日志、漏洞与风险。不确定是不是win11的原因

## 预期行为

调整布局，日志及漏洞应该在该页面滑动可见

## 实际行为

请在此处描述您实际看到的行为，也就是问题解决后出现的结果。如果可能，请提供具体的结果示例。

## 复现步骤

请在此处提供能够复现该问题的具体步骤。如果问题是随机发生的，或者需要特定的环境条件才能复现，请提供更详细的说明。

1. 步骤 1
2. 步骤 2
3. 步骤 3

## 环境信息

- 操作系统: win32
- 系统架构: x64
- Yakit 版本: 1.2.1-sp2
- YakLang 版本: v1.2.1-sp4

## 补充说明

如果您有任何其他有关该问题的信息或评论，请在此处添加。

**Comment by Vernon818** [comment]
![image](https://github.com/yaklang/yakit/assets/94944398/de361347-2e08-4058-a453-9a2396eaefa3)
师傅我也是win11，好像没发现问题
