### ISSUE TITLE
不同的项目 web Fuzz 都是公用的吗？

### ISSUE THREAD

**Issue by 1i4n** [yaklang/yakit#817]
不同的项目 web Fuzz 都是公用的吗？新建项目后web Fuzz都是共用的，项目无法做区分，新建项目概念很模糊

**Comment by Vernon818** [comment]
是缓存是共用的，数据其实是按项目分开的

**Comment by Vernon818** [comment]
是的，流量数据、漏洞、资产这些数据其实都是按项目完全区分开的

**Comment by 1i4n** [comment]
有办法或者考虑做成每个项目是完全独立的环境吗，就像burp一样每个项目都完全独立，新建的项目跟之前的完全不重合，打开历史项目，webfuzz也会保留。

**Comment by VillanCh** [comment]
感谢师傅反馈，最近会调整这一部分的数据存储，现在只是数据缓存跟随用户了，流量还是跟随项目的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 1i4n ***@***.***&gt;
发送时间: 2023年6月6日 16:45
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 不同的项目 web Fuzz 都是公用的吗？ (Issue #817)





 
有办法或者考虑做成每个项目是完全独立的环境吗，就像burp一样每个项目都完全独立，新建的项目跟之前的完全不重合，打开历史项目，webfuzz也会保留。

**Comment by VillanCh** [comment]
web fuzzer 的操作加载目前属于缓存内容，这个其实是可以使用项目数据库的，在之后的版本中会实现这部分的功能～

**Comment by Vernon818** [comment]
最新版已优化
![image](https://github.com/yaklang/yakit/assets/94944398/9eb83b0b-7881-4ee3-abf5-246af0275bd9)
