### ISSUE TITLE
MIMT 本地hosts不生效

### ISSUE THREAD

**Issue by LazyMaple** [yaklang/yakit#819]
版本：v1.2.1-sp3 windows
步骤： 使用MIMT免配置启动，同时本地配置了域名解析
![image](https://github.com/yaklang/yakit/assets/12314941/e25f6915-7480-4274-8a81-5687b4077f0a)
现象：发现似乎没有读取本地hosts文件，yakit里面 hosts没有生效
![image](https://github.com/yaklang/yakit/assets/12314941/492b06f7-09f7-4475-aeb0-5856cebbbc1f)
![image](https://github.com/yaklang/yakit/assets/12314941/fe51c996-dccb-41a3-b925-563368ef5a52)

**Comment by VillanCh** [comment]
感谢师傅反馈，如果可能的话最近一两个版本会解决～







------------------ 原始邮件 ------------------
发件人: map1e ***@***.***&gt;
发送时间: 2023年6月7日 23:38
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] MIMT 本地hosts不生效 (Issue #819)





 
版本：v1.2.1-sp3 windows
 步骤： 使用MIMT免配置启动，同时本地配置了域名解析
 
 现象：发现似乎没有读取本地hosts文件，yakit里面 hosts没有生效

**Comment by Vernon818** [comment]
师傅更新一下最新版，已经修复了~

**Comment by LazyMaple** [comment]
nice~ 谢谢
