### ISSUE TITLE
BUG:启动 MITM 服务器 ERROR!

### ISSUE THREAD

**Issue by Ryze-T** [yaklang/yakit#822]
![image](https://github.com/yaklang/yakit/assets/76553352/5a5311c0-d0bf-41b7-a57b-471c168ed0e7)

**Comment by Vernon818** [comment]
师傅这个报错是你自己配的证书不对来着，看看ca和key那两个文件是不是空的哇，把证书恢复一下应该就好了

**Comment by Ryze-T** [comment]
mac下，免配置启动也需要配证书吗？
而且我在高级设置里下载了证书也安装了，也是一样的报错

**Comment by Vernon818** [comment]
免配置不需要证书，师傅看看我截图框起来的两个文件是不是空的，如果是空的就一起删掉
![image](https://github.com/yaklang/yakit/assets/94944398/f53eebed-5441-432a-93b0-79b65403e120)

**Comment by Ryze-T** [comment]
OK,文件不是空的，但是删掉也可以使用了，感谢

**Comment by Ryze-T** [comment]
请问，可不可以在mitm中加一个header呢，所有的包，包括插件探测的包都加上自定义的header

**Comment by Vernon818** [comment]
师傅可以用这个规则去加
![image](https://github.com/yaklang/yakit/assets/94944398/642e2720-de3d-4009-a757-359492da3772)

**Comment by Vernon818** [comment]
师傅可以加我个微信：Juzi19880818，可以进群方便交流~

**Comment by Ryze-T** [comment]
加了，师傅通过一下
