### ISSUE TITLE
【扫描】目录扫描时自定义字典爆破失败

### ISSUE THREAD

**Issue by threeworld** [yaklang/yakit#824]
![image](https://github.com/yaklang/yakit/assets/25133404/e038a61f-3053-4303-9435-4365922e6fcb)
应该为`/users.php`的形式

字典模板：
![image](https://github.com/yaklang/yakit/assets/25133404/3af8b307-7eea-4f59-935b-25520c5fa181)

**Comment by threeworld** [comment]
![image](https://github.com/yaklang/yakit/assets/25133404/978dd516-072a-4e6b-9fb0-51bd7e271c5f)
好像有做处理，但没生效？

**Comment by VillanCh** [comment]
师傅点击额外参数配置中有一个 “前缀” 

![image](https://github.com/yaklang/yakit/assets/13946521/e4663c87-4166-4d56-8b26-37a98a3ce941)

这个可以设置为 /

**Comment by threeworld** [comment]
谢谢~

**Comment by threeworld** [comment]
> 师傅点击额外参数配置中有一个 “前缀”
> 
> ![image](https://user-images.githubusercontent.com/13946521/244575043-e4663c87-4166-4d56-8b26-37a98a3ce941.png)
> 
> 这个可以设置为 /

谢谢师傅~
