### ISSUE TITLE
cve库初始化一直失败，yakit版本 v1.2.1-sp4

### ISSUE THREAD

**Issue by GatsbyJRT** [yaklang/yakit#826]
![图片](https://github.com/yaklang/yakit/assets/25054364/86164cd7-98e6-4ab0-bccf-1aa22a9d6df7)

**Comment by Vernon818** [comment]
哦哦，这个报错师傅试试看重启呢；如果还不行的话可以手动下载然后放在下面的目录下，重启软件即可
![image](https://github.com/yaklang/yakit/assets/94944398/8de8c5cf-4900-462a-af37-ebb59197cd6e)

**Comment by GatsbyJRT** [comment]
谢谢师傅，问题已解决，gzip文件放在目录下，再重启即可。
