### ISSUE TITLE
m1 pro 芯片无法使用 

### ISSUE THREAD

**Issue by fingershuaib** [yaklang/yakit#827]
iOS 13.3.1 ，如图
<img width="722" alt="image" src="https://github.com/yaklang/yakit/assets/30719651/69b4e342-3722-4313-ad8b-2569b97ad0af">

**Comment by VillanCh** [comment]
官网的安装引导中有这个部分的解决办法，查看yaklang.com的安装教程即可～





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: finger ***@***.***&gt;
发送时间: 2023年6月10日 08:47
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] m1 pro 芯片无法使用  (Issue #827)





 
iOS 13.3.1 ，如图
