### ISSUE TITLE
Web Fuzz 的HEX UI很奇怪

### ISSUE THREAD

**Issue by xizyy** [yaklang/yakit#83]
左边UI放大之前：
![image](https://user-images.githubusercontent.com/44395437/147827164-edb7fd11-fa02-4432-8f42-62ecabd001ba.png)
可以看到HEX的明文部分被遮住了

尝试放大：
![image](https://user-images.githubusercontent.com/44395437/147827215-10bbab7e-4141-4ce2-baea-39bf3898e638.png)
可以看到并没卵用。中间出现了大段空白。

无法对照HEX和TEXT

**Comment by VillanCh** [comment]
感谢提醒，我们来看一下怎么回事儿，初步估计字体的问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xizy ***@***.***&gt;
发送时间: 2021年12月31日 22:06
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] Web Fuzz 的HEX UI很奇怪 (Issue #83)





 
左边UI放大之前：
 
 可以看到HEX的明文部分被遮住了
 
尝试放大：
 
 可以看到并没卵用。中间出现了大段空白。
 
无法对照HEX和TEXT
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Vernon818** [comment]
@xizyy 为了感谢您对yak的支持，我们想邮寄一份小礼物给您，麻烦您微信添加一下：Juzi19880818，并备注好您的github账号，谢谢

**Comment by Vernon818** [comment]
这个问题已经在新版本中修复，大佬可以更新看看~
