### ISSUE TITLE
爆破两次后停止

### ISSUE THREAD

**Issue by yks176175** [yaklang/yakit#832]
如题，不知道是我不会用😂还是有bug
版本：
<img width="284" alt="Snipaste_2023-06-12_16-37-37" src="https://github.com/yaklang/yakit/assets/67717024/7b011fff-a23f-4d93-941f-25df45d45412">
系统：macos 13.4

<img width="1072" alt="Snipaste_2023-06-12_16-35-10" src="https://github.com/yaklang/yakit/assets/67717024/3484ca9d-baa4-4dea-93d1-ffcc5636224d">

**Comment by VillanCh** [comment]
爆破会自动检测目标是不是合理，如果端口根本不通或者无法完成握手，说明爆破没有意义，就会自动停止



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yks176175 ***@***.***&gt;
发送时间: 2023年6月12日 16:40
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 爆破两次后停止 (Issue #832)





 
如题，不知道是我不会用😂还是有bug
 版本：
 
 系统：macos 13.4

**Comment by yks176175** [comment]
明白了
