### ISSUE TITLE
查询 Projects 失败

### ISSUE THREAD

**Issue by mercury-RH** [yaklang/yakit#836]
查询 Projects 失败：Error: Error invoking remote method 'GetProjects': Error: 12 UNIMPLEMENTED: unknown method GetProjects for service ypb.Yak
创建新项目失败，项目名校验不通过：Error: Error invoking remote method 'IsProjectNameValid': Error: 12 UNIMPLEMENTED: unknown method IsProjectNameValid for service ypb.Yak

**Comment by OrangeWatermelon** [comment]
更新引擎再试下
