### ISSUE TITLE
【BUG】yakit免配置启动Chrome不能安装插件

### ISSUE THREAD

**Issue by xcry2006** [yaklang/yakit#837]
如题，添加什么插件都会显示未启用安装功能，重新加载也不行。

**Comment by Vernon818** [comment]
本周已修复，可通过设置路径启动Chrome来启动，本周发版后就可以使用~

**Comment by xcry2006** [comment]
> 本周已修复，可通过设置路径启动Chrome来启动，本周发版后就可以使用~

在哪里设置？没看到。

**Comment by Vernon818** [comment]
师傅更新最新版yakit和引擎，左上角会检测是否有可用谷歌，没有的话，则可以设置启动路径。这里
![image](https://github.com/yaklang/yakit/assets/94944398/5c2b67cb-fb42-4680-915a-01a22303965d)

**Comment by jeffchaos** [comment]
社区版 Yakit v1.3.2 依然存在这个问题，自动配置chrome后无法添加插件，提示：“未启用安装功能“

**Comment by WAY29** [comment]
免配置浏览器无法安装插件，这是因为扩展功能在免配置中禁用了，因为建议可以使用自己的谷歌浏览器
