### ISSUE TITLE
每隔几秒总会转圈卡死

### ISSUE THREAD

**Issue by testnet0** [yaklang/yakit#846]
mac m1 pro 16G
按理来说这个配置不应该几秒钟就转圈一次，完全不能正常使用

**Comment by Vernon818** [comment]
什么几秒钟转圈一次

**Comment by Vernon818** [comment]
麻烦师傅截图看看呢

**Comment by testnet0** [comment]
看下视频，一直是在输入的，但是每隔几秒钟就会CPU异常的高，而且卡死

https://github.com/yaklang/yakit/assets/18673513/3c9f2d5a-91a4-4702-8fe0-42d7d2c47e92

**Comment by testnet0** [comment]
![image](https://github.com/yaklang/yakit/assets/18673513/c1016971-eba0-498d-a91f-21129e250954)
测试把这个状态刷新间隔调高就可以正常用了，可能和这个有关系

**Comment by Go0p** [comment]
mac 下的 CPU 使用率是系统的，不是 Yakit 单独占用的

**Comment by Vernon818** [comment]
可能是频繁检查状态影响到了，师傅把他刷新时间调高就行
