### ISSUE TITLE
[BUG] Linux 下关闭键失效

### ISSUE THREAD

**Issue by ttimochan** [yaklang/yakit#855]
System: archlinux
Linux Kernel: 6.3.9-zen1-1-zen
Desktop Environment: KDE
Yakit Version: 1.2.2

我的情况和 

- https://github.com/yaklang/yakit/issues/839
- https://github.com/yaklang/yakit/issues/872

一样

感谢提供如此强大的平台，已经贡献到了 [AUR](https://aur.archlinux.org/packages/yakit-appimage)

**Comment by VillanCh** [comment]
感谢师傅反馈，我们稍后会找个 Linux 尝试复现一下这个问题，应该在近期的版本会尝试解决这个问题
猜是 Electron Builder 对某些桌面环境水土不服

**Comment by ttimochan** [comment]
补充截图

![image](https://github.com/yaklang/yakit/assets/91021824/e5e26e3b-18a8-4d4d-afad-28fce984a608)

**Comment by Go0p** [comment]
已修复
