### ISSUE TITLE
【BUG】端口扫描不勾选插件卡住

### ISSUE THREAD

**Issue by twsec-pro** [yaklang/yakit#856]
## 问题描述

端口扫描完成后，没有勾选插件，会一直卡在此页面下
![image](https://github.com/yaklang/yakit/assets/58679784/e7ab2b2f-0fcd-4ef3-9df2-8a8b9e3837a6)

**Comment by VillanCh** [comment]
感谢师傅反馈，但是本地我默认参数不带插件扫描一个C端目前没有复现，他正常结束了
