### ISSUE TITLE
【BUG】linux版本关闭yakit的时候无法关闭，报错No handler registered for 'app-exit'

### ISSUE THREAD

**Issue by littleping1987** [yaklang/yakit#872]
## 问题描述

linux版本关闭yakit的时候无法关闭，报错No handler registered for 'app-exit'
Error occurred in handler for 'app-exit': No handler registered for 'app-exit'

## 预期行为

能正常关闭yakit软件

## 实际行为

请在此处描述您实际看到的行为，也就是问题解决后出现的结果。如果可能，请提供具体的结果示例。

## 复现步骤

请在此处提供能够复现该问题的具体步骤。如果问题是随机发生的，或者需要特定的环境条件才能复现，请提供更详细的说明。

1. 打开yakit
2. 点击右上角的关闭按钮，无法关闭

## 环境信息

- 操作系统: linux
- 系统架构: x64
- Yakit 版本: 1.2.1-sp5
- YakLang 版本: v1.2.1-sp8

## 补充说明

如果您有任何其他有关该问题的信息或评论，请在此处添加。

**Comment by Go0p** [comment]
已修复
