### ISSUE TITLE
【建议】支持yakit 绿色化部署

### ISSUE THREAD

**Issue by yoke88** [yaklang/yakit#881]
建议增加yakit 绿色化部署，可以在配置更新好后，轻松拷贝到其他计算机执行
最好所有数据在同一个顶层目录，当然如果支持配置文件最好。
1. 比如把yak 引擎指向特定目录，把项目数据库放在专门的目录。

**Comment by di-ao** [comment]
附议，我个人也不喜欢把工具放在C盘，比较喜欢用便捷版工具。

**Comment by onewinner** [comment]
附议

**Comment by ViCrack** [comment]
附议，每次更新都要手动到文件夹下点击安装，有点麻烦。。。 
而且不清理的话，`C:\Users\admin\yakit-projects\yak-engine`下的东西越来越多了


我接下来打算用`scoop`来实现绿色化部署

**Comment by fantasy-2046** [comment]
附议

**Comment by WAY29** [comment]
#508
