### ISSUE TITLE
【需求】MITM免配置Chrome希望支持Edge

### ISSUE THREAD

**Issue by yoke88** [yaklang/yakit#882]
## 需求描述

目前MITM免配置仅支持Chrome，其实目前在windows 上MSEdge 使用的是chromium 的内核，和chrome差别不大，基本是内置的，而Chrome的下载更新还要点技巧，建议两则都支持。

## 解决方案

建议同时支持Chrome及微软Edge浏览器，如果实现了我前面提的绿色化版本（Portable version),可以自定义指定chromium内核浏览器的位置。

**Comment by yoke88** [comment]
另外发现MITM 的根证书是静态不变的，作为一个安全工具，私钥应该是掌握自己手上的，否则信任这个根证书后，意味这个根证书签发的证书都被信任了。

市面上的其他代理工具，burp,fiddler 等都是可以自己生成密钥对的，希望yakit 也支持。

**Comment by yoke88** [comment]
看到这里是支持自定义路径了，直接浏览msedge的路径就可以

![image](https://github.com/yaklang/yakit/assets/3146226/884d5bb5-1139-4480-854b-3908c68d8116)

**Comment by Vernon818** [comment]
可以用自己的密钥对哈，只是前端页面没有加入导入的功能，师傅可以直接把以下两个文件替换即可
![image](https://github.com/yaklang/yakit/assets/94944398/ecc3f0f5-5d54-42a6-b172-746f4358d324)
