### ISSUE TITLE
【需求】MITI交互式劫持设置了下游代理后，插件被动扫描无法正常挂上代理扫描，暴露真实IP

### ISSUE THREAD

**Issue by Ashupup** [yaklang/yakit#883]
访问网站倒是可以正常挂上代理，但是插件被动扫描不行，这是为啥

**Comment by Vernon818** [comment]
扫描代理可以在这里配置
![image](https://github.com/yaklang/yakit/assets/94944398/29ccb557-d03a-453c-be2b-d468c2449a0a)

**Comment by Ashupup** [comment]
貌似不太行，我使用插件被动扫描还是暴露真实ip，并且我也设置了
![image](https://github.com/yaklang/yakit/assets/78542852/26d6bdc9-bf19-401c-b751-4c10b4e12649)
![image](https://github.com/yaklang/yakit/assets/78542852/0e6d85b5-ea6f-466e-b914-475a86b4a9da)


这是我不用插件去被动扫描，只是单纯的访问不是我的真实ip
![1688714865092](https://github.com/yaklang/yakit/assets/78542852/bda122ef-dff0-431d-a2fe-d69e1d22ea04)

我用插件被动扫描，就是真实ip了
![image](https://github.com/yaklang/yakit/assets/78542852/6f00586a-048e-43d1-8a75-305b8be7d5ed)
