### ISSUE TITLE
【问题】 

### ISSUE THREAD

**Issue by threeworld** [yaklang/yakit#887]
![image](https://github.com/yaklang/yakit/assets/25133404/476cdf32-9c1a-4ded-b8a2-660769713716)
有时候响应很慢，但是用burpsuite很快，这是什么原因？

**Comment by VillanCh** [comment]
有时候远端服务器没有主动关闭连接，yakit 也并不会主动关闭连接，所以会等待连接自动超时结束后才会退出


可以师傅手动在请求中添加Connection: close或者缩短超时时间



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: twoday ***@***.***&gt;
发送时间: 2023年7月9日 11:38
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 【问题】  (Issue #887)





 

 有时候响应很慢，但是用burpsuite很快，这是什么原因？

**Comment by threeworld** [comment]
> 有时候远端服务器没有主动关闭连接，yakit 也并不会主动关闭连接，所以会等待连接自动超时结束后才会退出 可以师傅手动在请求中添加Connection: close或者缩短超时时间 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: twoday ***@***.***&gt; 发送时间: 2023年7月9日 11:38 收件人: yaklang/yakit ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [yaklang/yakit] 【问题】 (Issue #887) 有时候响应很慢，但是用burpsuite很快，这是什么原因？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

好的谢谢
