### ISSUE TITLE
Web Fuzzer 响应用chrome打开

### ISSUE THREAD

**Issue by Szkkhh** [yaklang/yakit#890]
![image](https://github.com/yaklang/yakit/assets/112854893/14cb0bae-98d5-4f56-915a-a4340285aa97)
用这个打开响应页面后，CSS等消失，并不是最初的页面
![image](https://github.com/yaklang/yakit/assets/112854893/9f3ce096-73d3-401e-b352-613678ed2688)

**Comment by OrangeWatermelon** [comment]
可以提供下网站吗

**Comment by Szkkhh** [comment]
> 可以提供下网站吗

这是自己搭的靶场dvwa

**Comment by OrangeWatermelon** [comment]
哦哦，webfuzzer打开确实可能会有问题。因为这个响应内容是从数据库读取的，webfuzzer执行只会获取目标页面，不会加载css，js文件，所以数据库不存在这些文件。可以试下mitm模式的从chrome打开

**Comment by Szkkhh** [comment]
> 哦哦，webfuzzer打开确实可能会有问题。因为这个响应内容是从数据库读取的，webfuzzer执行只会获取目标页面，不会加载css，js文件，所以数据库不存在这些文件。可以试下mitm模式的从chrome打开
十分感谢，mitm感觉不是特别方便，不能像BP一样，右边可以看到响应

**Comment by OrangeWatermelon** [comment]
burp内置了浏览器，存在安全风险的
