### ISSUE TITLE
启动失败了

### ISSUE THREAD

**Issue by bingpo** [yaklang/yakit#9]
Yakit Server 认证失败：Yak Server 未启动或网络不通，或证书不匹配

**Comment by bingpo** [comment]
一样的提示。。。尝试了好多次了

**Comment by bingpo** [comment]
> 可以自己在命令行中输入 yak grpc 然后选择手动连接到启动 grpc 服务器的端口～

一样的提示：Yakit Server 认证失败：Yak Server 未启动或网络不通，或证书不匹配 、。。。。尝试很多次了

**Comment by VillanCh** [comment]
微信公众号发给我你的微信，我后台加你看下啥情况～

**Comment by WasteMaterial** [comment]
请问现在还需要证书么，从🔰雨苁🔰那里了解到的，不过他那里给的证书链接已经失效了

**Comment by Vernon818** [comment]
> 请问现在还需要证书么，从🔰雨苁🔰那里了解到的，不过他那里给的证书链接已经失效了

请问是说的什么问题呢？方便加微信详细聊一下吗？微信号：Juzi19880818

**Comment by Vernon818** [comment]
@bingpo 为了感谢您对yak和yakit的支持，我们想邮寄一份小礼物给您，麻烦您微信添加一下：Juzi19880818，并备注好您的github账号。如已经添加账号，请微信联系我一下，谢谢

**Comment by jobsgxx** [comment]
我这也是Yakit Server 认证失败：Yak Server 未启动或网络不通，或证书不匹配，这个是怎么回事儿？手动grpc也不行
