### ISSUE TITLE
linux一直安装失败

### ISSUE THREAD

**Issue by websecer** [yaklang/yakit#901]
`root@rpc:~# bash <(curl -sS -L http://oss.yaklang.io/install-latest-yak.sh)
Install for Linux amd64 release
-------------------------------------
Downloading for yak_linux_amd64
--2023-07-15 15:03:55--  https://yaklang.oss-accelerate.aliyuncs.com/yak/latest/yak_linux_amd64
Resolving yaklang.oss-accelerate.aliyuncs.com (yaklang.oss-accelerate.aliyuncs.com)... 8.131.131.34
Connecting to yaklang.oss-accelerate.aliyuncs.com (yaklang.oss-accelerate.aliyuncs.com)|8.131.131.34|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 65209424 (62M) [application/octet-stream]
Saving to: ‘yak_linux_amd64’

yak_linux_amd64            100%[=====================================>]  62.19M  5.31MB/s    in 12s     

2023-07-15 15:04:08 (5.15 MB/s) - ‘yak_linux_amd64’ saved [65209424/65209424]

Chmod +x yak_linux_amd64
Start install yak_linux_amd64 (ADD Yak to ENV PATH)
[WARN] 2023-07-15 15:04:08 [yakit:455] failed to add index on http_flows.source_type: no such table: main.http_flows
[WARN] 2023-07-15 15:04:08 [yakit:463] failed to add index on table: http_flows.tags: no such table: main.http_flows
[INFO] 2023-07-15 15:04:08 [yak:71] initialized cve database warning: cve database failed: empty

(no such table: main.http_flows) 
[2023-07-15 15:04:08]  

(no such table: main.http_flows) 
[2023-07-15 15:04:08]  
[INFO] 2023-07-15 15:04:08 [yak:148] current yak binary: /root/yak_linux_amd64
[INFO] 2023-07-15 15:04:08 [yak:196] installed yak... now you can exec `yak version` to check...
[INFO] 2023-07-15 15:04:08 [yak:71] initialized cve database warning: cve database failed: empty
Yak Language Build Info:
    Version: v1.2.2-sp4-8b9b7db07cabd82704f991a3d5f81db430c371a4
    GoVersion: go version go1.20.3 linux/amd64
    GitHash: 8b9b7db07cabd82704f991a3d5f81db430c371a4
    BuildTime: Thu Jul 13 16:35:21 2023 +0800

Cleaning cache file...
Finished
`

**Comment by websecer** [comment]
`[WARN] 2023-07-15 15:04:08 [yakit:455] failed to add index on http_flows.source_type: no such table: main.http_flows
[WARN] 2023-07-15 15:04:08 [yakit:463] failed to add index on table: http_flows.tags: no such table: main.http_flows`

**Comment by VillanCh** [comment]
yak version执行成功就是安装成功了，数据库初始化可以通过yak grpc命令手动触发



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: websecer ***@***.***&gt;
发送时间: 2023年7月15日 23:09
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] linux一直安装失败 (Issue #901)





 
***@***.***:~# bash <(curl -sS -L http://oss.yaklang.io/install-latest-yak.sh)
 Install for Linux amd64 release
 
Downloading for yak_linux_amd64
 --2023-07-15 15:03:55--  https://yaklang.oss-accelerate.aliyuncs.com/yak/latest/yak_linux_amd64
 Resolving yaklang.oss-accelerate.aliyuncs.com (yaklang.oss-accelerate.aliyuncs.com)... 8.131.131.34
 Connecting to yaklang.oss-accelerate.aliyuncs.com (yaklang.oss-accelerate.aliyuncs.com)|8.131.131.34|:443... connected.
 HTTP request sent, awaiting response... 200 OK
 Length: 65209424 (62M) [application/octet-stream]
 Saving to: ‘yak_linux_amd64’
 
yak_linux_amd64            100%[=====================================&gt;]  62.19M  5.31MB/s    in 12s
 
2023-07-15 15:04:08 (5.15 MB/s) - ‘yak_linux_amd64’ saved [65209424/65209424]
 
Chmod +x yak_linux_amd64
 Start install yak_linux_amd64 (ADD Yak to ENV PATH)
 [WARN] 2023-07-15 15:04:08 [yakit:455] failed to add index on http_flows.source_type: no such table: main.http_flows
 [WARN] 2023-07-15 15:04:08 [yakit:463] failed to add index on table: http_flows.tags: no such table: main.http_flows
 [INFO] 2023-07-15 15:04:08 [yak:71] initialized cve database warning: cve database failed: empty
 
(no such table: main.http_flows)
 [2023-07-15 15:04:08]
 
(no such table: main.http_flows)
 [2023-07-15 15:04:08]
 [INFO] 2023-07-15 15:04:08 [yak:148] current yak binary: /root/yak_linux_amd64
 [INFO] 2023-07-15 15:04:08 [yak:196] installed yak... now you can exec yak version to check...
 [INFO] 2023-07-15 15:04:08 [yak:71] initialized cve database warning: cve database failed: empty
 Yak Language Build Info:
 Version: v1.2.2-sp4-8b9b7db07cabd82704f991a3d5f81db430c371a4
 GoVersion: go version go1.20.3 linux/amd64
 GitHash: 8b9b7db07cabd82704f991a3d5f81db430c371a4
 BuildTime: Thu Jul 13 16:35:21 2023 +0800
 
Cleaning cache file...
 Finished
 `

**Comment by websecer** [comment]
感谢
