### ISSUE TITLE
MiTM中间人代理劫持MITM插件错误获取isHttps字段

### ISSUE THREAD

**Issue by Daangx** [yaklang/yakit#906]
在最新版的yakit中，isHttps获取错误，此处http，isHttps获取为true

<img width="1524" alt="图片" src="https://github.com/yaklang/yakit/assets/126078418/90b9ef1c-e448-4772-956c-5b883d43379d">
<img width="353" alt="图片" src="https://github.com/yaklang/yakit/assets/126078418/bbb7ac51-1c03-4f09-bbc1-6acbb5692c8b">

**Comment by OrangeWatermelon** [comment]
好的，下个版本就修了

**Comment by VillanCh** [comment]
引擎的 1.2.2-sp7 已经修复~
