### ISSUE TITLE
mac版本遭遇bug

### ISSUE THREAD

**Issue by Enoki-web** [yaklang/yakit#908]
## 问题描述

电脑mac,系统amd64

cve数据库初始化过程中,下载成功,初始化失败
![image](https://github.com/yaklang/yakit/assets/45222311/30f074f9-f81e-4cef-b1c1-9ff4ff9cad4f)

报错:
[UpdateCVEDatabase] error: 数据库加载失败（Reason）: cve database[/Users/xxx/yakit-projects/default-cve.db] failed: database disk image is malformed

**Comment by Vernon818** [comment]
师傅你关掉yakit重启呢

**Comment by Enoki-web** [comment]
重启没用，仍然是这个错误



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yakit ***@***.***&gt;
发送时间: 2023年7月19日 14:33
收件人: yaklang/yakit ***@***.***&gt;
抄送: Enoki-web ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[yaklang/yakit] mac版本遭遇bug (Issue #908)

**Comment by Vernon818** [comment]
师傅方便加我微信看看不：Juzi19880818

**Comment by k3rwin** [comment]
如何解决的？

**Comment by Vernon818** [comment]
1、删掉default-cve.db
