### ISSUE TITLE
【求助】WebFuzz 模块每个webfuzz可以独立吗？

### ISSUE THREAD

**Issue by 1i4n** [yaklang/yakit#910]
点击上个数据包，会返回到刚刚发送的其他fuzz数据包，排序的结果是按照全局的发包顺序排列的。
可以每个webfuzz单独排列吗？

**Comment by VillanCh** [comment]
感谢师傅反馈，这个功能有计划在做，每一个 Tab 的过程独立且可以被追踪

**Comment by WAY29** [comment]
已经在新版本实现
