### ISSUE TITLE
【需求】Yakit-功能优化的一些问题与建议

### ISSUE THREAD

**Issue by SimoLin** [yaklang/yakit#914]
## 需求描述

以前一直使用BurpSuite来代理抓包，后来尝试使用Yakit觉得也确实不错；
用了一段时间，觉得还是有些功能还可以更进一步，纯属个人建议，请酌情采纳。

## 解决方案

我希望产品能够实现以下功能：

1、支持调整字体与样式
目前默认只能调整字体大中小，不能选择系统已安装的其他字体、不能选择字号，Windows下用起来字体还是有点刺眼；
建议加入字体选择功能，如果可以使用代码开发的那些字体就会好看很多，同时可以区分0oO1liI这些字符
![image](https://github.com/yaklang/yakit/assets/24656521/ec181a31-80b4-4035-850b-85c6462d874c)

2、支持下游代理sock5账号密码认证
目前版本只能配置sock5代理地址端口，不能进行账号密码认证，建议增加一下

3、支持自定义调整功能快捷键
目前版本有些功能并不是经常用，但会占据系统的快捷键，建议增加自定义及开关的功能；
比如截图和录屏的功能快捷键是Ctrl+Shift+B，浏览器打开关闭收藏夹的功能快捷键也是这个，就被占用了。

4、流量代理功能HTTP History功能体验改进
目前版本HTTP History中的请求与响应包总是必须成对出现，必须等响应了才会完整出现在History列表中；
而不是像BurpSuite一样，有请求时就先出现并可以查看请求，有响应时再出现响应内容；
这个问题可能和工具代理流量的功能设计架构有关，可能不太好解决，其实不是特别影响使用，但如果能实现体验更好。

5、流量代理功能HTTP History功能体验改进
目前版本的流量历史列表中的字段是固定的，不能拖动，也不能调整只显示某些字段；
建议类似BurpSuite改为可以拖动字段前后显示顺序，同时建议增加“响应时间”字段，开发或测试有时需要看服务端响应的时间差；

其他的遇到了再提吧，哈哈哈

**Comment by ViCrack** [comment]
快捷键这个需求我之前也提过，等开发吧

**Comment by WAY29** [comment]
关于第二点，实际上是支持的，使用`socks5://username:pass@domain:port`的形式即可

**Comment by Vernon818** [comment]
好的，谢谢师傅反馈

**Comment by SimoLin** [comment]
> 关于第二点，实际上是支持的，使用`socks5://username:pass@domain:port`的形式即可

那工具的输入框提示是不是可以考虑增加一下描述，现在的只有`socks5://domain:port`这个描述，就不知道
![image](https://github.com/yaklang/yakit/assets/24656521/07e8fe6c-361a-4c83-9eb4-ca971e72b464)

**Comment by Vernon818** [comment]
可以的，后面我们描述调整一下
