### ISSUE TITLE
数据库 CVE管理 初始化数据库报错 

### ISSUE THREAD

**Issue by Admini521** [yaklang/yakit#916]
![1](https://github.com/yaklang/yakit/assets/55176505/8bef317f-5360-433f-85dd-ffd9e2df7171)
![2](https://github.com/yaklang/yakit/assets/55176505/af489b21-e224-412b-81ce-1b318312d297)

数据库 CVE管理 初始化数据库报错 
手动更新包也是 没有CVE管理
重置更新尝试多次都这报错

**Comment by onewinner** [comment]
我也遇到你这个问题，手动下载解压这个压缩包，默认软件解压的数据好像有问题，记住你手动解压出来就行

**Comment by Admini521** [comment]
> 
我是手动下载default-cve-db.gzip   手动解压gzip格式 不知道怎弄；   手动配置CVE管理也没有数据

**Comment by onewinner** [comment]
就用正常解压软件打开解压出来就行，你会发现你解压出来的文件大小，和它默认解压的有区别，将你解压的放到./yakit-projects下重启就可以了
