### ISSUE TITLE
【BUG】yso模块引号没正确处理，产生“代码注入”了

### ISSUE THREAD

**Issue by l3yx** [yaklang/yakit#924]
whoami");exec.System("open -a Calculator ");  //
![image](https://github.com/yaklang/yakit/assets/42339081/83aa07ae-2732-49b9-aaa9-7574e99d0652)

**Comment by l3yx** [comment]
> 好的师傅，马上修，暂时不用担心安全风险，其实如果可以调用后端grpc已经获取了引擎的最高权限，是允许执行任意yak代码的

知道，所以这不代码注入打的引号嘛哈哈

**Comment by WAY29** [comment]
fixed by https://github.com/yaklang/yaklang/pull/224
