### ISSUE TITLE
MIMT模式下插件的被动扫描不走全局代理

### ISSUE THREAD

**Issue by XXP07** [yaklang/yakit#927]
我尝试了很多方法，并尝试各种组合的设置以下这几种代理模块
![image](https://github.com/yaklang/yakit/assets/103628878/ade9aa67-dcf7-459c-b640-80a33ff3b97c)
![image](https://github.com/yaklang/yakit/assets/103628878/5aafae22-dd35-467f-aaea-c882fe2a46ea)
![image](https://github.com/yaklang/yakit/assets/103628878/a968efc1-4228-4f8a-8097-c1e14493c9a6)
但是不论怎么样组合怎么样去设置，最终只能在我开启MIMT时访问走我的代理
首先我以上三个代理全部设置好之后启动MIMT模式，不开启插件被动扫描的情况下尝试访问
![image](https://github.com/yaklang/yakit/assets/103628878/4ce6129f-74cb-4b49-a3ed-1cd233bfdfb4)
这里可以看到使用代理IP进行访问
接下来我开启一个插件进行被动扫描
![image](https://github.com/yaklang/yakit/assets/103628878/6124c8b3-56fc-47ce-9b39-ba7faf073f3d)
ke'yi可以看到下边这四条是这一次的访问记录，只有访问web走了代理流量，被动扫描依旧处于不走代理的情况
这种情况我尝试很多方法都无法解决，这个是我的做法问题还是我们的插件这里走代理的设计缺陷呢

**Comment by VillanCh** [comment]
之前的策略是专门做了分离，然后通过进程环境变量来控制；

但是现在看来显然是不合理的，我们在逐步调整，会让被动扫描的代理全部都是用 MITM 配置的代理；

感谢师傅反馈，在这个修改完成之后，我们会在这个 issue 链接 yaklang 引擎的改动分支

**Comment by VillanCh** [comment]
最新的引擎已经支持 MITM 代理配置应用到被动扫描插件中，师傅可以更新到最新的引擎再进行验证
