### ISSUE TITLE
【需求】希望可以把sqlmap和xray给集成进去

### ISSUE THREAD

**Issue by Ruqian01** [yaklang/yakit#929]

**Comment by Vernon818** [comment]
师傅劫持那里的下游代理填xray的地址就可以联动了，不需要集成进来哈~

**Comment by Ruqian01** [comment]
我是觉得把xray集成进去可以主动扫描更方便一点，这样就是渗透全程只打开yakit其他工具都不打开就可以完成全栈渗透了

**Comment by Vernon818** [comment]
我们是怕集成的太多，会比较重来着，所以暂时没有集成

**Comment by charis3306** [comment]
> 我是觉得把xray集成进去可以主动扫描更方便一点，这样就是渗透全程只打开yakit其他工具都不打开就可以完成全栈渗透了

我怀疑你是长亭引流的【狗头】

**Comment by ViCrack** [comment]
自己配下代理就行了，多方便，没必要啥东西都搞进去

**Comment by shanon00** [comment]
有yakit 的sqlmap 联动插件嘛？
