### ISSUE TITLE
【优化】Tab 栏无用空间的压缩

### ISSUE THREAD

**Issue by LztCode** [yaklang/yakit#943]
1、Yakit的UI界面有很大问题
<img width="521" alt="image" src="https://github.com/yaklang/yakit/assets/73683679/b730a7d6-26e6-4bdd-b5e5-188beb86d8b6">
2、从图片上看，在抓包改包这一核心功能上，无效的UI信息占用了五行，可以学习一下burp是怎么弄的，再精简一些。避免出现明明数据词条能合并到一行的，非要另起一行，明明可以弄下拉切换，非得弄个标签选项卡套娃。

**Comment by Vernon818** [comment]
好的，谢谢师傅反馈

**Comment by charis3306** [comment]
我提一嘴，能不能加个黑色界面的个人觉得黑色界面比较显眼。
![image](https://github.com/yaklang/yakit/assets/84823804/75c9b713-7d26-4f72-bb00-412cb93f9994)

**Comment by Vernon818** [comment]
有计划的，等UI改版结束就会做

**Comment by charis3306** [comment]
> 有计划的，等UI改版结束就会做

期待！

**Comment by VillanCh** [comment]
当前版本对 History Tab 做了一定程度优化，应该暂时可以缓解这个问题
