### ISSUE TITLE
【需求】希望添加一个类似 burpsuite里的一个功能.pitch-fork

### ISSUE THREAD

**Issue by pinklinux** [yaklang/yakit#958]
intrude模块的position中四种爆破模式：
1、sniper（狙击手）：单个爆破，当有2个时先将2爆破点固定（固定值为你在网页输入的默认值）在从爆破点1开始爆破，完后在固定1爆破点，对爆破点2进行爆破。
2、battering ram（攻城锤）：两个爆破点同时进行，如admin：admin
3、pitch-fork（叉子）：有两个爆破点，且会给两个爆破点分开设置字典，两个字典同时进行，按照行数少的字典来执行次数
4、cluster bomb（集束炸弹）：表示有两个爆破点，同时设置两个字典执行次数为两个字典的乘

现在遇到请求里,需要同时设置 2 个爆破点的话,好像没办法同时跑.能增加类似Intruder的这个功能吗.
现在我在请求里要是放 2 个  {{file:line   他只能按行读取最后一个file:line ,靠前的file:line 只读取第一行.每次请求都是第一行,不能同步按行读取.

**Comment by VillanCh** [comment]
同步读取需要都修改标签为 file:line::1即可


实际上默认是笛卡尔成积，可以通过::1改变运算顺序





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: pinklinux ***@***.***&gt;
发送时间: 2023年8月4日 12:41
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 【需求】希望添加一个类似 burpsuite里的一个功能.pitch-fork (Issue #958)





 
intrude模块的position中四种爆破模式：
 1、sniper（狙击手）：单个爆破，当有2个时先将2爆破点固定（固定值为你在网页输入的默认值）在从爆破点1开始爆破，完后在固定1爆破点，对爆破点2进行爆破。
 2、battering ram（攻城锤）：两个爆破点同时进行，如admin：admin
 3、pitch-fork（叉子）：有两个爆破点，且会给两个爆破点分开设置字典，两个字典同时进行，按照行数少的字典来执行次数
 4、cluster bomb（集束炸弹）：表示有两个爆破点，同时设置两个字典执行次数为两个字典的乘
 
现在遇到请求里,需要同时设置 2 个爆破点的话,好像没办法同时跑.能增加类似Intruder的这个功能吗.
 现在我在请求里要是放 2 个  {{file:line   他只能按行读取最后一个file:line ,靠前的file:line 只读取第一行.每次请求都是第一行,不能同步按行读取.

**Comment by ViCrack** [comment]
这块功能我也搞不懂，如果有三四个以上的需要同时替换的位置，如何实现类似burp的battering ram效果
