### ISSUE TITLE
【Bug】右键菜单显示不全

### ISSUE THREAD

**Issue by ViCrack** [yaklang/yakit#960]
比如在webfuzz靠上的位置点击右键的时候，往往上一半的菜单显示不出来了。。。。

或许这块可以考虑优化下，上面空间不够的话，让它从鼠标点的下方弹出？

![图片](https://github.com/yaklang/yakit/assets/18179821/f112db7e-4336-475b-a521-9976d1c490ae)

**Comment by Vernon818** [comment]
是的，之前发现了，后面会优化一下
