### ISSUE TITLE
[yak_to_caller_manager:807] load[hijackHTTPRequest] hook failed: empty callers

### ISSUE THREAD

**Issue by WinonaForever** [yaklang/yakit#966]
## 问题描述

请在此处提供您遇到的问题的详细描述。请描述问题的表现、发生的频率、影响范围以及任何其他相关信息。如果可能，请提供具体的步骤来重现该问题。

## 预期行为

请在此处描述您预期的行为，也就是问题被解决后应该出现的结果。如果可能，请提供具体的结果示例。

## 实际行为

请在此处描述您实际看到的行为，也就是问题解决后出现的结果。如果可能，请提供具体的结果示例。

## 复现步骤

请在此处提供能够复现该问题的具体步骤。如果问题是随机发生的，或者需要特定的环境条件才能复现，请提供更详细的说明。

1. 步骤 1
2. 步骤 2
3. 步骤 3

## 环境信息

- 操作系统: darwin
- 系统架构: arm64
- Yakit 版本: 1.2.3-sp3
- YakLang 版本: v1.2.4

## 补充说明

如果您有任何其他有关该问题的信息或评论，请在此处添加。

**Comment by Vernon818** [comment]
师傅这个是个日志，一般不会影响执行的
