### ISSUE TITLE
【需求】WEB Fuzzer的数据提取功能

### ISSUE THREAD

**Issue by pinklinux** [yaklang/yakit#968]
我需要提取文章内容 ID.一页里面有 10 条."contentId": "2030077355000628d",   类似这样.但是在 <提取响应数据包中内容>里 实际只会提取每页的第一行,不能完整提取每页的 10 条,要是这样设置
<img width="305" alt="image" src="https://github.com/yaklang/yakit/assets/37838492/2513ec39-9254-4345-8e03-786b4c291d5c">
<img width="870" alt="image" src="https://github.com/yaklang/yakit/assets/37838492/ea696bbb-3d81-4091-a37b-60fefca7ca0f">这样可以实现,但是导出功能没有,看看是完善提取正则,或者加个导出指定列功能?

**Comment by Vernon818** [comment]
好的，感谢师傅反馈

**Comment by Vernon818** [comment]
师傅，最新的版本已经支持导出提取数据了，在左侧提取器配置好后，在列表导出即可
