### ISSUE TITLE
职业习惯了，属于是

### ISSUE THREAD

**Issue by Git-Again** [yaklang/yakit#969]
<img width="802" alt="图片" src="https://github.com/yaklang/yakit/assets/107609054/a8677cb9-ef47-4d76-a8a3-13316ee223b8">

**Comment by VillanCh** [comment]
感谢师傅反馈，网络调试功能会被 “高级配置-实验性功能-本地网络异常诊断” 替换~&nbsp;


有问题的代码，在 communication.js 中～



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Again ***@***.***&gt;
发送时间: 2023年8月10日 08:38
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 职业习惯了，属于是 (Issue #969)

**Comment by VillanCh** [comment]
新的版本中，网络调试/诊断功能代替了 exec “Ping”，师傅可以尝试一下新的 “网络调试”

**Comment by Vernon818** [comment]
感谢师傅参与我们的众测活动，麻烦师傅联系工作人员wx：Juzi19880818，给你邮寄一个小礼物

**Comment by Vernon818** [comment]
为了感谢师傅给我们提出的bug，准备给师傅邮寄一个小礼物，麻烦联系工作人员wx：Juzi19880818
