### ISSUE TITLE
【BUG】yakit fuzz菜单显示问题

### ISSUE THREAD

**Issue by getcode2git** [yaklang/yakit#989]
## 问题描述
点击fuzzer发包的body时菜单会显示不完整，点击其他地方没有问题
## 预期行为
正常显示所有菜单

## 实际行为

![image](https://github.com/yaklang/yakit/assets/16176349/45ae79d6-0a62-456e-ac52-d7b4b817c135)

## 环境信息
操作系统: win10
系统架构: x64
Yakit 版本: Yakit-1.2.3-sp3 内测版

**Comment by ViCrack** [comment]
这个我之前就提过了，重复了



https://github.com/yaklang/yakit/issues/960
