### ISSUE TITLE
建议快捷键: command+w 关闭 tab

### ISSUE THREAD

**Issue by dem0ns** [yaklang/yakit#99]
😁

**Comment by VillanCh** [comment]
感谢反馈，研究一下如何在前端劫持 command w 关闭 tab&nbsp;


其实我也有这个需求，只是目前框架下有点不好做，但是努努力应该也能实现



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Dem0ns ***@***.***&gt;
发送时间: 2022年1月24日 18:21
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] 建议快捷键: command+w 关闭 tab (Issue #99)





 
😁
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
