### ISSUE TITLE
【BUG】过滤器的规则对于插件无用

### ISSUE THREAD

**Issue by TryA9ain** [yaklang/yakit#993]
-[BUG]
## 复现过程
比如我设置了过滤器，只想要过滤 *baidu.com 的资产。
<img width="717" alt="image" src="https://github.com/yaklang/yakit/assets/51145610/7357d9f0-24ba-49e4-b590-aa1706532a7c">
我并未启用任何插件，而且除了官方自带的插件，并未安装任何第三方插件
<img width="490" alt="image" src="https://github.com/yaklang/yakit/assets/51145610/3605fefb-1192-4c2b-a3ca-2970044d06f7">
可以看到，MITM 和 爬虫结果目前都是正确的，都只过滤了 *baidu.com。
<img width="1028" alt="image" src="https://github.com/yaklang/yakit/assets/51145610/2e46c225-bcf5-4948-9ec6-77f5c36867b8">
现在我们来单独看一下“插件”的结果，可以看到，不只过滤了 *baidu.com，还过滤了其他无关的域名。
<img width="1523" alt="image" src="https://github.com/yaklang/yakit/assets/51145610/58955386-c3ae-4d15-be88-6479ed8346e7">
## 影响
这样会导致，当你想要仅仅扫描 *baidu.com 的资产时，插件还会将其他的不相关资产也扫描。

**Comment by WAY29** [comment]
插件中的流量是指纹探测的流量，这个指纹探测是yak引擎的内置行为，但是实际上这个行为在没加载端口扫描插件时不应该进行，已经在[此pr](https://github.com/yaklang/yaklang/pull/347)中修复

**Comment by Vernon818** [comment]
感谢师傅参与我们的众测活动，麻烦师傅联系工作人员wx：Juzi19880818，给你邮寄一个小礼物
