### ISSUE TITLE
【需求】history定位当前显示的请求响应

### ISSUE THREAD

**Issue by VVeakee** [yaklang/yakit#994]
## 需求描述

![image](https://github.com/yaklang/yakit/assets/85714114/ada4dbc6-ef49-4c98-9a34-0a78db8b719b)
情况1,当颜色很多时,不容易看到自己正在看到是哪个请求,途中正在查看的是265
情况2,测试某一个上传功能,比如现在id到了200,上传图后请求id到了230,那我查看数据包是不是要从201开始看起
id-201到id-230都是上传产生的数据包,这30个数据包会把屏给刷下去,如果我不记住id的话,根本不知道上传产生的数据包是从哪开始的

## 解决方案
原来的状态,显示的是id=20
![image](https://github.com/yaklang/yakit/assets/85714114/74098dea-af83-4108-bb51-9479912464d3)
点击某个功能后,新增了30个数据包,id 21-50,此时显示的是id 38-50
通过点击快速跳转,改变上面的显示,以20为底显示,快速查看这个功能新产生的数据包
![image](https://github.com/yaklang/yakit/assets/85714114/0667c731-040e-4cf1-8014-c1955a54dc6a)
这样就可以确定哪些数据包是这个功能产生的并且快速定位
目前我确定一个功能产生的数据包是记住现在的id,测试功能后,翻到原来的id

**Comment by Carochen13** [comment]
感谢师傅的建议，请联系工作人员领取礼物，24-26号可额外在CCS展台领取牛牛公仔

**Comment by Vernon818** [comment]
感谢师傅参与我们的众测活动，麻烦师傅联系工作人员wx：Juzi19880818，给你邮寄一个小礼物

**Comment by Carochen13** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Vernon818** [comment]
Yakit v1.2.7-sp4 已支持

**Comment by Carochen13** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
