### ISSUE TITLE
【需求】发包后提取全部数据

### ISSUE THREAD

**Issue by honmashironeko** [yaklang/yakit#997]
在Web Fuzzer那边批量发包后，获取响应包的数据，并提供导出功能

**Comment by honmashironeko** [comment]
提取响应包数据内容这个功能，只会匹配第一个，后面的都无法匹配了

**Comment by Vernon818** [comment]
师傅你配置左边的提取数据，然后导出的时候会表里提取数据那个字段一起导出来
![image](https://github.com/yaklang/yakit/assets/94944398/a0231060-e982-43c3-b43f-e36d435cc4b5)
![image](https://github.com/yaklang/yakit/assets/94944398/807bf39a-2762-4410-b0d3-aabacd66cf15)
