### ISSUE TITLE
【bug】会产生两个content-type头

### ISSUE THREAD

**Issue by cc8ci** [yaklang/yakit#999]
请求包会产生两个content-type头，部分程序两个content-type头会直接报错
![06](https://github.com/yaklang/yakit/assets/48230666/13840fbd-777a-4f4b-a8fa-43d58e135bbc)

**Comment by Vernon818** [comment]
感谢师傅参与我们的众测活动，麻烦师傅联系工作人员wx：Juzi19880818，给你邮寄一个小礼物
